### ISSUE TITLE
Ninja output into dumb terminal is not machine parsable

### ISSUE THREAD

**Issue by colincross** [ninja-build/ninja#1010]
When ninja writes to a smart terminal it writes the status line for each edge when the command starts and then again when the command finishes immediately followed by the command output.  When writing to a dumb terminal it only writes the status line when the command starts, to avoid duplicate status lines in the output.  When building in parallel the dumb output ends up looking like:
status for cmd 1
status for cmd 2
output for cmd 1
output for cmd 2

This prevents automated tooling from parsing out the output from and individual command, for example to associate error messages or warnings with the file that caused them.

PR #999 changes the status printing for dumb terminals to only print when the edge finishes, instead of when the edge starts.  This is a little less useful for a human reading the output as it runs, as you can't see what command is currently running, but I expect all interactive uses of ninja to use a smart terminal.  For dumb terminal outputs, which I expect is normally redirecting to a file, the output will always be
status for cmd 1
output for cmd 1
status for cmd 2
output for cmd 2

Parsers can use a token in NINJA_STATUS to recognize status lines, and assume everything after a status line is output from that command until the next status line is seen.

**Comment by nico** [comment]
It's an interesting idea. Not seeing what's currently running is a bit weird, but in interactive mode that happens frequently too. And it keeps things simple, which is nice.

I posted this to the mailing list for discussion here: https://groups.google.com/forum/#!topic/ninja-build/-wQL6d8d0gg

**Comment by martine** [comment]
(We really should make interactive mode update with which command is still
running if we're waiting for something...)

**Comment by maximuska** [comment]
@martine: I've proposed once the 'still running' patch which prints the
name of (one of the) long-rung running command in the interactive mode:
https://github.com/martine/ninja/pull/629.

Using it myself actually.
SEND
Yesterday
Unread
מיטב דש טרייד
סקירה שבועית מאקרו ושווקים 30-08-2015
This month
Unread
BundlePurchases (25)
Avangate Customer Service, PayPal, כללית, dnt-reply, HotNet, קבוצת
ישראכרט, לאומי
קארד ...
Ariel Zeitlin via LinkedIn
 (2)
Catch-up
 –
LinkedIn Ariel Zeitlin Ariel Zeitlin Co-Founder & CTO at Guardicore Monday
17th looks fine.
June
lock-free
[lock-free] Abridged summary of lock-free@googlegroups.com - 2 updates in 1
topic
 –
lock-free@googlegroups.com Google Groups Today's topic summary View all
topics Pros and Concerns
lock-free
[lock-free] Abridged summary of lock-free@googlegroups.com - 5 updates in 2
topics
 –
lock-free@googlegroups.com Google Groups Today's topic summary View all
topics Pros and Concerns
lock-free
[lock-free] Abridged summary of lock-free@googlegroups.com - 1 update in 1
topic
 –
lock-free@googlegroups.com Google Groups Today's topic summary View all
topics Pros and Concerns
Maxim Kalaev
Office address
 –
The office address is: 550 King ST Littleton, MA 01460 Maxim Kalaev
IBM-XIV, Israel
Maxim Kalaev
Route - boston to littleton
 –
https://www.google.co.il/maps/dir/Boston+Logan+International+Airport,+Harborside+Drive,+Boston,+MA,+
מיטב דש טרייד
סקירה שבועית מאקרו ושווקים 7-6-2015
ninja-build
Abridged summary of ninja-build@googlegroups.com - 1 update in 1 topic
 –
ninja-build@googlegroups.com Google Groups Today's topic summary View all
topics Semantics of
vlada
חוברת2.xlsx
May
מיטב דש טרייד
סקירה שבועית מאקרו ושווקים 10-5-2015
Unread
American Express
הודעת החיוב החודשית בדואר אלקטרוני מילת זיהוי:HENHEN
 –
אם הקישור לצפייה בהודעת החיוב אינו מוצג כראוי - אנא לחץ כאן מקסים קלייב
שלום, הודעת החיוב החודשית
April
lock-free
[lock-free] Abridged summary of lock-free@googlegroups.com - 1 update in 1
topic
 –
lock-free@googlegroups.com Google Groups Today's topic summary View all
topics MPSC + backoff
Snoozed 4 months ago
Unread
לאומי קארד
מקסים קלייב, פירוט החיובים החודשי ממתין לך באתר לאומי קארד. מילת זיהוי :
חנחנ
 –
מקסים קלייב החל מהיום, פירוט החיובים שלך בחשבון שמספרו מסתיים ב- 5894
ימתינו לך באזור האישי. לצפייה
March
illia
 (2)
illia shared an album with you.
 –
You are invited to view illia's photo album: Bansko (2015 03 13-20) Bansko
(2015 03 13-20) Mar 15
Earlier
Maxim Kalaev
emacs & python
 –
http://www.emacswiki.org/emacs/PythonProgrammingInEmacs#toc8
http://superuser.com/questions/589059/
me
http://kartina.tv/
 –
http://kartina.tv/ -- Maxim
Maxim Kalaev
book
 –
"The 7 habits of highly effective people" by Stephen R. Covey.:
http://www.amazon.com/
Maxim Kalaev
Self-Service Linux book
 –
http://www.scribd.com/doc/84665121/99/Global-Constructors-and-Destructors
Maxim Kalaev
The Algorithm Design Manual (Mixed media product) By (author) Steve S.
Skiena --
 –
Maxim Kalaev IBM-XIV, Israel NAS Development Team

**Comment by sgraham** [comment]
I don't feel strongly, but I do sometimes watch sloooow bot output streaming as "pseudo" interactive, which will be running in dumb mode, so it's sort of nice to see what's running. But it's not a big deal if the other uses are important.

**Comment by nico** [comment]
@sgraham I do that all the time too. But you currently don't really know what's running either, right? Currently, all running commands have been printed somewhere above, but you don't know what's still active. (To be clear, I'm slightly nervous about this too, but I think in practice it might be ok. And if it isn't, then we can come up with something else then.)

**Comment by nico** [comment]
Since #999 is merged, this is fixed for now. If #999 turns out to be annoying, we can reopen this.
