### ISSUE TITLE
Support for building a single translation unit

### ISSUE THREAD

**Issue by rcdailey** [ninja-build/ninja#1012]
I'd like to be able to build a single translation unit as a target:

```
ninja Some/Directory/HelloWorld.cpp
```

This is useful to be able to test changes I made to a single CPP file. Is this possible?

**Comment by sgraham** [comment]
You can do `ninja Some/Directory/HelloWorld.cpp^`. See
https://martine.github.io/ninja/manual.html#_running_ninja.

**Comment by rcdailey** [comment]
That's a very obscure syntax and not very easily found in the documentation. Honestly from a usability perspective, I expected to find an option for this.

**Comment by jimon** [comment]
I guess you need to build corresponding obj file, like

    ninja Some/Directory/HelloWorld.obj

so this will build obj file as a target by invoking compilation of cpp file.

**Comment by jhasse** [comment]
As the support for this is there, I'm closing this issue. If you have ideas for a less confusing syntax or how the documentation could be improved regarding this, please reopen.
