### ISSUE TITLE
link to chrome ninja docs

### ISSUE THREAD

**Issue by ariccio** [ninja-build/ninja#1038]
The link to the chrome ninja docs, in the "extensive" manual, is out of date.

The URL should be: https://chromium.googlesource.com/chromium/src/+/master/docs/ninja_build.md

**Comment by nico** [comment]
http://www.w3.org/Provider/Style/URI.html etc :-/ Thanks, I'll wait a bit to see if they'll move it again soon before updating the manual (it's not a dead link, just a manual redirect…)
