### ISSUE TITLE
-k 0 is not documented

### ISSUE THREAD

**Issue by orlp** [ninja-build/ninja#1056]
Current documentation is the following:

    -k N     keep going until N jobs fail [default=1]

I suggest this instead:

    -k N     keep going until N jobs fail (0 is unbounded) [default=1]

Although the exact wording doesn't matter, a small documentation of this feature would be nice.

**Comment by tfarina** [comment]
To me this does not seem to improve much. What unbounded means? Or, passing zero will result in which behavior?

**Comment by orlp** [comment]
I'm not a native speaker, so I'm not sure whether I used the right word.

Unbounded in this context means that `ninja` will not stop after any finite number of jobs fail - only when it can no longer make any progress (all leaves in the build dependency tree have failed or completed).

**Comment by nicolasdespres** [comment]
What about "unlimited"?

**Comment by orlp** [comment]
@nicolasdespres I fail to see how that is an improvement over unbounded. I feel that if one is going to be unclear then so is the other.

**Comment by jimporter** [comment]
As a native English speaker, "unlimited" is a bit clearer (and certainly more natural sounding).

**Comment by nico** [comment]
dupe of #1006
