### ISSUE TITLE
Ninja: No Work to Do

### ISSUE THREAD

**Issue by chaseWillden** [ninja-build/ninja#1061]
I get the following Ninja message:

```
ninja -C out/Release nw -j4
ninja: Entering directory `out/Release'
ninja: no work to do.
```
Any suggestions?

**Comment by sgraham** [comment]
Everything's good? What do you expect to happen?

**Comment by martine** [comment]
This is saying that the "nw" target is up to date.  Is that what you expect?

**Comment by chaseWillden** [comment]
No this is the issue, I haven't built it yet.

**Comment by chaseWillden** [comment]
@martine Ninja worked a few weeks ago. I have version 1.6.0. I'm building on linux. It should be building. Any suggestions?

**Comment by jimon** [comment]
@chaseWillden try this

	ninja -C out/Release -t clean
	ninja -C out/Release nw -j4

**Comment by chaseWillden** [comment]
@jimon I just tried that, but I still get the same error. I even whipped up a new VM with Linux and got the code, but still the same issue...

**Comment by tfarina** [comment]
@chaseWillden could you share with us the code for your build.ninja file? Is the code for nw open source? Is your ninja file generated by a meta tool like cmake, gyp, or is it hand-made?

**Comment by chaseWillden** [comment]
@tfarina Yes it is open source. Here's the repository:

https://github.com/nwjs/nw.js

The build instructions for it are here:

https://github.com/nwjs/nw.js/wiki/Building-nw.js

My build.ninja file is:

https://github.com/chaseWillden/chromium.src/blob/nw12/build.ninja

The build.ninja file is not actually in the root folder, it belongs in the out/Release folder, but that folder is in my .gitignore.

**Comment by chaseWillden** [comment]
@tfarina Oh I forgot to mention that the file is generated by gyp.

**Comment by chaseWillden** [comment]
I guess the we switched to a new gyp file and I was unaware. Problem solved.
