### ISSUE TITLE
add option to clean targets non recursively

### ISSUE THREAD

**Issue by NiklasRosenstein** [ninja-build/ninja#1066]
I'm often find myself wanting to clean the output files of a specific rule, but *not* clean any of its dependencies.

**Comment by NiklasRosenstein** [comment]
Seems like the `-r` option does exactly that. Misleading, imho. The help is not very clear about that and the `-r` is rather counter intuitive when searching for a way to clean non-_**r**ecursive_. I changing the current

      -r     interpret targets as a list of rules to clean instead

to 

      -r     interpret targets as a list of rules to clean instead (non-recursive clean)

**Comment by nico** [comment]
I guess `-r` is short for "rule", not "recursive" :-)

A web search for "ninja non-recursive clean" now finds this issue which explains how to do this (thanks!), so hopefully this will be better now.

**Comment by tapika** [comment]
Would it be possible to share exactly how non-recursive clean can be achieved ?
Tried your search text, but could not find any articles.

**Comment by tapika** [comment]
Deleting specific target folder recursively seems to do the trick. Need to know which folder however, which can be cmake naming specific.
