### ISSUE TITLE
add cwd variable to specify working directory of rule/build

### ISSUE THREAD

**Issue by NiklasRosenstein** [ninja-build/ninja#1070]
I want to suggest supporting a `cwd` variable to specify the working directory for a rule or a single build. `build` will have to translate relative `$in` and `$out` filenames respectively. Meta build systems will know the behaviour of specifying `cwd` and can make sure to transform relative paths used in `command` respectively.

__Example__

```
rule echo:
  command = echo $in --> $out

build resources/some_res.txt: echo obj/some_res.o
  cwd = resources
```

I would expect the following output

    some_res.txt --> ../obj/some_res.o

__Possible Application__

Using `objcopy` to create an object file which embeds resources and binary data will create a symbol based on the input filename, including the directory! Eg. the file `resources/some_res.txt` would get the symbol `_resources_some_res_txt_start`. Switching to the `resources` directory would allow us to pass only the filename and get `_some_res_txt_start` as the symbol.

```
rule embed:
  command = objcopy -I binary -O elf32-i386 -B i386 $in $out'

build resources/some_res.txt: embed obj/some_res.o
  cwd = resources
```

**Comment by nicolasdespres** [comment]
Hi. You could generate something like that:
```
rule embed:
  command = cd ${cwd} && objcopy -I binary -O elf32-i386 -B i386 $input $output

build resources/some_res.txt: embed obj/some_res.o
  input = some_res.txt
  output = obj/some_res.o
  cwd = resources
```

**Comment by NiklasRosenstein** [comment]
```
rule dtschump.CImg.run_edge_explorer2d
  command = cd c:\users\niklas\desktop\cimg\examples && c:\users\niklas\desktop\cimg\build\dtschump.cimg\edge_explorer2d.exe
  pool = console
build dtschump.CImg.run_edge_explorer2d: dtschump.CImg.run_edge_explorer2d c$:\users\niklas\desktop\cimg\build\dtschump.cimg\edge_explorer2d.exe
```

That doesn't seem to work, at least on Windows. :(

**Comment by martine** [comment]
In what way does it fail?

**Comment by NiklasRosenstein** [comment]
```
[1/1] cd C:\Users\niklas\Desktop\CImg\examples && c:\u...dtschump.cimg\build\dtschump.cimg.examples\captcha.exeFAILED: cd C:\Users\niklas\Desktop\CImg\examples && c:\users\niklas\desktop\dtschump.cimg\build\dtschump.cimg.examples\captcha.exe
CreateProcess failed: The system cannot find the file specified.
ninja: build stopped: subcommand failed.
```

**Comment by martine** [comment]
Ah right, "cd" is not a program.  Try inserting cmd /c at the beginning of
the command line. We should put this in the docs somewhere.

**Comment by NiklasRosenstein** [comment]
Oh course! It works now. Thanks :+1:

**Comment by nico** [comment]
Sounds like this can be done without additional code in ninja already.
