### ISSUE TITLE
Management of windows root directory

### ISSUE THREAD

**Issue by SadE54** [ninja-build/ninja#1071]
I'm using python to automatically generate ninja files from eclipse project files on a windows system. Eclipse returns absolute paths, and ninja gave me an error because of the ':' char in the path : 
build $builddir/test.o :  compile "D:/subdir1/subdir2/test.c" 

ninja: error: sources.ninja:1: expected newline, got ':'
build $builddir/test.o :  compile "D:/subdir1/....
                                                      ^ near here

I guess ninja does not understand the double quotes :-/

**Comment by NiklasRosenstein** [comment]
No problem here. Maybe there must not be a space after `build <filename>` and the first `:`? Are you using `ninja_syntax.py`?

**Comment by SadE54** [comment]
The space is not there , I made abn error writing the comment.
build $build_dir\faults_def.o:  compile D:\Project_1\Sources\Faults\faults_def.c

I'm not using ninja_syntax.py , just classical write() because there's just 'build' lines in this ninja include file.

**Comment by NiklasRosenstein** [comment]
Please use code formatting, Sir.

There are no quotes in the example line of your last comment. In that case, I think you will have to escape the `:`.

    build $build_dir\faults_def.o: compile D$:\Project_1\Sources\Faults\faults_def.c

Or

    build $build_dir\faults_def.o: compile "D:\Project_1\Sources\Faults\faults_def.c"

**Comment by SadE54** [comment]
You're right , I should very my comments before posting ;-)
I indeed forgot the double quotes, but in my ninja file there are.
```python
build $builddir/Faults.o:  compile "D:/Project_1//ME_Application/Sources/UserApp/Faults.c"
```
I'm still getting the build "compile ninja: error: sources.ninja:1: expected newline, got ':' "
pointing to the ':' adter 'D'

**Comment by NiklasRosenstein** [comment]
Ah, now I remember. Ninja does not support quotes in this context. You have to use a `$` escape.

**Comment by martine** [comment]
The double-quote character is never used for quoting in Ninja.
All quoting is done via dollar signs.

Manual reference on lexical syntax:
https://ninja-build.org/manual.html#_lexical_syntax

On Mon, Dec 14, 2015 at 9:28 AM, Niklas Rosenstein <notifications@github.com

**Comment by SadE54** [comment]
Escaping the semi colon with ```$``` is Ok now , thanks. If I'm using double quotes, I get a 
```FindFirstFileExA``` error ... It seems clear I must avoid double quotes on ```build lines```.
 My compiler still need the quotes in paths with spaces so I could provide it in the ```rule``` block !

**Comment by martine** [comment]
See the discussion of rule variables here:
https://ninja-build.org/manual.html#ref_rule

$in and $out will be quoted.

**Comment by nico** [comment]
Yes, there are two levels of quoting here: You need to escape `:` for ninja via `$:` (since it's a special character in ninja files). Ninja then passes everything as-is after `$` escape handling to subprocesses, and these may need additional quoting (via " or similar). Sounds like you figured it out though :-)
