### ISSUE TITLE
Context of the include directive

### ISSUE THREAD

**Issue by SadE54** [ninja-build/ninja#1072]
Hi,
I'm using a include directive like this in my main ninja file: 
```include sources.ninja```
The ```sources.ninja``` file is in the same directory than ```build.ninja```
And I call ninja using path variables from eclipse. The problem is that the include directory seems to use the path context of Eclipse and not the one from ninja : the include file is not found.
If I'm executing ninja from the command line and from the same directory than ```build.ninja and sources.ninja``` , it's working well. 
The only way I found is to use an absolute path in ```build.ninja``` for the include but I would find a cleaner way :-/

**Comment by martine** [comment]
All paths in ninja should be relative to the directory containing the root build.ninja.  Does that help?

**Comment by martine** [comment]
How does eclipse execute ninja?  Does it print a command line?

**Comment by SadE54** [comment]
Yes , I change the default make in my project by ninja. After some researching , I found a solution in Eclipse. There's a field to set the Build directory for the builder , and by pointing to the ninja file, it's working well. So I guess Eclipse use this setting to change the context for ninja.

**Comment by nico** [comment]
You can probably also pass `-C folder/with/your/buildfile` to ninja from Eclipse.
