### ISSUE TITLE
Include file and commands order

### ISSUE THREAD

**Issue by SadE54** [ninja-build/ninja#1077]
Hi,

I'm currently have a ninja project with 2 ninja files, one including the other . The first is to manage the complete process while the second only compile and link my files

```python
rule compile
  depfile = $builddir\$out.d
  deps = gcc
  command = $cc $cflags -c --depend $out.d  "$in" -o $out
  description = Building C file $in

rule link
  command = $linker $lflags $in -o $out
  description = Linking files to $axf

rule clean
  command = $rm -d $builddir
  description = Cleaning directory $builddir

rule before_1
  command = blahh blah
  description = Create sources list

rule before_2
  command = blahh
  description = Prepare files

rule after
  command = blahh
  description = Create .hex file

build before_1: before_1
build before_2: before_2
#---------------------------------------------------
# sub ninja files with sources to compile/link
#---------------------------------------------------
include sources.ninja

build after: after
```

and the include file:
```python
build $builddir/source.o: compile source.c
build $builddir/$axf: link $builddir/source.o 
```
The problem is that commands are not executed in the order at the include level. 
the rule ```after``` is executed between the compilation and the link of the included ninja file . So it completely messed up my output files. I tried using the ```-j 1``` option to be sure that it's not linked to concurrency job

**Comment by nico** [comment]
This is working as intended: Ninja executes things in dependency order, not in the order they're in the manifest file. If you want to run commands in a certain order, you need to specify dependencies between them.

It's possible (and easy) to write a generator that runs commands in top-down order. Maybe one of the generators listed at https://github.com/ninja-build/ninja/wiki/List-of-generators-producing-ninja-build-files can do this; if not maybe you can use `misc/ninja_syntax.py` to write one yourself (just let each command write a stamp file as a side effect, and have the next command depend on the previous command's stamp file).
