### ISSUE TITLE
Timing build time per subninja

### ISSUE THREAD

**Issue by gioragutt** [ninja-build/ninja#1080]
I need to time how much time each subninja takes to build.

I've encountered 2 main problems:  
============
1. I can't really find a way to time a targets other then timing each command by wrapping it with a timing script.  
2. I can't link a rule to a certain subninja.

Would there be another way other then time each module?
&
Is there a way to export a $subninja as a variable, like $out?

Sincerely, giorag.

--
Edit: If adding this as a feature to ninja(timing each submodule build time) would be possible, it would be great!

**Comment by nicolasdespres** [comment]
You could add a phony target (called `sub_all` for instance) depending on all the targets defined in your subninja file. Then for timing you can do: `time ninja sub_all`

**Comment by gioragutt** [comment]
My target is not to time the whole build process, but to time each subninja seperately.
The purpose of it, eventually, is to figure out why some subninjas take longer than usual to build

**Comment by nicolasdespres** [comment]
I think I got that. When you pass a target as argument to ninja (like `sub_all`) it builds only this target.

You can repeat this process for all your subninja.

**Comment by ilyapopov** [comment]
You can also have a look to `.ninja_log` file, which lists start and end times for all edges in first and second columns.

**Comment by gioragutt** [comment]
Does it list it in all versions of ninja? My version of ninja is probably
1.3 or something...

2015-12-28 20:22 GMT+02:00 Ilya Popov <notifications@github.com>:

**Comment by ilyapopov** [comment]
In 1.3.4 it does. What do you see in your `.ninja_log`? What does it say in the first line (which is comment)? Is it "`# ninja log v5`"?

**Comment by gioragutt** [comment]
I'm currently not at my workplace, I'll return an answer tomorrow

2015-12-29 11:54 GMT+02:00 Ilya Popov <notifications@github.com>:

**Comment by nico** [comment]
See also https://groups.google.com/forum/#!topic/ninja-build/aD82sxwD3_o -- seems more like a support question than an issue in ninja itself, so closing this.
