### ISSUE TITLE
Ninja not executing python good

### ISSUE THREAD

**Issue by gioragutt** [ninja-build/ninja#1081]
When I set the command in build.ninja as `command = python some_script.py some argument` it messes up the execution of the script and other python scripts that are executed during that script. Any idea why that happens?  

My script always emits: `failed: 1: Syntax error: end of file unexpected (expecting ")") ` and the file it emits from is perfectly fine ( [Stackoverflow Post](http://stackoverflow.com/questions/34431557/syntax-error-end-of-file-unexpected-expecting-python))

**Comment by martine** [comment]
Can you paste the output of `ninja -j1 -v` ?

**Comment by gioragutt** [comment]
Actually I can't, because the PC I run ninja on is on a different computer on a completely different network without any way to communicate with WWW... Anything I can look for in the output and tell you...?

**Comment by martine** [comment]
Ninja works fine for thousands of people, which means the problem is likely something specific to your setup.  Without knowledge of your setup, I cannot guess what is wrong.  If you are unable to provide information, I suggest debugging it using the normal tools you'd use to debug such a problem.

**Comment by NiklasRosenstein** [comment]
You could first try to reproduce the issue locally. You do have access to
the `build.ninja` file and. the Python script?

**Comment by gioragutt** [comment]
The rule that is there was hand copied, it's generated with ninja_syntax so it's not it...

**Comment by gioragutt** [comment]
When I run the script normally, without ninja, it runs fine

**Comment by NiklasRosenstein** [comment]
Well then run it again, but with ninja, and pass the -j1 -v options to
ninja. :)

**Comment by gioragutt** [comment]
I see nothing when I run it with `-j1 -v`. Everything is the same except it outputs the command every time.

**Comment by kirbyfan64** [comment]
Sure this isn't a file system issue? Is reading anything from that directory unusually slow?

(I normally hate when people say that things are file system issues, but this sounds odd...)

The script works perfectly outside of Ninja?

**Comment by gioragutt** [comment]
Yes it does. I suspect it has something to do with the PYTHONPATH variable, I later noticed that some of the rules set a value to it. Can this be a factor?

**Comment by martine** [comment]
Unless you can provide a working Ninja build file that reproduces your problem, we cannot help you.  I suggest copying one of your actual build files and deleting all the sensitive information.  Feel free to reopen this bug at that point.
