### ISSUE TITLE
Windows + long command lines

### ISSUE THREAD

**Issue by kaavla** [ninja-build/ninja#1083]
Thanks for all responses in advance. 

It appears that a similar problem was discussed before in https://github.com/ninja-build/ninja/issues/53.

My problem is that i have a a very long command line which exceeds the windows command line limit. 
So i tried using the following rule:
rule link
  command = cmd.exe /c $link @$out.rsp 
  description = LINK $out
  rspfile = $out.rsp
  rspfile_content = $in $linkflags $libs /out:$out

However it still does not work and i get the following error:

[3/3] LINK testQ.exe
FAILED: cmd.exe /c link @testQ.exe.rsp
Microsoft (R) Incremental Linker Version 10.00.40219.01
Copyright (C) Microsoft Corporation.  All rights reserved.

testQ.exe.rsp : fatal error LNK1170: line in command file contains 131071 or more characters
ninja: build stopped: subcommand failed.
	
Seems like the rspfile should not be more than 131071 characters...What am i doing wrong..
Shank

**Comment by sgraham** [comment]
There's $in_newline which will fix that problem, likely.

**Comment by kaavla** [comment]
Thanks .. that seems to have done the trick.. I was pulling my hair out by trying to introduce newline into the $in parameter (http://altdevblog.com/2013/08/25/code-build-opt-p4a/)

I wish this was updated in the manual at: https://ninja-build.org/manual.html

**Comment by nico** [comment]
in_newline is documented at https://ninja-build.org/manual.html. What would you change in the manual?

**Comment by nico** [comment]
(also, closing this issue since it seems resolved. but i'd be curious how you'd improve the manual to make this easier.)

**Comment by martine** [comment]
One thing I've been considering adding to the manual is some sort of
"common patterns" section -- e.g. how to set up an MSVC build (using
depslog, rspfile, in_newline, etc.) or how to set up generated headers.
