### ISSUE TITLE
Command substitution

### ISSUE THREAD

**Issue by svnpenn** [ninja-build/ninja#1089]
With makefile, you can use syntax like this:

~~~
VR != git describe --tags --abbrev=

dist:
  zip program-$(VR).zip program.exe
~~~

Is something like this possible with Ninja?

**Comment by m-mullins** [comment]
The intention for ninja is that this logic is handled by the script that generates the ninja files.

However I think this is possible as the commands are run on a shell. I need to confirm this:

rule dist: 
    command = zip program-$( git describe --tags --abbrev= ).zip program.exe

build zip: dist program.exe

**Comment by m-mullins** [comment]
Actually i think it should be:

build zip: dist

**Comment by martine** [comment]
No, your generator program should run this command before generating the ninja file.  The intent is that a no-op ninja build does no work.

**Comment by svnpenn** [comment]
@martine what generator program? I just created `build.ninja` with text editor and run `ninja`

**Comment by tfarina** [comment]
@svnpenn see https://github.com/ninja-build/ninja/wiki/List-of-generators-producing-ninja-build-files

**Comment by svnpenn** [comment]
@tfarina this project seems like a waste then. It cannot compile beyond the simplest examples without relying on other build systems?

**Comment by tfarina** [comment]
@svnpenn that is by design, "It differs from other build systems in two major respects: it is designed to have its input files generated by a higher-level build system". See the first paragraph at https://ninja-build.org/

**Comment by svnpenn** [comment]
@tfarina why wouldnt I just use Cmake then? Cant Cmake already do everything Ninja does, without being crippled?

**Comment by tfarina** [comment]
@svnpenn No, CMake won't build your project, Ninja will. CMake generates the ninja build files for you, 'cmake -GNinja', then you run ninja on build.ninja to actually build anything. Ninja will just call whatever you put in the 'command = ' line.

**Comment by svnpenn** [comment]
@tfarina ok, so Ninja is a drop in faster replacement for make it seems. However, unlike make, you cant really use Ninja by itself.

**Comment by tfarina** [comment]
@svnpenn Ninja was not designed to be a drop-in replacement for make. Many lessons were learned from its syntax and usage through the years and the designers of Ninja were careful not to make the same mistakes.

**Comment by svnpenn** [comment]
@tfarina it maybe not have been designed to be, but it is:

- it compiles c/c++, like make
- it uses a "makefile", like make
- it can work with Cmake, for a layer of abstraction

Call it what you want, but if it walks like a duck and talks like a duck...

**Comment by kirbyfan64** [comment]
You're not supposed to use Ninja by itself. Ninja is designed to be fast at the expense of being rigid.

**Comment by martine** [comment]
Please see the design goals of the project (and particularly the non-goals there):
https://ninja-build.org/manual.html#_design_goals

See also the section of the manual where we encourage you to use a different system if such a system works:
https://ninja-build.org/manual.html#_using_ninja_for_your_project

**Comment by svnpenn** [comment]
I rethought my process, and Ninja can be used for my purposes. I ended up just hard coding the version number, which is a good practice anyway.

However in the end I did go back to make. Even though I dont need command substitution at this point, make seems to offer a more terse syntax, as it does not require "rule" blocks, everything can go under "build" blocks. This is an interesting project though. I like that it has a built-in "clean" target.

**Comment by kirbyfan64** [comment]
@svnpenn You may want to try one of the generators in the [list](https://github.com/ninja-build/ninja/wiki/List-of-generators-producing-ninja-build-files); I think you might particularly find GN and BuildFox interesting.

**Comment by svnpenn** [comment]
@kirbyfan64 thanks, but want something simple like this:

1. program for compiling (gcc)
2. program for building (ninja, make)

Whereas your suggestion seems like this:

1. program for compiling (gcc)
2. program for building (ninja, make)
3. program for assembling (GN, BuildFox)

**Comment by kirbyfan64** [comment]
@svnpenn Well, you only need to run GN once. From then on, you run just `ninja`, and if any of the GN build scripts change, the Ninja scripts will automatically be regenerated. Not sure about BuildFox.
