### ISSUE TITLE
Rule-level variables

### ISSUE THREAD

**Issue by svnpenn** [ninja-build/ninja#1091]
I see this in the manual:

> Rule-level variables from the rule block (i.e. $command)

Does the mean the result of a command line is accessible via `$command`? If so,
where could you even use it?

**Comment by m-mullins** [comment]
rule foo:
        command = gcc -c -o $out $in
        description = $command

**Comment by svnpenn** [comment]
@m-mullins could you use `$command` from another rule?

**Comment by m-mullins** [comment]
Rules are like functions with their variables scope, however "build" declarations can pass their variables to the rule they used, Ive seen this pattern used in a few ninja files that are generated from make files:

```
rule makecommand:
    command = $comm
    description = $desc

build target.o: makecommand target.cpp
     comm = g++ -c -o target.o target.cpp
     desc = building target.cpp

build another.o: makecommand another.cpp
     comm = g++ -c -o another.o another.cpp
     desc = building another.cpp

build target.so: makecommand target.so
     comm = g++ -o target.so target.o another.o
     desc = linking target.so
```

**Comment by nico** [comment]
This doesn't sound like a bug report or a feature request :-)

Thanks @m-mullins for explaining :-) There's also a mailing list at https://groups.google.com/forum/#!forum/ninja-build
