### ISSUE TITLE
[Win] Can not combain two or more command in 'command' in rules

### ISSUE THREAD

**Issue by Abergard** [ninja-build/ninja#1124]
On Windows 10 I have created a test version of my own clean action:
 ```
rule myclean
  command = dir && dir
build clean: myclean
```

I don't know why, but it doesn't work. Every time I try to run ninja clean I get error
```
 [1/1] dir && dir
 FAILED: dir && dir
 dir: cannot access '&&': No such file or directory
 dir: cannot access 'dir': No such file or directory
 ninja: build stopped: subcommand failed.
```
It seems that it can be a problem with recognizing a linker word. Anybody know how to resolve this problem, or what is the root cause?

Regards,
Abergard

**Comment by sgraham** [comment]
Commands are run by CreateProcess, so you can do this with `cmd /c dir &&
dir`.

**Comment by martine** [comment]
We should have this in the docs somewhere, but I think we don't.

Ninja executes the command as given. If you want shell interpretations like
&&, use
  command = cmd /c "Foo && bar"

**Comment by Abergard** [comment]
Oh, It's work. Thanks a lot for quick answer.
