### ISSUE TITLE
Bootstrapping failed due to warning on Windows (MSVC)

### ISSUE THREAD

**Issue by Araeos** [ninja-build/ninja#1129]
# Description
Bootstrapping ninja using Visual Studio 2015 fails due to compiler warning.

I guess this is due to a new warning introduced with version 19, while the warning disappears using the
recommended option `/Wv:18`.

# Output
```
C:\Users\araeos\Documents\dev\git\ninja>python .\configure.py --bootstrap
bootstrapping ninja...
warning: A compatible version of re2c (>= 0.11.3) was not found; changes to src/*.in.cc will not affect your build.
build.cc
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\iosfwd(343): error C2220: warning treated as error - no 'object' file generated
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\iosfwd(343): warning C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\iosfwd(343): note: to simplify migration, consider the temporary use of /Wv:18 flag with the version of the compiler with which you used to build without warnings
when running:  cl /nologo /Zi /W4 /WX /wd4530 /wd4100 /wd4706 /wd4512 /wd4800 /wd4702 /wd4819 /wd4355 /wd4091 /GR- /wd4267 /DNOMINMAX /D_CRT_SECURE_NO_WARNINGS /DNINJA_PYTHON="python.exe" /FS /Ox /DNDEBUG /GL -c src\build.cc /Fobuild\build.obj
Traceback (most recent call last):
  File ".\configure.py", line 466, in <module>
    objs += cxx(name)
  File ".\configure.py", line 262, in cxx
    return n.build(built(name + objext), 'cxx', src(name + '.cc'), **kwargs)
  File ".\configure.py", line 148, in build
    self._run_command(self._expand(cmd, local_vars))
  File ".\configure.py", line 169, in _run_command
    subprocess.check_call(cmdline, shell=True)
  File "C:\Program Files\Python35\lib\subprocess.py", line 584, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cl /nologo /Zi /W4 /WX /wd4530 /wd4100 /wd4706 /wd4512 /wd4800 /wd4702 /wd4819 /wd4355 /wd4091 /GR- /wd4267 /DNOMINMAX /D_CRT_SECURE_NO_WARNINGS /DNINJA_PYTHON="python.exe" /FS /Ox /DNDEBUG /GL -c src\build.cc /Fobuild\build.obj' returned non-zero exit status 2
````

P.S.: In the context of compiler options, may I ask why RTTI is disabled?

**Comment by nico** [comment]
That looks like a bug in the 19 headers, right? If the compiler warns about noexcept with exceptions disabled, the system headers shouldn't use noexcept when exceptions are disabled. Can you file this with Microsoft?

Is this with the released version of 2015 update 2, or with a prerelease? If it's with the released version, then we probably have to add /Wv:18 :-/

ninja doesn't use RTTI, so we don't want to have to pay for it.

**Comment by sgraham** [comment]
I think this was in 2015 RTM, I'll confirm.

**Comment by sgraham** [comment]
I can't reproduce on either of VS2015 Update 1 or Update 2. (cl.exe
19.00.23506 or 19.00.23918)

**Comment by Araeos** [comment]
My specs are:
 - cl version 19.00.23918 using the native command prompt for x86
 - Installed Visual Studio 2015 Update 2 (Released march 30th)
 - Windows 10
 - And if it matters in any way python 3.5.1
 - Using ninja branch release (commit 484c16336f19bd8970bb6e75322d61b92a229899)

When I posted this issue I was using update 1, but installing update 2 did not change this behaviour.
If this issue is not reproducable, how would my system differ when using the native tools command prompt? Maybe its the directx sdk (June 2010) or the Windows SDK for 8.1 (not maintained anymore).

**Comment by sgraham** [comment]
Oh. Yes, broken at 1.6.0, fixed at head. I think
https://github.com/ninja-build/ninja/commit/a4327b9fb07f1ea678e92c1f06aeb22c129827e2
probably.

**Comment by Araeos** [comment]
I cannot build the version you mentioned, but compiling the master (78f548880e549c701bd77760e4b3f3a4ee147641) works without issues.

**Comment by nico** [comment]
Sounds like this is done. We'll have a new release soon (hopefully next week).
