### ISSUE TITLE
Add a "one file" mode that builds the output of a single file

### ISSUE THREAD

**Issue by evmar** [ninja-build/ninja#113]
Like ctl-f7 in MSVC.

**Comment by Hi-Angel** [comment]
> This is trivial to implement, so I'll do it now!
> 
> "Hard" questions though:
> 
> * What should the syntax be?  Options are (1) magic flag, (2) something like "foobar.cc^" meaning the output of foobar.cc.  2 is cuter to me but 1 is probably less confusing.
> * What are the exact semantics?  If a file has multiple outputs, do we only build one or all?
> 
> I think it's actually possible to do this without any special ninja support:
> 
> ```
> $ ninja -t query src/ninja.cc
> src/ninja.cc:
>   output: cxx
>     build/ninja.o
> ```
> 
> Something could just as well parse that. But that's no fun.

Doesn't work for me. I've used this to test whether a file compiles, and it gave an output like yours. So relaxed I ran build of the full target, and then after a while it failed on that exact file.



> Fixed.

Is there a particular command I can use now?
