### ISSUE TITLE
[Windows] Permission denied error when opening the build log

### ISSUE THREAD

**Issue by ldionne** [ninja-build/ninja#1132]
I have an issue which might be a problem with Ninja, or a problem with CMake, or a problem with Windows. But my best guess is that it's a problem with Ninja on Windows, so I'm asking here first.

Basically, the issue arises when building the same target over and over. It keeps on working and rebuilding the target (as expected), but at the 53rd rebuild, it fails with an error `ninja: error: opening build log: Permission denied`.

The exact issue can be reproduced with the following CMakeLists file:

```cmake
cmake_minimum_required(VERSION 3.1)
find_package(Ruby 2.1)

file(WRITE main.cpp "int main() { }\n")
add_executable(main main.cpp)
add_custom_target(make_main
    COMMAND ${RUBY_EXECUTABLE} -r time -r fileutils
        -e "100.times do |i|"
        -e "  puts %{#{i+1}th time}"
        -e "  FileUtils.touch('main.cpp', mtime: Time.now+1)"
        -e "  output = `\"${CMAKE_COMMAND}\" --build \"${CMAKE_BINARY_DIR}\" --target main`"
        -e "  raise output if not $?.success?"
        -e "end"
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    VERBATIM
)
```

In case you don't know CMake, we're creating an executable target and then another target that's going to build the executable target over and over (100 times). We use Ruby for this, but it's just because I suck at scripting the Windows command line. Notice that we touch the `main.cpp` file to make sure the executable target is rebuilt every time; otherwise Ninja will just build the target once, and rightfully so.

To reproduce, just paste the above code in a `CMakeLists.txt` file and issue

```sh
mkdir build
cd build
cmake .. -GNinja
cmake --build . --target make_main
```

This works perfectly on Linux, but fails (consistently) after the 52nd rebuild on Windows. You can see a sample run of the above on our Appveyor build, [here](https://ci.appveyor.com/project/ldionne/metabench/build/1.0.479/job/nakb6953633u641t#L54).

For cross-referencing purposes, this issue started off in ldionne/metabench#109.

**Comment by ldionne** [comment]
Oh yeah, and the version we're having problems with is Ninja 1.6.0. Also, here are some things I tried:

- Instead of running Ninja over and over from within Ninja (via the build files generated by CMake), if we just create an executable target and then build it many times via a normal shell script, everything works fine. This was tested [here](https://ci.appveyor.com/project/ldionne/metabench/build/1.0.481/job/qy11tk2uxm4bf757).

- If we don't touch the `main.cpp` file, Ninja does not rebuild the executable target and it never fails even if we ask Ninja to rebuild it 100 times. Tested [here](https://ci.appveyor.com/project/ldionne/metabench/build/1.0.482/job/eo8y73gcqt60mk2s).

- If we sleep 2 seconds between each rebuild, it still fails with the same error. So it does not appear to be caused by some strange interaction between time stamps, Ninja and the filesystem (we've had that). This was tested [here](https://ci.appveyor.com/project/ldionne/metabench/build/1.0.483/job/l2vyawi983sau7m0).

I'll be immensely grateful for any pointers; I've been looking at this bug for a couple of days and this is blocking an important PR on our part.

**Comment by nico** [comment]
Wow, thanks for the great repro! I'll look at this a bit now.

**Comment by nico** [comment]
Hm, I can't reproduce. Since I don't have ruby on my Windows box, I ran this script instead:

```
@echo off
for /l %%i in (0, 1, 100) do (
  echo %%i th time
  touch main.cpp
  ninja main
  sleep 1
)
```

(The `sleep 1` is needed since ninja doesn't implement high-res timestamps -- there's a bug for that somewhere. Without it, only every 10th build or so actually does something.) This builds main fine 100 times on my system. I also tried using `cmake.exe --build . --target main` instead of `ninja main`.

Can you repro this locally, or do you only see it on appveyor?

**Comment by nico** [comment]
Ooooh I see, you're saying you're creating a cmake project that has a target that runs ninja, and then you call that via ninja!

In that setup the two ninjas share one build directory, right? That probably won't work very well: Ninja puts some files to keep state into the build dir (.ninja_log and .ninja_deps), and the outer and inner ninjas will fight for writing to these files. We're somewhat careful about this, and the two ninja processes shouldn't corrupt each other's state and nothing should crash (this used to be not true in older versions), but I'm guessing that there's some OS file locking thing going on here.

Ninja isn't designed to be used in "recursive" mode -- it's designed to load the whole build graph at startup, and to have a single ninja process in charge of everything. Ideally, you'd manage to do things in that setup. That way, parallelism will work better, progress output will be correct, ninja can make better scheduling decisions, etc.

If you do need a recursive ninja call for some reason (you should try to not need this, really), then try giving that its own build directory (-C flag), then this specific problem should go away. But

**Comment by ldionne** [comment]
Thanks for the insight.

> Can you repro this locally, or do you only see it on appveyor?

No, as I said in the first point above, I can't reproduce it if I run Ninja in a loop from the command line. It only triggers if Ninja is running Ninja.

> If you do need a recursive ninja call for some reason (you should try to not need this, really), then try giving that its own build directory (-C flag), then this specific problem should go away.

I'll give this a try. We really have to run Ninja from within Ninja for our project. It's not a normal build system setup (otherwise I would agree that our setup is twisted as hell), it's a CMake module to perform compile-time benchmarks for C++ metaprogramming libraries.

**Comment by martine** [comment]
The one piece that might not be obvious about Ninja versus Make is that it writes some state to the build directory (for example, it notes the command lines that were used to produce outputs so it can rebuild them when the command lines change).  For this reason if you're doing any temporary builds you should use a new build directory for each, so that this metadata can be tossed out when you're done.

**Comment by ldionne** [comment]
Hmm, I understand how that makes sense from your side of things. From our side of things, what we need is to create CMake executable targets in the current project, and also CMake custom targets to build these executable targets in the current project. The custom targets basically compile the executable targets a bunch of time and they gather compilation statistics (compile-time and executable size, right now). It's important that all of these targets appear in the same CMake project, so that they can be manipulated by the users of our CMake module. Now, the only way I see of doing this is as we do currently (or to significantly change the design of our module and make it less easy to interact with from a CMake perspective, which is not acceptable).

Is there _any_ way to make Ninja reentrant? Like disabling the usage of the build log or something else?

**Comment by nico** [comment]
No. (Well, it's _mostly_ reentrant, except if two ninjas write to the log at the same time on Windows.)

Do you have to do the build in the same build dir? Could you run cmake in a different build dir for certain targets to create new ninja files there? I.e. don't run `cmake build` but run full-on `cmake -GNinja` for a subtarget somewhere?

**Comment by ldionne** [comment]
> No. (Well, it's mostly reentrant, except if two ninjas write to the log at the same time on Windows.)

Well so it's not reentrant on Windows. I mean it's definitely a justifiable design choice and I agree with the rationale you explained above, but let's not play with words.

> Do you have to do the build in the same build dir? Could you run cmake in a different build dir for certain targets to create new ninja files there? I.e. don't run cmake build but run full-on cmake -GNinja for a subtarget somewhere?

I understand your suggestion. However, that means defining the executable target (the one which is being benchmarked in our case) in a different CMake project. This, unfortunately, is not a solution because we support setting custom properties (includes paths, compiler flags, etc..) on a per-target basis, and that requires the target being part of the same CMake project (AFAIK).

**Comment by nico** [comment]
I think you can pass in includes compiler flags etc to cmake via `-DCMAKE_C_FLAGS`, and I think you can read the current cflags in cmake via `${CMAKE_C_FLAGS}`, so it seems (handwavily) possible to pass on your compiler flags to a sub-cmake.

**Comment by ldionne** [comment]
Reading the flags set on a per target basis is more tricky, and I'm not sure it's going to be possible to pass them out and then into another CMake project in a cross-platform way, i.e. without assuming some syntax of compiler options. But that's in my hands, and I'll look into it to confirm it's not possible (hooray if I'm wrong).

I understand that we're using Ninja in an unusual way, and that you can't accommodate us. Thanks for the help and prompt replies anyway!

**Comment by SpearThruster** [comment]
Any progress on this issue?

**Comment by KUGA2** [comment]
I get the same error for the same reason.

First of all: Nice reproduction, however you should add `USES_TERMINAL` to `add_custom_target` for better logging.

Then, well, according to the discussion you should never run ninja from ninja. To avoid this (and keep all the code together) you should maybe configure the ruby script to the build directory and run it there manually. This may be an "OK" workaround:

    cmake_minimum_required(VERSION 3.1)
    
    file(WRITE main.cpp "int main() { }\n")
    add_executable(main main.cpp)
    
    file(WRITE make_main.rb
    "require 'fileutils'
    100.times do |i|
      puts %{#{i+1}th time}
      FileUtils.touch('main.cpp', mtime: Time.now+1)
      output = `\"${CMAKE_COMMAND}\" --build \"${CMAKE_BINARY_DIR}\" --target main`
      raise output if not $?.success?
    end"
    )

Results in:

    C:\tmp\ninja_reentrant>cmake -GNinja .
    -- The C compiler identification is MSVC 16.0.40219.1
    ...
    C:\tmp\ninja_reentrant>ninja
    [2/2] Linking CXX executable main.exe
    C:\tmp\ninja_reentrant>ruby make_main.rb
    1th time
    ...
    100th time

PS: I would use a CMake Script instead of ruby to avoid more dependencies. But thats just my preference.
