### ISSUE TITLE
Regression from #999: NINJA_STATUS %e on dumb terminals starts from epoch 

### ISSUE THREAD

**Issue by colincross** [ninja-build/ninja#1146]
#999 made dumb terminals only output when edges finish.  BuildStatus::overall_rate_ stopwatch is only initialized to the current time when PrintStatus is called with finished_edges_ == 0, but on a dumb terminal it will be called for the first time when finished_edge_ = 1, which results in very long elapsed times:
NINJA_STATUS="[%r processes, %f/%t @ %o/s : %es ] "
[0 processes, 2/2 @ 0.0/s : 1461869902.367s ]

**Comment by gkistanova** [comment]
I do not see how to re-open this issue.
It is still open with the current trunk. The fix is in the https://github.com/ninja-build/ninja/pull/1174.

**Comment by randomascii** [comment]
Any estimates for when this might roll out in a release? It makes build performance testing require a whole mess of math.

**Comment by nico** [comment]
I'll try to do a minor release this or next week. If nothing has happened in eight days, please ping me.
