### ISSUE TITLE
Building of Static Library fails with Cmake 3.5.2

### ISSUE THREAD

**Issue by Talarion83** [ninja-build/ninja#1160]
Hi,

I'm trying to post this here, while I hope this is not a CMake problem. I have a project where I cross compile with cmake and ninja. The resulting build fails as soon as i use any ADD_LIBRARY. Here is the resulting build.ninja file:

build lib/src/libctrl.a: CXX_STATIC_LIBRARY_LINKER__ctrl lib/src/CMakeFiles/ctrl.dir/ctrl_lib.cpp.obj
  LANGUAGE_COMPILE_FLAGS = -DMIPS=1 -DMIPS24KF=1 -DCLI_WITH_DISABLE_CLOCK_INT=1 -DMIPS24KF_64BIT_FPU=1 -DACE_ARMCPP -DACE_LACKS_PRAGMA_ONCE -DTARGET -DDO_NOT_USE_BOOST -O3 -Acpu(24k) -mtune=24kf -mips32r2 -mfp64 -fno-jump-tables -fno-exceptions -fcheck-new -fsigned-char -fno-rtti -fno-common -G0 -mno-gpopt -EL -fno-math-errno -fno-finite-math-only -fno-rounding-math -mhard-float  -Wformat -Wno-write-strings -Wimplicit -Wunused-function -Wunused-value -Wno-invalid-offsetof -Wsign-compare -Wdeprecated -Wno-pmf-conversions -Werror=enum-compare -Werror=return-type
  OBJECT_DIR = lib\src\CMakeFiles\ctrl.dir
  POST_BUILD = cd .
  PRE_LINK = cd .
  TARGET_COMPILE_PDB = lib\src\CMakeFiles\ctrl.dir\
  TARGET_FILE = lib\src\libctrl.a
  TARGET_PDB = lib\src\libctrl.pdb

This seems fine to me. I do not know how these build files work exactly but everything i see seems to make sense. But the resulting command, when I execute ninja (both 1.7.1 and 1.6) looks as follows:

[2/2] cmd.exe /C "cd . && "C:\Program Files (x86)\CMake\bin\cmake.exe" -E remove lib\src\libctrl.a && D:\gcc\win32\mips-sde-elf\bin\mips-sde-elf-ar.exe qc lib\src\libctrl.a  lib/src/CMakeFiles/ctrl.dir/ctrl_lib.cpp.obj && : lib\src\libctrl.a && cd ."

FAILED: cmd.exe /C "cd . && "C:\Program Files (x86)\CMake\bin\cmake.exe" -E remove lib\src\libctrl.a && D:\gcc\win32\mips-sde-elf\bin\mips-sde-elf-ar.exe qc lib\src\libctrl.a  lib/src/CMakeFiles/ctrl.dir/ctrl_lib.cpp.obj && : lib\src\libctrl.a && cd ."

It seems weird that we do a cd . before and after the build but ok. What does fail is the command that starts with a colon.

Thanks
Michael

**Comment by ScottBailey** [comment]
I believe this is a CMake problem.

I'm not exactly sure where the problem is, but I'd start by looking at
cmNinjaNormalTargetGenerator::ComputeLinkCommand().

Best luck!

SB

On Fri, Jun 3, 2016 at 6:47 AM, Talarion83 <notifications@github.com> wrote:

> Hi,
>
> I'm trying to post this here, while I hope this is not a CMake problem. I
> have a project where I cross compile with cmake and ninja. The resulting
> build fails as soon as i use any ADD_LIBRARY. Here is the resulting
> build.ninja file:
>
> build lib/src/libctrl.a: CXX_STATIC_LIBRARY_LINKER__ctrl
> lib/src/CMakeFiles/ctrl.dir/ctrl_lib.cpp.obj
> LANGUAGE_COMPILE_FLAGS = -DMIPS=1 -DMIPS24KF=1
> -DCLI_WITH_DISABLE_CLOCK_INT=1 -DMIPS24KF_64BIT_FPU=1 -DACE_ARMCPP
> -DACE_LACKS_PRAGMA_ONCE -DTARGET -DDO_NOT_USE_BOOST -O3 -Acpu(24k)
> -mtune=24kf -mips32r2 -mfp64 -fno-jump-tables -fno-exceptions -fcheck-new
> -fsigned-char -fno-rtti -fno-common -G0 -mno-gpopt -EL -fno-math-errno
> -fno-finite-math-only -fno-rounding-math -mhard-float -Wformat
> -Wno-write-strings -Wimplicit -Wunused-function -Wunused-value
> -Wno-invalid-offsetof -Wsign-compare -Wdeprecated -Wno-pmf-conversions
> -Werror=enum-compare -Werror=return-type
> OBJECT_DIR = lib\src\CMakeFiles\ctrl.dir
> POST_BUILD = cd .
> PRE_LINK = cd .
> TARGET_COMPILE_PDB = lib\src\CMakeFiles\ctrl.dir\
> TARGET_FILE = lib\src\libctrl.a
> TARGET_PDB = lib\src\libctrl.pdb
>
> This seems fine to me. I do not know how these build files work exactly
> but everything i see seems to make sense. But the resulting command, when I
> execute ninja (both 1.7.1 and 1.6) looks as follows:
>
> [2/2] cmd.exe /C "cd . && "C:\Program Files (x86)\CMake\bin\cmake.exe" -E
> remove lib\src\libctrl.a &&
> D:\gcc\win32\mips-sde-elf\bin\mips-sde-elf-ar.exe qc lib\src\libctrl.a
> lib/src/CMakeFiles/ctrl.dir/ctrl_lib.cpp.obj && : lib\src\libctrl.a && cd ."
>
> FAILED: cmd.exe /C "cd . && "C:\Program Files (x86)\CMake\bin\cmake.exe"
> -E remove lib\src\libctrl.a &&
> D:\gcc\win32\mips-sde-elf\bin\mips-sde-elf-ar.exe qc lib\src\libctrl.a
> lib/src/CMakeFiles/ctrl.dir/ctrl_lib.cpp.obj && : lib\src\libctrl.a && cd ."
>
> It seems weird that we do a cd . before and after the build but ok. What
> does fail is the command that starts with a colon.
>
> Thanks
> Michael
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ninja-build/ninja/issues/1160>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAXP9a36BVISAwRs2txXCOH5wp64lsnMks5qIDBbgaJpZM4ItjCp>
> .
>



-- 
Scott Bailey

**Comment by Talarion83** [comment]
Thanks for the answer. I would like to start by finding out what's wrong with my build.ninja. Cause I do not see a reason why it would add that additional command between the actual linking and the POST_BUILD. If I remove that and execute the command manually, everything is fine and the library gets linked.
Where would I find cmNinjaNormalTargetGenerator::ComputeLinkCommand() ?

**Comment by ScottBailey** [comment]
grep for it in the CMake source.  (See https://cmake.org/download/)

However, I see CMake 3.6.0-rc1 is available.  You should probably test vs
3.6.0 and write your bug (and patch?) against that...

SB

On Sat, Jun 4, 2016 at 3:07 AM, Talarion83 <notifications@github.com> wrote:

> Thanks for the answer. I would like to start by finding out what's wrong
> with my build.ninja. Cause I do not see a reason why it would add that
> additional command between the actual linking and the POST_BUILD. If I
> remove that and execute the command manually, everything is fine and the
> library gets linked.
> Where would I find cmNinjaNormalTargetGenerator::ComputeLinkCommand() ?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/ninja-build/ninja/issues/1160#issuecomment-223747725>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAXP9TBkwRnlpP1yS03-o3i5Ora6fnZSks5qIU5vgaJpZM4ItjCp>
> .
>



-- 
Scott Bailey

**Comment by martine** [comment]
Ninja just executes the commands you give it, so this is definitely a problem in either cmake or your build environment.

The command line comes from the rule definition of `CXX_STATIC_LIBRARY_LINKER__ctrl` (the first thing after the colon in the build line), which will be defined in one of your other .ninja files.  Perhaps the colon you're seeing is the expansion of a variable that is getting mangled for some reason.

Just a guess, but from the command you're using here it looks like it's trying to express some postprocessing step on the `.a` file, but some layer might think it's running on Unix and trying to write a command using the `:` builtin, which doesn't exist on Windows?

**Comment by martine** [comment]
One more thing to try is using Makefiles from CMake, as that will pin down better where the issue lies.

**Comment by moberhuber** [comment]
I've run into something similar, when cross-compiling a sharedlib with "version" property with Ninja on Windows. I think it's a defect in cmake and I've filed an issue:

https://gitlab.kitware.com/cmake/cmake/issues/16393

Let's see what the cmake gurus say...

**Comment by moberhuber** [comment]
For the records, this issue did turn out to be a cmake problem, and it was fixed:
https://gitlab.kitware.com/cmake/cmake/commit/ea59867187e8bdb8a7ffda37ad58e7f8493ebf7c
