### ISSUE TITLE
browse option appears to have XSS vulnerability

### ISSUE THREAD

**Issue by randomascii** [ninja-build/ninja#1167]
After leaving "ninja -t browse" running I received this report:

"The remote host is running a web server that fails to adequately sanitize request strings of malicious JavaScript.  By leveraging this issue, an attacker may be able to cause arbitrary HTML and script code to be executed in a user's browser within the security context of the affected site."

I assume that this refers to the server created by ninja's browse feature. This is all I know.

**Comment by nico** [comment]
I think #1157 fixed this. Please reopen if this is something else.
