### ISSUE TITLE
after build, how to install?

### ISSUE THREAD

**Issue by 8l** [ninja-build/ninja#1171]
Hi, 

after build llvm with ninja, how to install llvm to /usr?
search ninja manual, couldn't find the information.

TIA

**Comment by ScottBailey** [comment]
install the executable:

   sudo cp ninja /usr/local/bin

and add the following to your ~/.bashrc file:

   # nice printing for ninja and bash tab completion
   export NINJA_STATUS="[%p %s/%t] "
  . <location of ninja's bash completion file>



On Thu, Jul 7, 2016 at 1:49 PM, 8l <notifications@github.com> wrote:

> Hi,
>
> after build llvm with ninja, how to install llvm to /usr?
> search ninja manual, couldn't find the information.
>
> TIA
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ninja-build/ninja/issues/1171>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAXP9ZnoUl0PhsoIZ2j-R-CGTf9tX6p7ks5qTWZKgaJpZM4JHfDZ>
> .
>



-- 
Scott Bailey

**Comment by martine** [comment]
Ninja just runs the commands it's instructed to.  To install LLVM as built with CMake, see the LLVM and CMake documentation.

**Comment by 8l** [comment]
Thanks for the reply, but sorry not helpful.

if i build default cmake without ninja, i can install llvm without any problem.
but built llvm with ninja, still i couldn't install llvm to /usr.

anyway, until find the info, i fallback to default cmake and make.

**Comment by dmerejkowsky** [comment]
You did not say what issue you were having. Can you share an error message?

But I think what @martine was trying to say is that's it's likely not a ninja bug.

**Comment by martine** [comment]
You should file this bug in the cmake or llvm tracker.  I'm sure they can help you!  :)

**Comment by honggyukim** [comment]
Hi @8l, it's very old issue but `ninja install` does installation job after `llvm` build.

**Comment by fenglc** [comment]
```
$ cmake . -DCMAKE_INSTALL_PREFIX=~/xxx/devlibs -G Ninja
$ ninja
$ ninja install
```
