### ISSUE TITLE
WindowsError: [Error 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by adrya407** [ninja-build/ninja#1179]
C:\Users\UserName\Desktop\ninja-master>python configure.py
Traceback (most recent call last):
  File "configure.py", line 320, in <module>
    if platform.msvc_needs_fs():
  File "configure.py", line 84, in msvc_needs_fs
    stderr=subprocess.PIPE)
  File "D:\ts_mirr\python\2.7.9_2\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "D:\ts_mirr\python\2.7.9_2\lib\subprocess.py", line 958, in _execute_chil
d
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Comment by evmar** [comment]
Looks like this is trying to run `cl`.  We should make the error message better, but to solve your problem you should read the Windows build instructions: https://github.com/ninja-build/ninja/blob/master/HACKING.md#building-for-windows

**Comment by adrya407** [comment]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE>python "c:\Users\UserName\Desktop\ninja-master\configure.py" --bootstrap
Traceback (most recent call last):
  File "c:\Users\UserName\Desktop\ninja-master\configure.py", line 229, in <module>
    ninja_writer = ninja_syntax.Writer(open(BUILD_FILENAME, 'w'))
IOError: [Errno 13] Permission denied: 'build.ninja'

Running from visual studio environment would lead me to this error (the file build.ninja is not open). If i modify in the code of configure.py at line 228 and set the BUILD_FILENAME with absolute path, i came back to my previous error:

**Comment by sgraham** [comment]
You want to be in the ninja directory when running it, otherwise it'll generate the build files in the VS directory, which isn't what you want.

So, 

C:\Users\UserName\Desktop\ninja-master>"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"

C:\Users\UserName\Desktop\ninja-master>python configure.py --bootstrap

**Comment by adrya407** [comment]
Thank you! This worked. A suggestion would be to provide for the user a set of "fixes" for specific errors, or a stept by step instalation tutorial.

**Comment by sgraham** [comment]
If you're just using ninja, you can also get the binaries from https://github.com/ninja-build/ninja/releases as described in the readme.
