### ISSUE TITLE
Using gcovr with ninja and CMake

### ISSUE THREAD

**Issue by anderspitman** [ninja-build/ninja#1183]
When building a C++ project with CMake using GNU make, I'm able to run [gcovr](http://gcovr.com/guide.html), a gcov wrapper, from the root of my repo and everything works automagically. However, when using ninja, Some files don't seem to be where gcovr expects them. I know that the gcov files generated by gcc depend on the directory where gcc was run. So I suspect that what's happening is make and ninja have fundamentally different approaches to managing the working directory, ie one of them always cd's into the individual directories and the other doesn't, or some similar issue. But I figured I would ask before assuming that's my problem. Is this the case?

**Comment by nico** [comment]
Ninja doesn't do any cd'ing automatically. Make doesn't either, as far as I know.

Maybe this is a cmake issue? I've run gcov on ninja itself successfully.

As-is, this issue doesn't have enough data to say anything conclusive :-)

**Comment by anderspitman** [comment]
Excellent, that's what I needed to know. Thanks!
