### ISSUE TITLE
The newest binary version of ninja doesn't support for Windows XP.

### ISSUE THREAD

**Issue by lygstate** [ninja-build/ninja#1207]
Make sure the subsystem to be 5.01

**Comment by nico** [comment]
What exactly is broken, and what do I need to change to fix that? What's the last version that works on XP?

**Comment by lygstate** [comment]
XP would report error about invalid executable

**Comment by gavanderhoorn** [comment]
I've had to use ninja on a Windows XP system recently and had to go back to version `1.6.0` for it t work. More recent builds seem to have the `subsystem` set to a value `> 5.01` which isn't XP compatible.

Not sure how much you want to accomodate us poor sods that have to deal with XP, but for my own builds I have to add `/SUBSYSTEM:WINDOWS,"5.01"` to my CMake linker flags to get things going again.

See [C/C++ Building Reference > Linking > Linker Options - /SUBSYSTEM (Specify Subsystem)](https://msdn.microsoft.com/en-us/library/fcc1zstk.aspx) for some info on `subsystem`.

**Comment by AS383** [comment]
On ReactOS I have the same problem: BAD_EXE_FORMAT. If I compile Ninja from source it's binary is large (~5 Mb).

**Comment by jhasse** [comment]
Since there haven't been updates to XP since June 2017, I think it's okay if the latest Ninja doesn't work there. Please use 1.6 or compile from source if you need it.
