### ISSUE TITLE
copyright is missing

### ISSUE THREAD

**Issue by dfroger** [ninja-build/ninja#1212]
The actual [copyright](https://github.com/ninja-build/ninja/blob/3082aa69b7be2a2a0607441a7a2615d78aa983d7/COPYING#L190) is missing:

    Copyright [yyyy] [name of copyright owner]

**Comment by dfroger** [comment]
Thanks!

**Comment by julian-klode** [comment]
Just saw this. This is not supposed to happen. You are supposed to take the template and put it into the source code with the stuff expanded, not modify the license file.

**Comment by nico** [comment]
Oh, sorry. I'll revert that change again, thanks for pointing this out.
