### ISSUE TITLE
Ninja in verbose mode fails smart terminal capabilities

### ISSUE THREAD

**Issue by dvdhrm** [ninja-build/ninja#1214]
Hey

Using `ninja -v` fails to use smart-terminal capabilities. The easiest way to reproduce is using gcc color output. It works fine in normal mode (`ninja`), but is stripped in verbose mode (`ninja -v`).

Looking at `build.cc`:

```cc
    // ninja sets stdout and stderr of subprocesses to a pipe, to be able to
    // check if the output is empty. Some compilers, e.g. clang, check
    // isatty(stderr) to decide if they should print colored output.
    // To make it possible to use colored output with ninja, subprocesses should
    // be run with a flag that forces them to always print color escape codes.
    // To make sure these escape codes don't show up in a file if ninja's output
    // is piped to a file, ninja strips ansi escape codes again if it's not
    // writing to a |smart_terminal_|.
    // (Launching subprocesses in pseudo ttys doesn't work because there are
    // only a few hundred available on some systems, and ninja can launch
    // thousands of parallel compile commands.)
    // TODO: There should be a flag to disable escape code stripping.
    string final_output;
    if (!printer_.is_smart_terminal())
      final_output = StripAnsiEscapeCodes(output);
    else
      final_output = output;
    printer_.PrintOnNewLine(final_output);
```

The comment is correct, and I understand the logic there. Only problem is, using `-v` causes `set_smart_terminal(false)`. I think merging the `verbose` logic into the `smart-terminal` logic is the culprit. If it was two flags, one `smart-terminal` flag which tells whether escape-codes should be stripped, and a `verbose` flag, telling whether **ninja** should make use of escape-codes, this would work. Could also be combined into a tri-state.

If verbose-mode is not supposed to do coloring, feel free to close this. It seems counter-intuitive to me, though.

Thanks
David

**Comment by jhasse** [comment]
> It seems counter-intuitive to me, though.

I agree. "verbose" doesn't sound like something would be stripped from the output ;)

Thanks for the report, I've fixed this using two flags, as you suggested. I've also added a new Python script `misc/output_test.py` which checks that this works correctly and runs on Travis CI.

**Comment by dvdhrm** [comment]
Thanks a lot!
