### ISSUE TITLE
Ninja fails when run under ConEmu?

### ISSUE THREAD

**Issue by mtwilliams** [ninja-build/ninja#1221]
Hi,

Unfortunately, I've run into this perplexing issue. I never encountered this before, until suddenly, one day I was receiving errors like:

```
$ ninja -j 1
[1/5] ninja -t msvc -e _build/yeti_debug_windows_x86_64.env_block -- link.exe @_build/bin/yeti_debug_windows_64.dll.rsp
FAILED: _build/bin/yeti_debug_windows_64.dll
ninja -t msvc -e _build/yeti_debug_windows_x86_64.env_block -- link.exe @_build/bin/yeti_debug_windows_64.dll.rsp
ninja: fatal: CreateProcess: The parameter is incorrect.

ninja: build stopped: subcommand failed.
```

When running `ninja` under a MinGW console (shell).

However, when I run `ninja` under plain ol' `cmd.exe`... it works perfectly.

**Comment by evmar** [comment]
Looking around online I see some discussion about a bad PATH environment variable (maybe referencing a nonexistent directory?).  Can you check yours?

**Comment by mtwilliams** [comment]
Certainly. I'll give it look (and play around) when I get the chance.

**Comment by mtwilliams** [comment]
Looks like it's ConEmu that's the causing the problem here, specifically the following three additions to `PATH`:

```
/c/Program Files/ConEmu/ConEmu/Scripts
/c/Program Files/ConEmu
/c/Program Files/ConEmu/ConEmu
```

**Comment by jhasse** [comment]
Do you think ninja can do anything about that?

**Comment by mtwilliams** [comment]
May be worth sanitizing Unix-style paths on Windows?

**Comment by Kazark** [comment]
I run Ninja in ConEmu and have no problems. But I'm not running MinGW. I'm running it through PowerShell. This does seem more related to MinGW than ConEmu to me.

**Comment by jhasse** [comment]
> May be worth sanitizing Unix-style paths on Windows?

`c:/Program Files/ConEmu/ConEmu/Scripts` should work (Windows supports forward slashes as path seperators), it's `/c` vs `c:` that's causing problems.

I'm using Ninja with MinGW just fine, so it really seems to be ConEmu shouldn't add those paths there (I guess the other paths in `PATH` use `c:`?)

**Comment by mtwilliams** [comment]
Other paths do, yes. I've just given up on ConEmu.

**Comment by nico** [comment]
Sounds like the consensus is that this is a conemu bug.
