### ISSUE TITLE
can not find "Ninja" when working with cmake

### ISSUE THREAD

**Issue by BeLearner** [ninja-build/ninja#1222]
When I type command

*cmake -GNinja /path/to/project*

I get the error:

*CMake Error: CMake was unable to find a build program corresponding to "Ninja". CMAKE_MAKE_PROGRAM is not set. You probably need to select a different build tool.*

when I copy the executable program "ninja" to */usr/local/bin/ninja*(*not /usr/local/bin/Ninja*),cmake works well.So I suggest that add command

 *cp ninja /usr/local/bin/ninja*

 after executing command:

*./configure.py --bootstrap*

in file README

**Comment by nico** [comment]
`cmake -GNinja` assumes that ninja is in PATH. I think most folks get ninja from https://github.com/ninja-build/ninja/releases , so I'm not sure if making configure print this would help much (and it'd be fairly unusual). Seems more like something to be documented on the cmake side.
