### ISSUE TITLE
Building Ninja in Cygwin

### ISSUE THREAD

**Issue by TheClockworker** [ninja-build/ninja#1238]
I'm having great difficulty building Ninja in Cygwin. It says that it requires re2c which also doesn't build properly. Please help....

**Comment by sgraham** [comment]
You shouldn't need re2c unless you're changing the parser (i.e. the message is a warning, not an error).

However, I would not recommend using a cygwin binary, instead build with real Windows and use that binary from cygwin if you must use it in a cygwin context.

**Comment by TheClockworker** [comment]
Thank you, your advice worked on my end.
