### ISSUE TITLE
bash freezes while building projects in MSYS2 (triggered by rescaling the window)

### ISSUE THREAD

**Issue by Ede123** [ninja-build/ninja#1256]
(this is a cross posting of Alexpux/MINGW-packages/issues/2246)

> When using the MSYS2 version of ninja (mingw64-w64-ninja) to build projects inside an MSYS2 shell (bash based on Cygwin) the console window freezes as soon as I try to resize it.
>
>While the build proceeds uninterrupted in background, the console window becomes unresponsive, Windows marks it as "Not Responding" and grays it out, and a waiting cursor is displayed when hovering over it.
>
>When the build finishes (sometimes - but seldom - also in some build steps in between) all output is produced at once.
>
>When using the same ninja.exe from a normal Windows cmd.exe window and building the same project the issue does not happen. cmd.exe stays responsive and outputs continuously.
>
>One thing I noticed: When using the MinGW shell ninja outputs one line for each build job. Executing the same command in cmd.exe all commands are output on the same line (the line changes dynamically). Maybe this is related?

Would you have any idea what is going on? I'm happy in helping to debug / test, but I have no idea were I could start...

**Comment by jhasse** [comment]
Can you try running `ninja` in `fish` instead of `bash`?

Also try running it through `winpty` (`winpty ninja`).

**Comment by Ede123** [comment]
Issue seems to be mostly fixed now.

The dialog still freezes for a few seconds but updates shortly after, not sure which update caused the improvement.
