### ISSUE TITLE
ninja clean fails

### ISSUE THREAD

**Issue by paulharris** [ninja-build/ninja#1257]
I have built ninja 1.7.2 from git, and have *not* installed it in /usr/bin

I see this behaviour:
$ ninja clean
[1/1] Cleaning all built files...
FAILED: clean 
/usr/bin/ninja -t clean
/bin/sh: 1: /usr/bin/ninja: not found
ninja: build stopped: subcommand failed.

Yes, I can run ninja -t clean,
but seems strange that ninja may end up calling a different version of itself.

cheers,
Paul

**Comment by NiklasRosenstein** [comment]
How is your `clean` target defined?

**Comment by paulharris** [comment]
Uuuh, oh yeah... its generated by cmake so I guess its actually cmake's fault...

**Comment by nico** [comment]
Yes, this sounds like a downstream issue somewhere :-)
