### ISSUE TITLE
Not all code has been clang-format'ed?

### ISSUE THREAD

**Issue by rookie1024** [ninja-build/ninja#1259]
I'm not sure if this is because of how I've personally configured clang-format (although `~/.clang-format` shouldn't be a problem, right?) or if it's because clang-format is just not run before files are committed, but when I ran clang-format in-place over the `src/` directory (except *.in.cc) it made changes in 70 different files.

Not that this is a huge problem, but I'm currently editing files and I keep noticing that when I format a file, it's not just my code that gets changed.

**Comment by nico** [comment]
Yes, the .clang-format is there to help with new code, I didn't reformat everything.

If you use the git-clang-format script that comes with clang-format, it'll only format lines touched in your commits. So only your code should be changed if you use that, I think.

**Comment by rookie1024** [comment]
Okay.  I was only asking because I use a keybind for clang-format in VS Code, so I was caught off-guard by the entire file suddenly lighting up green and red.

**Comment by nico** [comment]
I really like http://llvm.org/viewvc/llvm-project?view=revision&revision=305665 where you can now configure vim to only format what you changed on save. Maybe something similar could be done for VS code.
