### ISSUE TITLE
Backslashes not escaped when using response files on Windows with GCC

### ISSUE THREAD

**Issue by ChilliScott** [ninja-build/ninja#1262]
It is quite an unusual compile path but I'm compiling on Windows using a GCC cross compiler. The issue occurs when using rspfile and rspfile_content where the contents are written to the rsp_file with backslash path separators. When GCC reads the response file the backslashes are not present (as they are not escaped) and the compiler/linker cannot find any of the files.

I'll see if I can fix it and submit a pull request if that would help. In the meantime I'll need to handle the response file generation manually to get round the issue

EDIT:

I forgot to mention that I tried escaping the file paths before passing them into rspfile_content but ultimately had no effect.

**Comment by ChilliScott** [comment]
Have realised that since I'm using GCC it works with Unix style paths (i.e. separated by forward slashes) so I've just changed the paths I'm feeding to rspfile_content to use '/' rather than '\'. Since it is unusual to be compiling with GCC on Windows and that GCC handles Unix paths this is probably not really an issue

**Comment by Lekensteyn** [comment]
Can you check whether #1342 solves the problem for you?

**Comment by jhasse** [comment]
Sorry for the delay. Can you rebase one more time? Thanks in advance!
