### ISSUE TITLE
GYP link to Chromium is broken

### ISSUE THREAD

**Issue by jtmcdole** [ninja-build/ninja#1263]
The manual links to the following page:
https://chromium.googlesource.com/chromium/src/+/master/docs/ninja_build.md

Which is a 404.

**Comment by nico** [comment]
@dpranke, you removed that file in https://codereview.chromium.org/2526563003 . (There are 2 other references to it https://cs.chromium.org/search/?q=ninja_build.md+package:%5Echromium$&type=cs). Do you think we should just remove that GYP paragraph from the ninja manual, or replace it with a GN paragraph (if so, where should that point?)?

**Comment by dpranke** [comment]
I would at the very least change that paragraph to talk about GN. It seems reasonable to *also* mention gyp, in which case I might link to https://gyp.gsrc.io.

And, we should update the other two references to ninja_build.md to point to something else as appropriate.

**Comment by jhasse** [comment]
See #1484.
