### ISSUE TITLE
Ninja on windows additional white lines

### ISSUE THREAD

**Issue by atsju** [ninja-build/ninja#1272]
Cmake 3.7.2
Ninja 1.7.2

When building with ninja (I was used to Unix Makefiles) under windows any warning, error or command will add an additional whyte empty line

An example being clearer:
```
[37/139] Building C object CMakeFiles/outHexFile_Release_storage.c.obj
[38/139] Building C object CMakeFiles/outHexFile_Release.elf.dir/C_/.../systick.c.obj
C:\...systick.c: In function 'xxx_init':

C:\.....systick.c:38:9: warning: 'return' with a value, in function returning void

  return -1; //TODO JST unimplemented function

         ^

C:\...........
```
Notice there is no white line when the print is issued by ninja ([37/139], [38/139])

**Comment by nico** [comment]
Which compiler are you using?

**Comment by atsju** [comment]
Arm-none-eabi-gcc (version from 2016 q4 if y remember correctly)

**Comment by nico** [comment]
Are you using the ninja binary from https://github.com/ninja-build/ninja/releases ? If not, did you build it under cygwin perchance?

**Comment by atsju** [comment]
Yes I am using the Windows binary from there

**Comment by nico** [comment]
I believe #1156 probably fixed this.
