### ISSUE TITLE
Default value for -j does not take into account CPU set limitation

### ISSUE THREAD

**Issue by r-darwish** [ninja-build/ninja#1278]
When running a Docker container with the `--cpuset-cpus=0` flags, the `nproc` command inside the container returns 1. However, when running `ninja --help` it seems that this limitation isn't taken into account by the default `-j` value: 

`-j N     run N jobs in parallel [default=10, derived from CPUs available]`.

**Comment by nico** [comment]
Would #1224 fix this?

**Comment by r-darwish** [comment]
Unfortunately no. I tried using your branch of ninja, as well as run this sample program inside a docker container ran with `--cpuset-cpus 0` (where the output of `nproc` is 1) and got "8" printed twice:

```
#include <unistd.h>
#include <iostream>

int main() {
        std::cout << sysconf(_SC_NPROCESSORS_ONLN) << std::endl;
        std::cout << sysconf(_SC_NPROCESSORS_CONF) << std::endl;
        return 0;
}
```

**Comment by nico** [comment]
Do other apps under docker handle this flag well? Is there some other sysconf we're supposed to check? Or is this a docker-side bug?

**Comment by r-darwish** [comment]
The `nproc` command shows the expected output, which is 1. I'm not sure that this is a bug Docker, but instead it is the fact that Docker uses namespacing instead of virtualization, so the real computer hardware information is exposed to the container despite the fact that it is limited to be scheduled only on one CPU. The actualy number of CPUs isn't hidden from the container by any means (if you run `htop` inside a container limited to a specific CPU you'd still see al the CPU information). After opening this issue [I asked in Stackoverflow](http://stackoverflow.com/questions/43845218/get-the-same-output-of-the-nproc-command-in-python?noredirect=1#comment74745250_43845218) how to achieve the same result of `nproc` using syscalls. However, the only answer I got was that it is a messy issue full of ifdefs and platform specific logic.

**Comment by jhasse** [comment]
Can you still reproduce this? On my machine (16 logical CPU cores), running

```sh
> docker run --cpuset-cpus=0 -t alpine /bin/sh -c "apk add ninja && ninja --help"
```

prints

```
  -j N     run N jobs in parallel [default=2, derived from CPUs available]
```

**Comment by kiwixz** [comment]
Unfortunately it only works on alpine, which seems to hide the real CPU count.

Examples on my 4 CPUs machine:
```
docker run --rm --cpuset-cpus=0 -t alpine /bin/sh -c "apk update; apk add ninja && ninja --help; nproc --all; nproc"

ninja defaults to 2
nproc --all: 1
nproc: 1
```

```
docker run --rm --cpuset-cpus=0 -t ubuntu /bin/sh -c "apt update && apt install ninja-build && ninja --help; nproc --all; nproc"

ninja defaults to 6
nproc --all: 4
nproc: 1
```

```
docker run --rm --cpuset-cpus=0 archlinux/base /bin/sh -c "pacman --noconfirm -Sy ninja && ninja --help; nproc --all; nproc"

ninja defaults to 6
nproc --all: 4
nproc: 1
```

**Comment by kiwixz** [comment]
BTW this is how nproc does it: https://github.com/coreutils/gnulib/blob/ddbd29c308b46cfba8a21d52d6e7a0dbd561bdbc/lib/nproc.c#L69

**Comment by jhasse** [comment]
Thanks! I've managed to fix it without introducing a dependency on pthread. Now we need some further testing, if this behaves the same when there's no CPU_SET limitation (it does on my system). Please check out the master branch and report results here, thanks :)

**Comment by nuxi** [comment]
According to the manpage, `sched_getaffinity()` and `CPU_COUNT()` are only available if `_GNU_SOURCE` is defined before including `sched.h`. So this new code isn't actually being enabled at build time.

ninja says it should go to 50:

```
bash-4.3# ninja -h
usage: ninja [options] [targets...]

if targets are unspecified, builds the 'default' target (see manual).

options:
  --version      print ninja version ("1.9.0")
  -v, --verbose  show all command lines while building

  -C DIR   change to DIR before doing anything else
  -f FILE  specify input build file [default=build.ninja]

  -j N     run N jobs in parallel (0 means infinity) [default=50 on this system]
  -k N     keep going until N jobs fail (0 means infinity) [default=1]
  -l N     do not start new jobs if the load average is greater than N
  -n       dry run (don't run commands but act like they succeeded)

  -d MODE  enable debugging (use '-d list' to list modes)
  -t TOOL  run a subtool (use '-t list' to list subtools)
    terminates toplevel options; further flags are passed to the tool
  -w FLAG  adjust warnings (use '-w list' to list warnings)
```

My cpuset only has 4 CPUs:

```
bash-4.3# grep Cpus_allowed /proc/self/status
Cpus_allowed:   0010,01001001
Cpus_allowed_list:      0,12,24,36
```

Assembly dump of `GetProcessorCount()` shows its still using `sysconf()`:

```
000000000041f780 <_Z17GetProcessorCountv>:
  41f780:       48 83 ec 08             sub    rsp,0x8
  41f784:       bf 54 00 00 00          mov    edi,0x54
  41f789:       e8 12 33 fe ff          call   402aa0 <sysconf@plt>
  41f78e:       48 83 c4 08             add    rsp,0x8
  41f792:       c3                      ret    
  41f793:       0f 1f 00                nop    DWORD PTR [rax]
  41f796:       66 2e 0f 1f 84 00 00    nop    WORD PTR cs:[rax+rax*1+0x0]
  41f79d:       00 00 00 
```
