### ISSUE TITLE
Command successful but file missing

### ISSUE THREAD

**Issue by panruochen** [ninja-build/ninja#1289]
Following are rules and commands from ninja.build:

rule rule12573
 description = target  C: ipa_nat_test <= vendor/qcom/opensource/data-ipa-cfg-mgr/ipanat/test/ipa_nat_test003.c
 depfile = out/target/product/ModuleX/obj/EXECUTABLES/ipa_nat_test_intermediates/ipa_nat_test003.P
 deps = gcc
 command = /bin/bash -c "(PWD=/proc/self/cwd  prebuilts/clang/host/linux-x86/clang-2690385/bin/clang -I vendor/qcom/opensource/data-ipa-cfg-mgr/ipanat/test/ -I vendor/qcom/opensource/data-ipa-cfg-mgr/ipanat/test/../../ipanat/inc -I out/target/product/ModuleX/obj/KERNEL_OBJ/usr/include -I vendor/qcom/opensource/data-ipa-cfg-mgr/ipanat/test -I out/target/product/ModuleX/obj/EXECUTABLES/ipa_nat_test_intermediates -I out/target/product/ModuleX/gen/EXECUTABLES/ipa_nat_test_intermediates -I libnativehelper/include/nativehelper \$$(cat out/target/product/ModuleX/obj/EXECUTABLES/ipa_nat_test_intermediates/import_includes) -isystem system/core/include -isystem system/media/audio/include -isystem hardware/libhardware/include -isystem hardware/libhardware_legacy/include -isystem hardware/ril/include -isystem libnativehelper/include -isystem frameworks/native/include -isystem frameworks/native/opengl/include -isystem frameworks/av/include -isystem frameworks/base/include -isystem out/target/product/ModuleX/obj/include -isystem bionic/libc/arch-arm64/include -isystem bionic/libc/include -isystem bionic/libc/kernel/uapi -isystem bionic/libc/kernel/common -isystem bionic/libc/kernel/uapi/asm-arm64 -isystem bionic/libm/include -isystem bionic/libm/include/arm64 -c    -fno-exceptions -Wno-multichar -fno-strict-aliasing -fstack-protector-strong -ffunction-sections -fdata-sections -funwind-tables -Wa,--noexecstack -Werror=format-security -D_FORTIFY_SOURCE=2 -fno-short-enums -no-canonical-prefixes -Werror=pointer-to-int-cast -Werror=int-to-pointer-cast -Werror=implicit-function-declaration -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Werror=date-time -DNDEBUG -O2 -g -Wstrict-aliasing=2 -DNDEBUG -UDEBUG  -D__compiler_offsetof=__builtin_offsetof -Werror=int-conversion -Wno-reserved-id-macro -Wno-format-pedantic -Wno-unused-command-line-argument -fcolor-diagnostics -nostdlibinc     -target aarch64-linux-android -Bprebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/aarch64-linux-android/bin    -std=gnu99      -fpie -D_USING_LIBCXX   -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast  -Werror=address-of-temporary -Werror=null-dereference -Werror=return-type  -MD -MF out/target/product/ModuleX/obj/EXECUTABLES/ipa_nat_test_intermediates/ipa_nat_test003.d -o out/target/product/ModuleX/obj/EXECUTABLES/ipa_nat_test_intermediates/ipa_nat_test003.o vendor/qcom/opensource/data-ipa-cfg-mgr/ipanat/test/ipa_nat_test003.c ) && (cp out/target/product/ModuleX/obj/EXECUTABLES/ipa_nat_test_intermediates/ipa_nat_test003.d out/target/product/ModuleX/obj/EXECUTABLES/ipa_nat_test_intermediates/ipa_nat_test003.P; sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\\\\$$//' -e '/^\$$/ d' -e 's/\$$/ :/' < out/target/product/ModuleX/obj/EXECUTABLES/ipa_nat_test_intermediates/ipa_nat_test003.d >> out/target/product/ModuleX/obj/EXECUTABLES/ipa_nat_test_intermediates/ipa_nat_test003.P; rm -f out/target/product/ModuleX/obj/EXECUTABLES/ipa_nat_test_intermediates/ipa_nat_test003.d; )"
build out/target/product/ModuleX/obj/EXECUTABLES/ipa_nat_test_intermediates/ipa_nat_test003.o: rule12573 vendor/qcom/opensource/data-ipa-cfg-mgr/ipanat/test/ipa_nat_test003.c out/target/product/ModuleX/obj/KERNEL_OBJ/usr out/target/product/ModuleX/obj/EXECUTABLES/ipa_nat_test_intermediates/import_includes || all_copied_headers

I run:
ninja -f out/ninja.build out/target/product/ModuleX/obj/EXECUTABLES/ipa_nat_test_intermediates/ipa_nat_test003.o
The command ends successfully but out/target/product/ModuleX/obj/EXECUTABLES/ipa_nat_test_intermediates/ipa_nat_test003.P does not exist.

To find out what happens, I add a loop at the end of the command
  while [ -z \$$(cat /tmp/done) ]; then do sleep 1; done

At this time, I run following shell commands
$ps -ef
prc      10805 10629 88 17:02 pts/30   00:00:13 prebuilts/ninja/linux-x86/ninja -f out/build.ninja out/target/product/ModuleX/obj/EXECUTABLES/ipa_n
prc      11138 10805  0 17:02 ?        00:00:00 /bin/sh -c /bin/bash -c "(PWD=/proc/self/cwd  prebuilts/clang/host/linux-x86/clang-2690385/bin/cl
prc      11139 11138  0 17:02 ?        00:00:00 /bin/bash -c (PWD=/proc/self/cwd  prebuilts/clang/host/linux-x86/clang-2690385/bin/clang -I vendo
prc      11144 11139  0 17:02 ?        00:00:00 /bin/bash -c (PWD=/proc/self/cwd  prebuilts/clang/host/linux-x86/clang-2690385/bin/clang -I vendo
prc      11153 11144  0 17:02 ?        00:00:00 sleep 1

diff /proc/11139/cmdline /proc/11144/cmdline shows no differences.
Question 1: Why two identical processes are created?

$file out/target/product/ModuleX/obj/EXECUTABLES/ipa_nat_test_intermediates/ipa_nat_test003.P
out/target/product/ModuleX/obj/EXECUTABLES/ipa_nat_test_intermediates/ipa_nat_test003.P: ASCII text

As you can see, ipa_nat_test003.P exists.

But if I go on with following commands:

echo 1 > /tmp/done
$file out/target/product/ModuleX/obj/EXECUTABLES/ipa_nat_test_intermediates/ipa_nat_test003.P
out/target/product/ModuleX/obj/EXECUTABLES/ipa_nat_test_intermediates/ipa_nat_test003.P: ERROR: cannot open `out/target/product/ModuleX/obj/EXECUTABLES/ipa_nat_test_intermediates/ipa_nat_test003.P' (No such file or directory)

Question 2: Where is out/target/product/ModuleX/obj/EXECUTABLES/ipa_nat_test_intermediates/ipa_nat_test003.P gone?

Both 1.6.0 and 1.7.2 have the same issue.

**Comment by nico** [comment]
You list ` out/target/product/ModuleX/obj/EXECUTABLES/ipa_nat_test_intermediates/ipa_nat_test003.P` as a depfile. In deps=gcc mode, ninja reads the depfile after each command finishes, and then deletes the depfile. You can pass `-d keepdepfile` to prevent that -- this can be useful for debugging, but I'm not aware of other use cases where that's needed.

Does that answer your question?

**Comment by panruochen** [comment]
Yeah, that answers my question.
