### ISSUE TITLE
Unix/Windows path resolution?

### ISSUE THREAD

**Issue by mcandre** [ninja-build/ninja#1301]
I'm shopping for cross-platform build tools, in particular, build tools that help to seamlessly write build configurations that "just work" with both Unix and Windows environments. Specifically, I never want to write a conditional to handle `~` vs `%userprofile%`, but instead rely on a single syntax that the build tool automatically converts to the platform-specific one on execution. What would a cross-platform `.ninja` file look like?

If the author writes paths in Unix-style form, does Ninja automatically convert these to Windows paths in Windows environments? And what about when in cygwin environments in WIndows?

**Comment by jhasse** [comment]
Sorry that there hasn't been an answer for so long. I guess you should look into a higher-level build system like CMake or Meson if you don't want to worry about most cross-platform issues.

If you're still having questions about ninja, please ask on the mailing list: http://groups.google.com/group/ninja-build

**Comment by nico** [comment]
To answer the question: Ninja doesn't do any path conversions. On Windows it goes through some lengths to make sure that it hands the same \s and /s to subprocesses as present in the build.ninja file.

See also the text on https://ninja-build.org/ and https://ninja-build.org/manual.html#_philosophical_overview – ninja's philosophy is that such features should be in the generator. https://github.com/ninja-build/ninja/wiki/List-of-generators-producing-ninja-build-files is a list of generators that can produce ninja input.

**Comment by jonesmz** [comment]
Perhaps this should be directly explained in the readme / website for future readers. I wondered this myself.

**Comment by nico** [comment]
https://ninja-build.org/manual.html#_philosophical_overview / https://ninja-build.org/manual.html#_design_goals do attempt to explain this. What do you think is missing?

**Comment by jonesmz** [comment]
In the non-goals section. Just say "ninja does not do file path convention adaptations".

Or if you want it to be more general " ninja does not hold the hand of the generator program, such as not doing file path conversions."
