### ISSUE TITLE
ninja dies with SIGABRT when build is interrupted with ^C

### ISSUE THREAD

**Issue by keszybz** [ninja-build/ninja#1305]
Seems to happen occasionally when ^C is pressed. See https://bugzilla.redhat.com/show_bug.cgi?id=1471246 for backtraces and more detail.

I can't isolate the exact version, but it only started happening in the last few weeks (currently Fedora is at ninja-build-1.7.2-4.fc26.x86_64).

**Comment by nico** [comment]
Fedora uses glibc as C library, right? I wonder if the posix_spawn() + POSIX_SPAWN_USEVFORK might be related. However, without POSIX_SPAWN_USEVFORK posix_spawn() shouldn't have changed behavior with glibc, and POSIX_SPAWN_USEVFORK hasn't made it into a release yet.

**Comment by jhasse** [comment]
I can't reproduce this on Fedora 28, is this still happening for you? If so, please reopen.

**Comment by keszybz** [comment]
FWIW, I haven't seen this in a while.
