### ISSUE TITLE
CentOS cmake -G Ninja can't found ninja

### ISSUE THREAD

**Issue by heroims** [ninja-build/ninja#1308]
ninja --version is worked

[lookfe@troy xcbuild]$ cmake -G Ninja

CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.

CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:

CMAKE_C_COMPILER_ENV_VAR

CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.

Missing variable is:

CMAKE_C_COMPILER

CMake Error: Could not find cmake module file: /home/lookfe/testIOS/xcbuild/CMakeFiles/2.8.12.2/CMakeCCompiler.cmake

CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.

Missing variable is:

CMAKE_CXX_COMPILER_ENV_VAR

CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.

Missing variable is:

CMAKE_CXX_COMPILER

CMake Error: Could not find cmake module file: /home/lookfe/testIOS/xcbuild/CMakeFiles/2.8.12.2/CMakeCXXCompiler.cmake
-- Configuring incomplete, errors occurred!

[lookfe@troy xcbuild]$ ninja --version

1.7.2

[lookfe@troy xcbuild]$ uname -a

Linux troy 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

It looks can't run in CentOS

**Comment by cdbennett** [comment]
CMake 2.8.12 is really old now.  It was released in October 2013, so it's almost 4 years old.

Perhaps it is a CMake shortcoming in finding Ninja.

This is probably not a Ninja bug.

**Comment by heroims** [comment]
It can run when I use CMake 3.9.1

**Comment by petrasvestartas** [comment]
Run the editor or command line with "Administrative settings"
