### ISSUE TITLE
Support unlimited number of parallel jobs #1379

### ISSUE THREAD

**Issue by martell** [ninja-build/ninja#1309]
Hey @nico,

I am looking to add a new mode, possibly a value passed to `-j` (or reading an environment variable to decide to enable this special mode or not) that runs as many parallel tasks as possible.
The easy way would be to just pass `-j 1000` or something silly but I would like to actually get the number of concurrent tasks possible, which depends on the project, it could be limited by one part of a build depending on something previous being built and linked by the same project

Looking through the code, `wanted_edges_` and `command_edges_ ` pop out in `src/build.cc`
Could i get your input on how I would achieve this mode?

I assume this part is not possible because ninja just does what the it is told by the script but is there a way to differentiate between compile and link jobs for this. 

Best,
Martell

**Comment by ilyapopov** [comment]
Can you use pools feature for this? Cmake allows you to configure pools for compilation and linking https://cmake.org/cmake/help/v3.9/prop_gbl/JOB_POOLS.html

**Comment by martell** [comment]
@ilyapopov this is not something I want to do at the cmake level.
I want ninja to just run every task it possibly can in parallel which should not be too difficult.

@bradking would probably know best what to do here :)

**Comment by bradking** [comment]
@martell take a look at `RealCommandRunner::CanRunMore`.

**Comment by mathstuf** [comment]
Make does this by using `-j0` to do it.

**Comment by nico** [comment]
To me, passing `-j 1000` is a good way to do this. It's understandable.

Supporting `-j 0` would be consistent with `-k 0` (which I'm not in love with; `-k 100000` does the same and is more understandable – but we have `-k 0` and won't take it away).

I think #1358 implements something like that.
