### ISSUE TITLE
Add string "verbose" for -v help

### ISSUE THREAD

**Issue by pksadiq** [ninja-build/ninja#1310]
Usually I grep for "verbose" string to see if any command have such capabilities. I believe many do the same, because that is a commonly used term (And I missed the verbose flag because of that, which might be a funny to say).

So, it might be better to reword the help string of "-v" to include the word "verbose" somewhere.

Thanks

**Comment by jhasse** [comment]
Maybe just add `--verbose` as an alternative spelling?

**Comment by pksadiq** [comment]
Sure, that would help too
