### ISSUE TITLE
Ability to redirect .ninja_log and .ninja_deps to alternate directory

### ISSUE THREAD

**Issue by jonesmz** [ninja-build/ninja#1311]
I've searched the list of existing issues (both open and closed) on Github and I didn't see anything relating to this. Please correct me if this is a duplicate issue.

Is ninja able to redirect .ninja_log and .ninja_deps to a command-line configurable location, instead of writing them to the current working directory?

**Comment by evmar** [comment]
See `builddir`: https://ninja-build.org/manual.html#ref_toplevel

**Comment by evmar** [comment]
(And beyond that, no.)

**Comment by jonesmz** [comment]
Thank you, that solves my problem.

Might I recommend explicitly calling out the names of the files that are redirected by that variable in the documentation that you linked me to? It was not clear when I read it the first time that it would have this effect.

**Comment by evmar** [comment]
Send a pull request!

**Comment by evmar** [comment]
The second paragraph here is fairly explicit, though it's easy to miss:
https://ninja-build.org/manual.html#ref_log
