### ISSUE TITLE
Using Ninja with a compiler with buggy command line parsing

### ISSUE THREAD

**Issue by cr1901** [ninja-build/ninja#1312]
I'm attempting to port the Meson build system to the [Watcom C Compiler](http://openwatcom.org). I wish to use Watcom with a project of mine which is meant to compile with any C89 compiler for any target, provided Meson can run on the host platform.

Watcom has a number of issues that make it less than ideal for porting to Meson, but the main one of concern for `ninja` is that the Watcom linker doesn't understand files that are separated by spaces alone. To avoid a number of parsing issues, a command line invocation of the linker should look like the following:

```
wlink name output.exe file 'path\to\obj1', 'path\to\obj2'
```

Quoting each filename is required because some characters are considered special to the linker otherwise. Quoting before creating $in is not possible because `ninja` won't be able to find dependencies for a given build statement. Either the commas are required or the following command line will work- spaces between input files are insufficient:

```
wlink name output.exe file 'path\to\obj1' file 'path\to\obj2', etc
```

While Watcom is still [in development](https://github.com/open-watcom/owp4v1copy), a new release is unlikely to occur soon. So I was thinking of adding an extension to the $in directive (maybe `$in_comma_quote`) which escapes filenames with quotes and separates each input file with a comma and space.

I'd be happy to add this functionality myself, but I'd like feedback before I introduce what is effectively a hack for a compiler that doesn't follow standard command-line conventions. More charitably, I'd call this increasing the compiler diversity that `ninja` is able to support :).

**Comment by jimon** [comment]
I'm not sure what the right solution should be, though it feels that a hotfix to wrap wlink in a python/shell/etc script and do small bit of processing like that should unblock you :)

**Comment by cr1901** [comment]
Yes, a script will work, but it's certainly not ideal. Additionally, I have other compilers not currently supported (`sdcc`) that I wish to add, so I just wanted to bring this up/start a conversation :P. Watcom is pretty badly-behaving, but I can think of a scenario where other tools exist that need more sophisticated parsing than just $in or $in_newline.

Worst case, I do the script though.

**Comment by evmar** [comment]
An option we've recommended in the past is to just pass the mangled command line separately:

```
rule watcom_link
   command = wlink name $out $in_mangled

build output.exe: watcom_link a.obj b.obj
  in_mangled = 'a.obj', 'b.obj'
```

The idea here is that your generator is uniquely equipped to know all the idiosyncrasies of the required input.  Ninja only provides the `$in` variable for convenience; after parsing in memory using it is effectively equivalent to the above.

**Comment by evmar** [comment]
Relevant Ninja code that your generator could emulate:
https://github.com/ninja-build/ninja/blob/7bbc708ff08f5660f4cff4b3e8c675bec428a1f2/src/graph.cc#L299

But I expect you can avoid most of this complexity because you don't need implicit inputs, shell-style escaping, etc.

**Comment by cr1901** [comment]
@evmar Yes, I do believe this will work, thank you! :)

I just got a multifile compile w/ Watcom working tonight!
