### ISSUE TITLE
depfile (gcc) with multiple rules for same output not supported

### ISSUE THREAD

**Issue by lindquist** [ninja-build/ninja#1317]
I am trying to use ninja for compiling code for a Blackfin DSP from Analog Devices. Their toolchain has a horrid buildsystem (heavily tied into their Eclipse based IDE).

The dependency file format output does not work with ninja. I am specifying "gnu style dependencies":

```
startup_code.doj: ../../../../Blackfin/include/adi_osal.h
startup_code.doj: ../../../../Blackfin/include/adi_osal_arch.h
startup_code.doj: ../../../../Blackfin/include/cplb.h
startup_code.doj: ../../../../Blackfin/include/defBF706.h
startup_code.doj: ../../../../Blackfin/include/sys/_adi_platform.h
startup_code.doj: ../../../../Blackfin/include/sys/anomaly_macros_rtl.h
startup_code.doj: ../../../../Blackfin/include/sys/defBF706.h
startup_code.doj: ../../../../Blackfin/include/sys/defBF70x_id_macros.h
startup_code.doj: ../../../../Blackfin/include/sys/exception.h
startup_code.doj: ../../../../Blackfin/include/sys/fatal_error_code.h
startup_code.doj: ../../../../Blackfin/include/sys/platform.h
startup_code.doj: startup_code.asm
```

But it would seems that ADI do not agree on what gnu style is. I'm thinking that I will probably need to post-process the dependency file output, but I'm not sure what the best approach would be here. Or perhaps ninja should accept this format in the first place?

The end result is that if I try to change 'startup_code.asm', then I get the following error:

`ninja: error: dependency cycle: startup_code.doj -> startup_code.doj`

**Comment by mathstuf** [comment]
This issue can be resolved I believe. @jhasse

**Comment by jhasse** [comment]
thx
