### ISSUE TITLE
phony cycles not previously diagnosed now break since PR 1111

### ISSUE THREAD

**Issue by bradking** [ninja-build/ninja#1322]
CMake versions 2.8.12.x and 3.0.x incorrectly produce build statements of the form `build a: phony a` in certain cases.  This was a bug in CMake introduced by commit `v2.8.12~248^2` and fixed by commit `v3.1.0-rc1~353^2~2`.  See [CMake Issue 14972](https://gitlab.kitware.com/cmake/cmake/issues/14972).

Ninja didn't previously detect cycles involving only phony build statements, but does since PR #1111.  This broke `ninja`'s tolerance of the range of CMake versions with the above bug.

**Comment by bradking** [comment]
Cc: @nico

The changes in #1111 do not break on correct build graphs and are very important in the work toward Ninja+Fortran support.  The detection of these cycles is a bug fix that has simply exposed a bug in old CMake versions that has also long been fixed.  IMO we should not revert the changes or introduce additional complexity in the graph/build logic just to support people using such old CMake versions.  If one is using a CMake that old one can use a Ninja that old too.

A middle-ground solution would be to tolerate the specific case produced by the buggy CMake versions without trying to tolerate phony cycles in general.  Prior to PR 1111 we tolerated both full cycles:

```
build a: phony b
build b: phony a
```

and self-referencing phony build statements:

```
build a: phony a
```

CMake 2.8.12 and 3.0 only produce the latter.  We can tolerate that with a hack in the parser to drop inputs of phony rules that correspond to their outputs.

**Comment by nico** [comment]
Can we handle this similarly to #931? I.e.

1. Add `-w phonycycle=warn|err` flag, make that default to `warn` for now
2. If that's set to `warn`, do your #1323, but emit a warning
3. If that's set to err, keep current behavior (but maybe include "-w phonycycle" in the cycle error message if the cycle is from a phony edge)
4. At some point in the future, change the default to `err`
5. Eventually, remove the flag

?

**Comment by bradking** [comment]
@nico yes a deprecation path will be good to help prevent similar generator bugs in the future.  I can work on that.  Do you intend to add such a warning in a 1.8 patch release, or start with the quick-fix from #1323 for 1.8.2 and add the warning in post-1.8 development?

**Comment by bradking** [comment]
@nico I updated #1323 to add the `-w phonycycle=...` diagnostic.
