### ISSUE TITLE
ninja: fatal: CreateProcess: Accept is denied. vx.cpp

### ISSUE THREAD

**Issue by xuboabc** [ninja-build/ninja#1324]
I am using ninja to build skia on Windows7, when i use "ninja -C out/Static", it always print " ninja: fatal: CreateProcess: Accept is denied. vx.cpp". Anybody know what's wrong?

**Comment by mathstuf** [comment]
It seems that something might be running `vx.cpp` as an executable. Running with `-v` to show the command Ninja is trying to run would help.
