### ISSUE TITLE
What is the latest release?

### ISSUE THREAD

**Issue by bdubbs** [ninja-build/ninja#1325]
In some places it says 1.7.2, but the releases section has 1.8.0 and 1.8.1.  

We mange about 1000 packages and need a way to automate the detection of new releases. For github, we normally have a script parse the releases page for the most recent version.  If there is a better way for us to automatically determine the latest version of this package, please let us know.

In addition, I note that there is no NEWS file in the release tarball to say what features have changed.  The git change log is terribly inefficient for users because it essentially gives equal weight to simple typos in a comment to substantive usage/API changes.  A short summary of changes is appreciated.

  -- Bruce Dubbs
     linuxfromscratch.org

**Comment by nico** [comment]
The latest release is 1.7.2, see the releases section. We're trying to qualify a new release, but we ran into an issue during the process (see #1322). Once that's sorted out, there will be a new release on the releases pages, and there will be a release announcement with a list of changes linked from there. Usually, releases go more quickly and what you do should work fine most of the time. But the releases page is the authoritative source.
