### ISSUE TITLE
HACKING: performance testing?

### ISSUE THREAD

**Issue by Lekensteyn** [ninja-build/ninja#1338]
From HACKING.md:

> If you have a Chrome build handy, it's a good test case.  Otherwise,
> [the github downoads page](https://github.com/ninja-build/ninja/releases)
> has a copy of the Chrome build files (and depfiles). You can untar
> that, then run
> 
>     path/to/my/ninja chrome
> 
> and compare that against a baseline Ninja.

Where can this copy be found? (There is also a typo in *GitHub down**l**oads page* by the way.)

Is `misc/write_fake_manifests.py` supposed to be used for this? Should the docs be extended such that `ninja -d stats` is mentioned?

**Comment by nico** [comment]
Yes, `msc/write_fake_manifests.py` is good for testing parser performance (more concretely, see manifest_parser_perftest which runs this script and then collects some perf data).

I think the download link is probably obsolete -- iirc github used to offer file hosting long ago, but that was removed (also long ago). That part of HACKING looks outdated.
