### ISSUE TITLE
Ninja on win32

### ISSUE THREAD

**Issue by atsju** [ninja-build/ninja#1339]
I just tried ninja 1.7.2. and 1.8.2, none of these seems to run on windows 7 32 bits version. 
Is this normal ?

**Comment by nico** [comment]
We switched to building 64-bit binaries because they were a bit faster, and most machines are 64-bit nowadays. If you need a 32-bit binary, you can build ninja yourself in a 32-bit MSVC shell. It should build fine in 32-bit.
