### ISSUE TITLE
Generated cache failed with "Ninja".

### ISSUE THREAD

**Issue by Emilyliuliu** [ninja-build/ninja#1341]
The cache generation failed when I used the "Ninja" generator  in VS to generate a cache for a CMake Folder, VS language I use the CSY. Please see as below:

CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/Preview/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.9/Modules/CMakeTestCCompiler.cmake:51 (message):
1> The C compiler "C:/Program Files (x86)/Microsoft Visual
1> Studio/Preview/Enterprise/VC/Tools/MSVC/14.11.25503/bin/Hostx86/x86/cl.exe"
1> is not able to compile a simple test program.
1> 
1> It fails with the following output:
1> 
1> Change Dir: C:/Users/mdTestAU/CMakeBuilds/8f040025-9a15-ab3e-8889-d02267d3b2e5/build/x86-Release/CMakeFiles/CMakeTmp
1> 
1> 
1> 
1> Run Build
1> Command:"C:/PROGRA~2/MICROS~2/Preview/ENTERP~1/Common7/IDE/COMMON~1/MICROS~1/CMake/Ninja/ninja.exe"
1> "cmTC_3e975"
1> 
1> ninja: error: build.ninja:30: loading 'rules.ninja': SystÚm nem¨×e
1> nalÚzt uvedenř soubor.
1> 
1> 
1> 
1> 
1> include rules.ninja
1> 
1> 
1> ^ near here
1> 
1> 
1> 
1> 
1> 
1> CMake will not be able to correctly generate this project.
1> Call Stack (most recent call first):
1> CMakeLists.txt(4): (project)
1> 
1> 
1> -- Configuring incomplete, errors occurred!
1> See also "C:/Users/mdTestAU/CMakeBuilds/8f040025-9a15-ab3e-8889-d02267d3b2e5/build/x86-Release/CMakeFiles/CMakeOutput.log".
1> See also "C:/Users/mdTestAU/CMakeBuilds/8f040025-9a15-ab3e-8889-d02267d3b2e5/build/x86-Release/CMakeFiles/CMakeError.log".
1> C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\PREVIEW\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe -G "Ninja" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\mdTestAU\CMakeBuilds\8f040025-9a15-ab3e-8889-d02267d3b2e5\install\x86-Release" -DCMAKE_BUILD_TYPE="RelWithDebInfo" -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\PREVIEW\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" "C:\Users\mdTestAU\Desktop\zlib1211\zlib-1.2.11" – vráceno s ukončovacím kódem: 1
Přepínač konfigurace na x86-Release je hotový.

**Comment by mathstuf** [comment]
This is a CMake error, not a Ninja error. Something went wrong in the configure step of the project. Looking for that error would be the way to fix it (it isn't in your provided output). If you're still having issues, please email the [CMake mailing list](https://cmake.org/mailman/listinfo/cmake).

@nico Feel free to close this.
