### ISSUE TITLE
Allow defaulting `-C` to `build`

### ISSUE THREAD

**Issue by haasn** [ninja-build/ninja#1343]
`build` seems like a very popular choice of a build directory name; and has been a common convention throughout the documentation of pretty much every `cmake` or `meson` project. It's also used as the name of the default directory by tools such as `waf`.

As such, I think it would be reasonable behavior to allow `ninja` to act as if it was passed with `-Cbuild` by default if `./ninja.test` was not found but `./build/ninja.test` exists, without the user having to manually alias this. The potential for unexpected behavior here seems pretty low to me.

**Comment by nico** [comment]
Hm, I'm not sure if we want this. None of the projects I use ninja in use `build` as build directory name (llvm, chromium, several small one-off projects). This seems like too much magic to me.

**Comment by jhasse** [comment]
If you interested in this, check out my ninja frontend which does exactly that: https://bixense.com/ja/

For Ninja itself I also think that it would be better to be explicit.

**Comment by mathstuf** [comment]
I agree that I wouldn't want this. I do use directories named `build`, but they are usually siblings to source trees, not children.

**Comment by evmar** [comment]
I think this isn't in the spirit of Ninja.  Our design goals even call this out: "very little policy about how code is built":
https://ninja-build.org/manual.html#_design_goals
