### ISSUE TITLE
OOM not detected (continuing compilation and 0 exit code)

### ISSUE THREAD

**Issue by matthieu-nesme** [ninja-build/ninja#1353]
Hi,
I am using ninja1.5.1 (ubuntu16.04), so maybe it has been corrected (sorry for that).

When compiling (with gcc7.2.0 with `-j n` option) all the ram is filled out generating an out-of-memory that kills the g++ processes with this message:
```
g++-7: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
```

**BUT**

ninja continues its job as if nothing is happening, trying to compile the next files (their processes are then killed too as soon as they arrive).

Then ninja returns a 0 exit code as if nothing happened!

**Comment by nico** [comment]
I'm afraid this doesn't have enough detail to be actionable. Ninja stops the build if the child says it fails.
