### ISSUE TITLE
I don't want to surround by single-quote.

### ISSUE THREAD

**Issue by hsnks100** [ninja-build/ninja#1357]
I don't want to surround by single-quote when I use assign-statement for variable.
Hi. I these days enjoy using ninja build system.

But, I suffer from ninja because of single-quote. 

this is my script.
```
common_objs = common/sample_comm_vpss.o common/sample_comm_vo.o common/sample_comm_isp.o common/sample_comm_audio.o common/loadbmp.o common/sample_comm_ive.o common/sample_comm_venc.o common/sample_comm_vi.o common/sample_comm_sys.o ../lib/libmpi.a ../lib/libive.a ../lib/libmd.a ../lib/libtde.a ../lib/libVoiceEngine.a ../lib/libupvqe.a ../lib/libdnvqe.a ../lib/libisp.a ../lib/libsns_ar0130.a ../lib/lib_cmoscfg.a ../lib/lib_iniparser.a ../lib/lib_hiae.a ../lib/lib_hiawb.a ../lib/lib_hiaf.a ../lib/lib_hidefog.a
build obj/sample_region: link obj/sample_region.o ${common_objs} 
```
I don't intent to surround by single-quote about ${common_objs}. 
```
ninja: error: 'common/sample_comm_vpss.o common/sample_comm_vo.o common/sample_comm_isp.o common/sample_comm_audio.o common/loadbmp.o common/sample_comm_ive.o common/sample_comm_venc.o common/sample_comm_vi.o common/sample_comm_sys.o ../lib/libmpi.a ../lib/libive.a ../lib/libmd.a ../lib/libtde.a ../lib/libVoiceEngine.a ../lib/libupvqe.a ../lib/libdnvqe.a ../lib/libisp.a ../lib/libsns_ar0130.a ../lib/lib_cmoscfg.a ../lib/lib_iniparser.a ../lib/lib_hiae.a ../lib/lib_hiawb.a ../lib/lib_hiaf.a ../lib/lib_hidefog.a', needed by 'obj/sample_region', missing and no known rule to make it
```

common_objs are recognized with long filename including space. I already have read user-manual, But I can't find guide to resolve this. I also try to use ar-command to combine .a, .o files. It may difficult to combine for me. I don't know that I can ask this problem here. Anyway I am waiting for your helping.

In advance, THANK YOU FOR READING.

**Comment by atetubou** [comment]
You can use rspfile and rspfile_content for such case.
https://ninja-build.org/manual.html#ref_rule

**Comment by evmar** [comment]
See this section of the manual:
https://ninja-build.org/manual.html#_lexical_syntax
"A build or default statement is first parsed as a space-separated list of filenames and then each name is expanded. This means that spaces within a variable will result in spaces in the expanded filename."

I suggest eliminating the common_objs variable and instead putting the full list in the build statement.

**Comment by hsnks100** [comment]
I'm going to use like common_objs because of reuseability...And common_objs is used often, 

therefore must I repeatly use "~.o, ~.a, ~.o... stuff like that..."?? I think It is not efficient about NINJA SYSTEM.

**Comment by evmar** [comment]
I think you'd need to repeat them thousands of times before you could have
any performance impact.

**Comment by hsnks100** [comment]
I have mean that this work flow is boring work because full list of files are duplicated through a lot of .ninja files.

**Comment by evmar** [comment]
See the third paragraph on the home page.

**Comment by hsnks100** [comment]
thank you.

I got it that I should use another support tools such as gn, cmake ... and stuff like that to make what I want to do. right?

I want to confirm what I understand because I actually get used to using English. 

thanks to ninja-build contributers. :-)

**Comment by evmar** [comment]
That is correct, yes.  Good luck!
