### ISSUE TITLE
Stop ninja from regenerating build.ninja file when unnecessary

### ISSUE THREAD

**Issue by flybd5** [ninja-build/ninja#1359]
Ninja has a bug in that it does not know how to handle spaces in paths on OSX. Spaces in volume names is extremely common in OSX. To correct this in a build (the Chromium build) I edited the build.ninja file to escape the spaces in the paths. However, when I do that, ninja insists on overwriting the file again and reinstating the path it can't handle. I can find no way to stop or circumvent this erroneous behaviour. I even tried setting up a symlink without the space, and ninja insists on using the path the symlink points to instead of the symlink. Anyway to get ninja to behave correctly and get it to do what it should do, rather than what it wants to do?

**Comment by evmar** [comment]
It sounds like you're encountering a bug.  Can you describe the bug?

**Comment by flybd5** [comment]
My main work volume on my Mac is named "Mac 2TB". This is not unusual in the Mac world, where users want to use meaningful names for files with spaces and other characters. 

That means that my home directory is "/Volumes/Mac 2TB/Users/jjimenez" and everything under that is the same way. Ninja does not make any attempt to escape the space in "Mac 2TB" or to put double quotes around it. It then only reads the paths for the project up to the space, and everything fails, for obvious reasons.

If I change the build.ninja file to make it work, Ninja regenerates it and fails again.

If I cp the file and make the changes, then it works, but only up to the point where it needs to make an external call in the same volume structure. It again fails to escape or double quote and the whole thing barfs.

I am using the latest Chromium source and following the Google instructions on how to set up and build, but this is keeping from doing anything. Ninja does not respect symlinks, it still wants to use the symlink target and not the symlink as the base directory, so I can't fake it into working that way.

**Comment by evmar** [comment]
Ninja handles spaces in paths just fine, as far as we know.  From your description I still cannot tell what is going wrong.  Can you frame the question in the form of "this specific input file and this on-disk state and this command causes X to happen when I expect Y to happen"?

**Comment by flybd5** [comment]
No, it doesn't, otherwise it would work fine for me.

My question and test case is clear and easy to replicate. Instead of asking
me to reframe my question, try to install chromium and build the chrome
target in a volume with spaces in the name, and watch what happens.
Everything else on my Mac works fine, only Ninja fails.


On Nov 20, 2017 12:38 AM, "Evan Martin" <notifications@github.com> wrote:

Ninja handles spaces in paths just fine, as far as we know. From your
description I still cannot tell what is going wrong. Can you frame the
question in the form of "this specific input file and this on-disk state
and this command causes X to happen when I expect Y to happen"?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ninja-build/ninja/issues/1359#issuecomment-345560039>,
or mute the thread

**Comment by evmar** [comment]
I don't work on Chromium, so I likely will not have time to figure out the bug.  Sorry.

**Comment by flybd5** [comment]
Nobody's has said anything about "work on Chromium," that's just the test
case that generates the build.ninja that surfaces the bug. You're just
being asked to look into and fix the bug.

**Comment by flybd5** [comment]
Juans-MacBook-Pro:Default jjimenez$ ninja chrome
[1/1] Regenerating ninja files
FAILED: build.ninja
/Volumes/Mac 2TB/Users/jjimenez/chromium/src/buildtools/mac/gn --root=/Volumes/Mac 2TB/Users/jjimenez/chromium/src -q gen .
/bin/sh: /Volumes/Mac: No such file or directory
ninja: error: rebuilding 'build.ninja': subcommand failed

**Comment by flybd5** [comment]
And this is why Ninja fails. The build.ninja file starts with this:

```
rule gn
  command = /Volumes/Mac 2TB/Users/jjimenez/chromium/src/buildtools/mac/gn --root=/Volumes/Mac 2TB/Users/jjimenez/chromium/src -q gen .
  description = Regenerating ninja files
```

**Comment by atetubou** [comment]
ninja runs command  with `/bin/sh -c "$command"`, so you need to escape space in your command.
command = /Volumes/Mac\ 2TB/Users/jjimenez/chromium/src/buildtools/mac/gn --root=/Volumes/Mac\ 2TB/Users/jjimenez/chromium/src -q gen .

If you use gn, this looks gn's bug rather than ninja.

**Comment by flybd5** [comment]
I will check on this and come back when I have an answer or more info.
Thank you.
