### ISSUE TITLE
.ninja_log behavior

### ISSUE THREAD

**Issue by svnpenn** [ninja-build/ninja#1368]
With make, you can have a makefile like this:

~~~make
.RECIPEPREFIX +=
xr.txt:
  touch $@
~~~

and as long as "xr.txt" exists, the rule will not be run, even once. However
with a build.ninja like this:

~~~ninja
rule ya
  command = touch $out
build xr.txt: ya
~~~

the rule will always be run at least once. it appears that with ninja, the
behavior hinges on both the file in question, as well as ".ninja_log". if either
as missing, then command is run. does ninja have an option to run more like make
in this regard?

**Comment by nico** [comment]
No. Ninja tracks if the commandline used to build an output changes, and if no log entry exists, ninja doesn't know the command and assumes it changed.

(What's your use case here?)
