### ISSUE TITLE
CreateProcess error message should be improved

### ISSUE THREAD

**Issue by randomascii** [ninja-build/ninja#1380]
If ninja tries to execute a non-existent process (such as if goma is not installed or is installed in the wrong location) then the message printed is:

    CreateProcess failed: The system cannot find the file specified.
    ninja: fatal: ReadFile: The handle is invalid.

This is not very helpful. Ninja should detect this particular error code and take it as a trigger to print the path to the process that it tried to create. Or maybe it should always print that.

This error has been hit particularly frequently lately due to a change in the default install location for goma.

I could even see a case for having a special-case check for goma - "please make sure goma is installed" or some-such, but special case checks are ugly so probably not.

**Comment by csharrison** [comment]
+1 I just hit this on an older checkout and it stumped me.

**Comment by mathstuf** [comment]
This error path already is special-cased in `subprocess-win32.cc`. Giving extra information in the stock string would be useful.

**Comment by randomascii** [comment]
I just hit another variant of this (I was about to file an issue then noticed that I already did). In this new case ninja was being asked to execute a command with a greater-than-32 K command-line. The only way I was able to figur eout what was going on was to build a custom version of ninja that printed out the command line before calling Win32Fatal("CreateProcess");

Anybody know whether a pull request with this change would be likely to be accepted?

diff --git a/src/subprocess-win32.cc b/src/subprocess-win32.cc
index 4bab719..ec7e1be 100644
--- a/src/subprocess-win32.cc
+++ b/src/subprocess-win32.cc
@@ -124,6 +124,7 @@ bool Subprocess::Start(SubprocessSet* set, const string& command) {
           "specified.\n";
       return true;
     } else {
+      fprintf(stderr, "Failed command line is %s\n", command.c_str());
       Win32Fatal("CreateProcess");    // pass all other errors to Win32Fatal
     }
   }

Alternately a string could be constructed and passed to Win32Fatal if that is preferable.

**Comment by mathstuf** [comment]
Please look at #1474 for adding other special case error messages for different error cases.

**Comment by mathstuf** [comment]
> The only way I was able to figur eout what was going on was to build a custom version of ninja that printed out the command line before calling

`ninja -v` was not sufficient?

**Comment by randomascii** [comment]
ninja -v prints commands after they have completed, I believe. For whatever reason, the problematic command line was not printed until I used a custom ninja - only the prior commands were printed.

Thank you for the link to that change. I think that would have correctly diagnosed the problem, but still wouldn't have told me what was causing the problem. However it does give me some ideas for how to create a PR.

**Comment by mathstuf** [comment]
I wonder if `ninja -vv` or some higher verbosity level could be used to output command lines before they're executed. Or maybe #1600 is the way this will finally get resolved.

**Comment by randomascii** [comment]
I looked into this a bit more, testing my known failure case with another custom build of ninja. This change works nicely and prints a nice message (highly edited - it was over 35,000 characters, definitely too long);

ninja: fatal: CreateProcess: The parameter is incorrect.hird_party/blink/renderer/bindings/modules/v8:bindings_modules_impl__jumbo_merge(//build/toolchain/win:win_clang_x86)
 (is the command line too long? Command line: c:/src/depot_tools/bootstrap-3_8_0_chromium_8_bin/python/bin/python.exe ../../build/config/merge_for_jumbo.py --outputs gen/third_party/blink/renderer/bindings/modules/v8/bindings_modules_impl_jumbo_1.cc 
...
list=__third_party_blink_renderer_bindings_modules_v8_bindings_modules_impl__jumbo_merge___build_toolchain_win_win_clang_x86__rule.rsp)

Here is the change:

https://github.com/randomascii/ninja/commit/97c84870020a57f9d0cd0991b128eed833c5f8ee


Alternately, another option is to get rid of the special Win32Fatal paths in Subprocess::Start. These calls are the source of the problem, I would argue. Because of them "-k 0" doesn't behave as expected, and the failing command is not printed. If they were removed then these failures would be handled by the normal mechanisms, instead of being cryptic failures.

I think either solution works. Preferences?

**Comment by mathstuf** [comment]
Could the offending rule's output instead be listed? That should make it unique enough to investigate what's happening.

**Comment by randomascii** [comment]
I, guess? What would be the advantage of that over the other two suggestions? And do you have a PR for that suggestion?

**Comment by mathstuf** [comment]
The command line being too long is just going to be a gigantic block and determining where `-o` is usually going to involve putting it to a file and grepping in an editor or making some pipeline to split arguments into lines and then grepping with context to find the "important" bit of the command line (remember, we're on Windows; you don't always have the nice Unix toolbox handy).

With the output, getting the command can be done deterministically with `ninja $output -v` (maybe with `-n`) and inspected (if necessary). Usually, I suspect just the output will be enough to track down how to make the producer of the rule use a response file or whatever is needed to fix it.

**Comment by randomascii** [comment]
To make this more concrete:

I hit this in Chromium when experimenting with jumbo (from a repo synced to before it was disabled). I set jumbo_file_merge_limit to various levels and when it was set to three the build failed - cryptically.

I spent quite a while trying to understand what was causing the failure with no luck. Once I hacked ninja to print the failing command the failure was trivially obvious - with a jumbo_file_merge_limit of 3 the number of jumbo source files created was so great that it exceeded the command-line limit.

That is to say:
- ninja normally prints failing command lines
- breaking that expectation causes confusion (why doesn't -k 0 work as expected?) and makes analysis harder
- printing the command line turned this failure from inscrutable to obvious
- I have a PR ready that will fix this, and a suggestion for alternate ways of ensuring that the command line will be printed

Printing the rule's output instead *might* work, but it is still unexpected and different behavior from ninja, with no PR to support it.

I could ask for approval for the PR, but I wonder if removing the special-case code that stops ninja from printing the command-line automatically would be better. I'm not personally interested in experimenting with printing the rule's output instead.

**Comment by mathstuf** [comment]
Those are questions more for @jhasse I think. Making this error path more along the lines of other errors does sound like a good improvement to me though.

**Comment by jhasse** [comment]
> Once I hacked ninja to print the failing command the failure was trivially obvious - with a jumbo_file_merge_limit of 3 the number of jumbo source files created was so great that it exceeded the command-line limit.

@randomascii Would this be fixed by #1637?

**Comment by randomascii** [comment]
Assuming that this part of the fix lands:

      fprintf(stderr, "\nCreateProcess failed. Command attempted:\n\"%s\"\n",
              command.c_str());

then that would indeed fix the problem. Any solution that ensures that the full command is printed on failure will address this (apparently large) set of cryptic failures.

I still wonder if the better solution might be to remove the calls to Win32Fatal that cause the command to not be printed and make -k 0 behave oddly. The Win32Fatal call has been there from the beginning, it got removed in one case in this change:

https://github.com/ninja-build/ninja/commit/665a30bc2dc78940ff3e1ec90d2f5bb7d329a71c

and given that we keep finding problems with it I think we should consider just not calling Win32Fatal when CreateProcess fails, given what we know now.

That is, printing the command line makes the failures less cryptic. Not calling Win32Fatal also does that, and also lets "ninja -k 0" run all non-failing commands, as expected.

**Comment by jhasse** [comment]
I could be argued that exceeding the command-line limit is an error in the build manifest which even `-k 0` shouldn't ignore.

**Comment by randomascii** [comment]
That sounds reasonable enough.

In that case one of the PRs that prints the command line before Win32Fatal or during is necessary to resolve the various issues.

**Comment by jhasse** [comment]
Fixed by #1637 then :)

**Comment by randomascii** [comment]
Verified! With that change landed the diagnosis of my issue is trivial. Thanks all.
