### ISSUE TITLE
Setting variable for a group of builds

### ISSUE THREAD

**Issue by omicronns** [ninja-build/ninja#1383]
I have a following question. I have a build.ninja file that should build couple of libraries, and link them together. I can't find a way to set a variable to a given value for a group of build commands eg. sequence of builds of files for single library. I don't want to create new rules for every target, since it seems ugly. What is the way to do it in ninja? Below is sample build.ninja describing the problem.

```
builddir = build
flags = -Wall

rule cc
  command = gcc $flags -c -o $out $in
rule ar
  command = ar rcs $out $in
rule ld
  command = gcc -o $out $in $libs

# something to set flags to -w for building libsum
build $builddir/sum1.o: cc src/sum1.c
build $builddir/sum2.o: cc src/sum2.c
  # for sum2.c flags will be -Wpedantic
  flags = -Wpedantic
# something to restore global flags
build $builddir/libsum.a: ar $builddir/sum1.o $builddir/sum2.o

build $builddir/mul.o: cc src/mul.c
build $builddir/libmul.a: ar $builddir/mul.o

build $builddir/main.o: cc src/main.c
build $builddir/main: ld $builddir/main.o
  libs = -lmul -lsum
```

**Comment by evmar** [comment]
```
build $builddir/sum1.o: cc src/sum1.c
  flags = -Wpedantic
build $builddir/sum2.o: cc src/sum2.c
  flags = -Wpedantic
```

It's redundant but you can handle the redundancy in the program that generates `build.ninja`.

**Comment by omicronns** [comment]
It is awkward if I want to leave possibility to shadow variable on source level, since I can't use "target level" variable value in other way than to merge it in the generator. Also setting this variables for large set of files, increases ```build.ninja``` file a lot. I think it would be nice feature to have something like scope for just shadowing variables:
```
scope
  flags = -w
  build $builddir/sum1.o: cc src/sum1.c
  build $builddir/sum2.o: cc src/sum2.c
    flags = -Wpedantic

build $builddir/libsum.a: ar $builddir/sum1.o $builddir/sum2.o
```
In this case i can still use variable from outer scope like:
```
scope
  flags = $flags -Wno-unused
  build $builddir/sum1.o: cc src/sum1.c
  build $builddir/sum2.o: cc src/sum2.c
    flags = $flags -Wpedantic # flags = -Wall -Wno-unused -Wpedantic

build $builddir/libsum.a: ar $builddir/sum1.o $builddir/sum2.o
```

**Comment by evmar** [comment]
We originally had a design very much like that for similar reasoning, but ended not pursuing it.

We have experience with huge `build.ninja` files, like 10mb in size, and things are still fast, so I wouldn't worry about duplication unless it becomes a problem.

**Comment by nico** [comment]
(Thread on explicit scoping: https://groups.google.com/forum/#!searchin/ninja-build/nico$20scope%7Csort:date/ninja-build/QsJIJU_5blI/Z5L_ostWTnsJ)
