### ISSUE TITLE
Add some option to filter out targets from phony list

### ISSUE THREAD

**Issue by martinetd** [ninja-build/ninja#1385]
I have some project with a `build all: phony many targets and more plus tags` rule, which is great, except that I sometimes don't want to build just one of these targets (in this case, because it has some corner case that's badly implemented, here it's a ctags command that doesn't handle removed files properly until the remove has been commited)

So I can run `ninja many targets and more plus` which works, but is a bit annoying, as that list of target changes regularly and it'd be much simpler to write `ninja -x tags` for example.
(I can't really add a new phony rule with the rest as the build.ninja file is generated by meson, the extra target is added through `custom_target` with `build_by_default` set; I didn't see any way to make meson generate an alternate target with all-but-tags either)

Would it make sense to add some sort of option to exclude a target?

If that approach is sensible I'll be happy to try to do it and submit a PR, but would like approval on the concept first - I could totally understand wanting to keep ninja slim and refusing that flat out, no point in wasting time in this case :p

Thanks!

**Comment by mathstuf** [comment]
This sounds like a feature request to Meson more than a Ninja feature since it's something easily doable by generators.

**Comment by martinetd** [comment]
Hi, thanks for the reply.

I think it's a bit different, we could configure the generator to make two targets but that's pretty rigid.
If you want to cover all possibilities you'd need an exponential number of phony targets, that's not quite viable, and I'd be hard pressed to come up with a naming scheme that'd make sense to remember these.

The other way around (adding extra targets) is easy, e.g. if we'd remove `tags` from the `all` target then I could just run `ninja all tags` -- why not make that symetrical?

If exclude is a bit more general and just prevents targets to run even if they were pulled in dependency (now I've looked at the code it doesn't look like the phony target list is different from computed deps), then I can also come up with odd uses of such an option to e.g. exclude some arbitrary target if my repo is dirty and I want to test something totally separate quickly without branching off (I know, I'm weird)


Anyway, no strong feeling here, feel free to close this issue if you think it's out of scope.
(My offer to actually code this still stands if it would be acceptable, so "feature request" is a bit off ;))

**Comment by mathstuf** [comment]
Oh, I see, you want to *exclude* a target from being built.

> prevents targets to run even if they were pulled in dependency

I don't think that'd work very well. What semantics would this have?

> I can also come up with odd uses of such an option to e.g. exclude some arbitrary target if my repo is dirty and I want to test something totally separate quickly without branching off (I know, I'm weird)

This doesn't make much sense to me. Do you have something more concrete?

> Anyway, no strong feeling here, feel free to close this issue if you think it's out of scope.

I don't have that power here :) . I haven't seen many cases where arbitrary target removal from a DAG makes sense. Maybe for a handful of "special" targets (e.g., build a package, run tests, get source revision information) which is manageable from a generator point-of-view (and the former two probably shouldn't be in `all` anyways), but not arbitrary subsets.

**Comment by martinetd** [comment]
>> prevents targets to run even if they were pulled in dependency
>
> I don't think that'd work very well. What semantics would this have?

Just doesn't run the target. If it never was run before the build will probably fail because of the missing output, if the target had run previously it'd just use the previous version even if some files are dirty and it should have been rebuilt. User is responsible for shooting themselves in the foot here, tbh.

>> I can also come up with odd uses of such an option to e.g. exclude some arbitrary target if my repo is dirty and I want to test something totally separate quickly without branching off (I know, I'm weird)
>
> This doesn't make much sense to me. Do you have something more concrete?

I did say I'm weird. tbh this is far fetched even for me, but it's theorically possible: for example, a project is split into directories A and B that each generate a sub-library target, which is later on combined and used in directory C.
Say I have some development in A that I don't want to include (because it doesn't build, or change is invasive), but some test in B that I want. I could rebuild all --exclude A/liba.a (or whatever the target name is) and get the latest (previous) version of A that had compiled together with new changes of B, relinked into C.

Frankly that's not really a use-case I want to advertise anyway, it's way more reliable to stash the A side off in git, but stuff that I described in my top post (like ctags that mostly work but sometimes doesn't) could be valid enough :)

I agree most targets I'd want to exclude probably shouldn't be part of `all`, can only blame the supreme leader for that, but in this particular case the target mostly works and even I very rarely want it excluded.
In my short-sighted mind, it sounds more convenient to add --exclude ctags when that happen than to rerun meson configure -Denable_ctags=no, rebuild, then once that's fixed itself not forget to re-enable it.
Admitedly, we could just make the target more robust though... :)

**Comment by mathstuf** [comment]
> Just doesn't run the target. If it never was run before the build will probably fail because of the missing output, if the target had run previously it'd just use the previous version even if some files are dirty and it should have been rebuilt. User is responsible for shooting themselves in the foot here, tbh.

FWIW, CMake generates these kinds of targets for its Makefiles generator with a `/fast` suffix. So the `install/fast` target would try to install, but fail if any source files don't exist.

> I did say I'm weird. tbh this is far fetched even for me, but it's theorically possible:

I agree that it seems like `git stash` is a better solution here.

> Admitedly, we could just make the target more robust though... :)

I think this sounds like a better solution :) .
