### ISSUE TITLE
Add ARGS command line option to pass arguments to target.

### ISSUE THREAD

**Issue by phcerdan** [ninja-build/ninja#1387]
Assuming a target called `test`, so we could do:
```
ninja test ARGS="-R FooTest"
```
Which would be symmetric to existing `make` usage.
```
make test ARGS="-R FooTest"
```

My use case is unit testing using `ctest`. I can use `ctest` directly in the build directory, and pass arguments to it.
```
ctest -R "FooTest"
```

But I would like to call those tests from elsewhere, so I was using:
```
make test -C $build_dir ARGS="-R FooTest"
```

But ninja doesn't have this feature.

**Comment by nico** [comment]
Can't you just use `(cd $build_dir && ctest -R "FooTest")`? What's the advantage of involving ninja?

**Comment by phcerdan** [comment]
Ups, I didn't know that under `()` there is not change of directory. Anyway, I thought that passing whatever extra `ARGS` was a nice feature.

**Comment by nico** [comment]
Cool, sounds your use case is addressed, so closing this out for now :-)

**Comment by cruisercoder** [comment]
With ninja effectively as the front end command for GN, it would be useful to have just a bit more capability in passing arguments to scripts as it would make useful things simpler and less error prone for users.   A more compact form would be arguments after-- get passed to scripts.   Example:

ninja -C out/debug util/module:test && out/debug/module_test --gtest_filter=test1

with arg passing:

ninja -C out/debug util/module:run -- --gtest_filter=test1

It would also be useful if ninja had a way to pass the -v setting .to scripts.

**Comment by jhasse** [comment]
> With ninja effectively as the front end command for GN,

That's not a good idea if you want lots of features and quality-of-life improvements. Ninja is small and rather "low-level".

As for the test: IMHO it's much more transparent if unit test arguments are only passed to the test runner, e.g. you call the binary directly yourself. Let's say you want to wrap the call with `vallgrind`, how would you do that with ninja? Or you want to see it's output while it's being generated?

**Comment by cruisercoder** [comment]
Yes of-coarse, but ninja already knows the path to the test so it can help make the command shorter.  Argument forwarding just opens up some additional flexibility.

**Comment by jhasse** [comment]
Ah I see. That's unfortunate indeed, but as the generator also knows this, I think he should be the one who provides the shortcuts / a frontend. CMake does this with `cmake --build` and `ctest`, GN should probably too.

**Comment by phcerdan** [comment]
>With ninja effectively as the front end command for GN

What is GN?

**Comment by metti** [comment]
> What is GN?
https://gn.googlesource.com/gn/

**Comment by cruisercoder** [comment]
GN is the meta build system for Chromium that targets ninja.  It's a great build system but not well known.  Picking up on your example:

ninja -C out/debug widget:test && ./out/debug/theTestBinary --gtest_filter=test1

As I mentioned, GN has ninja do the actual builds, with GN being called as needed when build definitions change.  So if ninja supported arg forwarding, it could result in a much simpler command for users because ninja already has output directory (out/debug), the target (widget:test), and can run the test as well if forwarding were possible: 

ninja -C out/debug widget:test --  --gtest_filter=test1

**Comment by evmar** [comment]
Another option is to pass via the environment, like

```
...
  command = theTestBinary $$ARGS
```

and then

```
$ ARGS="-foo bar" ninja ...
```
