### ISSUE TITLE
/build/browse_py.h:2:1: error: expected primary-expression before ';' token

### ISSUE THREAD

**Issue by quicktrick** [ninja-build/ninja#1391]
Hello!  I'm trying to build `ninja` from the source code on Qnap NAS (`Linux QNAP 3.4.6 #1 SMP Fri Dec 8 10:21:53 CST 2017 i686 GNU/Linux`).  And I get the following error:

    # ./configure.py --bootstrap
    bootstrapping ninja...
    od: invalid option -- 't'
    BusyBox v1.27.2 () multi-call binary.
    
    Usage: od [-aBbcDdeFfHhIiLlOovXx] [FILE]
    
    Print FILE (or stdin) unambiguously, as octal bytes by default
    In file included from ./src/browse.cc:22:0:
    ./build/browse_py.h:2:1: error: expected primary-expression before ';' token
     ;
     ^
    when running:  g++ -MMD -MT build/browse.o -MF build/browse.o.d -g -Wall -Wextra -Wno-deprecated -Wno-missing-field-initializers -Wno-unused-parameter -fno-rtti -fno-exceptions -fvisibility=hidden -pipe '-DNINJA_PYTHON="python"' -O2 -DNDEBUG -fdiagnostics-color -DUSE_PPOLL -DNINJA_HAVE_BROWSE -I. -march=prescott -O2 -pipe -fomit-frame-pointer -fno-caller-saves  -c ./src/browse.cc -o build/browse.o
    Traceback (most recent call last):
      File "./configure.py", line 456, in <module>
        objs += cxx('browse', order_only=built('browse_py.h'))
      File "./configure.py", line 282, in cxx
        return n.build(built(name + objext), 'cxx', src(name + '.cc'), **kwargs)
      File "./configure.py", line 164, in build
        self._run_command(self._expand(cmd, local_vars))
      File "./configure.py", line 189, in _run_command
        subprocess.check_call(cmdline, shell=True)
      File "/subprocess.py", line 291, in check_call
    subprocess.CalledProcessError: Command 'g++ -MMD -MT build/browse.o -MF build/browse.o.d -g -Wall -Wextra -Wno-deprecated -Wno-missing-field-initializers -Wno-unused-parameter -fno-rtti -fno-exceptions -fvisibility=hidden -pipe '-DNINJA_PYTHON="python"' -O2 -DNDEBUG -fdiagnostics-color -DUSE_PPOLL -DNINJA_HAVE_BROWSE -I. -march=prescott -O2 -pipe -fomit-frame-pointer -fno-caller-saves  -c ./src/browse.cc -o build/browse.o' returned non-zero exit status 1.

How can I fix it?

    /build/browse_py.h
    
    const char kBrowsePy[] =
    ;

**Comment by sgraham** [comment]
The easiest way might be to make https://github.com/ninja-build/ninja/blob/master/configure.py#L107 return False for your platform.

**Comment by jonesmz** [comment]
Its been several years and several updates of ninja, including a new cmake build system

Can this issue be closed?

**Comment by quicktrick** [comment]
I don't even remember what I was doing it for anymore.  Yes, you can close it, it is no longer relevant.
