### ISSUE TITLE
Gradle .pom No trusted certificate found 

### ISSUE THREAD

**Issue by elig0n** [ninja-build/ninja#1395]
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring root project 'scrcpy'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:3.0.1.
     Required by:
         project :
      > Could not resolve com.android.tools.build:gradle:3.0.1.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.pom'.
               > sun.security.validator.ValidatorException: No trusted certificate found

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 6m 49s
ninja: build stopped: subcommand failed.

**Comment by evmar** [comment]
This looks like you're using ninja to execute a subcommand involving gradle(?) and that command is failing.  You should diagnose that; ninja is behaving correctly here and telling you that it failed.
