### ISSUE TITLE
ninja couldn't be found by cmake

### ISSUE THREAD

**Issue by galahard** [ninja-build/ninja#1396]
I've got a problem when i trying to compile an android sdk with ninja and cmake, but i've got this message : <CMake was unable to find a build program corresponding to "Ninja", xxxxxx >.
But i did add the ninja to PATH, and when i type <ninja --version>, i can get message: <1.8.2>, i have no ideas what wrong with it

**Comment by mqudsi** [comment]
Shouldn’t you be filing this with the cmake crew?

**Comment by galahard** [comment]
Yes, i did that and it works, sorry i am a newcomer for this, thanks
