### ISSUE TITLE
Bootstrap instructions have been lost

### ISSUE THREAD

**Issue by byron-hawkins** [ninja-build/ninja#1401]
Older versions of the ninja documentation (including the readme and the manual) mentioned how to bootstrap a git clone. The current version omits the word "bootstrap" entirely, and gives no hint about how to get a ninja binary. This line needs to be put back in the README:

    python configure.py --bootstrap

**Comment by evmar** [comment]
https://github.com/ninja-build/ninja/blob/master/README#L13

**Comment by byron-hawkins** [comment]
Hm, looks like I searched the manual for "bootstrap" but somehow missed it in the README (after scouring it several times...) It might be easier to find on a code line by itself, like in my original comment. But anyway, my mistake.

**Comment by evmar** [comment]
The logic of it is (not saying it makes sense, but the reasoning it's this way): the manual is only info you'd need if you had an installed binary already, while the stuff in git is the stuff you'd need if you checked out from git.
