### ISSUE TITLE
ninja: fatal: CreateProcess: The parameter is incorrect on Windows in Virtualbox

### ISSUE THREAD

**Issue by emmenlau** [ninja-build/ninja#1402]
I'd like to run ninja from cmake for many packages, but for some packages, I quite reproducibly I get an error
```
ninja: fatal: CreateProcess: The parameter is incorrect
```
I'm using Ninja 1.8.2 binary (current latest) with 4 jobs. Some packages build fine, and some of the packages build at least a few files. For example when I build zlib, it reproducibly fails on file 12 out of 25. The same builds always work with `jom -j4` or `nmake`.

My setup is quite complex. I have continuous integration with Windows 7 VS2015 and VS2017 set up in VirtualBox machines. The VMs run on Ubuntu 16.04 on an AMD Ryzen. cmake and ninja are orchestracted from Cygwin bash shell that executes `cmd /C`. Before starting `cmd` I remove almost all Cygwin environment settings like `PATH`, `LANG`, `MAKE`, ... etc to get a clean environment.

**Comment by emmenlau** [comment]
By the way, a very similar setup seems to work with `gcc`/`MSYS2` from the `MSYS2` bash shell. Ninja works just fine there. So possibly the issue is specific to `Cygwin` bash?

**Comment by rfgplk** [comment]
How long is the command line you are passing to ninja? Windows may fail to create a process if the string you pass to CreateProcess/CreateProcessA is too long (8191 characters, which I believe is the default Windows command line length limit). There are other reasons why process creation may fail, but this is the most common one. If this is the case, the 'bug' isn't in ninja, but is indirectly caused by Windows limitations; ninja attempts to create a process, yet is unable to do so, thus terminating since this is the only logical thing to do.


Sorry for the late reply, I hope this helped you if you haven't solved it on your own yet.

**Comment by emmenlau** [comment]
Dear @rfgplk , thanks for the helpful reply, maybe this is really the underlying problem! Gosch Windows is such a nuicance (sorry for the rant, I'll stop right there).

So I understand there is not really anything that can be done about it, is there? The cmake generator would need to try and build shorter command lines. Its certainly possible because `jom` builds the Makefile-based build quite fine. Are you in any contact with cmake development of the Ninja generator? Do you know if this is a viable route, seeing that Windows may not increase their limits any time soon? :-( :-(

**Comment by rfgplk** [comment]
Ok, after inspecting `jom` source code, the only difference in process generation is that `jom` indirectly calls `CreateProcessW`, while `ninja` calls `CreateProcessA` explicitly. I'm not a Windows developer and I'm not too well versed with the underlying function calls, but Windows may grant a larger limit if you use wide strings (?).

Changing src/subprocess-win32.cc may fix this, I don't have a Windows machine on hand so I cannot check this unfortunately.
`
  #include <locale>
  /*...*/
  std::wstring_convert<std::codecvt<char16_t,char,std::mbstate_t>,char16_t> convert;
  std::u16string wstr = convert.from_bytes(command);
  wchar_t* wcommand = _wcsdup((const wchat_t*)wstr.c_str());
  if (!CreateProcessW(NULL, wcommand, NULL, NULL,
                      /* inherit handles */ TRUE, process_flags,
                      NULL, NULL,
                      &startup_info, &process_info)) {
    DWORD error = GetLastError();
    if (error == ERROR_FILE_NOT_FOUND) {
      // File (program) not found error is treated as a normal build
      // action failure.
      if (child_pipe)
        CloseHandle(child_pipe);
      CloseHandle(pipe_);
      CloseHandle(nul);
      pipe_ = NULL;
      // child_ is already NULL;
      buf_ = "CreateProcess failed: The system cannot find the file "
          "specified.\n";
      return true;
    } else {
      Win32Fatal("CreateProcess");    // pass all other errors to Win32Fatal
    }
  }

`

**Comment by emmenlau** [comment]
Dear @rfgplk , thanks for this very great support. I can try CreateProcessW() after easter holidays, so it will take a while. But I checked up on https://msdn.microsoft.com/en-us/library/windows/desktop/ms682425%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396 and the documentation there says that the maximum command line length for these functions is 32,768 characters. This is also supported by other sources like https://stackoverflow.com/a/9992329/7200132.
The noteworthy exceptions seems to be `cmd` that can handle only 8191 characters.

Would it help if I send you the ninja build file for inspection? Maybe something else is off?

**Comment by emmenlau** [comment]
Finally the mystery is solved: On my system, the executable `cmcldeps.exe` was missing. There is no error in this case, just a broken `rules.ninja` file where the entry for the RC_COMPILER command is empty. Re-adding `cmcldeps.exe` fixed the issue.

On a related note: It would have helped a lot if the error message from ninja included the fact that the executable command is empty. ninja was just printing that the execution failed, without further hints as to what may be wrong.

**Comment by jhasse** [comment]
That would be #1637 if I'm not mistaken.

**Comment by emmenlau** [comment]
Yes! The printing as suggested there would have helped me quite a bit. Thanks.
