### ISSUE TITLE
Edges with output have wrong status line after #1405

### ISSUE THREAD

**Issue by colincross** [ninja-build/ninja#1418]
#1405 updates the status line to show the oldest running edge instead of the most recently finished edge, but does so before the edge output has been printed.  For example, this file:
```
rule echo
  command = sleep $delay && echo $out
  description = echo $out

build a: echo
  delay = 3
build b: echo
  delay = 2
build c: echo
  delay = 1
```

Produces:
```
[1/3] echo a
c
[2/3] echo a
b
[3/3] echo a
a
```

When it should produce:
```
[1/3] echo c
c
[2/3] echo b
b
[3/3] echo a
a
```

**Comment by jhasse** [comment]
Thanks for the detailed description! I've used your test case to add an automated test for this to Travis CI: https://github.com/ninja-build/ninja/blob/3841023a44621e8d8133e9eb6e79e26481dc0bc3/misc/output_test.py#L34
