### ISSUE TITLE
CMake/Ninja/MSVC RC command line issue with a path starting with '@' symbol

### ISSUE THREAD

**Issue by hokiedsp** [ninja-build/ninja#1429]
Hi,

I'm reporting a bug in calling MSVC RC command line tool from Ninja/CMake (could be an implicit call). I originally reported the issue on MSVC forum and MS determine the issue lies with Ninja. Please see [this link](https://developercommunity.visualstudio.com/content/problem/234068/rc-command-line-issue-with-a-path-starting-with.html) for my initial reporting there and subsequent feedback from MS. 

I have a CMake file structure where the source file is located in a subfolder "@Lime". When compiling, CMake/Ninja places all the intermediate build files in the "build\@Lime\CMakeFiles\mexfcn.dir" then tries to run the MSVC linker, which internally calls the RC command line with the following arguments:

"rc /fo@Lime\CMakeFiles\mexfcn.dir/manifest.res @Lime\CMakeFiles\mexfcn.dir/manifest.rc"

This fails (exit code 1) with the following message:

"fatal error RC1110: could not open Lime\CMakeFiles\mexfcn.dir/manifest.rc"

Notice that the '@' symbol is missing in the file it tried to open.

If I put the "@Lime" subfolder inside another folder, say "+MyPackage" the build routine succeeds. So, it's not a problem with all non-alphanumeric character.

[Minimum Example Download](https://developercommunity.visualstudio.com/storage/attachments/27417-rc-ninja-bug.zip)

**Comment by mathstuf** [comment]
This is likely [this CMake issue](https://gitlab.kitware.com/cmake/cmake/issues/16171).

**Comment by jhasse** [comment]
If I understand it correctly: This is a bug in `rc` where using rsp files would be a workaround.

> We have determined that this issue belongs to Ninja since things work when using the Visual Studio generator.

What does the Visual Studio generator do differently though? Does it use rsp files?

Either way: Nothing Ninja can do about this, sorry.
