### ISSUE TITLE
src/depfile_parser.cc and src/lexer.cc should be added to .gitignore and removed from the index

### ISSUE THREAD

**Issue by marcelpaulo** [ninja-build/ninja#1440]
*src/depfile_parser.cc* and *src/lexer.cc* should be added to *.gitignore* and removed from the index since they are regenerated by `./configure.py --bootstrap`. I had built ninja using:

```
git clone git://github.com/ninja-build/ninja.git
./configure.py --bootstrap
sudo cp -av ninja /usr/local/bin/
```

and when I tried to update it with `git pull --rebase --prune -v`, git complained that there were unstaged changes, and indeed:

```
paulo:~/src/ninja$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   src/depfile_parser.cc
        modified:   src/lexer.cc

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by sgraham** [comment]
How did they change for you locally? I believe they're not .gitignored because if the user doesn't have re2c the checked in copies are used, rather than failing the build.

**Comment by marcelpaulo** [comment]
I have re2c 1.0.1 installed. The build didn't actually fail, it just regenerated *depfile_parser.cc* and *lexer.cc*, which I only noticed when I later tried to `git pull --rebase`.

**Comment by marcelpaulo** [comment]
Oh, apologies, now I see what you mean: if re2c is not installed, the lexer and parser are not regenerated, so it makes sense to keep them in the index.

**Comment by sgraham** [comment]
Can you check `git diff`? Is it just something trivial like a version number in a comment, or did the contents change materially?

**Comment by marcelpaulo** [comment]
Oh dear, I'm kind of slower than usual today, please forgive me, you did ask:

> How did they change for you locally?

and I overlooked it.

The contents changed extensively. I've pasted the diff [here](https://paste.ee/p/mhYNH).

**Comment by marcelpaulo** [comment]
I'm running re2c **1.0.1-1** from the Ubuntu Bionic repositories.

**Comment by sgraham** [comment]
Hmm, that's too bad. It looks like it's reordered the passes through the state machine somehow. I'm not sure what we should do about that. Possibly checking in a newer version will avoid the problem (unless the next time someone builds with a newer or older one, I guess).

**Comment by marcelpaulo** [comment]
What about setting **re2c** as a build dependency, not include the lexer/parser with the sources, let the build generate them ? And, of course, gitignore them.

**Comment by sgraham** [comment]
Yeah, that would work some platforms. I think it is (was?) hard to get a build of re2c for Windows, and maybe for Mac. Not sure about all of https://github.com/ninja-build/ninja/blob/master/configure.py#L68 .

**Comment by sgraham** [comment]
(We could probably also .gitignore the files all the same, I think that just means having to `git add -f` or something, but since they change so rarely that probably doesn't matter.)

**Comment by marcelpaulo** [comment]
> Yeah, that would work some platforms

Oh, I forget that ninja is everywhere. My suggestion was too Linux-centric.

**Comment by nico** [comment]
I'm going to close this out since the original suggestion doesn't work (the build should work when you don't have re2c installed), and since it's not clear what to do instead.
