### ISSUE TITLE
Ninja build : Redirect error output to a log file

### ISSUE THREAD

**Issue by saraAshaikh** [ninja-build/ninja#1443]
I am using ninja build for compilation , it works fine and is quite fast but i am not able to redirect outputs. I am migrating from gnu make and would like to redirect the error output to a log file and exit if there are any compilation errors.

Below is the snippet:

cc = gcc
cflags= -c
rule compile 
  command = $cc $cflags  $in -o $out &> log.err || ( cat log.err; exit 1; )

build ninja/hello.o: compile hello.c

It produces below error: 

gcc: error: &>: No such file or directory

The command works fine when its used in gnu make/shellprompt but fails when the command is invoked by ninja build via cygwin. Please can someone tell me how can I solve this problem, as there are huge number of files that needs to be compiled and i just want to display errors on screen and not informaton messages and warning messages. Any pointers to solve this will be really appreciated.
Thank You in advance!

**Comment by atetubou** [comment]
On windows, ninja uses CreateProcess API to invoke command. It does not support bash specific notation.
What happen if you write command like below?
```
cc = gcc
cflags= -c
rule compile
command = bash -c "$cc $cflags $in -o $out &> log.err || ( cat log.err; exit 1; )"
```

**Comment by saraAshaikh** [comment]
Thanks it works.
But it does reflect proper output when it enters the || condition.
I added a colour output in || condition, but it did not display any colour.
command = bash -c " $cc $ccflags $in.k -o $out &> log.err || ( echo -e '\e[0:31m' \"compile fail \"'\e[0m'; cat log.err; exit 1 ; )"
This does not give coloured red output which I would expect. Please can you provide pointers on it.

**Comment by saraAshaikh** [comment]
Thanks it works.
But it does reflect proper output when it enters the || condition.
I added a colour output in || condition, but it did not display any colour.
command = bash -c " $cc $ccflags $in.k -o $out &> log.err || ( echo -e '\e[0:31m' \"compile fail \"'\e[0m'; cat log.err; exit 1 ; )"
This does not give coloured red output which I would expect. Please can you provide pointers on it.

**Comment by nico** [comment]
ANSI output on Windows under cygwin doesn't work, https://github.com/ninja-build/ninja/pull/1319#issuecomment-439188115

Closing this since the original issue was addressed.
