### ISSUE TITLE
ninja build: unable to show coloured output

### ISSUE THREAD

**Issue by saraAshaikh** [ninja-build/ninja#1444]
I am using cygwin and I would like to show coloured output when compilation fails.

I added a colour output in || condition, but it did not display any colour.
command = bash -c " $cc $ccflags $in.k -o $out &> log.err || ( echo -e '\e[0:31m' "compile fail "'\e[0m'; cat log.err; exit 1 ; )"
This does not give coloured red output which I would expect. Please can you provide pointers on it.
Any help would really be appreciated.
Thank You in Advance!

**Comment by atetubou** [comment]
What is shown when you run ninja with -v?
Copying showed command works fine?

**Comment by saraAshaikh** [comment]
It displays garbage values on screen for failing condition. No red colour is shown.
During positive condition it prints the entire command.

**Comment by saraAshaikh** [comment]
Also when i remove cat log.err then garbage values are not displayed but it prints compile fail without red colour
|| ( echo -e '\e[0;31m' compile fail '\e[0m'; exit 1; )"

**Comment by atetubou** [comment]
You may need to escape double quotation and backslash.
```
command = bash -c " $cc $ccflags $in.k -o $out &> log.err || ( echo -e '\\e[0:31m' \"compile fail \" '\\e[0m'; cat log.err; exit 1 ; )"
```

**Comment by saraAshaikh** [comment]
It still does not work :(. There is no colour in output.

**Comment by saraAshaikh** [comment]
Is this a bug?

**Comment by atetubou** [comment]
I want to know the answer of following questions with copy of output from your shell.

1. what is shown when you run `echo -e "\e[31m" "compile fail "` on your cygwin shell?
1. what is shown when you run ninja with `command = bash -c "echo -e '\e[31m' 'compile fail'"`
1. what is shown when you run ninja with `command = bash -c "echo -e '\\e[31m' 'compile fail'"`

**Comment by saraAshaikh** [comment]
Below are the outputs :
1. When runnning on cygwin shell. Below is the image. It just enters into edit mode and nothing is printed.
![1](https://user-images.githubusercontent.com/31311035/40988399-78723058-68da-11e8-87c1-62c8e22c6df7.png)
2. When running on ninjs with command = bash -c "echo -e '\e[31m' 'compile fail'". It does not print color output. Below is the image.
![2](https://user-images.githubusercontent.com/31311035/40988678-3ca1620a-68db-11e8-8829-dfd631d5f7d3.png)
3. Also does not print color output as done in step 3. Below is the image
![3](https://user-images.githubusercontent.com/31311035/40988952-fa4a3ab6-68db-11e8-953b-6757d8bbb8bd.png)

**Comment by saraAshaikh** [comment]
Do you need any other information or output?I tried many options but still not able to get colour output

**Comment by atetubou** [comment]
Sorry, I'm not sure why this happens, but windows ninja looks not showing exact output from subprocess.
I'm suspecting there are issue around subprocess-win32.cc, but cannot find the reason of drop of escape sequence.

**Comment by saraAshaikh** [comment]
Can we raise a bug for this?

**Comment by saraAshaikh** [comment]
?

**Comment by DonVito10** [comment]
Nemesis

**Comment by saraAshaikh** [comment]
Nemesis?

**Comment by evmar** [comment]
If 
echo -e "\e[31m" "compile fail"
doesn't show color under your terminal, then this is an issue with your terminal and not with Ninja.

**Comment by nico** [comment]
Ninja doesn't support ansi output on Windows. See also https://github.com/ninja-build/ninja/pull/1319#issuecomment-439188115
