### ISSUE TITLE
A Change in Preprocessor command is not recognised without a clean

### ISSUE THREAD

**Issue by akshayupendran** [ninja-build/ninja#1445]
Hello All,

I am new to ninja and the build system world.

I use a Ninja_v1.8.2 and CMake_v3.10.2.

If i change any preprocessor commands in an already built module's .h, these changes are not recognised by ninja but they are always recognised by make.

Basically any define changes in .h is not recognised by ninja.

Example:
I have a particualr a.h where the following is present:
#undef ENABLED

If I change it to:
#define ENABLED and rebuild without cleaning, as ninja 
ninja: no work to do.

**Comment by akshayupendran** [comment]
The only way to solve this problem seems to be explicitally linking related libraries.

**Comment by ePirat** [comment]
This sounds like failure to correctly set up dependencies by the meta build system or in the build system definition, so in your case CMake or your CMake build file.

**Comment by mathstuf** [comment]
Agreed that this is more closely related to CMake. I'd recommend posting over in [the CMake issue tracker](https://gitlab.kitware.com/cmake/cmake/issues) with a small reproducible test case.

**Comment by jhasse** [comment]
I can also not reproduce this with CMake 3.11.2.

@akshayupendran Can you check if this is till an issue and reopen if so? A minimal example to reproduce it would also help a lot.
