### ISSUE TITLE
ninja: error: mkdir() No such file or directory

### ISSUE THREAD

**Issue by Mrmayank** [ninja-build/ninja#1448]
Building native code source files for Android Studio project using gradle and cmake:
I got following error:
ninja: error: mkdir(some_dir_inside_externalnativebuild_folder): No such file or directory.

This error comes when compiling files which are not present in the default cpp folder of Android Studio.
However, in the 'CmakeLists.txt' I have provided the correct path to these native files.

**Comment by jhasse** [comment]
Thanks for the report. Are you sure, that it isn't a bug in Gradle or CMake though? Anyway: We'd need an example to reproduce this. Please try to find the culprit in your build definitions and reopen this issue.

**Comment by doghmoh** [comment]
@Mrmayank I had the same error but your solution didn't fix it.
