### ISSUE TITLE
ninja -v does not work as stated

### ISSUE THREAD

**Issue by maassg** [ninja-build/ninja#1450]
expected:
ninja -v  show all command lines while building

but it does:
any output only shows up when build process has finished.

**Comment by evmar** [comment]
Nobody else has reported this, so I believe it is something local to your system.  Which suggests you'll have to provide more information.

**Comment by Crides** [comment]
No it's not. I'm also encountering this problem. When calling anything other than `ninja -h` it would just hang. There is no `build.ninja` in my directory.

**Comment by evmar** [comment]
@Crides that appears to be something other than what the original person was reporting.  Both of you, please feel free to open a bug report with information that would help us track this down -- there's nothing we can do when you say "it hangs" when it works locally.

https://www.chiark.greenend.org.uk/~sgtatham/bugs.html
