### ISSUE TITLE
Support ANSI colors on Windows

### ISSUE THREAD

**Issue by Boddlnagg** [ninja-build/ninja#1451]
Clang's `cl.exe` has an option `-fansi-escape-codes` which makes it output ANSI colors instead of using the usual Windows console API. The console of Windows 10 in one of the updates gained the ability to show those colors correctly. This means that theoretically I could set that option and make Ninja correctly forward the colors (which can never work with the usual colors in Windows, because they are not part of the output stream).

However, it doesn't work for some reason, which I was not yet able to find out. Ninja will forward the colors with `pool = console`, but otherwise it won't. Furthermore, the the mode for automatic parsing of include dependencies via `deps = msvc` will probably also need to learn to ignore, but forward the ANSI escape codes.

**Comment by Befzz** [comment]
Windows user too(10 + clang), cmd.  
can't get colored output without `pool = console`

![coloredout](https://user-images.githubusercontent.com/1160036/42823494-584b63b2-89e6-11e8-8a9b-f031c51e3db1.PNG)
![coloredout2](https://user-images.githubusercontent.com/1160036/42823859-49aa1816-89e7-11e8-8323-092830bf7baf.PNG)
👆

**Comment by mqudsi** [comment]
@Befzz what build of Windows 10?

**Comment by Boddlnagg** [comment]
I'm actually having the same problem as @Befzz, running Windows 10 1709. Unless I run in a command line windows started with `bash.exe`/WSL (and then launching `powershell.exe` there), then `-fansi-escape-codes` works. However, this is a problem either in Windows or in Clang, not in Ninja.

When I'm running from a WSL shell, where it works apart from Ninja, it still doesn't work *with* Ninja though, so this is why I reported it here.

**Comment by evmar** [comment]
We write to the console with a special Windows function that might evade however Windows 10 understands color, but looking at this code it looks like maybe in some cases with the console pool it falls back on fwrite, which might explain how you had it work at some point.
https://github.com/ninja-build/ninja/blob/master/src/line_printer.cc

**Comment by Boddlnagg** [comment]
@evmar: I never had it working *with* Ninja, only *without* Ninja. But now I can't even get it to work *without* Ninja ...

**Comment by jhasse** [comment]
> The console of Windows 10 in one of the updates gained the ability to show those colors correctly.

Unfortunately it only does so, after a WinAPI call, see #1462.

**Comment by Kazark** [comment]
It would be definitely be nice to see this. We mostly use ConEmu, which supports ANSI sequences, and we do have commands that emit colors. Some of them probably are not using ANSI sequences though...

**Comment by Boddlnagg** [comment]
I'm not sure, but with the new [ConPTY](https://blogs.msdn.microsoft.com/commandline/2018/08/02/windows-command-line-introducing-the-windows-pseudo-console-conpty/) it might even be possible to capture classic (non-ANSI)  colored console output on Windows. But ninja currently does not use pseudo ttys at all (see also the first entry in the [FAQ](https://github.com/ninja-build/ninja/wiki/FAQ)).

**Comment by Salamandar** [comment]
Hi, this still does not work on Mingw/Msys2. Gcc correctly outputs colors when called manually with the same args (`-fdiagnostics-color=always`), but not through Ninja.
Gcc correctly outputs colors when piped to less.

I tried ninja with a custom target calling a bash script : 
```
# test_color.sh
#/bin/bash

echo -e "\033[34mbleu, \033[1mgras, \033[4msouligné, \
> \033[5mclignotant \033[7met surligné\033[0m"


# Meson target: 
custom_target('test_color',
  command: [
    find_program('bash'),
    join_paths(meson.current_source_dir(), 'test_color.sh'),
  ],
  output: 'test_color.sh',
)
```
* The standalone script outputs colors
* `ninja test_color.sh` does **not** outupt colors
* If I add `console: true,` to the Meson code, the script is called with the `console pool` and colors appear.

**Comment by jhasse** [comment]
Are you running ninja through mintty (MSYS2's shell)? IIRC we only detect native Windows command prompts and therefore think that we're piped in that case. That's why ANSI escape codes get stripped.

Try running with `CLICOLOR_FORCE=1 ninja` or `winpty ninja`.
