### ISSUE TITLE
How to install new ninja for XP?

### ISSUE THREAD

**Issue by kitaro1** [ninja-build/ninja#1464]
Ninja 45 build. All attempts were unsuccessful.
Why?
I need info about polish language.

**Comment by jonesmz** [comment]
If you mean Windows XP... I *strongly* suggest you investigate alternative operating systems. Windows XP has been out of support since 2014.

Alternatively, consider compiling Ninja from source for your OS of choice if the existing binary doesn't work for you.

**Comment by jhasse** [comment]
Yes, you'd need to compile ninja from source in order for it to work on Windows XP, sorry.
