### ISSUE TITLE
Unable to compile cuda files

### ISSUE THREAD

**Issue by pradeepisro** [ninja-build/ninja#1465]
I am trying to build cuda file using CMake and Ninja. I am getting the following 
    
    -- The C compiler identification is GNU 5.4.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/mcw/PK/Experiments/C++/ninja/ninja_flag_test/build
    [1/2] /usr/local/cuda/bin/nvcc    -O3 -DNDEBUG -MD -MT CMakeFiles/ninja_test_.dir/test.cpp.o -MF          CMakeFiles/ninja_test_.dir/test.cpp.o.d -o CMakeFiles/ninja_test_.dir/test.cpp.o -c ../test.cpp
    FAILED: /usr/local/cuda/bin/nvcc    -O3 -DNDEBUG -MD -MT CMakeFiles/ninja_test_.dir/test.cpp.o -MF CMakeFiles/ninja_test_.dir/test.cpp.o.d -o CMakeFiles/ninja_test_.dir/test.cpp.o -c ../test.cpp
    nvcc fatal   : Unknown option 'MD'
    ninja: build stopped: subcommand failed.

This is my CMake file

    cmake_minimum_required(VERSION 3.5.1)
    project(ninja_test)
    add_executable(ninja_test_ test.cpp)
    set(CMAKE_CXX_COMPILER /usr/local/cuda/bin/nvcc)

I don't have any problem with `make`. Why is `-MD -MT` flags are added automatically?

**Comment by mathstuf** [comment]
This is likely a CMake issue. Please file it on the [CMake issue tracker](https://gitlab.kitware.com/cmake/cmake/issues/). Thanks.
