### ISSUE TITLE
Cmake and ninja: passing arguments to targets

### ISSUE THREAD

**Issue by passama** [ninja-build/ninja#1466]
I am using CMake and I would like to switch from Makefile to Ninja to improve perfomance.
But I face a a problem: I cannot pass argument to my CMake custom targets. It seems it is a limitation of ninja, but not sure.

Here is my typical use case, I use this pattern in many places to deal with many concerns :

```cmake
add_custom_target(do_the_job
     	COMMAND ${CMAKE_COMMAND} -DVERBOSE_MODE=\${verbose}
        -P share/do_the_job.cmake
```
The CMake script `do_the_job.cmake`'s variable `VERBOSE_MODE` is set according to the `verbose` argument value that is set when the make tool is called. For instance:

```
make do_the_job verbose=TRUE
```
It is important to avoid reconfiguring with cmake (which can take a long time with complex projects) any time we want to set the value of an argument for a target.

I would like to achieve exactly the same approach, or similar, with ninja:

```
ninja do_the_job verbose=TRUE
```
So is it possible with ninja ?

If yes, how ?

If not, is it planned to be implemented ?

**Comment by mathstuf** [comment]
Ninja does not support variable replacements in commands like this (Neither does any non-Make generator for that matter). I don't expect it will be supported in Ninja either.

IMO, better would be to have the test script check the environment for the variable then `VERBOSE=TRUE make do_the_job` and `VERBOSE=TRUE ninja do_the_job` both work.

**Comment by passama** [comment]
OK thanks for the answer and also for the good advice !
