### ISSUE TITLE
Allow building in parallel from multiple out directories

### ISSUE THREAD

**Issue by kulakowski** [ninja-build/ninja#1468]
The motivation: building a large project with both x64 and arm64 variants, and wanting to share a pool (probably a link pool) between them. This could in theory be faster than building serially, and in theory lass system swamping than building concurrently.

**Comment by kulakowski** [comment]
@travisg

**Comment by evmar** [comment]
Per Ninja's philosophy, it's up to the build generator to generate the appropriate build files to make this happen.

**Comment by kulakowski** [comment]
I get that. I think what I was thinking of is a situation where it might be easier to express the layout of a build across several directories, and to have a root of the build that is synthesized out of several files, rather than requiring one literal file. But @sgraham convinced me this is nearly possible anyway just by subninja-ing those other places in, modulo some path munging.

It's probably not worth anyone's time to do this in ninja.

**Comment by oharboe** [comment]
When working on multiple projects that come from different sources, it isn't practical to generate a single giant ninja file.

What's needed is a single ninja process that takes multiple independent ninja files as input.

In lieu of this, there should be a way for independent ninja processes to collaborate on scheduling processes to avoid running too many processes.
