### ISSUE TITLE
CMake Error: CMAKE_C_COMPILER not set and CMake Error: CMAKE_CXX_COMPILER not set

### ISSUE THREAD

**Issue by ZipirMario** [ninja-build/ninja#1470]
Hello, I am using macOSHighSierra version 10.13.6,
I installed cmake and ninja; using brew install cmake and brew install ninja. 

CMake Error at platforms/android/android.toolchain.cmake:458 (message):
  Could not find neither Android NDK nor Android standalone toolchain.

      You should either set an environment variable:
        export ANDROID_NDK=~/my-android-ndk
      or
        export ANDROID_STANDALONE_TOOLCHAIN=~/my-android-toolchain
      or put the toolchain or NDK in the default path:
        sudo ln -s ~/my-android-ndk /opt/android-ndk
        sudo ln -s ~/my-android-toolchain /opt/android-toolchain
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.12.2/share/cmake/Modules/CMakeDetermineSystem.cmake:94 (include)
  CMakeLists.txt:85 (project)

CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
Traceback (most recent call last):
  File "build_sdk.py", line 366, in <module>
    builder.build_library(abi, do_install)
  File "build_sdk.py", line 175, in build_library
    execute(cmd)
  File "build_sdk.py", line 23, in execute
    raise Fail("Child returned: %s" % retcode)
__main__.Fail: Child returned: 1

**Comment by mathstuf** [comment]
> CMake Error: CMake was unable to find a build program corresponding to "Ninja".

This means that CMake could not find the ninja. Is your `PATH` set up properly to have `ninja` in there?

Also, this is more likely a CMake or Homebrew issue than Ninja issue.

  - CMake: https://gitlab.kitware.com/cmake/cmake/issues/
  - Homebrew: https://github.com/Homebrew/homebrew-core

**Comment by motecshine** [comment]
brew install Ninja will fixe it

**Comment by petrasvestartas** [comment]
Run the editor or command line with "Administrative settings"
