### ISSUE TITLE
Allow disabling escape code stripping

### ISSUE THREAD

**Issue by Boddlnagg** [ninja-build/ninja#1475]
There's this little `TODO` comment in the code that handles ANSI escape code stripping:

https://github.com/ninja-build/ninja/blob/52c1d0c8f8545231581c4d51cb0a85f50564c415/src/build.cc#L170

This would be really useful to me, and I didn't find an open issue about it, so I'm opening this one.

**Comment by jmesmon** [comment]
There is an existing PR to add that functionality: https://github.com/ninja-build/ninja/pull/1268

**Comment by xftroxgpx** [comment]
Since 1.8.2 is still the latest ninja release, [this fixed patch](https://github.com/ninja-build/ninja/pull/1268#issuecomment-328405287) from a comment still works for me.

**Comment by mathstuf** [comment]
See also #912 which is probably obsoleted by this support. It does have other fixes though, so I'll rebase it to pull out the useful fixes after another fix lands.
