### ISSUE TITLE
How to let ninja + gn work on CentOS 6?

### ISSUE THREAD

**Issue by dlintw** [ninja-build/ninja#1476]
I found the binary release ninja can run on CentOS 6, but it require the 'gn' to let it useful.
The official 'gn' only provide source, and it require newer C++ and python which are not provided by CentOS 6 (gcc 4.4.7, python 2.6.6).

Is there any guide to build ninja + gn on CentOS 6?  Or, it could be put in release of ninja together?
I've tried to install local python 2.7.15. And clang-3.4.2-4.e16.x86_64.  And modify the build/gen.py from '-std=c++14' to '-std=c++1y'. But 'ninja -C out'  shows:

```
clang++ -MMD -MF base/callback_internal.o.d  -I/home/user/tmp/gn -I/home/guest/tmp/gn/out -DNDEBUG -O3 -fdata-sections -ffunction-sections -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color --sysroot=/home/guest/tmp/gn/build/../.linux-sysroot -std=c++1y -Wno-c++11-narrowing -c /home/guest/tmp/gn/base/callback_internal.cc -o base/callback_internal.o
In file included from /home/user/tmp/gn/base/callback_internal.cc:5:
In file included from /home/user/tmp/gn/base/callback_internal.h:13:
In file included from /home/user/tmp/gn/base/memory/ref_counted.h:12:
/home/user/tmp/gn/base/atomic_ref_count.h:11:10: fatal error: 'atomic' file not found
#include <atomic>
         ^
1 error generated.
[2/238] CXX base/files/file_path.o
FAILED: base/files/file_path.o
```

**Comment by kirbyfan64** [comment]
This is likely because your version of libstdc++, which provides the headers, is too old. Have you tried using a Developer Toolset?

**Comment by dlintw** [comment]
> This is likely because your version of libstdc++, which provides the headers, is too old. Have you tried using a Developer Toolset?
I  don't know is there 'newer' developer toolset for such old CentOS 6.

I found a dirty workaround, use alpine to build and copy the related library from it. This workaround is based on the gcc library file does not conflict with old CentOS 6's.

1. Build by docker `docker run -i -t -v /mnt/tmp alpine` on other machine
```
apk update
apk add ninja alpine-sdk git make gcc g++ python tar wget bash re2c
git clone https://gn.googlesource.com/gn
cd gn
CC=cc CXX=c++ AR=ar python2 build/gen.py --no-sysroot
ninja -C out
cp /lib/ld-musl-x86_64.so.1 /usr/lib/libgcc_s.so.1 /lib/ld-musl-x86_64.so.1 out/gn /mnt/tmp
```
2. Install to CentOS related directories
```
sudo cp /mnt/tmp/ld-musl-x86_64.so.1 /mnt/tmp/libgcc_s.so.1 /lib
sudo cp gn /usr/bin
```

**Comment by h1z1** [comment]
Not quite shure why this would be closed.  Is there anything in release notes as to libc version requirements?  Requiring Google for a build system seems kinda counter productive.

Related #1533
