### ISSUE TITLE
Needs release

### ISSUE THREAD

**Issue by Twey** [ninja-build/ninja#1477]
There are a variety of bugs in ninja that have been fixed on master but still exist elsewhere because they have not been incorporated into a release.  For example, we're trying to use ninja internally at my company, but are suffering through https://github.com/ninja-build/ninja/pull/1219 ; we are using an internally-maintained patchset that includes the fix, but this is obviously suboptimal.

Is there a roadmap for a ninja release that distros can package?  The last (even patch) release was over a year ago.

**Comment by nico** [comment]
Yes, let's try to do a release in the next month or two. Sorry about the radio silence.

**Comment by Boddlnagg** [comment]
But https://github.com/ninja-build/ninja/issues/1418 should be investigated first ...

**Comment by jhasse** [comment]
> Is there a roadmap for a ninja release that distros can package?

I've created https://github.com/ninja-build/ninja/milestone/1 as some kind of roadmap what needs to get fixed before the next release.

**Comment by Twey** [comment]
Thank you so much, folks! It's a great relief to hear this — I was a little worried that ninja wasn't active any more. ☺

**Comment by Twey** [comment]
It looks like the roadmap is all done! ^_^

**Comment by Pwera** [comment]
+1

**Comment by jonesmz** [comment]
@jhasse 

Could https://github.com/ninja-build/ninja/milestone/1  be updated, so contributors know which PRs need attention first?

**Comment by jhasse** [comment]
As far as I'm concerned there's nothing left to be done for 1.9.0.

**Comment by jonesmz** [comment]
@nico @evmar Any advice?

**Comment by ignatenkobrain** [comment]
There's RELEASING file in repository. Please release new version. Thanks!

**Comment by nico** [comment]
Yes, see RELEASING. Step 1 is to send something like the "Call for 1.8 testing: vfork spawn, larger path component, faster clparser, vs2017, uclibc, dragonfly" thread for 1.9 and wait a bit, and not merge any commits in the meantime.

**Comment by jhasse** [comment]
Okay, I've posted to the mailing list :) https://groups.google.com/forum/#!topic/ninja-build/F5CWcXiv4TU

If I forgot any important change that needs more testing, please add a post there.

**Comment by ignatenkobrain** [comment]
@jhasse seems that no one has any objections, could you make new release?

Thanks!

**Comment by jhasse** [comment]
I don't have access to a Mac, so I'll fix #1509 first.

**Comment by jonesmz** [comment]
It's been over 30 days.

My mailing list message asking about this is sitting in moderator limbo. Is the mailing list moderator not active at this time?

What else needs to be done for a release?

**Comment by jhasse** [comment]
> What else needs to be done for a release?

Just #1509.

**Comment by jhasse** [comment]
Released. Only thing left: https://github.com/ninja-build/ninja-build.github.io/pull/6

**Comment by Boddlnagg** [comment]
At least on Windows, for the newly released version, `ninja --version` reports `1.8.2.git`, and when you upgrade from the previously released version, it seems to be recognized as a downgrade and ninja reports
```
ninja: warning: bad deps log signature or version; starting over
```
... and builds everything from scratch.

**Comment by mathstuf** [comment]
I don't think Ninja ships with support for multiple deps log formats, so I'm not surprised at that if 1.9 has a new format.

**Comment by jhasse** [comment]
Thanks @Boddlnagg! That's indeed a bug: I've uploaded the wrong binaries ... Very sorry for that.

I've updated them and now ninja should correctly report its version as 1.9.0.
