### ISSUE TITLE
Failed when using with xcbuild.

### ISSUE THREAD

**Issue by 372945980** [ninja-build/ninja#1487]
When I excute the code `xcbuild -executor ninja [-workspace Example.xcworkspace ...]` in command line, it failed.Any suggestion would be great appreciated!

`warning: unhandled Compiler key SupportedLanguageVersions
warning: unhandled ProductType key IsUnitTest
warning: unhandled ProductType key IsUITest
warning: unhandled ProductType key IsUnitTest
warning: unhandled ProductType key IsUnitTest
warning: unhandled ProductType key IsUITest
warning: unhandled ProductType key IsUnitTest
error: cannot find base BuildSystem specification 'embedded-shared:com.apple.buildsettings.standard'
error: cannot find base ProductType specification 'embedded-shared:com.apple.product-type.framework'
error: cannot find base ProductType specification 'embedded-shared:com.apple.product-type.xpc-service'
error: cannot find base ProductType specification 'embedded:com.apple.product-type.pluginkit-plugin'
error: cannot find base BuildSystem specification 'embedded:com.apple.build-system.core'
error: cannot find base BuildSystem specification 'embedded:com.apple.build-system.native'
error: cannot find base Linker specification 'embedded:com.apple.pbx.linkers.ld'
error: cannot find base ProductType specification 'embedded-simulator:com.apple.product-type.pluginkit-plugin'
warning: unhandled PlatformVersion key BuildAliasOf
warning: unhandled Product key BuildID
warning: unhandled Product key BuildID
warning: unhandled PlatformVersion key BuildAliasOf
warning: unhandled Product key BuildID
warning: unhandled Product key BuildID
warning: unhandled PlatformVersion key BuildAliasOf
warning: unhandled Product key BuildID
warning: unhandled Product key BuildID
warning: unhandled PlatformVersion key BuildAliasOf
warning: unhandled PlatformVersion key BuildAliasOf
warning: unhandled Product key BuildID
warning: unhandled Product key BuildID
warning: unhandled Product key BuildID
warning: unhandled Product key BuildID
warning: unhandled Product key BuildID
warning: unhandled Product key BuildID
warning: unhandled Architecture key DeploymentTargetRange
warning: unhandled Architecture key DeploymentTargetRange
warning: unhandled Architecture key DeploymentTargetRange
warning: unhandled ProductType key IsUnitTest
warning: unhandled ProductType key IsUITest
warning: unhandled ProductType key IsUnitTest
error: cannot find base ProductType specification 'iphoneos-shared:com.apple.product-type.application'
error: cannot find base ProductType specification 'iphoneos-shared:com.apple.product-type.app-extension'
error: cannot find base ProductType specification 'iphoneos-shared:com.apple.product-type.app-extension'
error: cannot find base BuildSystem specification 'embedded:com.apple.build-system.native'
error: cannot find base ProductType specification 'appletvos-shared:com.apple.product-type.app-extension'
error: cannot find base ProductType specification 'appletvos-shared:com.apple.product-type.app-extension'
error: cannot find base ProductType specification 'watchos-shared:com.apple.product-type.application'
error: cannot find base ProductType specification 'watchos-shared:com.apple.product-type.app-extension'
error: cannot find base ProductType specification 'watchos-shared:com.apple.product-type.app-extension'
error: cannot find base ProductType specification 'watchos-shared:com.apple.product-type.app-extension'
error: cannot find base Compiler specification 'embedded:com.apple.compilers.llvm.clang.1_0.compiler'
error: cannot find base Compiler specification 'embedded:com.apple.xcode.tools.swift.compiler'
error: cannot find base Linker specification 'embedded:com.apple.pbx.linkers.ld'
error: cannot find base Compiler specification 'embedded:com.apple.xcode.tools.swift.compiler'
error: cannot find base Linker specification 'embedded:com.apple.pbx.linkers.ld'
error: cannot find base BuildSystem specification 'macosx:com.apple.buildsettings.standard'
Generating Ninja files...
warning: object version 48 may be unsupported
warning: object version 48 may be unsupported
unable to find executable: builtin-infoPlistUtility
error: failed to build target ninja
error: failed to generate build.ninja`

**Comment by jhasse** [comment]
I think this has something to do with Xcode, not Ninja itself. Please ask on stackoverflow.com or try [Ninja's mailing list](http://groups.google.com/group/ninja-build).
