### ISSUE TITLE
How to see the full list of processed files?

### ISSUE THREAD

**Issue by ilg-ul** [ninja-build/ninja#1489]
Is there any way to configure ninja to **do not** overwrite the display of the current processed file, and leave the entire list visible?

In the version I use (1.8.2), when the build is complete, only the link step is displayed and I would like to see the full list of compiled files.

(It's not that I do not trust ninja, but I'm actually working on integrating ninja in my own automated build tools, and I'd be more confident that my tools generate the correct ninja files by seeing the full list on the screen)

**Comment by jhasse** [comment]
Yes: Either pass `-v` (will enable additional output) or do one of the following:

```
ninja | cat
```

```
env TERM=dumb ninja
```

Hope that helps :)

**Comment by ilg-ul** [comment]
Passing `-v` showed the list of full command lines. Not exactly the desired behaviour, but I can live with it.

The other suggestions are less useful, since my build tools are not Linux specific.

Thank you.

**Comment by jhasse** [comment]
> not Linux specific.

Windows?

**Comment by ilg-ul** [comment]
Well, yes and no.

I start ninja/make from a portable node.js CLI application ([xmake](https://github.com/xpack/xmake-js)).
