### ISSUE TITLE
Library most depended on builds last causing serialized link

### ISSUE THREAD

**Issue by trebconnell** [ninja-build/ninja#1504]
My project builds a library (Common) that nearly every other target links against.  The issue is that objects for Common are built last.  Which means that when Common links, all other targets are done building and now are blocking on Common. 

Since every other target explicitly depends on Common I'd hope that Common's objects could be built first so it can start linking early and be done by the time other targets are ready to link.

This issue is perhaps fixable by #232 

This is in ver 1.8.2

**Comment by nico** [comment]
ninja currently builds things roughly in the order they're listed in the build manifest. If you can coax your generator to list the sources for the Common library first, it should be built first.

**Comment by trebconnell** [comment]
I cannot find a good way to do precompiled header without causing this issue.  This could be considered a bug on CMake since it's the one writing the ninja build file in a strange order.

If you'd like you can close this.

Thanks,

**Comment by jhasse** [comment]
Okay. Btw: #376
