### ISSUE TITLE
Incorrect condition for `st_mtim` field name

### ISSUE THREAD

**Issue by michaelforney** [ninja-build/ninja#1510]
I noticed an issue with the ifdefs in d2bf82fe (nanosecond mtime fields). That commit seems to be misinterpreting how feature test macros work[0]. `_POSIX_C_SOURCE`, `_XOPEN_SOURCE`, `_BSD_SOURCE` and `_SVID_SOURCE` are defined by the *application* to tell the libc headers what to expose. They are not defined by the libc as the commit message says.

The POSIX standardized field name is st_mtim[1], so that should be used as the default and worked around only for platforms that don't have this field (i.e. macOS and apparently AIX). This will prevent having to extend the condition for every platform that uses the POSIX name (i.e. Solaris in 1952afa5, and FreeBSD in febd3b37). This also breaks on musl, and I suspect BSDs as well.

[0] https://ftp.gnu.org/old-gnu/Manuals/glibc-2.2.3/html_node/libc_13.html
[1] http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/sys_stat.h.html

**Comment by markand** [comment]
Hello,

Is there any chance that the fix gets merged? It looks like Alpine also use this [patch](https://git.alpinelinux.org/aports/tree/main/ninja/fix-musl.patch).

**Comment by jhasse** [comment]
Yes, someone needs to check if this doesn't break anything for AIX, Android, and Solaris and comment on #1510. In general I would prefer if we could test more of this with CI, see #1526.
