### ISSUE TITLE
CMake "CodeBlocks - Ninja" -v option

### ISSUE THREAD

**Issue by GFeicht** [ninja-build/ninja#1512]
I'm using CMake to create a "CodeBlocks - Ninja" project.
It works but in the CodeBlocks Build options the ninja-call always has the "-v" parameter.
Does anybody know how to bring CMake not to add the "-v" option to the ninja call?
I tried something like "-DCMAKE_VERBOSE_MAKEFILE=OFF", but it did not help...

**Comment by jhasse** [comment]
I think you should ask this on a CMake support forum, as it isn't an issue with ninja itself.

**Comment by GFeicht** [comment]
Ok, Thanks!
