### ISSUE TITLE
Binary reproducible manual using asciidoctor

### ISSUE THREAD

**Issue by domenkozar** [ninja-build/ninja#1528]
As part of making [NixOS image binary reproducible](https://r13y.com) we've noticed that [ninja manual is not binary reproducible](https://r13y.com/diff/nc8q6v3mx4cdrwn1fzspwrygka9c2hcc-ninja-1.8.2.drv.html) since chapter titles get assigned auto-generated random id.

I'd suggest using asciidoctor.org that makes asciidoc documentation a breeze and fixes the issue by making auto-generated links derived from the title itself.

I've uploaded [a demo of how manual would look without any tweaks](https://static.domenkozar.com/ninja.html) using `asciidoctor manual.asciidoc -o ninja.html`.

**Comment by jhasse** [comment]
If I understand it correctly: Fixed by #1529.
