### ISSUE TITLE
After installing via pip3, ninja/ninja install works, but sudo ninja install "command not found"

### ISSUE THREAD

**Issue by GregHewittDA** [ninja-build/ninja#1531]
Hey ya'll,

I'm using an Up Squared bored with Ubuntu 16.04, and as part of the steps to install gstreamer plugins for Intel's GPU, I've been introduced to ninja. I recognize that most of ya'll have very specific and detailed questions, where this is more basic - I apologize in advance.

In my build directory, I successfully execute ninja, but when it's time to "sudo ninja install" i get a "command not found" error. This puzzles me because I can import ninja into my python3 console as a user or root. Can anyone provide some advice to move forward?

**Comment by jhasse** [comment]
What does `whereis ninja` return?

**Comment by GregHewittDA** [comment]
Hi @jhasse, whereis ninja returns /home/lab/.local/bin/ninja

If I run as root, no output from that command - is the solution as simple as installing as root?

**Comment by jhasse** [comment]
root doesn't have `/home/lab/.local/bin` in the `PATH`. I don't know how you installed ninja, but if you use `apt` it would go to `/usr/bin`.

Yes, that's probably the solution.

**Comment by GregHewittDA** [comment]
Hi @jhasse pip3 install ninja - it was an instruction in Intel's Media SDK branch for their up squared board. Their documentation is on the order 4 versions behind their software, so I've discovered numerous bumps in the road like this. Thanks for the help on this issue.
