### ISSUE TITLE
Build fixes for DragonFly

### ISSUE THREAD

**Issue by davshao** [ninja-build/ninja#1532]
Discovered for 1.9.0

--- src/disk_interface.cc.orig	2019-01-30 18:58:59.000000000 +0000
+++ src/disk_interface.cc
@@ -206,7 +206,7 @@ TimeStamp RealDiskInterface::Stat(const
   return ((int64_t)st.st_mtimespec.tv_sec * 1000000000LL +
           st.st_mtimespec.tv_nsec);
 #elif (_POSIX_C_SOURCE >= 200809L || _XOPEN_SOURCE >= 700 || defined(_BSD_SOURCE) || defined(_SVID_SOURCE) || \
-       defined(__BIONIC__) || (defined (__SVR4) && defined (__sun)) || defined(__FreeBSD__))
+       defined(__BIONIC__) || (defined (__SVR4) && defined (__sun)) || defined(__FreeBSD__) || defined(__DragonFly__))
   // For glibc, see "Timestamp files" in the Notes of http://www.kernel.org/doc/man-pages/online/pages/man2/stat.2.html
   // newlib, uClibc and musl follow the kernel (or Cygwin) headers and define the right macro values above.
   // For bsd, see https://github.com/freebsd/freebsd/blob/master/sys/sys/stat.h and similar

From DragonFly dports devel/ninja 1.8.2

--- src/util.cc.orig	2017-09-11 01:20:10.000000000 +0000
+++ src/util.cc
@@ -40,7 +40,7 @@
 
 #include <vector>
 
-#if defined(__APPLE__) || defined(__FreeBSD__)
+#if defined(__APPLE__) || defined(__FreeBSD__) || defined(__DragonFly__)
 #include <sys/sysctl.h>
 #elif defined(__SVR4) && defined(__sun)
 #include <unistd.h>

**Comment by jhasse** [comment]
Would #1513 fix your issue as well?

**Comment by jhasse** [comment]
If not, please reopen.
