### ISSUE TITLE
How to install Vim plugin using Vundle?

### ISSUE THREAD

**Issue by Muffo** [ninja-build/ninja#1538]
Could you please clarify how to install the Vim plugin using Vundle? Maybe adding it as a comment in the plugin file itself would be useful for future reference.

I tried the following but they didn't work:
```
Plugin 'ninja-build/ninja'
Plugin 'ninja-build/ninja', {'rtp': 'misc/'}
```

**Comment by goshhhy** [comment]
The vim script in misc is currently not provided as a pathogen bundle, so package managers like Vundle will not be able to install it. Instead you will have to manually download and install the file to your '~/.vim/syntax/' folder.

**Comment by mqudsi** [comment]
I actually forked the vim script out of this project awhile ago (2 years ago, according to the git history) for this reason; it loads for me directly (with dein) from the alternate url: https://github.com/mqudsi/ninja.vim

**Comment by jonesmz** [comment]
Is this still an issue? Or can it be closed now?

**Comment by Muffo** [comment]
Not an issue anymore. Closing ticket.
