### ISSUE TITLE
How to export all rules by compdb?

### ISSUE THREAD

**Issue by dlintw** [ninja-build/ninja#1539]
I'm using 'gn' as frontend tool of ninja.
I don't know wha't the proper rules to export all ruls by compdb

I found maybe the rules come from build/toolchain/BUILD.gn.
And I review ninja.build, try to figure out all rules manually.

It seems as

    ninja -t compdb cc cxx alink solink link stamp copy

But, there are many other rule which is not come from toolchain/BUILD.gn. So,

```
$ find .  -name '*.ninja' -exec grep -l '^rule' {} /dev/null \;
./toolchain.ninja
./build.ninja
```

So, the current workaround seems be

    ninja -t compdb  $(grep '^rule' build.ninja  toolchain.ninja | awk '{print $2}')

But, I think this is just for 'gn' build tool,  it should has option to list all rules.

**Comment by jhasse** [comment]
> But, I think this is just for 'gn' build tool, it should has option to list all rules.

Either that or #1377.
