### ISSUE TITLE
ninja.exe reported as a virus

### ISSUE THREAD

**Issue by gmcode** [ninja-build/ninja#1540]
FYI, Windows Security Essentials on Windows 7 reports that ninja.exe/ninja-win.zip contains the "win32/skeeyah,1" virus.

From v1.90:
https://github.com/ninja-build/ninja/releases

**Comment by mmlinford** [comment]
FWIW I built it following the instructions in HACKING.md and no complaints from Windows Defender.

**Comment by MarcKamradt** [comment]
Same problem on Windows 10 Pro 64 bit here. The zip file is automatically removed when being downloaded using Chrome.

**Comment by jhasse** [comment]
I can't reproduce this on Windows 7 Home 32 bit.

These are the sha256 hashes:

```
36988933d4eba04ed288740f578b6e579b2582c9bf4e51319a7335520cb2b324  ninja.exe
```

```
2d70010633ddaacc3af4ffbd21e22fae90d158674a09e132e06424ba3ab036e9  ninja-win.zip
```

The binary was downloaded from https://dev.azure.com/jhasse/jhasse/_build/results?buildId=34 btw and zipped by myself (Azure Pipelines creates an extra folder inside the zip which I wanted to avoid). Can you test if re-zipping the file fixes the problem?

**Comment by MarcKamradt** [comment]
I restored the .zip file using Windows Defender and then extracted the ninja.exe manually. I then uploaded the .exe to VirusTotal and here is the result: https://www.virustotal.com/gui/file/36988933d4eba04ed288740f578b6e579b2582c9bf4e51319a7335520cb2b324/detection

So the .exe itself is flagged by Windows Defender and not by other detection engines.

**Comment by MarcKamradt** [comment]
The sha256 of ninja.exe matches. I deleted the zip already, so no idea there.

**Comment by jhasse** [comment]
If it's the exe itself that gets detected, re-zipping won't help (Windows Defender extracts archives on the fly).

I guess someone should report this to Microsoft? Looks like a false-positive to me (or Azure Pipelines has been compromised).

**Comment by MarcKamradt** [comment]
I submited a report: https://www.microsoft.com/en-us/wdsi/submission/d0ca013d-ed87-4762-9dff-274e9d2a6640

**Comment by MarcKamradt** [comment]
Funny how Microsoft uses an outdated database themselves when doing an initial automated test - which of course does not detect anything wrong with ninja.exe...

**Comment by mmlinford** [comment]
Thanks for looking at this so quickly, @jhasse . I really, really wish we knew *why* it got flagged, though (I don't know if @MarcKamradt 's ticket contains details since I'm unable to access it for some reason, but googling for details on that specific name didn't tell me anything useful).

**Comment by MarcKamradt** [comment]
The ticket was resolved by Microsoft stating they will update their database. The ticket is already removed from their system and cannot be accessed anymore.

I manually updated my virus definitions and I could download the windows zip file without any problems. So I guess this is solved.

**Comment by jhasse** [comment]
Thanks!
