### ISSUE TITLE
v1.9.0 does not have the executable flag set (Linux/Mac)

### ISSUE THREAD

**Issue by Farwaykorse** [ninja-build/ninja#1551]
A minor thing, probably unintended, but it tripped my CI configuration.

Ninja release v1.9.0 for Linux (and Mac) is not marked as executable.
Where v1.8.2 extracts with the file permissions set to `0755`, v1.9.0 has `0666`.

**Comment by jhasse** [comment]
Unintended indeed, my bad, sorry! The whole release process needs to be automated more, I'm currently waiting for a repo owner for https://github.com/ninja-build/ninja/pull/1526.

Before I re-zip the binaries and update the release, does `chmod +x` for the Mac binary work if I do it on a Linux system?

**Comment by jhasse** [comment]
Thx! I've updated the release.
