### ISSUE TITLE
depfile degrades explicit dependency

### ISSUE THREAD

**Issue by jtxa** [ninja-build/ninja#1574]
A missing explicit dependency, like the C file itself, is causing such useful error message:
~~~
ninja: error: 'main.cpp', needed by 'CMakeFiles/issue_18985.dir/main.cpp.o', missing and no known rule to make it
~~~

If the compiler was previously called and a depfile has been read, this message does not occur anymore and the compiler is called instead and will fail because of the missing source file.

In my opinion explicit dependencies should always be handled as such, regardless of the information of a depfile.

But I think normal make has the same problem after reading .d files, so this is rather a feature request than a bug report. To be better than normal make.

[side discovery in a CMake issue](https://gitlab.kitware.com/cmake/cmake/issues/18985#note_571741)

**Comment by jhasse** [comment]
The reason for this is performance: Ninja wants to avoid asking the disk as much as possible. Since the compiler checks if the file exists anyway, the only advantage would be a consistent error message. I think the trade-off is okay.

**Comment by jtxa** [comment]
Thank you for clarification.
Although it's not true for this particular case, because the rebuild was initiated by this missing main.cpp.
But I agree that it may not worth to check for this corner case if there are many other cases because of the performance optimization.
