### ISSUE TITLE
Cannot access release notes

### ISSUE THREAD

**Issue by rafzi** [ninja-build/ninja#1576]
The release notes link on the website and the Github release page does not work:

https://groups.google.com/forum/#!topic/ninja-build/nY5Kb7zUvcg

Saying:

The group does not exist or you do not have permission to access it.

**Comment by jhasse** [comment]
Does this link work?

https://groups.google.com/d/msg/ninja-build/nY5Kb7zUvcg/FIIn5j6-EwAJ

**Comment by rafzi** [comment]
Nope, same issue.

You can probably test that in an incognito tab.

**Comment by jhasse** [comment]
You're right, the group settings were messed up. Should work now :)

Thanks for creating the issue.

**Comment by rafzi** [comment]
Thanks for the quick fix!
