### ISSUE TITLE
How to generate static .lib files on Windows

### ISSUE THREAD

**Issue by DragonOsman** [ninja-build/ninja#1581]
I want to know how I can have Ninja generate static .lib files.  I'm trying to build V8 with the version of Ninja that's shipped with the source tree (1.8.2). Any help is appreciated.  Thanks.

**Comment by atetubou** [comment]
I think this issue is not good asking in ninja. [v8-dev](https://groups.google.com/forum/?nomobile=true#!forum/v8-dev) seems appropriate.

Anyway, v8 build generates static lib by default if you follow
https://v8.dev/docs/build-gn#gm

Or specify is_component_build=false in args.gn.
