### ISSUE TITLE
ninja --version should not result in an error

### ISSUE THREAD

**Issue by shvelo** [ninja-build/ninja#1582]
Running `ninja --version` with ninja 1.9.0 results in the following output:

```
ninja: error: loading 'build.ninja': No such file or directory
```
This is wrong, it should not need to load `build.ninja` to print its own version.  

This breaks `meson` for me, since it uses `ninja --version` to determine installed Ninja version, it currently fails:

```
ERROR: Could not detect Ninja v1.5 or newer
```

**Comment by jhasse** [comment]
That's already how `--version` works. Please post more system information, so that we can reproduce.

**Comment by shvelo** [comment]
Looks like I had an older version of ninja somewhere in my PATH
