### ISSUE TITLE
Having an option to ignore generator rule/statement

### ISSUE THREAD

**Issue by bobzhang** [ninja-build/ninja#1585]
By default, ninja already ignore generator rules, but it does not work on CI sometimes, when doing a git clone, the timestamp is lost

**Comment by jhasse** [comment]
I'm not sure I understand what you mean. Is your build manifest not in Git?

**Comment by bobzhang** [comment]
Suppose you have a rule

```ninja
rule cpp 
	command = cpp $in -o $out
        generator = true
build xx.c : cpp xx.c.in
```
And you check in generated files in general, but in CI you don’t have cpp binary installed, it should be fine if git clone
preserved time stamp, the rule is not triggered. However, from time to time, the time stamp is not preserved in various environments, 
so the command cpp is still triggered, this would cause an error since cpp is not available (cpp is expected to be a dev dependency like re2c 
used in ninja)

**Comment by bauen1** [comment]
@bobzhang You're probably looking for a tool like [`git-restore-mtime`](https://github.com/MestreLion/git-tools) to correct the time stamps of the repo after checkout for CI.

This doesn't seem to be an issue with ninja, since it is behaving as expected (regenerating outdated build objects when needed).

**Comment by jhasse** [comment]
Or #1459 ;)

**Comment by bobzhang** [comment]
It is not ninja's fault, but in an imperfect world it would be nice to have ninja provide a work around. I could use tools like @bauen1 mentioned, but I had to make it available in CI first..
#1459 is similar but not exactly the same, ideally I want to have a way to skip the generator rules completely without relying timestamps. 
I have a local patch, I would like to send a PR if you are interested
