### ISSUE TITLE
Difficulty building ninja on linux using the boost library

### ISSUE THREAD

**Issue by OliPerraul** [ninja-build/ninja#1589]
Hi, I am facing issues trying to build ninja on ubuntu. I am executing the following command
`sudo python configure.py --bootstrap` however I get the following error:

````
./src/daemon.h:18:10: fatal error: boost/asio.hpp: No such file or directory
 #include <boost/asio.hpp>
````

I fully installed boost and made sure to to set the Boost environment variables in `/etc/environment`. 

````
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/operrault/boost_1_70_0"

BOOST_ROOT="/home/operrault/boost_1_70_0"
ASIO_HOME="/home/operrault/boost_1_70_0/boost/asio"
BOOST_INCLUDEDIR="/home/operrault/boost_1_70_0"
BOOST_LIBRARYDIR="/home/operrault/boost_1_70_0/stage/lib"
Boost_INCLUDE_DIRS="/home/operrault/boost_1_70_0"
Boost_LIBRARY_DIRS="/home/operrault/boost_1_70_0/stage/lib"
````

the boost/asio.hpp file does indeed exist on my drive and is located here:
`/home/operrault/boost_1_70_0/boost/asio.hpp`

Am I missing anything? I am really struggling with this issue. 

Thanks

**Comment by jhasse** [comment]
> however I get the following error:

Is this the full output?

(btw: You should install Boost using `sudo apt install libboost-dev`.)

**Comment by nico** [comment]
I don't see `src/daemon.h` in https://github.com/ninja-build/ninja/tree/master/src and I don't see any other boost dependencies in the tree. Ninja tries to have few dependencies and boost would be a very heavy dependency. Are you sure you got your source from here? Or are you trying to build some fork?

**Comment by OliPerraul** [comment]
Yes i am trying to build a fork I must use for a school assignment.

**Comment by jhasse** [comment]
You should ask the authors of the fork then ;)
