### ISSUE TITLE
the compilation database only contains the first file/output

### ISSUE THREAD

**Issue by Leedehai** [ninja-build/ninja#1590]
In the the compilation database JSON dumped by `ninja -t compdb link`, I noticed the "file" field only has the first item instead of all items that serve as the inputs for a command. This is also true for the "output" field.

This seems to be intentional - in [ninja.cc](https://github.com/ninja-build/ninja/blob/master/src/ninja.cc)'s method `NinjaMain::ToolCompilationDatabase`
```c++
        printf("\",\n    \"file\": \"");
        EncodeJSONString((*e)->inputs_[0]->path().c_str()); // only the first item
        printf("\",\n    \"output\": \"");
        EncodeJSONString((*e)->outputs_[0]->path().c_str()); // only the first item
```

But only recording the first item for these two fields in the compilation database defies the purpose of building a compilation database. This weird behavior makes subsequent tooling unreliable.

Thanks!

**Comment by Leedehai** [comment]
Example: linking two object files into one executable - only the first object is listed as the "file" in the JSON.

**Comment by nico** [comment]
The compilation database has a spec at https://clang.llvm.org/docs/JSONCompilationDatabase.html says that both these fields should contain a single element. If you want to put multiple elements there, you have to work with the spec folks upstream.

**Comment by Leedehai** [comment]
ok... the spec folks are probably reluctant to patch the flaw in the fear of breaking other utilities that depend on the current contract. Closing the issue.

**Comment by Leedehai** [comment]
A workaround is using `ninja -t query [target ...]` to get the inputs and outputs for targets listed, and parse the printout.

A drawback of the said workaround is the targets need to be listed explicitly - if the number of targets is huge (e.g. Chromium), it will exceed the limit of the size of a command string (max is 32 pages or 128 KB on Linux: /usr/include/linux/binfmts.h).

One not-so-elegant solution to this drawback is splitting the list up into several pieces and make the call multiple times; another solution is letting `ninja -t query` print all targets' inputs/outputs at once if no target is specified, or introducing a `--all` option (but I guess Ninja maintainers would not accept this proposal...)

**Comment by jhasse** [comment]
> but I guess Ninja maintainers would not accept this proposal

Why not?
