### ISSUE TITLE
Use Python 3 in configure.py

### ISSUE THREAD

**Issue by rossburton** [ninja-build/ninja#1601]
At the time I'm writing this, Python 2 will be end-of-line and thus unsupported in 5 months 19 days and 14 hours time.  I believe that `configure.py` should use `#! /usr/bin/env python3` to prepare for this.

**Comment by jhasse** [comment]
`#!/usr/bin/env python` doesn't necessarily mean Python **2** ;)

**Comment by rossburton** [comment]
Note that whilst the PEP says that, the reality is different: several platforms don't have a `python` binary if you remove Python 2.

**Comment by jhasse** [comment]
Sounds like a bug of those platforms to me.

**Comment by rubyFeedback** [comment]
> Note that whilst the PEP says that, the reality is different: several platforms don't have a python
> binary if you remove Python 2.

Typically how this is solved is to use aliases that point to the binary in place. That is usually what you get when you compile python from source, too, e. g. I have a bin/python3.7m and also the bin/python2.something (forgot which is the latest version but you get the idea).

The proper solution would be to simple use "python" and don't make any further assumptions about which version is the main one. Ninja can not assume to workaround for problems that are created in downstream distributions.

On a side note, the dichotomy in regards to python2 and python3 is quite annoying - although I use ruby most of the time, I use python as well, and I am glad that python2 is really really soon EOLed.
