### ISSUE TITLE
Start Win32 GUI app in ninja without waiting

### ISSUE THREAD

**Issue by huangqinjin** [ninja-build/ninja#1605]
Hi, I am new to ninja. I wrote a simple `build.ninja`:
```
rule gui
    command = cmd /C "start gui.exe"

build default: gui
```
Where `gui.exe` is a dummy Win32 GUI app. When I run `ninja` in CMD, it is blocked until I close the GUI window. In NMAKE, it doesn't get blocked. How can I make ninja act same as NMAKE? Thanks!

**Comment by jhasse** [comment]
Have a look at [start](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/start).

In general, I don't think this is a Ninja issue.

**Comment by huangqinjin** [comment]
After digging into the source code, I found out that ninja is waiting for std handles inherted by the child process `notepad.exe`. There is no way to prevent the stream inheritance. The workaround is using `Start-Process` cmdlet of Powershell. See [https://stackoverflow.com/questions/53231519/freeze-when-programmatically-launching-a-batch-file-with-output-redirection-w](https://stackoverflow.com/questions/53231519/freeze-when-programmatically-launching-a-batch-file-with-output-redirection-w).
