### ISSUE TITLE
AppVeyor continuous integration is failing since PR ninja-build#1016

### ISSUE THREAD

**Issue by jonesmz** [ninja-build/ninja#1611]
Specifically, on the mingw platform on AppVeyor:

subprocess.CalledProcessError: Command 'cmd /c ar cqs build/libninja.a.tmp build/build.o build/build_log.o build/clean.o build/clparser.o build/debug_flags.o build/depfile_parser.o build/deps_log.o build/disk_interface.o build/dyndep.o build/dyndep_parser.o build/edit_distance.o build/eval_env.o build/graph.o build/graphviz.o build/lexer.o build/line_printer.o build/manifest_parser.o build/metrics.o build/parser.o build/state.o build/string_piece_util.o build/util.o build/version.o build/subprocess-win32.o build/includes_normalize-win32.o build/msvc_helper-win32.o build/msvc_helper_main-win32.o build/getopt.o && move /Y build/libninja.a.tmp build/libninja.a' returned non-zero exit status 1.

Looks like maybe a symbol collision of some kind?

Not clear to me why the "ar" program isn't giving any diagnostic output.

**Comment by jhasse** [comment]
```
 sed -i 's|cmd /c $ar cqs $out.tmp $in && move /Y $out.tmp $out|$ar crs $out $in|g' configure.py
```
isn't working.

**Comment by jhasse** [comment]
I'm thinking about merging #1563 and don't bother fixing this, but to use CMake for MinGW instead. Opinions?

**Comment by jonesmz** [comment]
Yes please.

I would prefer CMake over python.

**Comment by jonesmz** [comment]
Especially since CMake also supports advanced features that would be useful with regard to using Ninja as a library, instead of an app, as briefly discussed here: https://github.com/ninja-build/ninja/pull/1614
