### ISSUE TITLE
Towards enabling ninja to be built as a library

### ISSUE THREAD

**Issue by jonesmz** [ninja-build/ninja#1613]
I wish to use ninja's code as a library inside of another application.

I'm well aware that ninja does not attempt to be a library, and am not asking for the Ninja project to support any kind of stable API.

I would like to remove the use of "using namespace std" in headerfiles, however, so that I don't have to deal with namespace pollution issues in my code that uses the ninja code as a library.

If I submit a pull request that does this, will it be accepted (assuming high enough quality) ?

**Comment by jhasse** [comment]
Let's continue the "using namespace std"-discussion in #1614.

And for the library discussion #1499.
