### ISSUE TITLE
test failure: SubprocessTest.InterruptChild on AIX 6.1

### ISSUE THREAD

**Issue by goshhhy** [ninja-build/ninja#1623]
this was found while doing testing for another issue.

on AIX 6.1 in master:

```
bash-4.4$ uname -a
AIX aix 1 6 00F774544C00
bash-4.4$ git clone https://github.com/ninja-build/ninja
Cloning into 'ninja'...
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (8/8), done.
Receiving objectsremote: Total 10348 (delta 2), reused 4 (delta 0), pack-reused 10340
Receiving objects: 100% (10348/10348), 3.67 MiB | 3.36 MiB/s, done.
Resolving deltas: 100% (7357/7357), done.
Checking connectivity... done.
bash-4.4$ cd ninja
bash-4.4$ ls
COPYING       HACKING.md    README        RELEASING     appveyor.yml  bootstrap.py  configure.py  doc           misc          src
bash-4.4$ ./configure.py --bootstrap
bootstrapping ninja...
warning: A compatible version of re2c (>= 0.11.3) was not found; changes to src/*.in.cc will not affect your build.
wrote build.ninja.
bootstrap complete.  rebuilding...
[28/28] LINK ninja
bash-4.4$ ./ninja ninja_test
[19/19] LINK ninja_test
bash-4.4$ ./ninja_test 
[14/332] SubprocessTest.InterruptChild
*** Failure in src/subprocess_test.cc:83
ExitInterrupted == subproc->Finish()
[332/332] BuildLogRecompactTest.Recompact
failed
bash-4.4$ 
```

**Comment by kadler** [comment]
My team ran in to this recently. During some investigation, I discovered that AIX uses a different exit status format than the shell returns.

AFAICT, POSIX shell behavior is to add 128 to the signal that the child ended with and return that. The test calls `kill -INT $$`, which gets passed through  `sh -c`, ie. `sh -c 'kill -INT $$'`. The shell will signal itself and end with exit code 130 (128 + 2 for SIGINT). This value is coincidentally the same format as what Linux, FreeBSD, and likely other POSIX systems use for the `WIFEXITED` and `WIFSIGNALLED` macros, but *not* AIX. On AIX, the bottom 8 bits are 0 if the process exited, while bit 0x40 is set if it is stopped, and it's considered signaled if it neither exited nor is stopped.

I plan to submit a PR to map the exit status to the format expected by the macros when we detect this scenario.
