### ISSUE TITLE
ninja wrongly copies selinux attributes from build-dir to install location on "ninja install"

### ISSUE THREAD

**Issue by jwrdegoede** [ninja-build/ninja#1625]
I hit this when building mutter from source (master branch) on a Fedora Rawhide system.

After running: `sudo ninja install -v -j4 -C x86_64-redhat-linux-gnu`

In my mutter dir then, then I get:

```
[hans@shalem mutter]$ ls -Z /usr/share/locale/nl/LC_MESSAGES/mutter.mo
unconfined_u:object_r:user_home_t:s0 /usr/share/locale/nl/LC_MESSAGES/mutter.mo

```

Which is surprising since normally when copying / installing a file the new copy gets new fresh selinux attributes, e.g.:

```
[hans@shalem mutter]$ sudo install -m644 -p /home/hans/projects/mutter/x86_64-redhat-linux-gnu/po/nl.gmo /usr/share/locale/nl/LC_MESSAGES/mutter.mo
[hans@shalem mutter]$ ls -Z /usr/share/locale/nl/LC_MESSAGES/mutter.mo
system_u:object_r:locale_t:s0 /usr/share/locale/nl/LC_MESSAGES/mutter.mo
```

ninja copying over the existing selinux attributes leads to the installed file having the wrong selinux attributes which results in selinux denials e.g.:

```
type=AVC msg=audit(1565102209.902:113): avc:  denied  { map } for  pid=1751 comm="gnome-shell" path="/usr/share/locale/nl/LC_MESSAGES/gnome-shell.mo" dev="nvme0n1p2" ino=3543080 scontext=system_u:system_r:xdm_t:s0-s0:c0.c1023 tcontext=unconfined_u:object_r:user_home_t:s0 tclass=file permissive=0
type=AVC msg=audit(1565102210.431:115): avc:  denied  { map } for  pid=1751 comm="gnome-shell" path="/usr/share/locale/nl/LC_MESSAGES/mutter.mo" dev="nvme0n1p2" ino=3540175 scontext=system_u:system_r:xdm_t:s0-s0:c0.c1023 tcontext=unconfined_u:object_r:user_home_t:s0 tclass=file permissive=0

```

Please fix ninja to not copy over selinux attributes from the build-dir to the installation target.

**Comment by jhasse** [comment]
I think Ninja doesn't copy the file, but Meson creates an `install` target which does it.

**Comment by jwrdegoede** [comment]
You are right, `ninja install` just calls `meson install --no-rebuild`, sorry for the noise, closing.

I've filed a new issue against meson for this: https://github.com/mesonbuild/meson/issues/5779
