### ISSUE TITLE
Unknown architecture (aarch64) -- unable to run ninja.

### ISSUE THREAD

**Issue by xiaobing395845388** [ninja-build/ninja#1648]
when i clone the code an run  ./configure.py --bootstrap
it reports errors

**Comment by jhasse** [comment]
Can you try again using CMake?

**Comment by xiaobing395845388** [comment]
> Can you try again using CMake?

how to use? can you give me an example,thank y

**Comment by jhasse** [comment]
Please re-open if you can also reproduce using CMake.
