### ISSUE TITLE
pip3 install ninja - ERROR: Failed building wheel for ninja

### ISSUE THREAD

**Issue by TGunthorpe** [ninja-build/ninja#1652]
Pico-imx6
Linux yocto 4.9.88-2.0.0
Python 3.7.4
pip 19.2.3
cmake 3.15.3 - installed manually
re2c 1.2.1
ninja 1.9.0

Commands:
pip3 install –-upgrade pip
pip3 install scikit-build

tar xvf ninja-1.9.0.tar.gz
cd ninja-1.9.0
python3 configure.py

Full log:
root@pico-imx6:~# sudo pip3 install ninja
Collecting ninja
  Using cached https://files.pythonhosted.org/packages/dd/96/e2ec4acccb8dee33b4987f553d531d61e3081c8d4cfbce249655dfe23906/ninja-1.9.0.post1.tar.gz
Building wheels for collected packages: ninja
  Building wheel for ninja (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rhii6e5h/ninja/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rhii6e5h/ninja/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-0q3wo_f_ --python-tag cp37
       cwd: /tmp/pip-install-rhii6e5h/ninja/
  Complete output (173 lines):

  --------------------------------------------------------------------------------
  -- Trying "Ninja" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  Not searching for unused variables given on the command line.
  CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-install-rhii6e5h/ninja/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "Ninja" generator - failure
  --------------------------------------------------------------------------------

  --------------------------------------------------------------------------------
  -- Trying "Unix Makefiles" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  Not searching for unused variables given on the command line.
  -- The C compiler identification is GNU 7.3.0
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- The CXX compiler identification is GNU 7.3.0
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /tmp/pip-install-rhii6e5h/ninja/_cmake_test_compile/build
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "Unix Makefiles" generator - success
  --------------------------------------------------------------------------------

  -- The C compiler identification is GNU 7.3.0
  -- The CXX compiler identification is GNU 7.3.0
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found PythonInterp: /usr/local/bin/python3.7 (found version "3.7.4")
  -- *********************************************
  -- Ninja Python Distribution
  --
  --   BUILD_FROM_SOURCE         : ON
  --   BUILD_VERBOSE             : OFF
  --
  --   ARCHIVE_DOWNLOAD_DIR      : /tmp/pip-install-rhii6e5h/ninja/_skbuild/linux-armv7l-3.7/cmake-build
  --
  --     src_archive             : unix_source
  --     <src_archive>_url       : https://github.com/kitware/ninja/archive/v1.9.0.g5b44b.kitware.dyndep-1.jobserver-1.tar.gz
  --     <src_archive>_sha256    : 449359a402c3adccd37f6fece19ce7d7cda586e837fdf50eb7d53597b7f1ce90
  --
  --     binary_archive          : linux32_binary
  --     <binary_archive>_url    : NA
  --     <binary_archive>_sha256 : NA
  -- *********************************************
  -- download_ninja_source - URL: https://github.com/kitware/ninja/archive/v1.9.0.g5b44b.kitware.dyndep-1.jobserver-1.tar.gz
  -- Configuring done
  -- Generating done
  CMake Warning:
    Manually-specified variables were not used by the project:

      PYTHON_INCLUDE_DIR
      PYTHON_LIBRARY
      SKBUILD

  -- Build files have been written to: /tmp/pip-install-rhii6e5h/ninja/_skbuild/linux-armv7l-3.7/cmake-build
  Scanning dependencies of target download_ninja_source
  [ 10%] Creating directories for 'download_ninja_source'
  [ 20%] Performing download step (download, verify and extract) for 'download_ninja_source'
  -- Downloading...
     dst='/tmp/pip-install-rhii6e5h/ninja/_skbuild/linux-armv7l-3.7/cmake-build/v1.9.0.g5b44b.kitware.dyndep-1.jobserver-1.tar.gz'
     timeout='none'
  -- Using src='https://github.com/kitware/ninja/archive/v1.9.0.g5b44b.kitware.dyndep-1.jobserver-1.tar.gz'
  -- verifying file...
         file='/tmp/pip-install-rhii6e5h/ninja/_skbuild/linux-armv7l-3.7/cmake-build/v1.9.0.g5b44b.kitware.dyndep-1.jobserver-1.tar.gz'
  -- Downloading... done
  -- extracting...
       src='/tmp/pip-install-rhii6e5h/ninja/_skbuild/linux-armv7l-3.7/cmake-build/v1.9.0.g5b44b.kitware.dyndep-1.jobserver-1.tar.gz'
       dst='/tmp/pip-install-rhii6e5h/ninja/src'
  -- extracting... [tar xfz]
  -- extracting... [analysis]
  -- extracting... [rename]
  -- extracting... [clean up]
  -- extracting... done
  [ 30%] No patch step for 'download_ninja_source'
  [ 40%] No update step for 'download_ninja_source'
  [ 50%] No configure step for 'download_ninja_source'
  [ 60%] No build step for 'download_ninja_source'
  [ 70%] No install step for 'download_ninja_source'
  [ 80%] Completed 'download_ninja_source'
  [ 80%] Built target download_ninja_source
  Scanning dependencies of target build_ninja
  [ 90%] Generating ../../../src/ninja
  od: invalid option -- 't'
  BusyBox v1.24.1 (2019-09-19 21:05:02 AEST) multi-call binary.

  Usage: od [-aBbcDdeFfHhIiLlOovXx] [FILE]
  In file included from ./src/browse.cc:23:0:
  ./build/browse_py.h:2:1: error: expected primary-expression before ';' token
   ;
   ^
  bootstrapping ninja...
  when running:  g++ -MMD -MT build/browse.o -MF build/browse.o.d -g -Wall -Wextra -Wno-deprecated -Wno-missing-field-initializers -Wno-unused-parameter -fno-rtti -fno-exceptions -fvisibility=hidden -pipe '-DNINJA_PYTHON="python3.7"' -O2 -DNDEBUG -fdiagnostics-color -DUSE_PPOLL -DNINJA_HAVE_BROWSE -I. -c ./src/browse.cc -o build/browse.o
  Traceback (most recent call last):
    File "configure.py", line 467, in <module>
      objs += cxx('browse', order_only=built('browse_py.h'))
    File "configure.py", line 284, in cxx
      return n.build(built(name + objext), 'cxx', src(name + '.cc'), **kwargs)
    File "configure.py", line 164, in build
      self._run_command(self._expand(cmd, local_vars))
    File "configure.py", line 189, in _run_command
      subprocess.check_call(cmdline, shell=True)
    File "/usr/local/lib/python3.7/subprocess.py", line 347, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'g++ -MMD -MT build/browse.o -MF build/browse.o.d -g -Wall -Wextra -Wno-deprecated -Wno-missing-field-initializers -Wno-unused-parameter -fno-rtti -fno-exceptions -fvisibility=hidden -pipe '-DNINJA_PYTHON="python3.7"' -O2 -DNDEBUG -fdiagnostics-color -DUSE_PPOLL -DNINJA_HAVE_BROWSE -I. -c ./src/browse.cc -o build/browse.o' returned non-zero exit status 1.
  make[2]: *** [CMakeFiles/build_ninja.dir/build.make:61: ../../../src/ninja] Error 1
  make[1]: *** [CMakeFiles/Makefile2:80: CMakeFiles/build_ninja.dir/all] Error 2
  make: *** [Makefile:130: all] Error 2
  Traceback (most recent call last):
    File "/usr/local/lib/python3.7/site-packages/skbuild/setuptools_wrap.py", line 577, in setup
      cmkr.make(make_args, env=env)
    File "/usr/local/lib/python3.7/site-packages/skbuild/cmaker.py", line 482, in make
      os.path.abspath(CMAKE_BUILD_DIR())))

  An error occurred while building with CMake.
    Command:
      "cmake" "--build" "." "--target" "install" "--config" "Release" "--"
    Source directory:
      /tmp/pip-install-rhii6e5h/ninja
    Working directory:
      /tmp/pip-install-rhii6e5h/ninja/_skbuild/linux-armv7l-3.7/cmake-build
  Please see CMake's output for more information.
  ----------------------------------------
  ERROR: Failed building wheel for ninja
  Running setup.py clean for ninja
Failed to build ninja
Installing collected packages: ninja
  Running setup.py install for ninja ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rhii6e5h/ninja/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rhii6e5h/ninja/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-u7rq3_m8/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-install-rhii6e5h/ninja/
    Complete output (173 lines):

    --------------------------------------------------------------------------------
    -- Trying "Ninja" generator
    --------------------------------
    ---------------------------
    ----------------------
    -----------------
    ------------
    -------
    --
    Not searching for unused variables given on the command line.
    CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-install-rhii6e5h/ninja/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
    --
    -------
    ------------
    -----------------
    ----------------------
    ---------------------------
    --------------------------------
    -- Trying "Ninja" generator - failure
    --------------------------------------------------------------------------------

    --------------------------------------------------------------------------------
    -- Trying "Unix Makefiles" generator
    --------------------------------
    ---------------------------
    ----------------------
    -----------------
    ------------
    -------
    --
    Not searching for unused variables given on the command line.
    -- The C compiler identification is GNU 7.3.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- The CXX compiler identification is GNU 7.3.0
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /tmp/pip-install-rhii6e5h/ninja/_cmake_test_compile/build
    --
    -------
    ------------
    -----------------
    ----------------------
    ---------------------------
    --------------------------------
    -- Trying "Unix Makefiles" generator - success
    --------------------------------------------------------------------------------

    -- The C compiler identification is GNU 7.3.0
    -- The CXX compiler identification is GNU 7.3.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Found PythonInterp: /usr/local/bin/python3.7 (found version "3.7.4")
    -- *********************************************
    -- Ninja Python Distribution
    --
    --   BUILD_FROM_SOURCE         : ON
    --   BUILD_VERBOSE             : OFF
    --
    --   ARCHIVE_DOWNLOAD_DIR      : /tmp/pip-install-rhii6e5h/ninja/_skbuild/linux-armv7l-3.7/cmake-build
    --
    --     src_archive             : unix_source
    --     <src_archive>_url       : https://github.com/kitware/ninja/archive/v1.9.0.g5b44b.kitware.dyndep-1.jobserver-1.tar.gz
    --     <src_archive>_sha256    : 449359a402c3adccd37f6fece19ce7d7cda586e837fdf50eb7d53597b7f1ce90
    --
    --     binary_archive          : linux32_binary
    --     <binary_archive>_url    : NA
    --     <binary_archive>_sha256 : NA
    -- *********************************************
    -- download_ninja_source - URL: https://github.com/kitware/ninja/archive/v1.9.0.g5b44b.kitware.dyndep-1.jobserver-1.tar.gz
    -- Configuring done
    -- Generating done
    CMake Warning:
      Manually-specified variables were not used by the project:

        PYTHON_INCLUDE_DIR
        PYTHON_LIBRARY
        SKBUILD

    -- Build files have been written to: /tmp/pip-install-rhii6e5h/ninja/_skbuild/linux-armv7l-3.7/cmake-build
    Scanning dependencies of target download_ninja_source
    [ 10%] Creating directories for 'download_ninja_source'
    [ 20%] Performing download step (download, verify and extract) for 'download_ninja_source'
    -- Downloading...
       dst='/tmp/pip-install-rhii6e5h/ninja/_skbuild/linux-armv7l-3.7/cmake-build/v1.9.0.g5b44b.kitware.dyndep-1.jobserver-1.tar.gz'
       timeout='none'
    -- Using src='https://github.com/kitware/ninja/archive/v1.9.0.g5b44b.kitware.dyndep-1.jobserver-1.tar.gz'
    -- verifying file...
           file='/tmp/pip-install-rhii6e5h/ninja/_skbuild/linux-armv7l-3.7/cmake-build/v1.9.0.g5b44b.kitware.dyndep-1.jobserver-1.tar.gz'
    -- Downloading... done
    -- extracting...
         src='/tmp/pip-install-rhii6e5h/ninja/_skbuild/linux-armv7l-3.7/cmake-build/v1.9.0.g5b44b.kitware.dyndep-1.jobserver-1.tar.gz'
         dst='/tmp/pip-install-rhii6e5h/ninja/src'
    -- extracting... [tar xfz]
    -- extracting... [analysis]
    -- extracting... [rename]
    -- extracting... [clean up]
    -- extracting... done
    [ 30%] No patch step for 'download_ninja_source'
    [ 40%] No update step for 'download_ninja_source'
    [ 50%] No configure step for 'download_ninja_source'
    [ 60%] No build step for 'download_ninja_source'
    [ 70%] No install step for 'download_ninja_source'
    [ 80%] Completed 'download_ninja_source'
    [ 80%] Built target download_ninja_source
    Scanning dependencies of target build_ninja
    [ 90%] Generating ../../../src/ninja
    od: invalid option -- 't'
    BusyBox v1.24.1 (2019-09-19 21:05:02 AEST) multi-call binary.

    Usage: od [-aBbcDdeFfHhIiLlOovXx] [FILE]
    In file included from ./src/browse.cc:23:0:
    ./build/browse_py.h:2:1: error: expected primary-expression before ';' token
     ;
     ^
    bootstrapping ninja...
    when running:  g++ -MMD -MT build/browse.o -MF build/browse.o.d -g -Wall -Wextra -Wno-deprecated -Wno-missing-field-initializers -Wno-unused-parameter -fno-rtti -fno-exceptions -fvisibility=hidden -pipe '-DNINJA_PYTHON="python3.7"' -O2 -DNDEBUG -fdiagnostics-color -DUSE_PPOLL -DNINJA_HAVE_BROWSE -I. -c ./src/browse.cc -o build/browse.o
    Traceback (most recent call last):
      File "configure.py", line 467, in <module>
        objs += cxx('browse', order_only=built('browse_py.h'))
      File "configure.py", line 284, in cxx
        return n.build(built(name + objext), 'cxx', src(name + '.cc'), **kwargs)
      File "configure.py", line 164, in build
        self._run_command(self._expand(cmd, local_vars))
      File "configure.py", line 189, in _run_command
        subprocess.check_call(cmdline, shell=True)
      File "/usr/local/lib/python3.7/subprocess.py", line 347, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command 'g++ -MMD -MT build/browse.o -MF build/browse.o.d -g -Wall -Wextra -Wno-deprecated -Wno-missing-field-initializers -Wno-unused-parameter -fno-rtti -fno-exceptions -fvisibility=hidden -pipe '-DNINJA_PYTHON="python3.7"' -O2 -DNDEBUG -fdiagnostics-color -DUSE_PPOLL -DNINJA_HAVE_BROWSE -I. -c ./src/browse.cc -o build/browse.o' returned non-zero exit status 1.
    make[2]: *** [CMakeFiles/build_ninja.dir/build.make:61: ../../../src/ninja] Error 1
    make[1]: *** [CMakeFiles/Makefile2:80: CMakeFiles/build_ninja.dir/all] Error 2
    make: *** [Makefile:130: all] Error 2
    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/site-packages/skbuild/setuptools_wrap.py", line 577, in setup
        cmkr.make(make_args, env=env)
      File "/usr/local/lib/python3.7/site-packages/skbuild/cmaker.py", line 482, in make
        os.path.abspath(CMAKE_BUILD_DIR())))

    An error occurred while building with CMake.
      Command:
        "cmake" "--build" "." "--target" "install" "--config" "Release" "--"
      Source directory:
        /tmp/pip-install-rhii6e5h/ninja
      Working directory:
        /tmp/pip-install-rhii6e5h/ninja/_skbuild/linux-armv7l-3.7/cmake-build
    Please see CMake's output for more information.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rhii6e5h/ninja/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rhii6e5h/ninja/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-u7rq3_m8/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

**Comment by jhasse** [comment]
The ninja pip package is actually not by us, please file an issue here: https://github.com/scikit-build/ninja-python-distributions

**Comment by wschin** [comment]
Try pip=19.0. This seems solving a similar problem on my side.

**Comment by WireBot34** [comment]
[This helped me in termux](https://github.com/termux/termux-packages/issues/8951#issuecomment-1207196457)

**Comment by jzohrab** [comment]
Old issue, apologies for posting, but it still shows up on google.

In case future **Mac** users come here: a pip install was failing with `ERROR: Failed building wheel for ninja`: I resolved this with `brew install cmake` before re-running the pip install.

**Comment by iamshahboz** [comment]
In my case, the Reason was a C++ compiler installed on my PC.
And by default, it creates a Python development environment. And no matter which package you try to install you get error message
Can't build a wheel for ninja 

Here is the link to the solution https://stackoverflow.com/a/79205727/15401874
