### ISSUE TITLE
Configure.py fails

### ISSUE THREAD

**Issue by AMDphreak** [ninja-build/ninja#1653]
I have no idea what is going on here.
```
configure.py
```
```
Traceback (most recent call last):
  File "configure.py", line 324, in <module>
    if platform.msvc_needs_fs():
  File "configure.py", line 87, in msvc_needs_fs
    stderr=subprocess.PIPE)
  File "C:\Users\rjamd\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\rjamd\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by jhasse** [comment]
Are you running from Visual Studio's command prompt?

**Comment by AMDphreak** [comment]
> 
> 
> Are you running from Visual Studio's command prompt?

Are you talking about the ones that prep the environment variables? No. I'm trying to use Clang Cmake and ninja. I don't understand the relationship between Visual Studio's build tools and the Clang/LLD/Cmake/Ninja workflow.

**Comment by jhasse** [comment]
If you want to use CMake to build Ninja, there's no need to call configure.py :)

**Comment by AMDphreak** [comment]
Instructions for using a compiler with the MS Visual C++ build tool-set:
- Follow instructions for deciding what programming/build environment to use:
   - [Microsoft Docs](https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=vs-2019#developer_command_prompt_shortcuts)
- Run the programming environment:
   1. Click Start
   2. Search and Run one of the following programming/build environments:
      - x86_x64 Cross Tools Command Prompt for VS 2019
      - x86 Native Tools Command Prompt for VS 2019
      - x64_x86 Cross Tools Command Prompt for VS 2019
      - x64 Native Tools Command Prompt for VS 2019
      - Developer Command Prompt for VS 2019
