### ISSUE TITLE
doc/manual.asciidoc : move some bullet points out of the comparison with make

### ISSUE THREAD

**Issue by johan-boule** [ninja-build/ninja#1655]
doc/manual.asciidoc:

The following bullet points in "Comparison to make" are deceptive because make handles this in a perfectly elegant way. It's good that ninja have them too, but please mention them in a separate section.

* "Ninja has special support for discovering extra dependencies at build time".
   => Make rebuilds the `include`d makefiles, which is as powerful has ninja's `deps` and `dyndep` combined.
* "Builds are always run in parallel"
   => Make has it just as an extra command line option `-j$(nproc)`. That's not worth mentioning as an "extra feature".
* "Command output is always buffered"
   => Make has it as the `-O` option. Same remark as previous point.
* "Rules can provide shorter descriptions of the command being run"
   => Make offers you to hide commands with the `-` prefix.

Please, for honesty, move those points to another section.

About that point:
*  "Output directories are always implicitly created"
   => First, make handles it by putting the directory as an order-only prerequisite, and a second rule to create that directory. I do recognise that it's nicer that ninja don't even bother the user with this, but on the other hand it does not match with ninja's design goals that were explained a few lines above.

**Comment by jhasse** [comment]
> "Ninja has special support for discovering extra dependencies at build time".
=> Make rebuilds the included makefiles, which is as powerful has ninja's deps and dyndep combined.

"These sorts of features can often be implemented using more complicated Makefiles, but they are not part of make itself."

> "Builds are always run in parallel"
=> Make has it just as an extra command line option -j$(nproc). That's not worth mentioning as an "extra feature".

That won't work on Windows (no `nproc`) or Bash-incompatible shells (e.g. fish). Of course that can be worked around, maybe we should change the wording to "Builds are run in parallel by default"?

(also not quite the same as Ninja's behavior as builds are *always* run in parallel, even if there's only one CPU, i.e. `nproc == 1`)

> Command output is always buffered
=> Make has it as the -O option. Same remark as previous point.

Correct me if I'm wrong: That was added in GNU Make 4.0, the bullet points were probably written before that. Also not everyone is using *GNU* Make.

> Rules can provide shorter descriptions of the command being run
=> Make offers you to hide commands with the - prefix.

And show a short description instead?

**Comment by jhasse** [comment]
Feel free to re-open if you want to discuss this further.

**Comment by johan-boule** [comment]
I don't have enough energy and will for a lost croisade. I'm interested in implementing C++20 module support and unfortunately, both make or ninja are now unfit for the task, hence why it's become a moot point to compare them.

**Comment by jhasse** [comment]
Ninja just gained support in #1521. Do you think it's still unfit even after this PR?

**Comment by johan-boule** [comment]
There are diverging opinion on the sustainability of depending on a general purpose tool like make or ninja for handling the complexity of C++ modules as they've been specified. My own opinion is that it's now become a more sane approach to embed the actual task executor into the high-level layer that does the actual dependency analysis. I'm aware that someome is developing the equivalent of the fscan tool for clang, which then would need to be combined with extended pkg-config, or new file format handling for modulemap files, or other vague compile_command.json files. While I believe it could be made to work with GNU make, my experience with such an attempt leads me to seek for a more integrated/unified approach, to get rid of the complicated tool interactions. Ninja's dyndep, as I mentioned, is a nice implementation/equivalent of GNU make's auto-remaking of included makefile, and in the end does not cover more use cases. There's actually even more complexity to handle when you want to use GCC because they chose a different approach than clang's dependency scanner. With GCC, the dependencies are discovered through a dialogue between the compiler and the build system: there's a bidirectional communication protocol, and the build system needs to launch dependent tasks to fulfill what the compiler asks for, and answer once the dependent task has completed, the whole thing being recursive. While it sounds crazy and it probably is, that GCC implementation is usable today, while clang's dependency scanner is still nonfunctional, and the accompanying fileformats are not ready withers. So, if one wants to use C++ modules without waiting for a couple more years at least, there's no choice but to abandon the traditional approach of gluing separate tools together.

**Comment by jonesmz** [comment]
Please format your comment

**Comment by johan-boule** [comment]
(a few formatting introduced in previous comment)

I understand my comments do sound mean towards ninja, but I think it's important to realise that the C++ modules do impact build system quite a lot than you'd expect, and that ninja plays in the *exact* same ball park as GNU make in terms of features supported.

Much more effort is currently spent in build systems with dedicated support of C++ than in general-purpose tools, which makes sense to me in the end.

This is why I originally mentioned in this ticket that a comparison between ninja and other tools shall emphasis what features ninja has that other tools don't. So far, the major differentiating factor I've found between Ninja and GNU make is that the latter is a programmable language and in that way covers more ground than Ninja as a stand-alone tool. That's something I would certainly mention if I were to write unbiased comparisons.

I also understand your point of view that it doesn't make any sense, in a competitive world, to introduce your own tool in a critical way. Such impartial judgment is to be written elsewhere.
