### ISSUE TITLE
Update 'ninja_syntax' on pypi

### ISSUE THREAD

**Issue by futile** [ninja-build/ninja#1658]
The ['ninja_syntax' package on pypi](https://pypi.org/project/ninja_syntax/) is useful as it bundles _only_ ninja_syntax.py, and not the rest of ninja. Also, it brings ninja's license file with it, which can be important (#1005).

However, the version in the pypi repository has last been updated Jan 24, 2017, and since then a few small changes have been made (e.g., 85fab32362e2afe3c58dde00ca36676c9e29a9a6).

Although these changes aren't major, it would be nice if the version on pypi could be updated! Thanks a lot! :)

**Comment by jhasse** [comment]
We aren't the maintainers of the pypi package, not sure where you need to ask, sorry.
