### ISSUE TITLE
Please create a "PRs welcome" label for the github issues list.

### ISSUE THREAD

**Issue by jonesmz** [ninja-build/ninja#1676]

**Comment by jhasse** [comment]
I'm skeptical. Where do you think this would help?

**Comment by jonesmz** [comment]
You closed the issue that demonstrated where this would be useful (https://github.com/ninja-build/ninja/issues/1677)

An assert is better than nothing, but I'd still rather have the appropriate typesafe template function to do the conversion.

The reason for creating the label in github is to mark an issue, which either describes a problem, or suggests a feature, as something that the project maintainers don't want to do, but would actually consider a PR to implement the described changes.

**Comment by jhasse** [comment]
> The reason for creating the label in github is to mark an issue, which either describes a problem, or suggests a feature, as something that the project maintainers don't want to do, but would actually consider a PR to implement the described changes.

I usually just comment in that case.

**Comment by jonesmz** [comment]
A label would allow someone who's interested in contributing to find an appropriate "First task" without having to read all 200 open issues, and 50 open PRs.

**Comment by jhasse** [comment]
Good point. Do you know examples from other GitHub projects what the exact name (and color) of the label should be?

**Comment by nightlark** [comment]
The default labels created on new GitHub repositories are:
`good first issue` - Good for newcomers (color #7057ff)
`help wanted` - Extra attention is needed (color #008672)

Some labels that other projects use include `up-for-grabs`, `first-timers-only` (https://www.firsttimersonly.com/, https://github.com/mungell/awesome-for-beginners), and `jump-in`.

**Comment by jhasse** [comment]
I've created the "help wanted" label :)
