### ISSUE TITLE
ninja cannot be built with uClibc++

### ISSUE THREAD

**Issue by neheb** [ninja-build/ninja#1684]
In src/hash_map.h , there is this lovely gnu libc++ specific header that gets included

```
#include <ext/hash_map>
```

unfortunately, uClibc++ does not include this. I don't know of a way to get around this.

**Comment by jhasse** [comment]
Would #1696 help?

**Comment by neheb** [comment]
Doesn’t look like it. In any case, uClibc++ is quite old in addition to being somewhat abandoned. I don’t think there’s much of a benefit in adding support. Closing.

**Comment by jonesmz** [comment]
Note: uClib++ is one of the build options for OpenWRT. 

Not saying ninja need support that. Just pointing out that its a consideration.

**Comment by neheb** [comment]
That’s only applicable if installing ninja on the device itself.

**Comment by jonesmz** [comment]
Well... Some people do.

OpenWRT can do more than just run a router :)

**Comment by neheb** [comment]
I'm well aware.

In any case, ninja uses hash maps, which uClibc++ does not support in any way.

I personally want to remove it from the OpenWrt tree and replace it with libcxx.

**Comment by jonesmz** [comment]
By all means, I would be happy to see that happen.
