### ISSUE TITLE
GitHub Actions: Statically link Visual C++ runtime

### ISSUE THREAD

**Issue by jhasse** [ninja-build/ninja#1692]
This will result in a bigger binary but no dependency on the VCRuntime installer.

**Comment by nightlark** [comment]
Is pulling in a copy of the [ucm cmake macros](https://github.com/onqtam/ucm) something you're okay with, or would you prefer the flags get added to targets manually?

**Comment by jhasse** [comment]
Haven't heard of ucm yet, sounds good :)

**Comment by jhasse** [comment]
How do you want to pull it in though? `ExternalProject` would be preffered (no extra code, still works without Git).

**Comment by nightlark** [comment]
My initial thought was stick a copy of ucm.cmake in a cmake modules folder (`set (CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${PROJECT_SOURCE_DIR}/cmake/")` and then include it with `include(ucm)`. But if `ExternalProject` is preferred, I think that could also work.

**Comment by jhasse** [comment]
On second thought ... might just be simpler to copy the flags from https://github.com/onqtam/ucm#macro-ucm_set_runtimestatic-dynamic

Or just from our own configure.py.

**Comment by jhasse** [comment]
I've tried:

```cmake
set(CMAKE_CXX_FLAGS_RELEASE "/MT /O2 /Ob2 /DNDEBUG")
```

But this results in

```
LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:library 
```

when linking. Any ideas?

**Comment by jonesmz** [comment]
Isn't /MT for linking against the multithreaded library? I thought Ninja was single threaded.

**Comment by nightlark** [comment]
/MT makes it use the static version of the run time library; the [MSVC compiler options reference](https://docs.microsoft.com/en-us/cpp/build/reference/md-mt-ld-use-run-time-library?view=vs-2019) lists the available options (static/dynamic and debug/nodebug).

The warning probably means something is still getting linked with the dynamic runtime. I'll see if I can find some time tonight to look at what's going on with static linking with MSVC.

**Comment by nightlark** [comment]
Well I added the same set command, and didn't see any linker warnings about MSVCRT -- maybe it's a difference in where the flags were set. I'll cleanup and push a copy of what I have.
