### ISSUE TITLE
Invalid volume label syntax with MinGW GCC 10

### ISSUE THREAD

**Issue by expnkx** [ninja-build/ninja#1693]
![image](https://user-images.githubusercontent.com/57303909/69611973-dfd9f580-0ffc-11ea-814f-b709f394166e.png)

**Comment by jhasse** [comment]
Can you try with #1671?

**Comment by jhasse** [comment]
Wait, no the problem seems to be `d/:`. No idea where that invalid volume label syntax comes from.

**Comment by expnkx** [comment]
> Wait, no the problem seems to be `d/:`. No idea where that invalid volume label syntax comes from.

How to try #1671?
"Wait, no the problem seems to be d/:. No idea where that invalid volume label syntax comes from."
I do not know. I will upload my MinGW GCC and you can test it. It is so sad ninja is the only tool which can be used on windows for GCC, however, it breaks as well :(

**Comment by jhasse** [comment]
Where did you download MinGW?

I'm using [MSYS2](http://www.msys2.org/) which works with mingw-w64 and Ninja.

**Comment by expnkx** [comment]
> Where did you download MinGW?
> 
> I'm using [MSYS2](http://www.msys2.org/) which works with mingw-w64 and Ninja.

No. Your version is too old. Mine is GCC 10.0
https://bitbucket.org/ejsvifq_mabmip/mingw-gcc-mcfgthread-pacman/src/master/

**Comment by expnkx** [comment]
![image](https://user-images.githubusercontent.com/57303909/69612705-427fc100-0ffe-11ea-8269-879e12ef48bb.png)

**Comment by jhasse** [comment]
So it works with 9 but stops working with 10?

**Comment by expnkx** [comment]
> So it works with 9 but stops working with 10?

Yes

**Comment by expnkx** [comment]
I will upload a full version so you can test it. Just use cmake + ninja to build ninja and you will see the problem.

**Comment by jhasse** [comment]
btw: You can try PRs by downloading the artifact. For #1671 that would be: https://github.com/ninja-build/ninja/runs/320687337

**Comment by expnkx** [comment]
> btw: You can try PRs by downloading the artifact. For #1671 that would be: https://github.com/ninja-build/ninja/runs/320687337

No use

**Comment by expnkx** [comment]
I have uploaded the latest version. You can unzip and try it.

https://bitbucket.org/ejsvifq_mabmip/mingw-gcc/src/master/

**Comment by expnkx** [comment]
@jhasse @evmar Can you fix the problem??

**Comment by jhasse** [comment]
No, sorry, I'm not a Windows expert (also I won't download binaries I don't trust, sorry).

Please don't ping people unless it makes sense or is urgent.

**Comment by jhasse** [comment]
It probably has something to do with the header dependency format by GCC, since the first build works. Could be a GCC bug, too. If you want to investigate Git-bisecting between 9 and 10 might point out what has changed there.

**Comment by expnkx** [comment]
> It probably has something to do with the header dependency format by GCC, since the first build works. Could be a GCC bug, too. If you want to investigate Git-bisecting between 9 and 10 might point out what has changed there.

Doubtful since cmake + make or mingw32-make still work.

**Comment by jhasse** [comment]
Maybe Make has a workaround for the wrong syntax.

**Comment by expnkx** [comment]
> Maybe Make has a workaround for the wrong syntax.

Is it easy for creating a workaround for this? I checked that .ninja_deps. All path was written wrongly into this file. More like a serialization bug.
D/:/hg

**Comment by jhasse** [comment]
I would prefer to find out why they are written like this.

**Comment by zero9178** [comment]
Did some investigation and this is indeed a bug in GCC. GCC-10 Inserts a \ before colons since this commit: https://github.com/gcc-mirror/gcc/commit/d7b6aee8cd346328b6f22fc415ffc28b9cf8a285. So either this needs to be fixed in GCC (most likely?) or the grammar needs to be updated to support this
