### ISSUE TITLE
[QUESTION] How to specifiy CUDA version using Ninja on Windows

### ISSUE THREAD

**Issue by RadMap** [ninja-build/ninja#1694]
I want to configure the CUDA version that is used when I build a program on Windows using Ninja as Generator. From [this](https://gitlab.kitware.com/cmake/cmake/issues/19173) post it seems like it should be possible to point Ninja to the desired CUDA version by setting the CUDACXX environmental variable. But this does not work for me. Ninja always picks up the CUDA version first in my PATH or alternatively it uses CUDA_PATH env on windows. Not sure of  which.

How can I configure the CUDA version used by Ninja?

**Comment by jhasse** [comment]
I'm pretty sure this is a CMake issue.

Also the issue tracker is not the place to ask questions.

https://stackoverflow.com/questions/59101668/how-to-specifiy-cuda-version-using-ninja-generator-on-windows
