### ISSUE TITLE
ninja: error: loading 'build.ninja': Le fichier spÚcifiÚ est introuvable.

### ISSUE THREAD

**Issue by JacqueSatan** [ninja-build/ninja#1715]
I installed ninja with chocolately, but it does the same with the binaries in release. This is the only thing I get when running ninja, with or without args.

```
>ninja -v
ninja: error: loading 'build.ninja': Le fichier spÚcifiÚ est introuvable.
```

**Comment by jhasse** [comment]
Ninja builds the project in the cwd, you'll need to cd into a directory where it makes sense to run ninja.
