### ISSUE TITLE
Pull GN in to the ninja-build project

### ISSUE THREAD

**Issue by JakeSays** [ninja-build/ninja#1739]
Not sure if this is the right place, but would it be possible to pull GN into the ninja-build project? It would be a lot more convenient than having to pull and build from the chromium repo. It would also make it easier for distros to include GN along with ninja.

**Comment by jonesmz** [comment]
What is GN and why would it make ninja build better at what it does?

Ninja is used by way more projects than Chromium.

**Comment by JakeSays** [comment]
@jonesmz GN is short for Generate Ninja, and as I understand it it's the original ninja file generator, but I'm not 100% sure on that. It's a very powerful and lightweight build system that fits in well with the lightweightness of ninja. It's the build tool for chromium, fuchsia, flutter, and other google projects, but I also use it in all of my work.

Just thought it would be a nice companion to ninja. The repo is here: [GN](https://gn.googlesource.com/gn/)

Anyway, just a thought.

**Comment by jhasse** [comment]
My guess would be that Google wants to keep its mission-critical projects on googlesource.com and avoid GitHub when possible.

I think the right place to ask for this would be https://groups.google.com/a/chromium.org/forum/#!forum/chromium-dev

**Comment by JakeSays** [comment]
@jhasse No problem. Thanks!
