### ISSUE TITLE
ninja: error:  unknown target 'all'

### ISSUE THREAD

**Issue by iFuSiiOnzZ** [ninja-build/ninja#1747]
Platform: Windows 10 x64
CMake: 3.16.2

Full error:
```
ninja: error: build.ninja:36715: unknown target 'all'
default all
           ^ near here
```
---
I found a problem related to the solution generation for ninja using CMake. In case you open a virtual drive pointing a specific folder CMake generates the solution without any problem but ninja can not build the solution (error on the title). Taking a look at the `ninja.build` file, for any `space` or `:` there is `$` sign.

An example of the `ninja.build`
```
#############################################
# A missing CMake input file is not an error.
-
build C$:/Program$ Files/CMake/share/cmake-3.16/Modules/CMakeCInformation.cmake C$:/Program$ Files/CMake/share/cmake-3.16/Modules/CMakeCXXInformation.cmake ...
```
---
How i found it (inside a batch file):
```
    mkdir %LOCAL_PATH%\..\..\build\cmake\%BUILD_TYPE%\%BUILD_PLATFORM%\QNX
    subst W: %LOCAL_PATH%\..\..\build\cmake\%BUILD_TYPE%\%BUILD_PLATFORM%\QNX

    set toochain=%LOCAL_PATH%/../../env/Common/cmake_toolchain/intel.cmake
    if %BUILD_PLATFORM% equ armv7le set toochain=%LOCAL_PATH%/../../env/Common/cmake_toolchain/armv7le.cmake

    pushd W:
        cmake -Wno-dev -G "Ninja" -DCMAKE_BUILD_TYPE=!BUILD_TYPE! -DOPTIMIZATION_CCACHE_ENABLED=OFF -DCMAKE_TOOLCHAIN_FILE=!toochain! !LOCAL_PATH!/../../
        if !errorlevel! neq 0 (
            popd
            subst /D W:
            goto error_cmake_project_generation
        )

        ninja
        if !errorlevel! neq 0 (
            popd
            subst /D W:
            goto error_build
        )
    popd
    subst /D W:
```
---
PS1: I tried to generate the solution for "Unix Makefiles" and executed `make` without any problem.
PS2: it seem that if I try to build the project at the root of any drive is not working

**Comment by mathstuf** [comment]
This sounds more like a CMake bug than a ninja bug. Could you please post on [CMake's issue tracker](https://gitlab.kitware.com/cmake/cmake/issues).

Cc: @bradking 

@jhasse I think this can be closed here.

**Comment by iFuSiiOnzZ** [comment]
Thank you! Posted on the CMake issue tracker
https://gitlab.kitware.com/cmake/cmake/issues/20404
