### ISSUE TITLE
 Ninja uses on PowerPC Mac OS X 10.4.11, Tiger, "-rpath" as loader switch although not supported

### ISSUE THREAD

**Issue by ballapete** [ninja-build/ninja#1749]
When I build on PowerPC Mac OS X 10.4.11, Tiger, at-spi2-core 2.34.0 with Ninja 1.10.0 every build fails:

:info:build /opt/local/bin/gcc-apple-4.2 -o registryd/at-spi2-registryd 'registryd/ef35e93@@at-spi2-registryd@exe/de-marshaller.c.o' 'registryd/ef35e93@@at-spi2-registryd@exe/registry-main.c.o' 'registryd/ef35e93@@at-spi2-registryd@exe/registry.c.o' 'registryd/ef35e93@@at-spi2-registryd@exe/introspection.c.o' 'registryd/ef35e93@@at-spi2-registryd@exe/deviceeventcontroller.c.o' 'registryd/ef35e93@@at-spi2-registryd@exe/reentrant-list.c.o' 'registryd/ef35e93@@at-spi2-registryd@exe/deviceeventcontroller-x11.c.o' 'registryd/ef35e93@@at-spi2-registryd@exe/display.c.o' 'registryd/ef35e93@@at-spi2-registryd@exe/event-source.c.o' 'registryd/ef35e93@@at-spi2-registryd@exe/ucs2keysym.c.o' -L/opt/local/lib -Wl,-dead_strip_dylibs -Wl,-undefined,error -Wl,-headerpad_max_install_names -pipe -Os -arch ppc -Wl,-headerpad_max_install_names -arch ppc atspi/libatspi.0.dylib -Wl,-framework -Wl,CoreFoundation -L/opt/local/lib -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lintl -L/opt/local/lib -ldbus-1 -Wl,-framework -Wl,CoreFoundation -L/opt/local/lib -lgobject-2.0 -lglib-2.0 -lintl -L/opt/local/lib -lX11 -L/opt/local/lib -lXtst -L/opt/local/lib -lXi -Wl,-headerpad_max_install_names -Wl,-rpath,@loader_path/../atspi
:info:build ld: -rpath can only be used when targeting Mac OS X 10.5 or later

Obviously the Ninja sources are faulty.

--

Greetings

   Pete

**Comment by annulen** [comment]
If I understand correclty, you are building `at-spi2-core` which shoud have recently switched from autotools to Meson build system using Ninja as backend. Ninja is low-level build system similar to make, it does not alter compiler or linker flags but instead exact run commands it was told to run. So, obviously it's not Ninja's fault. Please report issue to `at-spi2-core` instead.

But don't hold your breath, pre-rpath ways of OS X linking were even more obscure and it's unlikely anyone is going to support anything but rpath these days.
