### ISSUE TITLE
Missing release 1.10 on pypi

### ISSUE THREAD

**Issue by priv-kweihmann** [ninja-build/ninja#1754]
According to https://pypi.org/project/ninja/#history 1.9.0post1 (whatever that version might be) is the latest available version - are there any plans to dump a package to pypi soon?

**Comment by scivision** [comment]
that might be a question for scikit-build?

**Comment by jhasse** [comment]
The ninja pip package is actually not by us, please file an issue here: https://github.com/scikit-build/ninja-python-distributions
