### ISSUE TITLE
Does ninja support remote execution?

### ISSUE THREAD

**Issue by modoojunko** [ninja-build/ninja#1755]
hi,

I noticed that One PPT called "Remote Execution and Caching for Android Platform" . Inside it has one page , it shows that ninja cloud call re.warper to execute clang/java on remote server.

I want to know the details :D thanks. I was tried so many days to build AOSP in remote way, but failed.

**Comment by danw** [comment]
`rewrapper` is a compiler wrapper, and doesn't directly integrate with ninja -- the android-building google group may be a better place to ask about it.

You should be able to find the executables and build integration on AOSP, but it's only been tested with RBE, so if you don't have access to RBE, it may not be immediately useful. It is enabled on many of the builds exposed on ci.android.com, but in a remote-cache mode instead remote-execution at the moment.

**Comment by modoojunko** [comment]
@danw 
Thanks for your message. That's useful. 

I do not have RBE. So I need to ask quetion about Remote Cache. How does ninja work with that?

I can image this:

programmer A: ninja build some thing in AOSP and ninja send the final out files and intermediates files to Remote Cache
programmer B: ninja build some thing in AOSP version B, ninja found exist files in Remote Cacche so  it skips compile and copy that file to local to finish it.

I want to know the detail :) in code level how does this work?

**Comment by jhasse** [comment]
> the android-building google group may be a better place to ask about it.
