### ISSUE TITLE
Aseprite installation Error: Loading 'build.ninja': No such file or directory

### ISSUE THREAD

**Issue by FadedTubeSock** [ninja-build/ninja#1758]
Hello all! I know there were previous posts with the same issue, but the answers didn't seem to resolve them. Here are my steps: 
1) I installed ninja through 'brew install ninja'
2) I followed the steps to run CMake and compile files
3) The final step was to build Aseprite through the command 'ninja aseprite'. Here is where the below error message occurs. Have I done a mistake during installation? 

Please respond ASAP as I need to create a sprite for my upcoming game release. Thanks for the help!
<img width="511" alt="Screen Shot 2020-03-29 at 8 27 02 PM" src="https://user-images.githubusercontent.com/61721397/77865521-bd4f2780-71fc-11ea-94dc-13251995c0b4.png">

**Comment by jhasse** [comment]
This is not a support forum, sorry.

**Comment by FadedTubeSock** [comment]
I'm sorry, I should know this, but which is the support forum?

**Comment by jhasse** [comment]
https://groups.google.com/forum/#!forum/ninja-build

**Comment by nomi9995** [comment]
same issue
