### ISSUE TITLE
Any way to ask ninja to prioritise a file in compile order?

### ISSUE THREAD

**Issue by asmaloney** [ninja-build/ninja#1761]
(Asked the same question over at [cmake](https://discourse.cmake.org/t/any-way-to-tell-cmake-to-prioritise-a-file-in-compile-order/1005/3), and it was suggested I look to ninja.)

I was pointed at an [old (open) issue](https://github.com/ninja-build/ninja/issues/232). I'm not sure if it applies directly to what I'm asking or if anything was implemented.

I have a large project with many, many files.

One file takes a very long time to compile - about 2.5 minutes. I don’t have control over that file because it’s a third party dependency.

The build (across cores) looks like this:

<img width="1135" alt="CC Build 20200404" src="https://user-images.githubusercontent.com/391371/79144771-85fc8100-7d8d-11ea-92c0-68499ce556b5.png">

With fewer cores, it’s possible this file starts late in the compile which extends the compile time a lot.

Is there a nice way to ask ninja to compile this file as early as possible?

**Comment by jhasse** [comment]
I guess your build.ninja is generated by CMake?

Unfortunately there's no way without touching the build manifest. -> #232.

**Comment by asmaloney** [comment]
Yes it is generated by cmake.

So I would need something like #1333 to land here, and then for cmake to take advantage of that when generating the build.ninja file?

Just trying to understand the scope of the problem.

Thank you!

**Comment by jhasse** [comment]
You wouldn't need to wait for CMake, as you can specify the target order when calling ninja (if #1333 was merged). If I understand the PR correctly it would also notice the long compile time and build the target first on subsequent builds.

**Comment by asmaloney** [comment]
Wow - that sounds like it would be an amazing addition to ninja.

Thanks Jan!
