### ISSUE TITLE
Wiki: note that older ninja cannot output colors

### ISSUE THREAD

**Issue by wataash** [ninja-build/ninja#1778]
I noticed that gcc can't output colors even with `-fdiagnostics-color=always` when using ninja 1.8.2 (on Ubuntu 19.04), but can on ninja 1.10.0.git.

So I want to update the [wiki](https://github.com/ninja-build/ninja/wiki/FAQ) adding a note such like:

> If you're using version ?.?.? or later, you can force color on by ...

I want to know the exact version `?.?.?`, so does anyone know the exact commit or pull request at which ninja stopped stripping ANSI escapes?

**Comment by jhasse** [comment]
Are you talking about Windows? If so, that would be 1.9.0, see #1451.

**Comment by wataash** [comment]
Thank you for let me know that, but I'm using Linux (Ununtu 19.04).

**Comment by wataash** [comment]
Oh, I just realized that this problem occurs only when `ninja -v`...
(I'll paste screenshots)

**Comment by jhasse** [comment]
Ah, that was #1214 - also fixed in 1.9.0.
