### ISSUE TITLE
Add explicit inline copyright and licence statements to ninja_syntax.py

### ISSUE THREAD

**Issue by vuzdemav** [ninja-build/ninja#1781]
In the documentation at https://ninja-build.org/manual.html#_generating_ninja_files_from_code
> Feel free to just inline [misc/ninja_syntax.py] into your project’s build system if it’s useful.

It would be helpful if the misc/ninja_syntax.py included copyright and licence statements, so that this information is preserved when inlining into another project.

**Comment by vuzdemav** [comment]
I noticed in `CONTRIBUTING.md`:
> All source files should have the Google Inc. license header.

**Comment by vuzdemav** [comment]
Ideally this could also include an SPDX License Identifier comment https://spdx.dev/ids/

**Comment by jhasse** [comment]
So basically d890582883ebec99346aae6dba3f3af52e543fa9 for ninja_syntax.py. @evmar would you be okay with that?

**Comment by evmar** [comment]
It would have been nice in retrospect to make this file 0bsd but I guess it's Apache2, yeah.
