### ISSUE TITLE
mingw gcc. No sys/select.h on windows.

### ISSUE THREAD

**Issue by expnkx** [ninja-build/ninja#1782]
[40/57] Building CXX object CMakeFiles/libninja.dir/src/subprocess-posix.cc.obj
FAILED: CMakeFiles/libninja.dir/src/subprocess-posix.cc.obj
/mingw64/bin/c++.exe  -D_WIN32_WINNT=0x0601 -D__USE_MINGW_ANSI_STDIO=1  -Wno-deprecated -fdiagnostics-color -O3 -DNDEBUG -flto -fno-fat-lto-objects -MD -MT CMakeFiles/libninja.dir/src/subprocess-posix.cc.obj -MF CMakeFiles/libninja.dir/src/subprocess-posix.cc.obj.d -o CMakeFiles/libninja.dir/src/subprocess-posix.cc.obj -c ../src/subprocess-posix.cc
../src/subprocess-posix.cc:17:10: fatal error: sys/select.h: No such file or directory
   17 | #include <sys/select.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
[49/57] Building CXX object CMakeFiles/libninja.dir/src/util.cc.obj
ninja: build stopped: subcommand failed.

**Comment by expnkx** [comment]
failed to build ninja on windows

**Comment by jhasse** [comment]
subprocess-posix.cc shouldn't be compiled on Windows, see this snippet from CMakeLists.txt:

```cmake
if(WIN32)
	target_sources(libninja PRIVATE
		src/subprocess-win32.cc
		src/includes_normalize-win32.cc
		src/msvc_helper-win32.cc
		src/msvc_helper_main-win32.cc
		src/getopt.c
	)
	if(MSVC)
		target_sources(libninja PRIVATE src/minidump-win32.cc)
	endif()
else()
	target_sources(libninja PRIVATE src/subprocess-posix.cc)
endif()
```

What CMake version are you using? Is `WIN32` set?

**Comment by expnkx** [comment]
> subprocess-posix.cc shouldn't be compiled on Windows, see this snippet from CMakeLists.txt:
> 
> ```cmake
> if(WIN32)
> 	target_sources(libninja PRIVATE
> 		src/subprocess-win32.cc
> 		src/includes_normalize-win32.cc
> 		src/msvc_helper-win32.cc
> 		src/msvc_helper_main-win32.cc
> 		src/getopt.c
> 	)
> 	if(MSVC)
> 		target_sources(libninja PRIVATE src/minidump-win32.cc)
> 	endif()
> else()
> 	target_sources(libninja PRIVATE src/subprocess-posix.cc)
> endif()
> ```
> 
> What CMake version are you using? Is `WIN32` set?

MSYS2 MinGW-w64 make

cmake --version
cmake version 3.17.0

CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by jhasse** [comment]
Can you update to CMake 3.17.2 and try again?

**Comment by expnkx** [comment]
> Can you update to CMake 3.17.2 and try again?

Try again and failed again.

I just comment out the entire POSIX section in the cmakelists and it works.

**Comment by jhasse** [comment]
Looks like a CMake bug then. WIN32 should be set on Windows. Do you have problems building other CMake projects or just Ninja?

**Comment by expnkx** [comment]
> Looks like a CMake bug then. WIN32 should be set on Windows. Do you have problems building other CMake projects or just Ninja?

Well, not yet. Maybe those projects were written not just target win32.

**Comment by jhasse** [comment]
> Maybe those projects were written not just target win32.

What do you mean?

**Comment by expnkx** [comment]
> > Maybe those projects were written not just target win32.
> 
> What do you mean?

They just provide a general cmake and probably not trigger if(_WIN32) in cmake whatever.

**Comment by jhasse** [comment]
It's fairly easy to find a project which has Windows specific stuff in their CMakeLists.txt, most bigger projects do.

If you find one and it works there but doesn't for ninja, maybe we're doing something wrong in our CMakeLists.txt. Feel free to reopen with more info in that case.
