### ISSUE TITLE
80 column character limit

### ISSUE THREAD

**Issue by jonesmz** [ninja-build/ninja#1795]
Linux kernel deprecated the 80 column character limit rule.

Can Ninja do the same?

https://www.phoronix.com/scan.php?page=news_item&px=Linux-Kernel-Deprecates-80-Col

**Comment by jhasse** [comment]
While the old Coding Guidelines explicitly mentioned the 80-column limit, it's not a Ninja-rule, but part of the Google C++ Coding Style: https://google.github.io/styleguide/cppguide.html#Line_Length

I want to keep the additions where we deviate from the Google C++ Coding Style as short as possible.

**Comment by jonesmz** [comment]
The rule has been stupid since the mid 90s.

Why do you want to avoid deviating from the google coding style?

**Comment by jhasse** [comment]
Talk to Google then.

Because it's easier to point to it than to bike-shed over stuff like this.

**Comment by jonesmz** [comment]
I don't work for google, and neither do you (since the last time you talked about it, anyway).

*sigh* fine. Its a stupid rule and it makes the code harder to read, but whatever. Not the end of the world.
