### ISSUE TITLE
Windows: Ninja starts a dependent command before the dependency has finished.

### ISSUE THREAD

**Issue by alexreinking** [ninja-build/ninja#1802]
I'm running Ninja 1.10.0 through CMake and started getting an intermittent error that is very hard to debug. There appears to be a race condition between link.exe flushing its output to disk / releasing the file `wavelet.generator.exe` and the dependent commands launching and trying to run. 

```
D:\Halide-build\apps\app_test_wavelet>ninja clean && ninja
[1/1] Cleaning all built files...
Cleaning... 20 files.
[1/16] Building CXX object CMakeFiles\wavelet.generator.dir\D_\Halide-build\apps\_Halide_install\share\tools\GenGen.cpp.obj
Microsoft (R) C/C++ Optimizing Compiler Version 19.26.28806 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

[2/16] Building CXX object CMakeFiles\wavelet.generator.dir\inverse_haar_x_generator.cpp.obj
Microsoft (R) C/C++ Optimizing Compiler Version 19.26.28806 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

[3/16] Building CXX object CMakeFiles\wavelet.generator.dir\haar_x_generator.cpp.obj
Microsoft (R) C/C++ Optimizing Compiler Version 19.26.28806 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

[4/16] Building CXX object CMakeFiles\wavelet.generator.dir\inverse_daubechies_x_generator.cpp.obj
Microsoft (R) C/C++ Optimizing Compiler Version 19.26.28806 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

[5/16] Building CXX object CMakeFiles\wavelet.generator.dir\daubechies_x_generator.cpp.obj
Microsoft (R) C/C++ Optimizing Compiler Version 19.26.28806 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

[6/16] Linking CXX executable wavelet.generator.exe
Microsoft (R) Incremental Linker Version 14.26.28806.0
Copyright (C) Microsoft Corporation.  All rights reserved.

[7/16] Generating inverse_daubechies_x.runtime.lib
FAILED: inverse_daubechies_x.runtime.lib
cmd.exe /C "cd /D D:\Halide-build\apps\app_test_wavelet && "C:\Program Files\CMake\bin\cmake.exe" -E env "PATH=D:\Halide-build\apps\_Halide_install\bin\Release;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\\Extensions\Microsoft\IntelliCode\CLI;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\bin\HostX86\x86;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools;C:\Program Files (x86)\HTML Help Workshop;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\FSharp;C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x86;C:\Program Files (x86)\Windows Kits\10\bin\x86;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\\MSBuild\Current\Bin;C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\libnvvp;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\NVIDIA Corporation\Nsight Compute 2019.5.0;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2020.1.216\windows\mpi\intel64\bin;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64_win\mpirt;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\ia32_win\mpirt;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64_win\compiler;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\ia32_win\compiler;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files\Microsoft MPI\Bin;C:\Program Files\PuTTY;C:\Program Files\dotnet;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\MATLAB\R2018a\runtime\win64;C:\Program Files\MATLAB\R2018a\bin;C:\Program Files\CMake\bin;C:\ProgramData\chocolatey\bin;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\Git\cmd;C:\Users\Alex Reinking\AppData\Roaming\local\bin;C:\Users\Alex Reinking\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\FAHClient;C:\Program Files\Git\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VC\Linux\bin\ConnectionManagerExe" D:/Halide-build/apps/app_test_wavelet/wavelet.generator.exe -r inverse_daubechies_x.runtime -o . target=host"
This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher
[14/16] Generating haar_x.runtime.lib
ninja: build stopped: subcommand failed.
```

If I have ninja run an incremental build after getting this error, it completes without issue. I have tried reproducing this error with [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) running, but whatever it's doing to trace disrupts the race condition and it won't fail. Because I'm in a 32-bit cross-compiling scenario, I see errors in the Event Viewer that read like so:

```
The program or feature "\??\D:\Halide-build\apps\app_test_wavelet\wavelet.generator.exe" cannot start or run due to incompatibity with 64-bit versions of Windows. Please contact the software vendor to ask if a 64-bit Windows compatible version is available.
```

See [wavelet.dot.txt](https://github.com/ninja-build/ninja/files/4794625/wavelet.dot.txt) for the output of `ninja -t graph`. The dependency is clearly visible there.

**Comment by jhasse** [comment]
Do you have any Anti-Virus running?

**Comment by alexreinking** [comment]
Oh my gosh, @jhasse -- I was sure I had added my build directory to the Windows Defender exclusions, but upon double checking it appears I had not. Thank you for double checking me so effectively on that. I ran the build in a loop for ~20min locally and the issue hasn't resurfaced. I'll make sure the same is true on CI and then close the issue, if that's okay with you.

---

Relatedly, is there some way Ninja could diagnose this sort of failure as it exits to produce a more helpful error message? I'm still not even sure where that particular error message comes from.

**Comment by alexreinking** [comment]
Okay, we're pretty confident the cause of this was Windows Defender. OTOH, should Ninja not be able to work when Windows Defender is enabled?

**Comment by jhasse** [comment]
While the linker command has finished, the exe file still hasn't been completely written to disk (or flushed?) because it's checked by Anti-Virus (I think only executables are given this treatment). So there isn't anything Ninja can do about it and this shows you what a big mess Windows is.

Someone correct me if I'm wrong, I'm not a Windows expert and this is just based on my experience with Anti-Virus on Windows over the years.

**Comment by brlcad** [comment]
There are lots of conditions that can result in the file not being instantaneously written to disk including distributed fabric filesystems (common in HPC environments), network filesystems, and various kernel-injecting modules like anti-virus, deduplication block stores, and virtual filesystems.  

We've recently encountered this issue in Github runners where a large C file is compiled and ninja attempts to link the executable before the object file is written, resulting in an error.  Ninja could inject a 'sync' before linking to avoid this issue.  On fast local systems, this will be pretty much instantaneous. On slow/busy/interrupted file systems, sync will not return until all pending writes are physically complete.

**Comment by jhasse** [comment]
> in Github runners

OS?

> Ninja could inject a 'sync' before linking to avoid this issue.

Doesn't sound like Ninja's job to do this. You can already insert a sync step before linking.

**Comment by brlcad** [comment]
The most recent Github runner failure appears to be a virtualized Windows environment, but I have seen this issue on other platforms, on NFS filesystems, HPC systems, and even with modern distributed filesystems common to virtualized server environments (which the runner is almost certainly using).  The flawed assumption is typically that a file's data will be available when an executable exits, but that is only true for POSIX or if an application manually calls fsync(2), sync(2), or similar -- if the environment supports such a concept.  There are plenty of non-POSIX environments. 

Our ninja build comes from cmake, so no means to insert a sync step before linking.  Workaround is to single thread execution and unfortunately not use the ninja generator.  It's perhaps the larger overhead of make, but it seems to avoid the race condition.  Ninja's apparently just too fast. ;)

**Comment by jhasse** [comment]
> The flawed assumption is typically that a file's data will be available when an executable exits [...]

I don't agree that this assumption is flawed. If you can't assume that, all bets are off and you can't do any parallel work without calling (f)sync all over the place.

fsync flushes the cache to the physical disk, but *the cache* should be available instantly and different processes shouldn't have to race for it - especially not if the file has been (f)closed!

**Comment by brlcad** [comment]
> I don't agree that this assumption is flawed. If you can't assume that, all bets are off and you can't do any parallel work without calling (f)sync all over the place.

Yep, that's exactly right (though there are other synchronization mechanisms).  You are undoubtedly accustomed to working primarily on systems that strive for or _are_ POSIX compliant.  Some systems (e.g., NFS) can be configured both ways. Compliance has become so pervasive on desktops and Linux that it's all some people know, so I can understand your perspective.  You'd possibly dismiss non-compliant systems as broken.

That's certainly your prerogative.  I'm just trying to share some awareness that these environments have existed since at least the 80's, used to be handled by apps that wanted to support non-POSIX environments (as that didn't become a thing until the late 90's), are still common in many server filesystem environments today, and predominantly present as failures in robustness particularly affecting parallel I/O access.  You certainly have no reason to take my word on this, so I'd only refer you to Samba or NFS devs; and there's undoubtedly a stackoverflow on this. 

> fsync flushes the cache to the physical disk, but _the cache_ should be available instantly and different processes shouldn't have to race for it - especially not if the file has been (f)closed!

That's a very nice durability guarantee to have.  That's why POSIX imposes it as a requirement.

**Comment by jhasse** [comment]
I see, thanks for the explanation.

Back to the original suggestion:

> Ninja could inject a 'sync' before linking to avoid this issue.

Ninja doesn't what is a link step and what isn't. Theoretically Ninja could mark all output files as "potentially out of sync" and then 'sync' when one of those gets used by another step.
