### ISSUE TITLE
Windows 32 bit build

### ISSUE THREAD

**Issue by drkousek** [ninja-build/ninja#1808]
Hello.

I have problems to build Ninja on win 32 bit. 
If I try to use Python configure.py, it throws error.
If I try to build ninja by cmake and use MinGW, I get error again.
First is Python, second is MinGW.
https://imgur.com/a/AZHwWzw

Should you help me, how can I build ninja for 32 bit?
Appreciate it a lot and thank you for any help

**Comment by jhasse** [comment]
You should use mingw-w64 (don't worry about the w64, there's a 32 bit version, too) version of MinGW. You can get it via MSYS2 for example.

**Comment by kambala-decapitator** [comment]
@drkousek FYI I was able to compile 32bit version with msvc 2019 and python 3.10 under win 8.1 32bit
