### ISSUE TITLE
ninja deletes file for which the rule was removed

### ISSUE THREAD

**Issue by FnGyula** [ninja-build/ninja#1811]
Hi,

Recently I was trying to build [OpenEXR](https://github.com/AcademySoftwareFoundation/openexr) version 2.3.0 with the latest stable ninja 1.10.0 and also later tried with the version 6c5e886 with the same results.

Basically the CMake script of OpenEXR creates a rule-chain for producing look-up header files only if the file doesn't exist already. Which means, that the second time the configuration runs, it will remove these rules. When the rules removed, ninja 1.10.0 deletes the file, leading to compilation failure. Third time around, CMake doesn't find the header files, so decides to create the rule for them, so ninja correctly generates the files and all is good. Simply saying, it's a merry-go-around where every second build fails due to this issue.

I tested this behaviour with 1.9.0 and it doesn't happen.

The related log seems to be:

```
ninja explain: output OpenEXR/IlmImf/b44ExpLogTable.h of phony edge with no inputs doesn't exist
ninja explain: OpenEXR/IlmImf/b44ExpLogTable.h is dirty
ninja explain: OpenEXR/IlmImf/CMakeFiles/IlmImf.dir/ImfB44Compressor.cpp.o is dirty
ninja explain: output OpenEXR/IlmImf/dwaLookups.h of phony edge with no inputs doesn't exist
ninja explain: OpenEXR/IlmImf/dwaLookups.h is dirty
```

The same explain logs don't appear at all in 1.9.0

**Comment by jhasse** [comment]
So the CMake script of OpenEXR checks the state of the build directory? Sounds like a big no-no to me (i.e. something OpenEXR should fix).

Btw: CMake calls the `cleandead` tool introduced in Ninja 1.10 during configuration.

**Comment by FnGyula** [comment]
It is fixed in later versions, or at least the whole lookup generation changed. So, if I extract it correctly, it's CMake that introduced this behaviour by calling the cleandead stuff. Fair enough, I guess I have to patch the CMakeLists.txt then.

**Comment by jhasse** [comment]
Later versions of OpenEXR?
