### ISSUE TITLE
Issue using the pip version on Apple Silicon

### ISSUE THREAD

**Issue by rknall** [ninja-build/ninja#1814]
Currently pip only provides a x86_64 binary on Apple Silicon, leading to a version of ninja on the system which can fail to build correct targets (see https://gitlab.kitware.com/cmake/cmake/-/issues/20966 for reference).

The pip should provide an universal binary instead, or a platform specific one. Initial tests show, this would resolve the issue.

**Comment by jhasse** [comment]
This is something that comes often: We don't maintain ninja on pip, it's an unofficial fork. See https://github.com/scikit-build/ninja-python-distributions

You can build Ninja from source on the DTK or install it via Homebrew (that should compile it from source too, haven't tried it yet though).

**Comment by rknall** [comment]
Thanks, I filed an issue there (https://github.com/scikit-build/ninja-python-distributions/issues/35)

**Comment by rknall** [comment]
One more thing, compiling from source and installing from Homebrew both work great
