### ISSUE TITLE
Release notes of v1.10.1 require Google login

### ISSUE THREAD

**Issue by vog** [ninja-build/ninja#1830]
The release site

* https://github.com/ninja-build/ninja/releases/tag/v1.10.1

links to the release notes at:

* https://groups.google.com/g/ninja-build/c/QQM54eAhrjU/m/q5zn_zTlAQAJ

However, this link is only accessible with a Google login.

Proposed solution: Use a different, public link to the same article, such as:

* https://groups.google.com/d/msg/ninja-build/QQM54eAhrjU/q5zn_zTlAQAJ

**Comment by jhasse** [comment]
Done, thanks :)
