### ISSUE TITLE
Windows defender flags ninja.exe

### ISSUE THREAD

**Issue by CraftSpider** [ninja-build/ninja#1832]
I just got this error today for v1.10.1 with a code of "Trojan:Win32/Emali.A!cl", marked sever. Windows Defender automatically deletes the file, requiring manual intervention to restore it. I see there was a previous issue like this in #1540

**Comment by jhasse** [comment]
See https://groups.google.com/g/ninja-build/c/BcLa42ahfnU/m/DzB9LVliCAAJ

**Comment by gobater** [comment]
Symantec Endpoint Protection does not like the file either...

![image](https://user-images.githubusercontent.com/23657567/92372697-9d9e2280-f0fd-11ea-9ffc-568fa009b434.png)

**Comment by jhasse** [comment]
Please reopen if it still happens with 1.10.2.
