### ISSUE TITLE
Incorrect python path used on case-sensitive MacOS systems

### ISSUE THREAD

**Issue by alastair-harrison-oxb** [ninja-build/ninja#1835]
I originally raised this as an issue against the homebrew ninja formula:
https://github.com/Homebrew/homebrew-core/issues/60265

They think it's a problem with ninja, and have asked me to raise an issue here.

# What happened
I tried to use the `ninja -t browse` tool on a MacOS machine with a **case-sensitive** file system.

Repro steps:
```
touch CMakeLists.txt
cmake -GNinja .

ninja -t browse
```

The `ninja -t browse` command failed with an execvp error:
```
$ ninja -t browse
ninja: execvp: Not a directory
```

# Why it happened
Running `ninja -t browse` requires ninja to invoke python. The path to the python executable is baked-in to ninja at compile-time via a compile definition called NINJA_PYTHON:
https://github.com/ninja-build/ninja/blob/a63fb13322aac3ca56e008757eb0514d96549ab5/src/browse.cc#L50

NINJA_PYTHON is configured as part of the ninja bootstrap script:
https://github.com/ninja-build/ninja/blob/a63fb13322aac3ca56e008757eb0514d96549ab5/configure.py#L323

It comes from the --with-python option to configure.py, which has its default set here:
https://github.com/ninja-build/ninja/blob/a63fb13322aac3ca56e008757eb0514d96549ab5/configure.py#L217

So if you don't override the default, then NINJA_PYTHON gets set to the result of the expression:

```
os.path.basename(sys.executable))
```

On my system, `sys.executable` evaluates to:

```
/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
```

Once you pass it through `os.path.basename` you're left with just `'Python'`.

On a case-**insensitive** MacOS system, trying to invoke a binary called `Python` results in `/usr/bin/python` being used (which is a sym-link to the system python command above).

On a case-**sensitive** MacOS system, no command called `Python` can be found in the path. That's the reason for the `execvp` failure.

# Suggested fix

If the python path is going to be baked in to the executable then perhaps it should just default to `python`, all in lower-case. Users with more complicated situations can use the `--with-python` configure option.

Alternatively perhaps some way to alter to path at run-time would be useful. Either an environment variable or a ninja config file. Though I understand that ninja doesn't currently use those approaches for anything else (except `NINJA_STATUS`).

**Comment by jhasse** [comment]
Maybe this can be fixed by CMake or rather let's use the simple `python` approach when compiling Ninja with CMake. See #1822

**Comment by alastair-harrison-oxb** [comment]
OK, I've taken a look and I think I'm happy to attempt this. Can you just say a little more about what you mean by the 'simple `python` approach'?

I think you're suggesting that the CMake script needs to support the inlining of `browse.py`, and that `NINJA_PYTHON` should simply be set to `python`, rather than trying to do any system introspection? Presumably it would be worth providing a CMake cache variable to support setting `NINJA_PYTHON` to something else.

**Comment by jhasse** [comment]
> I think you're suggesting that the CMake script needs to support the inlining of browse.py, and that NINJA_PYTHON should simply be set to "python", rather than trying to do any system introspection?

Yes.

> Presumably it would be worth providing a CMake cache variable to support setting NINJA_PYTHON to something else.

IMHO that's not worth it. If someone really wants to do that (Do packagers need this?) he can modify the CMakeLists.txt. Or symlink `python`. KISS ;)

**Comment by aharrison24** [comment]
I've opened https://github.com/ninja-build/ninja/pull/1836 
For some reason GitHub wouldn't let me link multiple issues from the PR, so it's not been referenced automatically here.

**Comment by jhasse** [comment]
I think you need to remove "ninja-build/ninja" from the second issue reference.

**Comment by alastair-harrison-oxb** [comment]
Ah, I see. I got the digits in the issue number transposed! Will close this now that #1836 is merged.
