### ISSUE TITLE
Permission denied from pip-installed ninja

### ISSUE THREAD

**Issue by ndronen** [ninja-build/ninja#1837]
I've installed ninja into a virtual environment 10.0 via pip on MacOS and Linux. In both cases, the ninja executable isn't actually executable. I have to chmod 755 it manually before I can use it.

**Comment by jhasse** [comment]
The ninja pip package is actually not by us, please file an issue here: https://github.com/scikit-build/ninja-python-distributions

**Comment by ndronen** [comment]
👍
