### ISSUE TITLE
Strange (counter-intuitive) behavior on generator=1

### ISSUE THREAD

**Issue by vog** [ninja-build/ninja#1840]
The `generator` flag does not quite what one would expected it to do.

Consider the following parts of Ninja's own `build.ninja`:

```ninja
# Regenerate build files if build script changes.
rule configure
  command = ${configure_env}python $root/configure.py $configure_args
  generator = 1
build build.ninja: configure | $root/configure.py $root/misc/ninja_syntax.py
```

Also, let's repeat the relevant part of the manual:

> Files built using generator rules are treated specially in two ways: firstly, they will not be rebuilt if the command line changes; and secondly, they are not cleaned by default.

There are two counter-intuitive things here:

1. Why is build.ninja only regenerated when the script changes, and not when the command line changes? I can't think of any use for this special rule, but I do see the danger that this may bite some people because nobody will expect this.
2. The regenerated build.ninja is not reloaded. This means that despite build.ninja being regenerated, the rest of the build continues with the old version of build.ninja. That is, after changing the generator script, ninja needs to be run twice instead of once (and must be allowed to fail in between) to produce the correct result.

I propose two fixes here:

1. Rebuild rules with generator=1 also when the command line changes. That is, treat it like any other build rule in this regard.
2. After triggering a rule with generator=1, the current build is finished prematurely, and Ninja restarts completely, including loading the new build.ninja.

By the way, since Ninja already knows which build.ninja it is executed on, couldn't it automatically recognize any rebuild of that file, making the explicit generator=1 flag obsolete?

**Comment by jhasse** [comment]
1. Because when the script writes a new command line for this rule, that would cause it to be called again after the first re-generation.
2. It *does* get reloaded. Why do you think it wouldn't?

> By the way, since Ninja already knows which build.ninja it is executed on, couldn't it automatically recognize any rebuild of that file, making the explicit generator=1 flag obsolete?

Ninja already treats nodes with `build.ninja` as their output in a special way: It runs them first and reloads `build.ninja` if it has changed. The generator flag is for those other two things you mentioned.

**Comment by jhasse** [comment]
Please re-open if there are open questions left.
