### ISSUE TITLE
I designed a logo for Ninja

### ISSUE THREAD

**Issue by Alhadis** [ninja-build/ninja#1847]
[It's yours if you want it.](https://github.com/file-icons/icons/blob/76bd3c4f8b5be540b47771b0d53e6a435425c4c2/svg/GN.svg)

<img src="https://raw.githubusercontent.com/file-icons/icons/master/svg/GN.svg" alt="Logo" />

The weapon on the left is a sai, a traditional sparring weapon (ninja's weapon + build tool = **ninja build**).

**Comment by jhasse** [comment]
Thx, looks good :)
Ninja is a CLI tool though, I don't think there's a need for a logo in general.

**Comment by Alhadis** [comment]
> Ninja is a CLI tool though, I don't think there's a need for a logo

That logic makes absolutely no sense, but okay. 👍

**Comment by jonesmz** [comment]
While I don't personally think that this is the right logo for the project, I also agree that the reasoning makes no sense.

**Comment by Alex313031** [comment]
@Alhadis I'm using this in my Chromium fork, Thorium > https://github.com/Alex313031/Thorium/

**Comment by Alhadis** [comment]
@Alex313031 Thanks!

I think I made a mistake by posting this design as a silhouette (as it was intended for an icon-font). I should've kicked 3DS Max open and rendered [something over-the-top](https://raw.githubusercontent.com/Alhadis/language-maxscript/master/preview.png), but eh, too late for first impressions I guess. 🤷‍♂️

**Comment by mattgodbolt** [comment]
A logo's useful to use in presentations etc :) all the other build systems in a presentation I'm working on have some kind of logo, so @Alhadis I'll use yours but note it's very unofficial

**Comment by Alex313031** [comment]
@Alhadis @mattgodbolt So Chromium uses GN and Ninja as the build system, I have forked it and made my own "generic" extensible build configuration here that I use to build alot of my personal C++ projects > https://github.com/Alex313031/gn-build

I want to put both the GN and Ninja logo on it, but Ninja still doesn't have an official one, so just like I used it in Thorium like 2 years ago, I want to ask permission to use it again in this new repo.

If you're cool with it, did you ever make a better/modified version like you mentioned above?

**Comment by Alhadis** [comment]
> I want to put both the GN and Ninja logo on it, […] I want to ask permission to use it again in this new repo.

Go nuts with it, mate. 👍
