### ISSUE TITLE
Ninja ver 1.9.0 win10 -f filepath access denied

### ISSUE THREAD

**Issue by EkremYigit** [ninja-build/ninja#1851]
I want to setup ninja into my win10 pc. I follow these steps to setup.
1 - > Set the ninja.exe to environment path
2 - > Run cmd as administrator and paste this C:\Users\Ekrem\Desktop\ninja.exe -f C:\Users\Ekrem\Desktop\NinjaFolder
3 - > After file security configuration  I set free the all access permissions to everyone, either ninja.exe and ninjafolder.
But I still taking access denied error and I couldn't setup. Any Idea or helps ?.. Thanks alot

**Comment by jhasse** [comment]
Please use the latest version. Try running ninja with a debugger attached to see which call gets denied.
