### ISSUE TITLE
Ninja doesn't remove any generated precompiled header

### ISSUE THREAD

**Issue by suratovvlad** [ninja-build/ninja#1857]
Microsoft likes to update their compilers every two-three weeks. 
After the compiler update precompiled headers should be regenerated somehow.

Ninja, when it tries to build any target, tells me, that I need to rebuild precompiled headers.

> ..\..\..\baselibs\src\core\sql\statementhints.cpp: fatal error C1853: 'C:/viadat/projects/develop_cmake/out/build/x64-Release/baselibs/src/core/pch/CMakeFiles/vs_core_pch.dir/./cmake_pch.cxx.pch' precompiled header file is from a different version of the compiler, or the precompiled header is C++ and you are using it from C (or vice versa)

The problem is that in the project we have several precompiled headers for different libraries.
And cleaning with `ninja -t clean all` doesn't remove any of such header.
![image](https://user-images.githubusercontent.com/3812290/95332551-433ae200-08b4-11eb-8c82-23b5fbfaecc3.png)

It would be great if this command would clean precompiled headers as well.
Otherwise, is there any ninja option that forces rebuild of precompiling headers without cleaning all the stuff (because some targets could not use precompiled headers)? As I can see force rebuild is not an option for the ninja for some reasons #317

**Comment by jhasse** [comment]
Can you share a minimal reproducible example build.ninja file?

**Comment by suratovvlad** [comment]
This is simple example project

[CMakeProject2.zip](https://github.com/ninja-build/ninja/files/5364796/CMakeProject2.zip)

Steps to reproduce:

1. Run Visual studio dev prompt
2. Create build folder
3. Run cmake -G Ninja -B/path/to/build/folder -S/path/to/source/folder
4. In build folder run ninja
5. In build folder run ninja -t clean all
6. Generated precompiled header is not removed 

This is the generated build.ninja file

[build.ninja.zip](https://github.com/ninja-build/ninja/files/5364824/build.ninja.zip)

**Comment by suratovvlad** [comment]
Generated PDB files are not removed as well

**Comment by jhasse** [comment]
CMake needs to fix this: https://gitlab.kitware.com/cmake/cmake/-/issues/18284
