### ISSUE TITLE
Extract all sources dependencies

### ISSUE THREAD

**Issue by robin-thoni** [ninja-build/ninja#1858]
I need to extract all (direct+transitive) source (`.c`/`.cpp`/`.h`/...) dependencies for each binary we produce. My final goal is to get something like:
```
{
  "myapp": [
    "/path/to/src/main.cpp",
    "/path/to/src/MyClass.cpp",
    "/path/to/src/MyClass.h",
    "/usr/include/stdc-predef.h",
    "/usr/include/c++/7/iostream",
    ...
  ],
  "mylib.so": [
    "/path/to/src/MyLib.cpp",
    "/path/to/src/MyLib.h",
    "/usr/include/pthread.h",
    ...
  ],
  ...
}
```

Technically speaking, that can be generated by merging data from `ninja -t graph` and `ninja -t deps`: the `deps` tool will get all transitive dependencies for the object files, and `graph` will get all object files for every binary.

My problem is we have ~100 K targets, which gives a 27 MB graph file which takes ~20 minutes just to load in Python, not even mentioning the time to browse it.

The `targets` tool might also help, but with that many targets, it generated 300 GB and filled my disk.

Is there any (built-in) way to get these informations?
If not, would you accept a PR (a new tool) giving an easier access to it?

Thank you

**Comment by jhasse** [comment]
Is #1711 what you're looking for?

**Comment by user202729** [comment]
If someone come across this issue, the solution now is `ninja -t inputs <TargetName>`, implemented in https://github.com/ninja-build/ninja/pull/1730 . [Documentation](https://ninja-build.org/manual.html#_extra_tools). There's also `ninja -t deps <TargetName>` (cf. https://github.com/ninja-build/ninja/issues/2710#issuecomment-3778318666)
