### ISSUE TITLE
clash with byte on windows

### ISSUE THREAD

**Issue by expnkx** [ninja-build/ninja#1859]
D:/msys64/mingw64/include/c++/11.0.0/bits/cpp_type_traits.h:404:30: note: candidates are: 'enum class std::byte'
  404 |   enum class byte : unsigned char;
      |                              ^~~~
In file included from D:/msys64/mingw64/x86_64-w64-mingw32/include/wtypes.h:8,
                 from D:/msys64/mingw64/x86_64-w64-mingw32/include/winscard.h:10,
                 from D:/msys64/mingw64/x86_64-w64-mingw32/include/windows.h:97,
                 from D:/msys64/home/unlvs/ninja/src/util.cc:21:
D:/msys64/mingw64/x86_64-w64-mingw32/include/rpcndr.h:63:25: note:                 'typedef unsigned char byte'
   63 |   typedef unsigned char byte;
      |                         ^~~~
In file included from D:/msys64/mingw64/x86_64-w64-mingw32/include/msxml.h:25,
                 from D:/msys64/mingw64/x86_64-w64-mingw32/include/urlmon.h:450,
                 from D:/msys64/mingw64/x86_64-w64-mingw32/include/objbase.h:163,
                 from D:/msys64/mingw64/x86_64-w64-mingw32/include/ole2.h:17,
                 from D:/msys64/mingw64/x86_64-w64-mingw32/include/wtypes.h:13,
                 from D:/msys64/mingw64/x86_64-w64-mingw32/include/winscard.h:10,
                 from D:/msys64/mingw64/x86_64-w64-mingw32/include/windows.h:97,
                 from D:/msys64/home/unlvs/ninja/src/util.cc:21:
D:/msys64/mingw64/x86_64-w64-mingw32/include/oaidl.h:579:5: error: reference to 'byte' is ambiguous
  579 |     byte *pRecord;
      |     ^~~~
![image](https://user-images.githubusercontent.com/57303909/95647650-24e50a00-0a9f-11eb-933f-4b3365a82555.png)
https://stackoverflow.com/questions/45957830/gdipluspath-throws-ambiguous-byte-for-cstddef-and-rpcndr-h

**Comment by expnkx** [comment]
在 2020/10/10 下午2:25, sotrdg sotrdg 写道:
> D:/msys64/mingw64/x86_64-w64-mingw32/include/rpcndr.h:63:25: note:                 'typedef unsigned char byte'
>    63 |   typedef unsigned char byte;
>       |                         ^~~~
>

It's like that you have `using namespace std` somewhere in your code. Please try removing it.


-- 
Best regards,
LH_Mouse

**Comment by jhasse** [comment]
This is an ongoing effort, see #1614 for example.
