### ISSUE TITLE
Need more information output when running ninja install

### ISSUE THREAD

**Issue by JohnBurrell** [ninja-build/ninja#1860]
If you run ninja install as a non-root user, the directory permissions may not allow installation of the files. You get a message like this:

[0/1] Installing files.
Installing libxkbcommon.so.0.0.0 to /usr/lib
Installing libxkbcommon-x11.so.0.0.0 to /usr/lib
Installing libxkbregistry.so.0.0.0 to /usr/lib
Installing xkbcli to /usr/bin
Installation failed due to insufficient permissions.

This is confusing because the installation of xkbcli to /usr/bin was successful. It's the next attempt that failed. But it doesn't tell you what it was trying to install and to where. Please add this information so it's clear what went wrong.

Thanks

jb.

**Comment by jhasse** [comment]
This output doesn't come from Ninja but your generator (I guess Meson in your case?). Please file a bug there.
