### ISSUE TITLE
Failed building wheel for ninja(PEP517)

### ISSUE THREAD

**Issue by igormen2001** [ninja-build/ninja#1869]
I can't install Ninja on  kali linux

Collecting blosc
Using cached blosc-1.9.2.tar.gz (816 kB)
Installing build dependencies ... error
ERROR: Command errored out with exit status 1:
command: /usr/local/bin/python3 /usr/local/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-roj37yx0/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel scikit-build cmake ninja
cwd: None
Complete output (48 lines):
Collecting setuptools
Using cached setuptools-50.3.2-py3-none-any.whl (785 kB)
Collecting wheel
Using cached wheel-0.35.1-py2.py3-none-any.whl (33 kB)
Collecting scikit-build
Using cached scikit_build-0.11.1-py2.py3-none-any.whl (72 kB)
Collecting cmake
Using cached cmake-3.18.2.post1-py3-none-manylinux2014_aarch64.whl (15.2 MB)
Collecting ninja
Using cached ninja-1.10.0.post2.tar.gz (25 kB)
Installing build dependencies: started
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'done'
Preparing wheel metadata: started
Preparing wheel metadata: finished with status 'done'
Collecting packaging
Using cached packaging-20.4-py2.py3-none-any.whl (37 kB)
Collecting distro
Using cached distro-1.5.0-py2.py3-none-any.whl (18 kB)
Collecting six
Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting pyparsing>=2.0.2
Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Building wheels for collected packages: ninja
Building wheel for ninja (PEP 517): started
Building wheel for ninja (PEP 517): finished with status 'error'
ERROR: Command errored out with exit status 1:
command: /usr/local/bin/python3 /usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpgwqawgmf
cwd: /tmp/pip-install-u59m6gg9/ninja
Complete output (13 lines):
Traceback (most recent call last):
File "/usr/local/bin/cmake", line 5, in
from cmake import cmake
ModuleNotFoundError: No module named 'cmake'
File "/tmp/pip-build-env-c2lmolrm/overlay/lib/python3.7/site-packages/skbuild/setuptools_wrap.py", line 560, in setup
cmkr = cmaker.CMaker(cmake_executable)
File "/tmp/pip-build-env-c2lmolrm/overlay/lib/python3.7/site-packages/skbuild/cmaker.py", line 95, in init
self.cmake_version = get_cmake_version(self.cmake_executable)
File "/tmp/pip-build-env-c2lmolrm/overlay/lib/python3.7/site-packages/skbuild/cmaker.py", line 82, in get_cmake_version
"Problem with the CMake installation, aborting build. CMake executable is %s" % cmake_executable)
Traceback (most recent call last):

Problem with the CMake installation, aborting build. CMake executable is cmake
----------------------------------------
ERROR: Failed building wheel for ninja
Failed to build ninja
ERROR: Could not build wheels for ninja which use PEP 517 and cannot be installed directly
ERROR: Command errored out with exit status 1: /usr/local/bin/python3 /usr/local/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-roj37yx0/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel scikit-build cmake ninja Check the logs for full command output.

I guess there is also some problem with cmake but I have no idea what to do
I've tried different versions of python, pip but I'm getting the same error
I've spent couple days trying to solve the problem
Any help?

**Comment by jhasse** [comment]
The ninja pip package is actually not by us, please file an issue here: https://github.com/scikit-build/ninja-python-distributions
