### ISSUE TITLE
Build fails when using case sensitive folders on Windows

### ISSUE THREAD

**Issue by MartinBP** [ninja-build/ninja#1882]
Ninja is unable to find files in folders using upper case letters when case sensitive folders are enabled.

Issue can be reproduced by setting up the following folder structure and using the build.ninja file below.
[test_ninja.zip](https://github.com/ninja-build/ninja/files/5569895/test_ninja.zip)

```
`-- test_ninja
     |-- bar
     |    `-- hello.c
     |-- Foo
     |    `-- hello.c
```

test_ninja must be a case sensitive folder.
`fsutil.exe file setCaseSensitiveInfo .\test_ninja\ enable`

```
# build.ninja
cc     = gcc

rule compile
  command = $cc -c $in -o $out

rule link
  command = $cc $in -o $out

#Example 1: Using incorrect casing for 'foo'. Ninja correctly reports an error
#build hello.o: compile foo/hello.c
#Output => ninja: error: 'foo/hello.c', needed by 'hello.o', missing and no known rule to make it

#Example 2: Using correct casing for 'Foo'. Ninja reports the same error, but it should be able to find it.
#build hello.o: compile Foo/hello.c
#Output => ninja: error: 'Foo/hello.c', needed by 'hello.o', missing and no known rule to make it

#Example 3: Using incorrect casing for 'Bar'. Ninja reports the expected error "No such file or directory"
#build hello.o: compile Bar/hello.c
#[1/2] gcc -c Bar/hello.c -o hello.o
#FAILED: hello.o
#gcc -c Bar/hello.c -o hello.o
#gcc: error: Bar/hello.c: No such file or directory
#gcc: fatal error: no input files
#compilation terminated.
#ninja: build stopped: subcommand failed.

#Example 4: Using correct casing for 'bar'. Everything is lower case and so it works
#build hello.o: compile bar/hello.c

build hello: link hello.o

default hello
```

I would expect Example 2 above to work.
Changing the following function RealDiskInterface::Stat in disk_interface.cc to not perform a transform to lower case makes it work as expected.

```
TimeStamp RealDiskInterface::Stat(const string& path, string* err) const {
....

**Removing the two lines below fixes the issue**
  //transform(dir.begin(), dir.end(), dir.begin(), ::tolower);
  //transform(base.begin(), base.end(), base.begin(), ::tolower);

....
}
```

**Comment by jonesmz** [comment]
Does it work if you apply this patch?
https://github.com/ninja-build/ninja/pull/1671

**Comment by MartinBP** [comment]
> Does it work if you apply this patch?
> #1671

No, I get the same error using that pull request

**Comment by jonesmz** [comment]
In that case, can you make a pull request that does your suggested change, and add several test cases for your scenero?

It would also be interesting to see if there is any noticeable performance degradation with your change.

**Comment by jhasse** [comment]
The suggested change is just a workaround. Case sensitive folders on Windows is simply something Ninja doesn't support (yet).

**Comment by MartinBP** [comment]
> In that case, can you make a pull request that does your suggested change, and add several test cases for your scenero?
> 
> It would also be interesting to see if there is any noticeable performance degradation with your change.

Is there a good way to test the performance?
I had to do a few more changes to get all the tests (ninja_test.exe) to pass, so it would be nice to know if the performance has been impacted by those changes.

**Comment by jhasse** [comment]
No, not yet. #1733

**Comment by MartinBP** [comment]
I have looked a little bit more at the code and I can see that the casing is only an issue if the stat cache is being used.
If it is not being used then `StatSingleFile` is called instead of `StatAllFilesInDir`. The call to `StatSingleFile` is done prior to converting the path to lower case. This means that if stat cache is disabled then it actually works as expected on case sensitive folders.

My first take on fixing the case sensitive issues with the stat cache involves.

Remove the following line.
`transform(dir.begin(), dir.end(), dir.begin(), ::tolower);`
As I see it, the line does not make a difference on case insensitive folders.
The dir variable is later used in a call to FindFirstFileExA and on case insensitive folders casing does not matter.
It is also used as a key in the `cache_`. The key is case sensitive, but will not change between each call to `RealDiskInterface::Stat`, so not converting this to lower case should be fine.

Removing just this line fixes the issue with using the stat cache, when folders are using upper case letters and are case sensitive.
It does however not fix the issue with filenames having upper case letters.
In `StatAllFilesInDir` file names are being converted to lower case before being added to the `DirCache` within the `cache_`.
If these two " `transform(lowername.begin(), lowername.end(), lowername.begin(), ::tolower);` and `transform(base.begin(), base.end(), base.begin(), ::tolower);` " conversions are removed then it works as expected on case sensitive folders, but it will break it for people not using the correct casing on case insensitive systems because the key within the cache is case sensitive.

I have solved this by adding two entries for files containing upper case letters into the cache. One with the casing returned by `FindFirstFileExA` or `FindNextFileA` and another entry where it is converted to lowercase + suffix.

Example.
```
`-- bar
     |-- Hello.c
     |-- hello.c
     |-- hello.c_key
```
The cache will then contain:
```
cache["bar"] = {
 ["Hello.c_key"] = "Timestamp for Hello.c",
 ["hello.c_ckey"] = "Timestamp for Hello.c",
 ["hello.c_key"] = "Timestamp for hello.c",
 ["hello.c_key_key"] = "Timestamp for hello.c_key"
}
```
Hello.c with capital 'H' will result in two entries.

A suffix of "_key" is added to all filenames (keys) and a suffix of "_ckey" is added for lower case converted keys.
Without the suffix to all keys then a file with the name "Hello.c" and "hello.c_ckey" would end up with the same key.
The find operation in `RealDiskInterface::Stat` will then have to be modified so it tries the different combinations. First without changing the casing + "_key", then lower case + "_key" and finaly lower case + "_ckey".


Another option would be to check if the folder is case sensitive before deciding whether we should convert the filenames to lower case or not.
According to a comment here https://stackoverflow.com/questions/52206212/programmatically-check-windows-10s-case-sensitive-directory-attribute this does however not look to be supported by the Windows API headers.
_"It's not exposed yet in the Windows API, at least not in the 10.0.17134 headers"_
Requesting this information for each folder might eventually also impact the performance more compared to adding the additional entries to the cache, but I don't know this.

**Comment by MartinBP** [comment]
https://github.com/MartinBP/ninja/commit/791890cd50a635b3671f101a281ef7ec935725c2

**Comment by MartinBP** [comment]
I decided to go for a much simpler solution that covers almost all the cases. #1884 
The only case not covered by this solution is if there are two or more files with the same name (except casing) in the same case sensitive folder. All other cases should be handled by simply not converting the path to lower case.
It is still okay to convert all file names to lower case on both case sensitive and case insensitive folders, so I have not changed that.

**Comment by Bagira80** [comment]
> > I would be glad if it gets merged and released pretty soon, so that there might be a chance that it will be included in the next Visual Studio release/update.
> 
> Last time I checked Visual Studio was still shipping Ninja 1.8, so don't get your hopes up.

Dear @jhasse, I just checked and both, Visual Studio 2019 (16.11.9) and Visual Studio 2022 (v17.0.4), now come with the latest version (v1.10.2) of `ninja`. (Had this PR been merged already, both Visual Studio versions would have this fix already.)

> The PR looks okay but I'm not using Ninja on Windows much, so I can't review it enough.

Is there something that can be done to further progress this PR? Or is this PR doomed to become stale forever?

**Comment by jhasse** [comment]
> Had this PR been merged already, both Visual Studio versions would have this fix already.

The PR has been created after v1.10.2 was released, so no, it would not have this fix already.

> [...] but are there some further tests that I can run, so the PR can be accepted?

> Is there something that can be done to further progress this PR?

Unfortunately there are no easy-to-run scripts to check for performance regressions (see #1733). Creating such a script or manually checking would be the next step. Tests where the `DirCache` matters on Windows in particular.

**Comment by Bagira80** [comment]
> > Had this PR been merged already, both Visual Studio versions would have this fix already.
> 
> The PR has been created after v1.10.2 was released, so no, it would not have this fix already.

Sorry, my bad. I misread 2020 as 2021.

> > [...] but are there some further tests that I can run, so the PR can be accepted?
> 
> > Is there something that can be done to further progress this PR?
> 
> Unfortunately there are no easy-to-run scripts to check for performance regressions (see #1733). Creating such a script or manually checking would be the next step. Tests where the `DirCache` matters on Windows in particular.

To be honest, I do not really understand why you expect this PR to have any impact on the performance, in particular with the `DirCache`.

If I read it correctly, the changes of this PR are equivalent to the following, even more simple diff:

```diff
--- a/src/disk_interface.cc
+++ b/src/disk_interface.cc
@@ -180,13 +180,14 @@ TimeStamp RealDiskInterface::Stat(const string& path, string* err) const {
     dir = path;
   }

+  string dir_origcase = dir;
   transform(dir.begin(), dir.end(), dir.begin(), ::tolower);
   transform(base.begin(), base.end(), base.begin(), ::tolower);

   Cache::iterator ci = cache_.find(dir);
   if (ci == cache_.end()) {
     ci = cache_.insert(make_pair(dir, DirCache())).first;
-    if (!StatAllFilesInDir(dir.empty() ? "." : dir, &ci->second, err)) {
+    if (!StatAllFilesInDir(dir_origcase.empty() ? "." : dir_origcase, &ci->second, err)) {
       cache_.erase(ci);
       return -1;
     }
```

From this it should be obvious that the only difference is that `StatAllFilesInDir()` (and internally `FindFirstFileExA`) now receives a directory name which is no longer guaranteed to be all lower-case.

As a result there will not be any difference if the file-system is **not** case-sensitive. (Even when looking for the wrongly cased filename, `FindFirstFileExA` will find the file; as before.)  
On the other hand, for case-sensitive file-systems it now makes a difference: Without the changes from this PR the file cannot be found if its real case is not all lower-case. While with this PR it now can be found.

Still, the changes from this PR should not have any impact on performance for none case-sensitive file-systems.  
The impact on performance for case-sensitive file-systems is noticeable only insofar as the build-process now no longer will fail.

**Comment by jhasse** [comment]
Makes sense, thanks for the explanation. I've merged the PR :)

**Comment by Bagira80** [comment]
Thanks, I am glad I was helpful in analyzing and progressing this PR. 😄
