### ISSUE TITLE
MinGW: -static flag needed in CMake like configure.py

### ISSUE THREAD

**Issue by scivision** [ninja-build/ninja#1888]
I just confirmed that this issue still exists with current MSYS2/MinGW/GCC 10.2.0.

## Symptoms

If a MSYS2 user does not have MinGW DLL on their Windows PATH, ninja.exe will fail to run, when **built from Ninja's CMakeLists.txt**. 
However, a ninja.exe built from Ninja's configure.py --bootstrap does run. By inspection, the configure.py adds a "--static" flag to MinGW building ninja.exe, while CMakeLists.txt does not.

## Why this is important

Some Ninja users may not wish to always have MinGW on their path--apparently this was recognized for the configure.py build method but was apparently missed for those using CMake to build ninja.exe. All we are looking for is parity between CMakeLists.txt and configure.py Ninja build method for MinGW/MSYS2

**Comment by jhasse** [comment]
I like the CMakeLists.txt not to contain too many changes from the default. It should behave like most other CMake project.
