### ISSUE TITLE
Custom clean command for rules

### ISSUE THREAD

**Issue by dylanede** [ninja-build/ninja#1896]
(Related issues/PRs: #828 #1334 #1690)

I think it would be useful to be able to specify a custom command to run to clean the output of a rule when `ninja -t clean` is invoked, or if building the rule fails. This would be an additional field on rules called `clean` that specifies the command to run. This would help offload to the generator the tricky decision of what to do when cleaning targets that are directories, rather than failing to delete non-empty directories (the current behaviour, which may be desirable in some cases but not all).

**Comment by jhasse** [comment]
I would rather improve our directory support. Implementing custom clean commands sounds like repeating Make's mistakes.
