### ISSUE TITLE
Should support filename longer than 260 characters

### ISSUE THREAD

**Issue by 6ziv** [ninja-build/ninja#1900]
Well, I can see that it is a limitation from Microsoft Windows.
But MSDN suggests that this limitation may be removed.
[Enable Long Paths in Windows 10, Version 1607, and Later](https://docs.microsoft.com/zh-cn/windows/win32/fileio/maximum-file-path-limitation#enable-long-paths-in-windows-10-version-1607-and-later)
And there are cases we have to use long paths (when handling some really complicated 3rd-party projects).
Maybe ninja could only raise a warning, but do not stop the build, like cmake does?

**Comment by jhasse** [comment]
Duplicate of #1514.

**Comment by jhasse** [comment]
#1514 was removed by GitHub because the user who created was banned or something. No idea why they won't simply remove his posts only ...

Anyway, I will reopen this one then. #1514 can still be accessed via the GitHub API: https://api.github.com/repos/ninja-build/ninja/issues/1514/comments

**Comment by jhasse** [comment]
https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation

**Comment by LDong-Arm** [comment]
> https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation

Hi @jhasse,
 
From the page you linked, the user needs to edit the registry to enable long path support, and also the application needs to declare it in its own manifest (pasted from that page):
```
<application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings xmlns:ws2="http://schemas.microsoft.com/SMI/2016/WindowsSettings">
        <ws2:longPathAware>true</ws2:longPathAware>
    </windowsSettings>
</application>
```
Presumably adding this to [ninja.manifest](https://github.com/ninja-build/ninja/blob/master/windows/ninja.manifest) should work? Or how would this impact compatibility with old Windows?

Thanks.

**Comment by LDong-Arm** [comment]
Oh https://github.com/ninja-build/ninja/pull/1939 already does that actually.

**Comment by emmenlau** [comment]
So, what are the next steps for this issue?

**Comment by parbo** [comment]
`RealDiskInterFace` uses posix file functions like fopen, and also the *A versions of win32 calls, while the [long paths page](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry) says only *W versions are affected. Another option might be to prepend `\\?\`, but this only works for absolute paths.

**Comment by parbo** [comment]
I made a PR: https://github.com/ninja-build/ninja/pull/2289

**Comment by vbaderks** [comment]
Hi @parbo 

FYI: It seems that the Windows Universal C CRT only calls CreateFileW. It performs internally a codepage\utf-8 conversion to a wchar_t before calling CreateFileW:
C:\Program Files (x86)\Windows Kits\10\Source\10.0.22621.0\ucrt\lowio\open.cpp (method _sopen_nolock at line 833 for example)

**Comment by parbo** [comment]
Hmm, why didn't it work with fopen then? Maybe the longPathsAware manifest
doesn't extend through to linked libraries/dll:s?

**Comment by vbaderks** [comment]
@parbo. I am assuming that the longPathsAware manifest option applies to the .exe and is enabled process wide at startup or not. I didn't do a debug session in Ninja, just a debug-trace of a local app that uses fopen on Windows 11.

**Comment by parbo** [comment]
Maybe only some of the `*A` functions needed replacing, and not the `fopen`
et al.

**Comment by Jadeon-FPM** [comment]
How is this still an issue? It's looking like my only choice is to switch my workstation over to Linux to be able to build our Android app with the new RN architecture. This shouldn't be a problem.

**Comment by Sculas** [comment]
I can confirm the above comment as well. Even though I configured Windows to allow long paths, Ninja is failing to build a React Native/Expo app with the New Architecture.

**Comment by jhasse** [comment]
> How is this still an issue?

Because Windows still sucks.

**Comment by emmenlau** [comment]
> > How is this still an issue?
> 
> Because Windows still sucks.

True. But isn't it time to move on, and merge a solution?

**Comment by Sculas** [comment]
With #2321 and other PRs now merged, it seems to be fixed! We're just missing an official release, unfortunately.
Here's the workaround I used to compile a RN New Architecture app on Windows:

- Download the latest build artifact of Ninja (I used [this one](https://github.com/ninja-build/ninja/actions/runs/6913066009)) and put it in `C:\ninja\ninja.exe`.
- Go to `android/app/build.gradle` inside of your RN project and add this bit of code inside of `android.defaultConfig`:
```groovy
externalNativeBuild {
    cmake {
        arguments "-DCMAKE_MAKE_PROGRAM=C:\\ninja\\ninja.exe", "-DCMAKE_OBJECT_PATH_MAX=1024"
    }
}
```

To explain why this is needed:
Even *if* you've added `C:\ninja` to your path, Gradle still uses `ninja` from the built-in CMake from the Android SDK. Of course, it doesn't strictly need to be in `C:\ninja`, but chances are that most people have it there already. With just the first argument, it should probably compile already. However, CMake is still warning us about potentially broken builds because the path is too long, so we set it to 1024 to fix that with the second argument.

Lastly, if you want to make this more "contributor-friendly", you can run something like `where ninja` in your `build.gradle`, instead of having a hardcoded path like this. Just make sure to check the version beforehand :)

**Comment by Jadeon-FPM** [comment]
@Sculas 
I can confirm this works! Thank you!

I reinstalled Windows before trying this and assumed Windows 11 had long paths enabled by default. It doesn't, which is unfortunate. For anyone coming here due to this issue, make sure to do that first.

**Comment by CoorFun** [comment]
So, what's the plan for migrating Windows API calls from ANSI to Unicode style?

**Comment by XantreGodlike** [comment]
Why latest release of ninja according to github was in 2022?

**Comment by jhasse** [comment]
@XantreGodlike Because the lastest release of ninja was in 2022.

**Comment by jhasse** [comment]
You're using MinGW, @Sculas was referring to the artifact from GitHub Actions which builds with MSVC. Can you try that instead? Maybe it makes a difference because of the UCRT.

**Comment by smalik007** [comment]
The above built artifact link has expired. But I tried the latest built from the master ([ninja-build-artifact](https://github.com/ninja-build/ninja/actions/runs/8362552639)), I no longer see the ninja error due long path however my build still fails, Now this could be the MinGW that might be causing it to fail now. 
Thanks for the quick response :)

**Comment by Rc85** [comment]
> The above built artifact link has expired. But I tried the latest built from the master ([ninja-build-artifact](https://github.com/ninja-build/ninja/actions/runs/8362552639)), I no longer see the ninja error due long path however my build still fails, Now this could be the MinGW that might be causing it to fail now. Thanks for the quick response :)

Just go to https://github.com/ninja-build/ninja/releases to get latest release

**Comment by Rc85** [comment]
> With #2321 and other PRs now merged, it seems to be fixed! We're just missing an official release, unfortunately. Here's the workaround I used to compile a RN New Architecture app on Windows:
> 
> * **Enable Long Paths first!** Instructions to do that [here](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry#enable-long-paths-in-windows-10-version-1607-and-later).
> * Download the latest build artifact of Ninja [here](https://github.com/ninja-build/ninja/actions/workflows/windows.yml?query=is%3Asuccess+event%3Apush+branch%3Amaster) and put it in `C:\ninja\ninja.exe`.
> * Go to `android/app/build.gradle` inside of your RN project and add this bit of code inside of `android.defaultConfig`:
> 
> ```groovy
> externalNativeBuild {
>     cmake {
>         arguments "-DCMAKE_MAKE_PROGRAM=C:\\ninja\\ninja.exe", "-DCMAKE_OBJECT_PATH_MAX=1024"
>     }
> }
> ```
> 
> To explain why this is needed: Even _if_ you've added `C:\ninja` to your path, Gradle still uses `ninja` from the built-in CMake from the Android SDK. Of course, it doesn't strictly need to be in `C:\ninja`, but chances are that most people have it there already. With just the first argument, it should probably compile already. However, CMake is still warning us about potentially broken builds because the path is too long, so we set it to 1024 to fix that with the second argument.
> 
> Lastly, if you want to make this more "contributor-friendly", you can run something like `where ninja` in your `build.gradle`, instead of having a hardcoded path like this. Just make sure to check the version beforehand :)
> 
> **edit 21/03/2024: replaced expired artifact link with a link to the latest workflow runs**

The artifact link doesn't link to anywhere to download anything, so I assume you mean the latest version 1.11.1?

I have an RN project and a library (react-native-vision-camera) is giving me this error. I enabled long paths and tried your method by adding the code to my build.gradle and also to the camera's build.gradle, none worked. So maybe it's the ninja.exe that I was using?

The only thing that worked was rename my project path from `F:/Projects/<project-name>/<dir1>/<dir2>/<dir3>` to `F:/p/r/m/a/c`, which is ridiculous. It's so sad that in 2024, we still can't deal with long paths.

**Comment by jhasse** [comment]
There seem to be some issues left (only MinGW build? Without setting the registry value it should still not work?), but some are fixed. I will close this PR, please create new issues with specific failures that you see with 1.12.0 and in which circumstances they occur.

> The artifact link doesn't link to anywhere to download anything, so I assume you mean the latest version 1.11.1?

No, it was a master build with some changes not in 1.11.1. Please try 1.12.0 again.

**Comment by carrot93** [comment]
ninjia 1.12.1 still has not been solved "Filename longer than 260 characters Error" on windows( even Enablelongpath). So a temporary way is to shorten the file name(directory name). For python -m pip install, Temporarily "uuid.uuid4().hex[:8]" at "pip/_internal/req/req_install.py", and after install package, recovery to default. 
May be risky, temporary way, wait for ninja to update to new version.

**Comment by digit-google** [comment]
Can you provide exact reproduction steps so we can verify that ourselves (and verify the Ninja version being used too)?

**Comment by SidneyLann** [comment]
1. Clone https://github.com/SidneyLann/rn75.git to a long path dir
2. cd to android
3. yarn
4. yarn android
5. should have error: Filename longer than 260 characters Error

**Comment by Sculas** [comment]
> ninjia 1.10.2 still has not been solved "Filename longer than 260 characters Error" on windows( even Enablelongpath).

You're running Ninja **1.10.2**, correct? This issue has been fixed in [v1.12.0](https://github.com/ninja-build/ninja/releases/tag/v1.12.0) (get the latest version [here](https://github.com/ninja-build/ninja/releases/latest)).
Make sure you actually have long paths enabled in Windows as well, as this obviously doesn't work without that.

@SidneyLann Next time though, *please* read the issue comments before you post your own comment saying a version from 4 years ago doesn't work. Numerous fixes have been posted here already, and it was even closed with a "fixed in 1.12.0" comment.

Lastly, it seems your reproducer project is missing the React Native workaround specified here: https://github.com/ninja-build/ninja/issues/1900#issuecomment-1817532728
The Android SDK includes an old version of Ninja, which it uses by default unless you use that workaround (see comment for info).
(@carrot93 make sure you've done this as well if your project is also React Native!)

**Comment by sylque** [comment]
The provided workaround (https://github.com/ninja-build/ninja/issues/1900#issuecomment-1817532728) doesn't work for me. I get the error even with the Windows fix, the new ninja.exe installed in c:\ninja, and the modified `build.gradle`:

```
C:\xxxxxxxxxx\Tech\dev\xxxxxxxxxxxxxx\dev\test01\my-app2>npx expo run:android
› Building app...
Configuration on demand is an incubating feature.

> Configure project :expo

Using expo modules
  - expo-asset (11.0.1)
  - expo-blur (14.0.1)
  - expo-constants (17.0.3)
  - expo-file-system (18.0.6)
  - expo-font (13.0.2)
  - expo-haptics (14.0.0)
  - expo-keep-awake (14.0.1)
  - expo-linking (7.0.3)
  - expo-modules-core (2.1.2)
  - expo-splash-screen (0.29.18)
  - expo-system-ui (4.0.6)
  - expo-web-browser (14.0.1)


> Configure project :react-native-reanimated
Android gradle plugin: 8.6.0
Gradle: 8.10.2

> Task :react-native-reanimated:buildCMakeDebug[arm64-v8a] FAILED
C/C++: ninja: error: mkdir(src/main/cpp/reanimated/CMakeFiles/reanimated.dir/C_/xxxxxxxxxx/Tech/dev/xxxxxxxxxxxxxx/dev/test01/my-app2/node_modules/react-native-reanimated): No such file or directory

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-reanimated:buildCMakeDebug[arm64-v8a]'.
> com.android.ide.common.process.ProcessException: ninja: Entering directory `C:\xxxxxxxxxx\Tech\dev\xxxxxxxxxxxxxx\dev\test01\my-app2\node_modules\react-native-reanimated\android\.cxx\Debug\5v1g473x\arm64-v8a'
  [0/2] Re-checking globbed directories...
  ninja: build stopped: .

  C++ build system [build] failed while executing:
      @echo off
      "C:\\Users\\Sylvain\\AppData\\Local\\Android\\Sdk\\cmake\\3.22.1\\bin\\ninja.exe" ^
        -C ^
        "C:\\xxxxxxxxxx\\Tech\\dev\\xxxxxxxxxxxxxx\\dev\\test01\\my-app2\\node_modules\\react-native-reanimated\\android\\.cxx\\Debug\\5v1g473x\\arm64-v8a" ^
        reanimated ^
        worklets
    from C:\xxxxxxxxxx\Tech\dev\xxxxxxxxxxxxxx\dev\test01\my-app2\node_modules\react-native-reanimated\android
  ninja: error: mkdir(src/main/cpp/reanimated/CMakeFiles/reanimated.dir/C_/xxxxxxxxxx/Tech/dev/xxxxxxxxxxxxxx/dev/test01/my-app2/node_modules/react-native-reanimated): No such file or directory

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 18s
421 actionable tasks: 25 executed, 1 from cache, 395 up-to-date
Error: C:\xxxxxxxxxx\Tech\dev\xxxxxxxxxxxxxx\dev\test01\my-app2\android\gradlew.bat app:assembleDebug -x lint -x test --configure-on-demand --build-cache -PreactNativeDevServerPort=8081 -PreactNativeArchitectures=arm64-v8a,armeabi-v7a exited with non-zero code: 1
Error: C:\xxxxxxxxxx\Tech\dev\xxxxxxxxxxxxxx\dev\test01\my-app2\android\gradlew.bat app:assembleDebug -x lint -x test --configure-on-demand --build-cache -PreactNativeDevServerPort=8081 -PreactNativeArchitectures=arm64-v8a,armeabi-v7a exited with non-zero code: 1
    at ChildProcess.completionListener (C:\xxxxxxxxxx\Tech\dev\xxxxxxxxxxxxxx\dev\test01\my-app2\node_modules\@expo\spawn-async\src\spawnAsync.ts:67:13)
    at Object.onceWrapper (node:events:639:26)
    at ChildProcess.emit (node:events:524:28)
    at ChildProcess.cp.emit (C:\xxxxxxxxxx\Tech\dev\xxxxxxxxxxxxxx\dev\test01\my-app2\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1101:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
    ...
    at spawnAsync (C:\xxxxxxxxxx\Tech\dev\xxxxxxxxxxxxxx\dev\test01\my-app2\node_modules\@expo\spawn-async\src\spawnAsync.ts:28:21)
    at spawnGradleAsync (C:\xxxxxxxxxx\Tech\dev\xxxxxxxxxxxxxx\dev\test01\my-app2\node_modules\@expo\cli\src\start\platforms\android\gradle.ts:134:28)
    at assembleAsync (C:\xxxxxxxxxx\Tech\dev\xxxxxxxxxxxxxx\dev\test01\my-app2\node_modules\@expo\cli\src\start\platforms\android\gradle.ts:83:16)
    at runAndroidAsync (C:\xxxxxxxxxx\Tech\dev\xxxxxxxxxxxxxx\dev\test01\my-app2\node_modules\@expo\cli\src\run\android\runAndroidAsync.ts:48:24)
```
The new ninja .exe is installed and used: if I rename c:\ninja to c:\ninja2, the build fails, saying it cannot found ninja. But, as you can see above, it seems the old (default) ninja.exe is still called at some point.

Moving my project closer to the root of my drive solves the issue.

**Comment by h1nson** [comment]
Download the latest Ninja release from the [official repository](https://github.com/ninja-build/ninja/releases)
Replace the existing ninja.exe in $SDK_PATH$\cmake\$CMAKE_VERSION$\bin with the newly downloaded version

**Comment by panther7** [comment]
@h1nson  Same issue with ninja 1.13.1

**Comment by fr1g** [comment]
> ~With [#2321](https://github.com/ninja-build/ninja/pull/2321) and other PRs now merged, it seems to be fixed! We're just missing an official release, unfortunately.~ Here's the workaround I used to compile a React Native New Architecture app on Windows:
> 
> * **Enable Long Paths first!** Instructions to do that [here](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry#enable-long-paths-in-windows-10-version-1607-and-later).
> * Download the latest version of Ninja [here](https://github.com/ninja-build/ninja/releases/latest) (**at least v1.12.0**) and put it in `C:\ninja\ninja.exe`.
> * Go to `android/app/build.gradle` inside of your RN project and add this bit of code inside of `android.defaultConfig`:
> 
> externalNativeBuild {
>     cmake {
>         arguments "-DCMAKE_MAKE_PROGRAM=C:\\ninja\\ninja.exe", "-DCMAKE_OBJECT_PATH_MAX=1024"
>     }
> }
> To explain why this is needed: Even _if_ you've added `C:\ninja` to your path, Gradle still uses `ninja` from the built-in CMake from the Android SDK. Of course, it doesn't strictly need to be in `C:\ninja`, but chances are that most people have it there already. With just the first argument, it should probably compile already. However, CMake is still warning us about potentially broken builds because the path is too long, so we set it to 1024 to fix that with the second argument.
> 
> Lastly, if you want to make this more "contributor-friendly", you can run something like `where ninja` in your `build.gradle`, instead of having a hardcoded path like this. Just make sure to check the version beforehand :)
> 
> **edit 21/03/2024: replaced expired artifact link with a link to the latest workflow runs** **edit 20/10/2024: updated workaround to use the official release (v1.12.1, as of writing)**

well, seems on my side, those arguments are not working at all. the output from my console belike:

`````txt
CMake Warning in CMakeLists.txt:
    The object file directory

      K:/DevRepos/ZenChatty/front.rn/node_modules/.pnpm/react-native-worklets@0.5.1_e3492a94937dc0364f467377c0427388/node_modules/react-native-worklets/android/.cxx/Debug/49i85w6f/arm64-v8a/CMakeFiles/worklets.dir/./

    has 210 characters.  The maximum full path to an object file is 250
    characters (see CMAKE_OBJECT_PATH_MAX).  Object file

      K_/DevRepos/ZenChatty/front.rn/node_modules/.pnpm/react-native-worklets@0.5.1_e3492a94937dc0364f467377c0427388/node_modules/react-native-worklets/Common/cpp/worklets/AnimationFrameQueue/AnimationFrameBatchinator.cpp.o

    cannot be safely placed under this directory.  The build may not work
    correctly.


  ninja: error: manifest 'build.ninja' still dirty after 100 tries
`````

this stuff still refuses the arguments you mentioned (or, maybe this is not passed-in on my machine)
my ninja version is 1.13.1

**Comment by fr1g** [comment]
this stuff is really annoying... what to blame and who to blame? pnpm, ninja, rn, windows -- these are four holes on a cheese :((((((
anyway, I'm switching to yarn...

**Comment by MOHAMED-LAAGUILI** [comment]
@fr1g no shiiit im already sweating here  with build on android some errr with expo and mmkv turbo modules and new arch bla bla

**Comment by jerinho** [comment]
> > How is this still an issue?
> 
> Because Windows still sucks.

and you think you're not? it make no sense at all to have a long file name. it's file name not file content

**Comment by biergaizi** [comment]
@fr1g As a matter of public records, the error message you posted:

* The object file directory has 210 characters.  The maximum full path to an object file is 250 characters (see CMAKE_OBJECT_PATH_MAX).  Object file

* ninja: error: manifest 'build.ninja' still dirty after 100 tries

They are two unrelated error message that has nothing to do with each other. The first is a CMake warning which says it's possible that Ninja won't work correctly - but it's a warning, not an error, and doesn't prevent a build. Instead, the second error is a different a file timestamp problem, usually caused by system clock changes.

## Problem 1: File Path

If you have a file path length problem, the build should start successfully, and crash later in the middle at the affected files. A real crash looks as follows:

CMake warning first:

```
CMake Warning in qtdeclarative/src/quickcontrols/fluentwinui3/impl/CMakeLists.txt:
  The object file directory

    C:/Users/user/code/build/build/qt-everywhere-src-6.10.1/build/qtdeclarative/src/quickcontrols/fluentwinui3/impl/CMakeFiles/qtquickcontrols2fluentwinui3styleimplplugin.dir/./

  has 173 characters.  The maximum full path to an object file is 250
  characters (see CMAKE_OBJECT_PATH_MAX).  Object file

    qtquickcontrols2fluentwinui3styleimplplugin_QtQuickControls2FluentWinUI3StyleImplPlugin.cpp.obj

  cannot be safely placed under this directory.  The build may not work
  correctly.


-- Generating done (28.7s)
-- Build files have been written to: C:/Users/user/code/build/build/qt-everywhere-src-6.10.1/build
```


Start the build regardless, and much later in the build, it crashes

```
PS C:\Users\user\code\build\build\qt-everywhere-src-6.10.1\build> cmake --build . --parallel
[4763/6175] Automatic MOC for target qtquickcontrols2fluentwinui3styleimplplugin                                                                              
FAILED: qtdeclarative/src/quickcontrols/fluentwinui3/impl/qtquickcontrols2fluentwinui3styleimplplugin_autogen/timestamp qtdeclarative/src/quickcontrols/fluentwinui3/impl/qtquickcontrols2fluentwinui3styleimplplugin_autogen/mocs_compilation.cpp C:/Users/user/code/build/build/qt-everywhere-src-6.10.1/build/qtdeclarative/src/quickcontrols/fluentwinui3/impl/qtquickcontrols2fluentwinui3styleimplplugin_autogen/timestamp C:/Users/user/code/build/build/qt-everywhere-src-6.10.1/build/qtdeclarative/src/quickcontrols/fluentwinui3/impl/qtquickcontrols2fluentwinui3styleimplplugin_autogen/mocs_compilation.cpp
C:\WINDOWS\system32\cmd.exe /C "cd /D C:\Users\user\code\build\build\qt-everywhere-src-6.10.1\build\qtdeclarative\src\quickcontrols\fluentwinui3\impl && "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E cmake_autogen C:/Users/user/code/build/build/qt-everywhere-src-6.10.1/build/qtdeclarative/src/quickcontrols/fluentwinui3/impl/CMakeFiles/qtquickcontrols2fluentwinui3styleimplplugin_autogen.dir/AutogenInfo.json Release && "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E touch C:/Users/user/code/build/build/qt-everywhere-src-6.10.1/build/qtdeclarative/src/quickcontrols/fluentwinui3/impl/qtquickcontrols2fluentwinui3styleimplplugin_autogen/timestamp && "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E cmake_transform_depfile Ninja gccdepfile C:/Users/user/code/build/build/qt-everywhere-src-6.10.1 C:/Users/user/code/build/build/qt-everywhere-src-6.10.1/qtdeclarative/src/quickcontrols/fluentwinui3/impl C:/Users/user/code/build/build/qt-everywhere-src-6.10.1/build C:/Users/user/code/build/build/qt-everywhere-src-6.10.1/build/qtdeclarative/src/quickcontrols/fluentwinui3/impl C:/Users/user/code/build/build/qt-everywhere-src-6.10.1/build/qtdeclarative/src/quickcontrols/fluentwinui3/impl/qtquickcontrols2fluentwinui3styleimplplugin_autogen/deps C:/Users/user/code/build/build/qt-everywhere-src-6.10.1/build/CMakeFiles/d/8bcbe5f462757de910de6572f55a8d93c0e77a70b5b83e71746f1875cc09c7da.d"

AutoMoc subprocess error
------------------------
The moc process failed to compile
  "SRC:/build/qtdeclarative/src/quickcontrols/fluentwinui3/impl/qtquickcontrols2fluentwinui3styleimplplugin_QtQuickControls2FluentWinUI3StyleImplPlugin.cpp"  
into
  "SRC:/build/qtdeclarative/src/quickcontrols/fluentwinui3/impl/qtquickcontrols2fluentwinui3styleimplplugin_autogen/include/qtquickcontrols2fluentwinui3styleimplplugin_QtQuickControls2FluentWinUI3StyleImplPlugin.moc"
included by
  "SRC:/build/qtdeclarative/src/quickcontrols/fluentwinui3/impl/qtquickcontrols2fluentwinui3styleimplplugin_QtQuickControls2FluentWinUI3StyleImplPlugin.cpp"  
Process failed with return value 1
```

In fact some patched Ninja versions may even build the project successfully in spite of the warning.

I've personally noticed an extremely unusual behavior: when building Qt6, the `ninja` shipped in "Visual Studio 2022" raises this warning, but it may still work if your file path is long but not too long. One extra directory is enough to break the build.

## Problem 2: File Timestamps

The second message is the real error, it says CMake has tried running Ninja 100 times, but Ninja always reports the manifest as dirty, this is tracked by #1599. Like many build systems, Ninja use the file timestamps to determine which file of object code is outdated. So a common root cause is when your system clock has been changed after building some files, as a result, some object code may contain timestamps from the future, and Ninja will always see outdated outputs, because it expects the timestamps are always from the past.

```
  -- Configuring done (0.0s)

  -- Generating done (0.0s)

  -- Build files have been written to:
  C:/Users/user/code/qt-everywhere-src-6.10.1/build/qtbase/config.tests/arch

  [0/100] "C:\Program Files (x86)\Microsoft Visual
  Studio\2022\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe"
  --regenerate-during-build
  -SC:\Users\user\code\qt-everywhere-src-6.10.1\qtbase\config.tests\arch
  -BC:\Users\user\code\qt-everywhere-src-6.10.1\build\qtbase\config.tests\arch


  -- Configuring done (0.0s)

  -- Generating done (0.0s)

  -- Build files have been written to:
  C:/Users/user/code/qt-everywhere-src-6.10.1/build/qtbase/config.tests/arch

  ninja: error: manifest 'build.ninja' still dirty after 100 tries, perhaps
  system time is not set



Call Stack (most recent call first):
  qtbase/cmake/QtBaseConfigureTests.cmake:133 (qt_internal_run_config_test_architecture)
  qtbase/cmake/QtBaseConfigureTests.cmake:255 (qt_run_config_test_architecture)
  qtbase/cmake/QtBaseConfigureTests.cmake:268 (qt_run_qtbase_config_tests)
  qtbase/cmake/QtBaseHelpers.cmake:227 (include)
  qtbase/CMakeLists.txt:36 (qt_internal_qtbase_build_repo)


CMake Error at C:/Users/user/code/qt-everywhere-src-6.10.1/qtbase/cmake/QtProcessConfigureArgs.cmake:1175 (message):
  CMake exited with code 1.


CMake Error at C:/Users/user/code/qt-everywhere-src-6.10.1/cmake/QtIRProcessHelpers.cmake:173 (message):
  C:\Users\user\code\qt-everywhere-src-6.10.1/qtbase/configure.bat -top-level
  -prefix C:\Users\user/opt -DCMAKE_SYSTEM_VERSION=7
  -DCMAKE_C_FLAGS=/D_WIN32_WINNT=0x0601
  -DCMAKE_CXX_FLAGS=/D_WIN32_WINNT=0x0601 -submodules
  qtbase,qtsvg,qtdeclarative,qt5compat -- -DBUILD_qtbase=ON -DBUILD_qtsvg=ON
  -DBUILD_qtdeclarative=ON -DBUILD_qt5compat=ON exited with status: 1
```

To fix the second problem, delete *all* existing build outputs, temporary files and object code to restart from scratch with clean file timestamps. Alternatively, you can reset the timestamps of all build outputs and object code using PowerShell.

```
Get-ChildItem -Recurse -Path /build/output/ | ForEach-Object { $_.CreationTime = (Get-Date) }
Get-ChildItem -Recurse -Path /build/output/ | ForEach-Object { $_.LastWriteTime = (Get-Date) }
```

Don't use the `-File` argument because both files and directories must have their timestamps reset.

Sometimes, even deleting the build directory is not enough. The source code directories must also be restarted from scratch. You may also need to purge all dependencies as well, if those files provide `.cmake`.  You may need to hunt for timestamps in your entire filesystem. Sometimes, the `cmake` or Visual Studio installation itself in `Program Files` can also be the problem, because they provide `.cmake` files (see below)!

In my case, my source code directory's timestamp was 5 PM while the system clock was 1 PM.

```
PS C:\Users\user\code> ls


    Directory: C:\Users\user\code


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        12/25/2025   5:36 PM                qt-everywhere-src-6.10.1
-a----        12/25/2025   1:00 PM       54255931 qt-everywhere-src-6.10.1.tar.xz


PS C:\Users\user\code> date

Thursday, December 25, 2025 1:05:20 PM

PS C:\Users\user\code> Get-ChildItem -Recurse -Path /build/output/ | ForEach-Object { $_.CreationTime = (Get-Date) }
PS C:\Users\user\code> Get-ChildItem -Recurse -Path C:\Users\user\code | ForEach-Object { $_.LastWriteTime = (Get-Date) }
```

But it was still broken, I eventually invoked ninja manually at the affected directory using `-d explain` to debug:

```
PS C:\Users\user\code\qt-everywhere-src-6.10.1\build\qtbase\config.tests\arch> ninja -d explain          
ninja explain: output build.ninja older than most recent input C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.31/Modules/Platform/WindowsPaths.cmake (7884016156132623 vs 7884138951469734)
```

Gotcha. The broken timestamp is located under `C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/`. 

To fix Visual Studio's CMake installation:

```
# for 32-bit Visual Studio, and 32-bit/64-bit Visual Studio Build Tools 2022
Get-ChildItem -Recurse -Path "C:/Program Files (x86)/Microsoft Visual Studio/2022/" | ForEach-Object { $_.CreationTime = (Get-Date) }
Get-ChildItem -Recurse -Path "C:/Program Files (x86)/Microsoft Visual Studio/2022/" | ForEach-Object { $_.LastWriteTime = (Get-Date) }

# for 64-bit Visual Studio
Get-ChildItem -Recurse -Path "C:/Program Files/Microsoft Visual Studio/2022/" | ForEach-Object { $_.CreationTime = (Get-Date) }
Get-ChildItem -Recurse -Path "C:/Program Files/Microsoft Visual Studio/2022/" | ForEach-Object { $_.LastWriteTime = (Get-Date) }
```

If your CMake is installed using a different method, the paths will differ. The most reliable diagnosis is to use `ninja -d explain` under the affected build directory to see the root cause. But if the build is triggered by some complicated wrapper script or IDE, it may not be possible. In this case, hunting the entire computer's filesystems C:\, D:\ may be the only feasible option...

**Comment by amo-si** [comment]
Anybody managed to make it work in WSL?

I added the modified snippet
```bash
externalNativeBuild {
    cmake {
        arguments "-DCMAKE_MAKE_PROGRAM=/mnt/c/ninja/ninja", "-DCMAKE_OBJECT_PATH_MAX=1024"
    }
}
```

Since the actual executable lives in Windows and is a .exe, I created the symlink in WSL
`ln -s "/mnt/c/ninja/ninja.exe" "/mnt/c/ninja/ninja"` but I'm still missing something, 

I get the error
```
C++ build system [build] failed while executing:
      /mnt/c/Users/myuser/AppData/Local/Android/Sdk/cmake/3.22.1/bin/ninja \
        -C \
        /home/myuser/wkspaces/myworkspace/myproject/android/app/.cxx/Debug/3p26r714/arm64-v8a \
        appmodules \
        react_codegen_RNCSlider \
        react_codegen_RNKC \
        react_codegen_rnpicker \
        react_codegen_rnscreens \
        react_codegen_rnsvg \
        react_codegen_safeareacontext
    from /home/myuser/wkspaces/myworkspace/myproject/android/app
```

**Comment by Sculas** [comment]
@amo-si Try installing the Android SDK in WSL and using that. No matter what you do, you can't use Ninja from Windows with a project inside WSL, since CMake doesn't know it needs to specify a UNC path for that to work (it doesn't and causes that error you see).

I've personally found out that Android development with WSL is a bit of a painful experience because you need the Android SDK on Windows as well for the emulator, and then using ADB to connect them. I'm not sure if it's improved over the past few years; I hope it has. Hopefully, this solves your issue!

**Comment by hoang-mai** [comment]
i follow the instruction, but it doesn't work, i think the cause is that I use pnpm instead of npm . Anyone can help me please huhu!!!
