### ISSUE TITLE
Can universal builds be created for macOS with ninja?

### ISSUE THREAD

**Issue by vadi2** [ninja-build/ninja#1908]
Can universal builds be created for macOS with ninja? Using ninja as a cmake generator and elsewhere on the web I see that one needs to use XCode for universal binaries - this also seems to be confirmed with https://github.com/ninja-build/ninja/commit/242b7dd90007e1ac493cdf59a0a5980a72409efa.

**Comment by jhasse** [comment]
Yes, that should be possible as it's clang which does the heavy lifting, not Xcode. If it doesn't work, that would be a CMake issue.
