### ISSUE TITLE
Ninja build qt cause program start fail.

### ISSUE THREAD

**Issue by cathaysia** [ninja-build/ninja#1909]
Ninja ver: 1.10.2
platform: Windows10 + vs2019

Say that I want add a QScintilla(https://riverbankcomputing.com/software/qscintilla/download) library to my program. And I place these libs in qt install dir(C:\Qt\5.15.2\msvc2019_64\lib), and modify cmakelists like this:

![L16IJ3{NHLY990Z8(67XOVH](https://user-images.githubusercontent.com/42114817/106757914-dff76b80-666b-11eb-85ce-99119d2443cf.png)

Then, a runtime error:

![%) }S})JE$ (1VLVK1V@Z04](https://user-images.githubusercontent.com/42114817/106757960-ee458780-666b-11eb-856b-2e12ecec73f7.png)

Here I can promise I place QApplication before my QWidget.

Let's use nmake test this:

![MNHQ8$KI~B3_9XVT(UWI{@Y](https://user-images.githubusercontent.com/42114817/106758079-11703700-666c-11eb-8df9-5cab372103cd.png)

and modify qtcreator's generator to JOM, it works. So I guess ninja modify the order of my code when linking?

**Comment by jhasse** [comment]
You aren't using Ninja *at all*. -> CMake

**Comment by cathaysia** [comment]
> 
> 
> You aren't using Ninja _at all_. -> CMake

I don't think this is a error of cmake

**Comment by jhasse** [comment]
Then QScintilla, Qt, Qt Creator or nmake. Definitely not Ninja though, as you aren't using it.

**Comment by jhasse** [comment]
oh wait, I think I misunderstood. nmake was an example on how it *should* behave?

**Comment by cathaysia** [comment]
> oh wait, I think I misunderstood. nmake was an example on how it _should_ behave?

qtcreate use ninja as its generator default. I use nmake to contrast with ninja.

**Comment by jhasse** [comment]
I see, sorry for the confusion on my side.

I still think this is an issue with CMake's Ninja generator though (generating NMake Makefiles and Ninja build manifests are different code paths in CMake). I have no idea what the issue could be, you would have to break it down to a minmal build.ninja file which reproduces the error.
