### ISSUE TITLE
Add an environment variable to force "smart terminal" newlines

### ISSUE THREAD

**Issue by stk-ableton** [ninja-build/ninja#1926]
There's already an env var (`CLICOLOR_FORCE`) to force colored output even if stdout is not a tty. I'd like to have another one that does the same for the "print over previous line" behavior.

Background: I'm calling ninja from a Visual Studio Code extension; the extension reads ninja's output and prints it to VS Code's terminal. I'm already using `CLICOLOR_FORCE` to force colored output, which works great; I'd like to have a similar way of forcing ninja to print over lines like it would in a terminal.

I'd be happy to submit a PR, just wanted to test the waters first if it would have a chance of being accepted.

**Comment by jhasse** [comment]
To print over the previous line Ninja also checks the terminal width. So this isn't a simple toggle we can turn on.

The extension should give Ninja access to VS Code's terminal, you wouldn't need CLICOLOR_FORCE in that case, too.

If you just want the build line to be overwritten, try adding `\r` to NINJA_STATUS :)

**Comment by stk-ableton** [comment]
> To print over the previous line Ninja also checks the terminal width. So this isn't a simple toggle we can turn on.

Ah, I didn't think of that, of course. Well, the terminal width could be passed by an env var too, but I guess that's too ugly.

> The extension should give Ninja access to VS Code's terminal, you wouldn't need CLICOLOR_FORCE in that case, too.

That's not possible, as the extension needs to read ninja's output before printing it to the terminal. This is somewhat analogous to calling `ninja | tee log.txt`.

> If you just want the build line to be overwritten, try adding `\r` to NINJA_STATUS :)

I don't understand. This just overwrites the status itself, but not the previous output line.
