### ISSUE TITLE
Need Help... 

### ISSUE THREAD

**Issue by bubblestheclown** [ninja-build/ninja#1931]
All seems to go well until I try to test it..... There is no ninja_test file in the build-cmake folder.... anyone know why ?

c:\>git clone https://github.com/ninja-build/ninja.git
Cloning into 'ninja'...
remote: Enumerating objects: 25, done.
remote: Counting objects: 100% (25/25), done.
remote: Compressing objects: 100% (22/22), done.
Receiving objects: 100% (11407/11407), 4.15 MiB | 1.24 MiB/s, done.2 eceiving objects: 100% (11407/11407), 3.62 MiB | 1.17 MiB/s

Resolving deltas: 100% (8059/8059), done.

c:\>cmake -Bbuild-cmake -H.
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
-- Configuring done
-- Generating done
-- Build files have been written to: C:/build-cmake

c:\>cmake --build build-cmake
Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  CMakeVersion.vcxproj -> C:\build-cmake\Source\CMakeVersion.dir\Debug\CMakeVersion.lib
  cmsys.vcxproj -> C:\build-cmake\Source\kwsys\Debug\cmsys.lib
  cmsysTestDynload.vcxproj -> C:\build-cmake\Source\kwsys\Debug\cmsysTestDynload.dll
  cmsysTestDynloadImpl.vcxproj -> C:\build-cmake\Source\kwsys\dynloaddir\Debug\cmsysTestDynloadImpl.dll
  cmsysTestDynloadUse.vcxproj -> C:\build-cmake\Source\kwsys\dynloaddir\Debug\cmsysTestDynloadUse.dll
  cmbzip2.vcxproj -> C:\build-cmake\Utilities\cmbzip2\Debug\cmbzip2.lib
  cmnghttp2.vcxproj -> C:\build-cmake\Utilities\cmnghttp2\Debug\cmnghttp2.lib
  cmzlib.vcxproj -> C:\build-cmake\Utilities\cmzlib\Debug\cmzlib.lib
  cmcurl.vcxproj -> C:\build-cmake\Utilities\cmcurl\lib\Debug\cmcurl.lib
  cmexpat.vcxproj -> C:\build-cmake\Utilities\cmexpat\Debug\cmexpat.lib
  cmjsoncpp.vcxproj -> C:\build-cmake\Utilities\cmjsoncpp\Debug\cmjsoncpp.lib
  cmliblzma.vcxproj -> C:\build-cmake\Utilities\cmliblzma\Debug\cmliblzma.lib
  cmzstd.vcxproj -> C:\build-cmake\Utilities\cmzstd\Debug\cmzstd.lib
  cmlibarchive.vcxproj -> C:\build-cmake\Utilities\cmlibarchive\libarchive\Debug\cmlibarchive.lib
  cmlibrhash.vcxproj -> C:\build-cmake\Utilities\cmlibrhash\Debug\cmlibrhash.lib
  cmlibuv.vcxproj -> C:\build-cmake\Utilities\cmlibuv\Debug\cmlibuv.lib
  cmstd.vcxproj -> C:\build-cmake\Utilities\std\Debug\cmstd.lib
  CMakeLib.vcxproj -> C:\build-cmake\Source\Debug\CMakeLib.lib
  CTestLib.vcxproj -> C:\build-cmake\Source\Debug\CTestLib.lib
  CMakeLibTests.vcxproj -> C:\build-cmake\Tests\CMakeLib\Debug\CMakeLibTests.exe
  CPackLib.vcxproj -> C:\build-cmake\Source\Debug\CPackLib.lib
  cmake.vcxproj -> C:\build-cmake\bin\Debug\cmake.exe
  cmcldeps.vcxproj -> C:\build-cmake\bin\Debug\cmcldeps.exe
  cmsys_c.vcxproj -> C:\build-cmake\Source\kwsys\Debug\cmsys_c.lib
  cmsysTestProcess.vcxproj -> C:\build-cmake\Source\kwsys\Debug\cmsysTestProcess.exe
  cmsysTestSharedForward.vcxproj -> C:\build-cmake\Source\kwsys\Debug\cmsysTestSharedForward.exe
  cmsysTestsC.vcxproj -> C:\build-cmake\Source\kwsys\Debug\cmsysTestsC.exe
  cmsysTestsCxx.vcxproj -> C:\build-cmake\Source\kwsys\Debug\cmsysTestsCxx.exe
  color_warning.vcxproj -> C:\build-cmake\Tests\RunCMake\Debug\color_warning.exe
  cpack.vcxproj -> C:\build-cmake\bin\Debug\cpack.exe
  ctest.vcxproj -> C:\build-cmake\bin\Debug\ctest.exe
  ctresalloc.vcxproj -> C:\build-cmake\bin\Debug\ctresalloc.exe
  curltest.vcxproj -> C:\build-cmake\Utilities\cmcurl\Debug\curltest.exe
  exit_code.vcxproj -> C:\build-cmake\Tests\RunCMake\Debug\exit_code.exe
  fake_build_command.vcxproj -> C:\build-cmake\Tests\RunCMake\Debug\fake_build_command.exe
  kwiml_test.vcxproj -> C:\build-cmake\Utilities\KWIML\test\Debug\kwiml_test.exe
  memcheck_fail.vcxproj -> C:\build-cmake\Tests\CMakeLib\PseudoMemcheck\Debug\memcheck_fail.exe
  print_stdin.vcxproj -> C:\build-cmake\Tests\RunCMake\Debug\print_stdin.exe
  pseudo_BC.vcxproj -> C:\build-cmake\Tests\CMakeLib\PseudoMemcheck\Debug\BC.exe
  pseudo_cuda-memcheck.vcxproj -> C:\build-cmake\Tests\CMakeLib\PseudoMemcheck\Debug\cuda-memcheck.exe
  pseudo_emulator.vcxproj -> C:\build-cmake\Tests\RunCMake\Debug\pseudo_emulator.exe
  pseudo_emulator_custom_command.vcxproj -> C:\build-cmake\Tests\RunCMake\Debug\pseudo_emulator_custom_command.exe
  pseudo_emulator_custom_command_arg.vcxproj -> C:\build-cmake\Tests\RunCMake\Debug\pseudo_emulator_custom_command_arg.exe
  pseudo_llvm-rc.vcxproj -> C:\build-cmake\Tests\RunCMake\Debug\pseudo_llvm-rc.exe
  pseudo_purify.vcxproj -> C:\build-cmake\Tests\CMakeLib\PseudoMemcheck\Debug\purify.exe
  pseudo_valgrind.vcxproj -> C:\build-cmake\Tests\CMakeLib\PseudoMemcheck\Debug\valgrind.exe
  pseudonl_BC.vcxproj -> C:\build-cmake\Tests\CMakeLib\PseudoMemcheck\NoLog\Debug\BC.exe
  pseudonl_purify.vcxproj -> C:\build-cmake\Tests\CMakeLib\PseudoMemcheck\NoLog\Debug\purify.exe
  pseudonl_valgrind.vcxproj -> C:\build-cmake\Tests\CMakeLib\PseudoMemcheck\NoLog\Debug\valgrind.exe
  testAffinity.vcxproj -> C:\build-cmake\Tests\CMakeLib\Debug\testAffinity.exe
  testConsoleBufChild.vcxproj -> C:\build-cmake\Source\kwsys\Debug\testConsoleBufChild.exe
  testEncoding.vcxproj -> C:\build-cmake\Tests\CMakeLib\Debug\testEncoding.exe
  testUVProcessChainHelper.vcxproj -> C:\build-cmake\Tests\CMakeLib\Debug\testUVProcessChainHelper.exe

c:\>./build-cmake/ninja_test
'.' is not recognized as an internal or external command,
operable program or batch file.

c:\>

**Comment by jhasse** [comment]
`c:>cmake -Bbuild-cmake -H.`

cd into the ninja dir first.
