### ISSUE TITLE
It's difficult for users to figure out how to install to a custom path

### ISSUE THREAD

**Issue by eyalroz** [ninja-build/ninja#1942]
When a 'lay' user (not a developer)  builds a repository from sources, they often want to install it to some custom location (e.g. under /opt on Unix-like systems). However, it is not immediately obvious how to achieve this:

* The ninja binary doesn't say anything about it in it's `-h` info
* `man ninja` doesn't tell you how to do it
* The [official ninja documentation ](https://ninja-build.org/manual.html) doesn't tell you how to do it (unless I've missed it, in which case it's difficult to locate the information)

I believe the capability of installing to a custom location should have documentation much much more accessible to less savvy users.

**Comment by jhasse** [comment]
This depends on the generator, nothing ninja can do about it.

**Comment by eyalroz** [comment]
@jhasse : So, are you saying that ninja doesn't directly "do" installation, it's just a task the generator defines? Or is it aware of what installation is, but acts differently depending on the generator?

**Comment by jhasse** [comment]
> So, are you saying that ninja doesn't directly "do" installation, it's just a task the generator defines?

Yes :)
