### ISSUE TITLE
ninja: command not found after build by cmake 

### ISSUE THREAD

**Issue by zhuoran-guo** [ninja-build/ninja#1948]
hello, i do not have root right 
so I download the ninja by git clone 
and build it by cmake 
cmake -Bbuild-cmake -H.
cmake --build build-cmake
it works 
but when I write ninja in terminal 
it also shows the ninja: command not found
how should I do to use the command

**Comment by jhasse** [comment]
Pass `-C build-cmake`

**Comment by jhasse** [comment]
forget that, sorry. `cd build-cmake` and then there's `./ninja`

**Comment by zhuoran-guo** [comment]
i means i want to use ninja in terminal 
such as ninja --version

**Comment by redmms** [comment]
I have the same problem. I want to know my ninja version in Qt. And I tried to run "ninja --version" from my build directory. Nevertheless the command wasn't found, despite that "cmake --version"  works fine and .ninja_log and .ninja_deps files occur in the directory.
What should I do?

**Comment by jhasse** [comment]
You'll have to add the directory with the ninja binary to your PATH, see e.g. https://phoenixnap.com/kb/linux-add-to-path

**Comment by Ryu204** [comment]
Now you can also use this action: [setup-ninja](https://github.com/marketplace/actions/install-ninja-build-tool) to automate the process.
