### ISSUE TITLE
Bug: Ninja CleanDead tool remove non-dead dynamic outputs

### ISSUE THREAD

**Issue by Dragnalith** [ninja-build/ninja#1952]
When running `ninja -t cleandead`, ninja will remove file which are dynamic outputs of the build (files registered in dyndep files as implicit outputs), but those dynamic outputs should not be considered dead. For instance in my example below, input1.o and input2.o are removed by `ninja -t cleandead`.

I have looked at CleanDead implementation and I have noticed it was never calling `LoadDyndeps()` during its initialization.

------
Below the experience I made the reproduce the issue:
```
rule my_tool_dyndep
    command = python my_tool.py --dyndep $out --output $output $in
rule my_tool
    command = python my_tool.py --output $out $in

build output.txt.dyndep : my_tool_dyndep list.txt
    output = output.txt
build output.txt : my_tool list.txt || output.txt.dyndep
    dyndep = build/test2/outputB.txt.dd
```

`my_tool.py` read `list.txt`, which contains a list of file to concatenate. The concatenation written in `output.txt`. To to experiment dynamic outputs, it also output one <file>.o for every <file>.txt contain in list.txt (in my example list.txt contains input1.txt input2.txt).  When run with `--dyndep` the script only generate the dyndep corresponding to the expected action.

_output.txt.dyndep_
```
ninja_dyndep_version = 1
build output.txt | input1.o input2.o: dyndep | input1.txt input2.txt
```

**Comment by jhasse** [comment]
Related: https://gitlab.kitware.com/cmake/cmake/-/issues/21406

**Comment by dcbaker** [comment]
I failed to flag this with #2406, but I'm pretty sure that this should be closed as fixed.
