### ISSUE TITLE
Fully suppress ninja status when NINJA_STATUS is the empty string

### ISSUE THREAD

**Issue by EliRibble** [ninja-build/ninja#1954]
Currently if a user sets the environment variable `NINJA_STATUS` to the empty string then `ninja` will show status lines with no header but include each edge's description.

Instead `ninja` should detect when the environment variable is empty and fully suppress status output.

This is useful in situations where ninja is writing output to a file and the user wants the file to be very short and only show failure information, like capturing output in a build system.

**Comment by jhasse** [comment]
What if the user wants to only show edge description? ;)

It's too bad that the description wasn't part of `NINJA_STATUS` (see #1045) from the start. Changing the behavior now is prone to cause users too complain after updating.

Also see #480.

**Comment by EliRibble** [comment]
Okay, so would you accept a PR that implements #480 ? Because I could write that instead...

**Comment by jhasse** [comment]
Check out #1818. It's basically done and just needs to be rebased against master and have the small change applied that I've suggested in my last comment.
