### ISSUE TITLE
Using a rule variable twice in command is considered as a cycle

### ISSUE THREAD

**Issue by jayzhuang** [ninja-build/ninja#1966]
To reproduce this:

```
~/ninja-lab
> ls
build.ninja  ninja

~/ninja-lab
> ./ninja --version
1.10.2

~/ninja-lab
> cat build.ninja
rule cat
  rspfile = cat.rsp
  rspfile_content = a b c
  command = cat ${rspfile} ${rspfile} > ${out}

build a: cat

~/ninja-lab
> ./ninja
ninja: fatal: cycle in rule variables: rspfile -> rspfile
```

The error message looks incorrect because `rspfile` doesn't form a self cycle. I'd also expect the build to work, and see `rspfile_content` twice in `${out}`.

I've tried this on other rule variables like `description` and got the same error.

**Comment by Yogaht** [comment]
Hi, I'm interested in this issue and try to fix it, see #2202 , I think record the depth of recursive lookup could solve this problem, could you please take a look? @jhasse
