### ISSUE TITLE
ninja: bad depfile: multiple outputs under Alpine Linux 

### ISSUE THREAD

**Issue by Prostyle1337** [ninja-build/ninja#1974]
Hey,

currently im building gRPC under Alpine Linux with ninja 1.9 .

I got at almost every file i compile the error 
ninja: bad depfile: multiple outputs: _deps/grpc-src/third_party/protobuf/src/google/protobuf/stubs/strutil.h != _deps/grpc-build/third_party/protobuf/CMakeFiles/libprotobuf-lite.dir/__/src/google/protobuf/stubs/strutil.cc.o

despite that, its linking. 

It is working with other docker images like Debian or Ubuntu. Any clue? Can i suppress this warning somehow?

**Comment by digit-google** [comment]
Support for multiple outputs in depfiles was introduced in Ninja 1.10.0, it looks like the generator you are using depends on this. You should probably upgrade your Ninja binary to fix this instead.
