### ISSUE TITLE
ninja -C [path to .build] .check endlessly "Running tests" on FreeBSD

### ISSUE THREAD

**Issue by hunteroone** [ninja-build/ninja#1980]
Version: 1.10.2.2
OS: FreeBSD 13.0-RELEASE

I'm trying to compile a port using make with ninja but Ninja appears to be stuck checking the .build directory. It endlessly displays "[29/30] Running tests..."

If I end the process and run make install again (which activates Ninja), it shows that it enters the .build directory (in this case, .../work/tdepim-trinity_14.0.10/.build) and if I look at htop it's running ninja -C [the path..] .check, but it's using none of the CPU and only .1% of memory. Is this a known issue, an issue with something else, and is there a solution?

**Comment by jhasse** [comment]
I think this looks like an issue with your port - the test process is stuck.
