### ISSUE TITLE
Why Ninja outputs no colors but make does using the same CMakeLists.txt

### ISSUE THREAD

**Issue by c02y** [ninja-build/ninja#1984]
I'm using the same CMakeLists.txt, when I set `Unix Makefiles` which is the default value for `CMAKE_GENERATOR` variable, if there are errors in the source code, `make` will print colors for the "error" keyword and the related lines in the terminal, but when I set `CMAKE_GENERATOR` `Ninja`, `ninja` will not output any color for the "error" keyword and related lines( red for the "FAILED" line at the beginning of the output though).

https://github.com/ninja-build/ninja/issues/814 says I have to add 
```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fdiagnostics-color=always")
```
to make ninja output color and it works.

Since make doesn't need this line, is it able to make ninja output colors by default (use an option if you need to disable colors)

Is it a bug?

FYI:
ninja v1.10.2

**Comment by jhasse** [comment]
https://github.com/ninja-build/ninja/wiki/FAQ

**Comment by pauljnixon** [comment]
For GCC and CMake, you can change the default on your own system by adding the line `export CXXFLAGS=' -fdiagnostics-color'` to your `~/.bashrc`.  (This sets the systemwide default for the CMake variable you mentioned above.)

**Comment by Andrej730** [comment]
You can also use `-DCMAKE_COLOR_DIAGNOSTICS=ON` to force the colorful output from the cmake, it will provide `diagnostics-color` to compiler automatically. Settings `CXXFLAGS` as environment variable can be fragile - as some cmake files or other build systems might override it.

Maybe it's possible for cmake to assume it by default when using ninja generator and running cmake from the terminal, opened an issue in cmake - https://gitlab.kitware.com/cmake/cmake/-/issues/27468
