### ISSUE TITLE
ninja -v -C build ninja: Entering directory `build' ninja: fatal: chdir to 'build' - No such file or directory

### ISSUE THREAD

**Issue by Akhil564** [ninja-build/ninja#1985]
Hi, in the process of installing GTK stress testing tool  i need to do install dependencies. but when I am executing with ninja command i am getting an issue...anyone could you please help me out.. thanks in advance.

following are the dependencies need to install....
git clone --recurse-submodules -j4 https://gitlab.com/leinardi/gst.git
cd gst
git checkout release
pip3 install -r requirements.txt
meson . build --prefix /usr
ninja -v -C build
ninja -v -C build install
------------------------------------------------------------------------------------------------
getting an issue with ninja
#ninja -v -C build
ninja: Entering directory `build'
ninja: fatal: chdir to 'build' - No such file or directory

@jhasse 
@mydongistiny

_Originally posted by @Akhil564 in https://github.com/ninja-build/ninja/issues/1463#issuecomment-861611444_

**Comment by jhasse** [comment]
This is a meson issue.

**Comment by Akhil564** [comment]
thanks for reply, but how to reslove this issue. is there any possibility to work

**Comment by jhasse** [comment]
this is not a support forum, sorry

**Comment by passos** [comment]
so where is the support forum? @jhasse

**Comment by jhasse** [comment]
https://groups.google.com/g/ninja-build
