### ISSUE TITLE
ninja: error: loading 'build.ninja': No such file or directory

### ISSUE THREAD

**Issue by Heliogen** [ninja-build/ninja#1992]
Heads up: I am VERY new to this kind of stuff, so try to be as thorough as you can.

I was trying to compile aseprite the other day, and it was going smoothly until I ran this command to compile it:

> cd aseprite
mkdir build
cd build
cmake \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo \
  -DCMAKE_OSX_ARCHITECTURES=x86_64 \
  -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 \
  -DCMAKE_OSX_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk \
  -DLAF_BACKEND=skia \
  -DSKIA_DIR=$HOME/deps/skia \
  -DSKIA_LIBRARY_DIR=$HOME/deps/skia/out/Release-x64 \
  -DSKIA_LIBRARY=$HOME/deps/skia/out/Release-x64/libskia.a \
  -G Ninja \
  ..
ninja aseprite

I ended up getting this error:

> ninja: error: loading 'build.ninja': No such file or directory

I found a[ different article](https://github.com/ninja-build/ninja/issues/1463) with the same issue that seemed to have been solved, saying that you needed to generate the build.ninja file and then run the binary executable. What does this mean, and can you guys help me compile this?

**Comment by jhasse** [comment]
the cmake command failed.

**Comment by sfraczek** [comment]
I had the same problem and I have to say this is unhelpful error message :(

**Comment by sani442** [comment]
watch this video
 https://youtu.be/21-xiWaIV9I?si=jutAJY0kS-HX-QiW

**Comment by digit-google** [comment]
Sorry, but this is not a Ninja issue. You should ask on the aseprite forums. And please do not post links to videos.
