### ISSUE TITLE
Mark a build up to date without generating output file

### ISSUE THREAD

**Issue by sam1018** [ninja-build/ninja#1993]
As part of the build we run clang-tidy on each source file. Currently we generate one dummy file per source file after successfully running clang-tidy. Is it possible to mark the build target as dummy and not actually generate the output file?

**Comment by jhasse** [comment]
I think #1800 would be what you're looking for.

**Comment by jhasse** [comment]
fixed by f0e734cd30db752e401e76316b4e08b6a9b1abab
