### ISSUE TITLE
Cleandead removes input files that used to be outputs in a previous build.

### ISSUE THREAD

**Issue by digit-google** [ninja-build/ninja#1995]
The Fuchsia build, which uses GN + Ninja, found out that the Ninja cleandead tool would incorrectly remove input files that used to be output files in a previous build [1]. This of course breaks our incremental builds (which all run cleandead after regenerating all ninja build manifests).

This can be reproduced independently with a simple example that first uses this build.ninja file to create an empty "test_file" in the build directory.

```
rule touch_file
  command = touch $in
rule test_file: touch_file
rule dummy: touch_file test_file
```

This also adds an entry in .ninja_log for it.

Then modify the build.ninja file to read:
```
rule dummy: touch_file | test_file
```
while `test_file` is still in the build directory (assume it is now generated by the generator).

Running `ninja -t cleandead` will remove `test_file` even though it is listed as an input.

I have found that this comes from the following logic in Cleaner::CleanDead():

```
  for (BuildLog::Entries::const_iterator i = entries.begin(); i != entries.end(); ++i) {
    Node* n = state_->LookupNode(i->first);
    if (!n || !n->in_edge) {
      Remove(i->first.AsString());
    }
  }
```

In other words, anything that is in the build that is no longer an output in the build graph is removed, even if it is now an input.
By changing this to:

```
  for (BuildLog::Entries::const_iterator i = entries.begin(); i != entries.end(); ++i) {
    Node* n = state_->LookupNode(i->first);
    if (!n || (!n->in_edge && n->out_edges().empty())) {
      Remove(i->first.AsString());
    }
  }
```

The issue disappears for us. I can provide a PR with the fix and an associated CleanDeadTest instance. However, I was wondering first if this would break other things.

Also, we tried to use recompact before cleandead, but the former fails to remove the entry from the build log, due to the logic in IsPathDead() in src/ninja.cc, so the problem persists without changing the cleandead logic.

[1] https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=80734

**Comment by digit-google** [comment]
Friendly ping. Any specific thing that would prevent the current PR from being submitted?

**Comment by jhasse** [comment]
No, thanks for the PR with the test and your explanations!

> However, I was wondering first if this would break other things.

I don't think it would, but maybe @ikifof can comment on this.

**Comment by digit-google** [comment]
Thanks then :-)
