### ISSUE TITLE
Help installing ninja through binary on my mac

### ISSUE THREAD

**Issue by KassRigaya** [ninja-build/ninja#2011]
when i try to run the binary it just shows
 /Users/********/Downloads/ninja ; exit;
ninja: error: loading 'build.ninja': No such file or directory
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

What should i do now?

**Comment by jhasse** [comment]
read https://ninja-build.org/manual.html
