### ISSUE TITLE
git history differs slightly between master and releases?

### ISSUE THREAD

**Issue by emmenlau** [ninja-build/ninja#2028]
By chance I've just compared git history of the current master branch with my latest release branch 1.10.2. I've found that a few commits are available on master but missing from the release branch. Those are (in chronological order):
 - 0b6be43	tzik	2017-10-25 22:17:40 +0900	Look up header dependencies on the first-output build
 - 9d502da	Cameron Desrochers	2019-11-13 12:17:31 -0500	Removed unnecessary #ifdef following code review
 - 48a8a7a	Cameron	2019-11-12 21:13:36 -0500	Use symbolic constant as suggested in code review
 - de64856	Cameron Desrochers	2019-11-12 15:47:27 -0500	Fixed processor count detection on Windows when multiple processor groups (i.e. >64 processors) are present
 - 546e27c	Cameron Desrochers	2019-11-20 16:31:14 -0500	Style changes following code review
 - 9e1e51a	Cameron	2020-06-10 07:32:04 -0400	Tweaks following code review
 - 03cbfc6	Colin Cross	2016-11-14 17:13:16 -0800	Add unique IDs to edges
 - c09122c	Jan Niklas Hasse	2020-11-06 19:02:46 +0000	Replace Travis CI with GitHub Actions
 - d709a37	Orgad Shaneh	2020-11-11 13:52:54 +0200	Suppress MSVC warnings

I considered switching between master and release branch, but now I feel a bit uneasy as to why some changes may be present only in the one and not in the other? Thanks for any help...

**Comment by jhasse** [comment]
The release branch is 1.10.2, master is the current state of what will become 1.11.0.

**Comment by emmenlau** [comment]
> The release branch is 1.10.2, master is the current state of what will become 1.11.0.

Dear @jhasse , I can understand that this is the case. But that does not really explain why certain older commits from are missing from of the history. For example, 0b6be43 is a commit that seems to be in master since 2017-10-25, but that is not in 1.10.2. Is that intentional? Why does a commit from 2017 make sense in master but not in the release? Will it go into 1.11.0?

**Comment by jhasse** [comment]
That is the date of the commit, not the date when it was merged/committed on the master branch. See ffb47fcf82ed12f53c046f6d51401c34ec35eced

**Comment by emmenlau** [comment]
> That is the date of the commit, not the date when it was merged/committed on the master branch. See [ffb47fc](https://github.com/ninja-build/ninja/commit/ffb47fcf82ed12f53c046f6d51401c34ec35eced)

That may be true, but still there are several commits after 0b6be43 that made it into the release, so why not this one?

**Comment by jhasse** [comment]
You have to look at the commit graph, NOT the dates of the commits. There are no commits which went into the 1.10.2 release and which were on the master branch at that time which aren't on the release branch, too.

**Comment by emmenlau** [comment]
> You have to look at the commit graph, NOT the dates of the commits. There are no commits which went into the 1.10.2 release and which were on the master branch at that time which aren't on the release branch, too.

Argh, maybe you are right. I was not looking at the dates of the commits but at the (linearized) history of `git log`. Maybe this was confusing me!

**Comment by emmenlau** [comment]
Yes, its better visible in gitk, and you where right. Sorry for the confusion.

**Comment by jhasse** [comment]
No worries :)
