### ISSUE TITLE
Website: Grammar/structure: Comma missing. Present in manual.asciidoc

### ISSUE THREAD

**Issue by Jonta** [ninja-build/ninja#2035]
"Where other build systems are high-level languages, Ninja aims to be an assembler."

https://github.com/ninja-build/ninja/commit/9b8e55d235b34134cb421c9413e11a5a6d677ab2

Missing here: https://ninja-build.org/

"Structure": If that part of the website isn't an export of `manual.asciidoc`, perhaps it should be

Low priority, I'm sure. =)

**Comment by jhasse** [comment]
The website is here: https://github.com/ninja-build/ninja-build.github.io/blob/master/index.html

Not sure if the missing comma is that important, but feel free to create a PR there.
