### ISSUE TITLE
1.7.2 release download is broken

### ISSUE THREAD

**Issue by Neurotoxin001** [ninja-build/ninja#2046]
https://github.com/ninja-build/ninja/releases/tag/v1.7.2

When I click on https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-win.zip it's give me 401 error.
Can you reupload please?

**Comment by jhasse** [comment]
Please contact GitHub support, I do not have the 1.7.2 binaries, so I can't re-upload them.
