### ISSUE TITLE
Recompact fail with "failed recompaction: No such file or directory"

### ISSUE THREAD

**Issue by framillien** [ninja-build/ninja#2048]
In rare cases, on our builds we got this error during `recompact` step:

```
'C:/ProgramData/chocolatey/bin/ninja.exe' '-C' '<SOME_PATH>' '-t' 'recompact'
    failed with:
      ninja: warning: bad deps log signature or version; starting over
    ninja: error: failed recompaction: No such file or directory  
```

Trying to trace back why this is failing, we see that:

- `DepsLog::Load` delete `ninja_deps` and return `LOAD_SUCCESS` if version mismatch or headers are corrupted.
- `OpenDepsLog(/*recompact_only=*/ true)` doesn't stop because on`LOAD_SUCCESS`
- `DepsLog::Recompact` fail because of the missing `ninja_deps` file.

In our case we need to find why the file loading fail (corrupted file ?) but I wonder if this is intentionnal to fail in this case ? 

- if no, returning a `LOAD_NOT_FOUND` instead of `LOAD_SUCCESS` will skip the recompaction since the file was deleted.
- if yes, a more explicit error message could help

thanks,

**Comment by framillien** [comment]
An additionnal note: When we do the migration on our CI infra from version 1.9.X to version 1.10.2, we see similar error and decide to purge all workspaces to fix it.

Now we have investigated current issue, I suppose that having a `LOAD_NOT_FOUND` returned when version mismatched would have helped us to do a smooth Ninja upgrade (but not sure this is the very same error)

**Comment by framillien** [comment]
Doing some analyse of our jobs reports, we see at least 10 occurences of this problem, on few hundred of builds, only on Windows.

No clue for now on why the file is 'corrupted' but if recompaction could not fail when `DepsLog::Load` decide to silently delete the file to be recompacted, this will stabilize our builds.

**Comment by LeeRuns** [comment]
The -C option has never worked for me...really frustrating. I am running windows as well.

**Comment by obfuscated** [comment]
We started seeing this problem on our build farm after we've upgraded from 1.8 to 1.10.
After some investigation it turned out that the problem happens if the following steps are executed:
1. setup minimal cmake project
2. install ninja 1.8
3. build the project with it using `cmake <path> -G Ninja; ninja`
4. install ninja 1.10
5. run `cmake .` in the build folder.

These steps reliably reproduce the problem.
The problem happens even in 1.11 or master.

Here is the full log of commands:
```
 ~/projects/temp/cmake_minimal/build 0 > ninja-build --version
1.8.2
 ~/projects/temp/cmake_minimal/build 0 > cmake .. -G Ninja
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/obf7/projects/temp/cmake_minimal/build
 ~/projects/temp/cmake_minimal/build 0 > ninja-build 
[2/2] Linking CXX executable cmake_minimal
 ~/projects/temp/cmake_minimal/build 0 > ninja-build --version
1.11.0
 ~/projects/temp/cmake_minimal/build 0 > cmake .
-- Configuring done
-- Generating done
CMake Error:
  Running

   '/usr/bin/ninja-build' '-C' '/home/obf7/projects/temp/cmake_minimal/build' '-t' 'recompact'

  failed with:

   ninja: warning: bad deps log signature or version; starting over

  ninja: error: failed recompaction: No such file or directory



CMake Generate step failed.  Build files cannot be regenerated correctly.
 ~/projects/temp/cmake_minimal/build 1 > 
```

OS: CentOS 7
CMake: 3.22.2

**Comment by jhasse** [comment]
same output? If you can reproduce it, please open a new issue.
