### ISSUE TITLE
Incorrect version of Ninja installed using PIP on M1

### ISSUE THREAD

**Issue by nazar-pc** [ninja-build/ninja#2049]
On Mac when using ARM CPU the binary installed with PIP contains x86-64 executable instead of arm64.

I'm not sure whether this is the right place to report, let me know where to submit it instead if this is not the place.

Initially discovered in conjunction with Meson build system in https://github.com/versatica/mediasoup/issues/706

**Comment by ilyapopov** [comment]
Ninja package for pypi is maintained here: https://github.com/scikit-build/ninja-python-distributions
