### ISSUE TITLE
Version corresponding to Pytorch Version

### ISSUE THREAD

**Issue by xiongyt-bear** [ninja-build/ninja#2051]
I am trying to implement my cuda extension on pytorch1.8, But when I build it, I met a problem that says
  File "/home/xyt/anaconda3/envs/PyG/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

So. I want to know the latest ninja support which version pytorch?

**Comment by jhasse** [comment]
Please ask the pytorch project.

**Comment by Ding-Guo** [comment]
I have this problem too, have you solved it?

**Comment by xiongyt-bear** [comment]
yes, I have solved it. I adjust the source files' directory and run successfully. However, I do not know what the reason behind it.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ninja-build/ninja"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月18日(星期六) 晚上6:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ninja-build/ninja] Version corresponding to Pytorch Version (Issue #2051)





 
I have this problem too, have you solved it?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
