### ISSUE TITLE
The system cannot find the path specified. (os error 3)

### ISSUE THREAD

**Issue by mohanss08** [ninja-build/ninja#2057]
Windows 10 
    OS Build 19043.1348
    Ninja version 1.10.0.git

**Source Code Path:-**

    C:\Users\runersystem\AppData\Local\.mabs\siml-mibs-mrunner-m99-w88\workspace\projects\develop\mizen-scri1\tmp-cache\

**Build command:** Executed from above path.

    res/windows/ninja.exe -C build -f build.windows.ninja

**Error:-** 
> cp: error:
> '../res/eemplates/wob/pearaele/Mommoe/MUALib/rel/eau/eemplates/theme/changeable/images/Colector/R_Potary_selector_edit_pold_ic_delete_rg.png'
> -> '../dist/eemplates/wob/pearaele/Mommoe/MUALib/rel/eau/eemplates/theme/changeable/images/Colector/R_Potary_selector_edit_pold_ic_delete_rg.png':
> The system cannot find the path specified. (os error 3)
> 
> ninja: build stopped: subcommand failed.

`dist` directory create during run time and copies the files.

**Path:** - In the following path- No Errors. Copy and build works.

    C:\Users\runersystem\AppData\Local\.mabs\siml-mibs-mrunner-m99-w88\workspace\projects\develop\mizen-scri1\test\

For Example, Like below if i create one extra character it fails with above errors.

    C:\Users\runersystem\AppData\Local\.mabs\siml-mibs-mrunner-m99-w88\workspace\projects\develop\mizen-scri1\test1\

I'm not sure why with path length getting `The system cannot find the path specified. (os error 3)` error. 

1) The account `runersystem` is local system user and member of `Administrator` and `Power users` groups.
2) Windows 10 to accept File Paths Over `260 Characters` enabled `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem`  - `LongPathsEnabled` - `1`
3) Windows Update performed
4) Antivirus Un-installed.
5) Disk cleanup (Using Disk Cleanup) performed.
6) `chkdsk` scan performed.
7) `sfc /scannow` command executed.
8) User & System variables no issues.

Still encountering the same problem with length folder path. Also checked on another `Windows-10` system even in that also same problem persists.

Can someone let me know, what is wrong with directory length? Thanks in advance.

**Comment by jhasse** [comment]
> Windows 10 to accept File Paths Over 260 Characters enabled HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem - LongPathsEnabled - 1

This setting only affects application using UTF-16, not UTF-8 (like Ninja does), because *no idea, please ask Microsoft why they like torturing us all the time*.

See #1900.
