### ISSUE TITLE
Python subprocess breaks out of venv

### ISSUE THREAD

**Issue by brianolson** [ninja-build/ninja#2058]
Example:
https://git.libcamera.org/libcamera/libcamera.git/tree/utils/tracepoints/meson.build

Running `find_program('./gen-tp-header.py')`
It winds up running
```
/usr/bin/python3 /blah/blah/blah/libcamera/utils/tracepoints/./gen-tp-header.py ...
```

`gen-tp-header.py` has a helpful `#!/usr/bin/env python3` line, but that gets lost and we go to system Python which doesn't have some things installed that I have installed in the currently active venv and I was counting on using the venv. I assume `ninja` is _doing work_ to break out of the supplied `python3` that's first on PATH because of the venv, so, it shouldn't do that!

**Comment by ilyapopov** [comment]
Could you inspect the ninja files that meson generated? Most likely, it is meson that refers to globally-installed python by absolute path. Ninja knows nothing about python etc. it just executes commands as specified in build.ninja.

**Comment by jhasse** [comment]
This seems to be unrelated to Ninja. -> Meson
