### ISSUE TITLE
Failing at step 854 when compiling aseprite.

### ISSUE THREAD

**Issue by dogmann-112** [ninja-build/ninja#2059]
The command simply stops at step 854 when compiling aseprite.
Here is the error messeage with the line of coe above it:

Building CXX object laf\os\CMakeFiles\laf-os.dir\skia\os.cpp.obj
FAILED: laf/os/CMakeFiles/laf-os.dir/skia/os.cpp.obj

**Comment by ilyapopov** [comment]
There should be some text after "FAILED" line containing the actual error message from the compiler. You should read that and correct that error. Most likely, you have either missing dependencies or you build environment is set up in wring way. This is unlikely a bug in ninja itself.

**Comment by jhasse** [comment]
Please ask aseprite developers.
