### ISSUE TITLE
Windows 10/11 ARM binaries desired

### ISSUE THREAD

**Issue by gdamore** [ninja-build/ninja#2061]
Bootstrapping a build on Windows ARM is a bit of a challenge -- while Visual Studio can be downloaded, as well as LLVM, the CMake dependency is somewhat onerous as bootstrapping Windows ARM *host* binaries is not as trivial as we might like.

It would be nice if at the same that Windows x86 binaries were provided, that Windows arm binaries were.  (Btw, while I'm here, hopefully the macOS binaries are Universal with support for both m1 and Intel macs?)

**Comment by jhasse** [comment]
> Btw, while I'm here, hopefully the macOS binaries are Universal with support for both m1 and Intel macs?

Yes since 242b7dd90007e1ac493cdf59a0a5980a72409efa

**Comment by jonesmz** [comment]
The ninja ci and release system for windows lives in `.github/workflows/windows.yaml`

I'm sure a PR that adds ARM binaries for windows would be reviewed and discussed.

**Comment by jonesmz** [comment]
I tried investigating this today 

Msvc can generate arm binaries for windows. But github actions cannot be used to test the result. Github doesn't have arm runners, and windows 10 doesn't support arm userland emulation. And apparently running wine in qemu is a headache, running wine in wsl2 doesn't work and running qemu in wsl2 doesn't work.

So any arm binaries produced would be untested.


Assuming that's not a problem, I should be able to relatively easily add arm support to https://github.com/ninja-build/ninja/pull/2109

**Comment by Xazax-hun** [comment]
This would be highly appreciated,
