### ISSUE TITLE
Is there an upcoming release planned?

### ISSUE THREAD

**Issue by ssproessig-thales** [ninja-build/ninja#2095]
Hi ninja team,
the last official release was v1.10.2 on Nov 28, 2020. Do you plan on officially releasing a new version anytime soon?  Or shall the binaries from https://github.com/ninja-build/ninja/actions be taken?

There are many changes already in https://github.com/ninja-build/ninja/compare/v1.10.2...master  , some of which would be quite interesting for most people on Windows, I guess (like #1939).

Thank you for any answers!
Sören

**Comment by jhasse** [comment]
Yes, 1.11.0 is planned to be released soon. Check the milestones for release progress: https://github.com/ninja-build/ninja/milestone/3

**Comment by ssproessig-thales** [comment]
Hi @jhasse - sorry to ask again. The milestone seems to be complete. Do you already plan to release it?

**Comment by jhasse** [comment]
Yes, see https://groups.google.com/g/ninja-build/c/R2oCyDctDf8/m/-U94Y5I8AgAJ
