### ISSUE TITLE
On Windows, non .exe (like npm/xpm .cmd shims) must be invoked via cmd.exe 

### ISSUE THREAD

**Issue by ilg-ul** [ninja-build/ninja#2131]
In `src/subprocess-win32.cc` there is a comment stating that invoking commands via `cmd.exe` is not desired due to the 8192 limit.

Unfortunately, on Windows, there are cases when commands can be invoked **only** via `cmd.exe`, like the `.cmd` shims used by **npm**/**xpm** to forward the invocations to the actual `.exe` files, to compensate for the lack of functional links to files.

Since the xPack binary distribution of Ninja is expected to be used mainly in projects installed via **xpm**, I had to fork this repo and patch `src/subprocess-win32.cc` to use `cmd.exe` when the application is not explicitly an `.exe`:

- <https://github.com/xpack-dev-tools/ninja/blob/xpack/src/subprocess-win32.cc#L113-L172>

With this patch, I was able to successfully run unit-tests built with ninja and generated with both CMake and meson.

From my experience, initially I thought that it is the responsibility of the build generator creating the `ninja.build` file to properly invoke the commands via `cmd.exe`, and in certain limited situations this can be achieved, but unfortunately this cannot be guaranteed in all cases; the result is that `ninja.builds` directly invoking `.cmd` files are created, and ninja must deal with them.

I'd appreciate your comments on this issue.

If you have no better ideas, I can contribute a pull request with this patch.

**Comment by jonesmz** [comment]
> I am not a maintainer, i cannot merge pull requests

My opinion is that this is clearly a situation where it should be the generators responsibility to wrap commands that need to be invoked via cmd.exe, in calls to cmd.exe.

Can you provide an example situation that behaves like you said?

> ilg-ul
> unfortunately this cannot be guaranteed in all cases;

In fact, i think that the correct approach would be that https://github.com/ninja-build/ninja/blob/master/src/subprocess-posix.cc removes the addition of `/bin/sh -c` from the cmdline. This is an obvious potential source of overhead, having an additional sh/bash/ash/dash/zsh/whatever invocation for each subprocess.

**Comment by eli-schwartz** [comment]
Using the shell is very little overhead (/bin/sh is extremely fast, particularly if you use dash or something).

You kind of do need a shell in various situations, and it's currently assumed and therefore relied upon. I think the main thing Meson uses it for is `rm -f libfoo.a && ar csrD libfoo.a object.o`.

But another obvious use case is `VAR=val cmd --args`.

Both are documented in the ninja manual: https://ninja-build.org/manual.html#ref_rule_command

**Comment by ilg-ul** [comment]
> this is clearly a situation where it should be the generators responsibility to wrap commands that need to be invoked via cmd.exe, in calls to cmd.exe

in an ideal world it is probably ok, but in the real world, with multiple generators, ninja files which invoke .cmd shims directly are a fact of life.

> Can you provide an example situation that behaves like you said?

Sure. Instantiate the **Hello World** template on Windows following the steps in <https://github.com/xpack/hello-world-template-xpack/>  and check the generate ninja files, where you'll see direct invocations of `.cmd` files.

The use of `.cmd` shims is Windows specific, since there are no functional symbolic links to files, like on Unix-like systems; this solution was first adopted by npm and later used by xpm too.

**Comment by ilg-ul** [comment]
> Both are documented in the ninja manual: https://ninja-build.org/manual.html#ref_rule_command

Yes, the manual recommends using `cmd /c`, but, for various reasons, generators do not follow this recommendation.

@eli-schwartz, you can instantiate the same Hello World template and select meson; you'll notice that the `ninja.build` files also invoke `.cmd` shims directly, without `cmd.exe`.

**Comment by eli-schwartz** [comment]
> Yes, the manual recommends using `cmd /c`, but, for various reasons, generators do not follow this recommendation.

It's not a recommendation. It's a statement of possibility.

I know Meson doesn't invoke cmd,exe by default -- it knows this can be relied on for Linux, and for cases where Meson internally needs it, it invokes cmd /c in the backend.

On Windows, far more than on Linux, invoking a shell when not actually needed is probably a significant slowdown due to how expensive processes are. It's basically free on Linux.

**Comment by ilg-ul** [comment]
> It's not a recommendation. It's a statement of possibility.

Well, it may be considered a statement of possibility, but if you try to directly invoke a tool like `gcc.cmd`, the build will fail,  so I think it is more than a recommendation, it is a necessity. 

> On Windows, far more than on Linux, invoking a shell when not actually needed is probably a significant slowdown

Right, invoking a tool like `gcc.cmd` via a shell add a small overhead, but invoking it directly fails the build.

In my patch, if the invoked command has the `.exe` extension, I use it directly, otherwise I use a `cmd.exe`, so I am not _invoking a shell when not actually needed_.

**Comment by jonesmz** [comment]
> In an ideal world it is probably ok, but in the real world, with multiple generators, ninja files which invoke `.cmd` shims directly are a fact of life.

And your saying that those ninjafiles don't actually work. 

That doesn't imply that ninja should change its behavior. That implies that the ninjafile generator that is generating not working ninja files should stop doing so.

**Comment by jonesmz** [comment]
> Using the shell is very little overhead (/bin/sh is extremely fast, particularly if you use dash or something).

Yes, agreed. Little overhead, plus backwards compat problems if its removed.

Still doesn't seem like something ninja should be doing. Probably means in the future we could offer a flag that generators could set to disable this (small) overhead of inserting a call to `sh` if the generator is prepared to add `/bin/sh -c` to rules that need it.

**Comment by ilg-ul** [comment]
> ... a flag that generators could set to disable this (small) overhead of inserting a call to sh if the generator is prepared to add /bin/sh -c to rules that need it.

Sorry, but there is no need to do anything like this for Linux/macOS, the problem affects only Windows.

**Comment by ilg-ul** [comment]
> That implies that the ninjafile generator that is generating not working ninja files should stop doing so.

'generatorS' (plural). Both major generators (CMake & meson) create such files, and I wouldn't be surprised for others to do the same.

I agree that it would be nice for all of them to stop doing so, but what if they don't? Aren't the principles of defensive programming still valid?

**Comment by jonesmz** [comment]
> > ... a flag that generators could set to disable this (small) overhead of inserting a call to sh if the generator is prepared to add /bin/sh -c to rules that need it.
> 
> Sorry, but there is no need to do anything like this for Linux/macOS, the problem affects only Windows.

OK. So? It doesn't work on windows the way you want it to. Fix the generator that is misbehavior for your use case.

This isn't a situation of defensive programming. Its a situation of the generator not following the spec and/or existing behavior. Creating additional processes , e.g. calling cmd.exe, is very expensive on windows. The generators need to handle the existing behavior of ninja.

**Comment by jonesmz** [comment]
Re: removing /bin/sh on posix. I'm advocating this be merged (and updated first) https://github.com/ninja-build/ninja/pull/1872

**Comment by ilg-ul** [comment]
> Fix the generator that is misbehavior for your use case.

@eli-schwartz, do you plan to fix meson to invoke non `.exe` commands via `cmd.exe` to meet the ninja specs?

> Creating additional processes , e.g. calling cmd.exe, is very expensive on windows. 

The cost when ninja internally invokes non `.exe` commands via `cmd.exe` is the same as when the generator explicitly issues a line with `cmd.exe /c ...`.

**Comment by ilg-ul** [comment]
Apparently after updating to the latest cmake/meson/ninja this issues seems solved.
