### ISSUE TITLE
Ninja giving every error possible when trying to build a simple "Hello World"

### ISSUE THREAD

**Issue by gal-hadar115** [ninja-build/ninja#2134]
I have both Ninja and CMake downloaded.
I've been scouring the web trying to find solutions when I ran into every error possible. 
I set the C++ compiler to VS 2019, I put ninja in my path and still Ninja wont build every time coming up with a different error
![Screenshot 2022-05-18 164544](https://user-images.githubusercontent.com/95861868/169054363-6181fb07-b3e5-4bf4-8de1-c716a127bc00.png)

"The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:3 (project):
  The CMAKE_CXX_COMPILER:

    ;C:\Program;Files;(;x86;);\Microsoft;Visual;Studio\2019\Community\Common7\IDE\devenv.exe""

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH."
This is after I went into the GUI and made sure under advanced that the MAKE_CXX_COMPILER is the right path to the VS2019

**Comment by gal-hadar115** [comment]
Another error I ran into 
![Screenshot 2022-05-18 173615](https://user-images.githubusercontent.com/95861868/169067834-09911d95-14f3-4dc4-a857-b00a3e2d86ee.png)

**Comment by gal-hadar115** [comment]
Every guide I found online uses CMake and I follow their step one by one and while they go about it with no problems I run into these. So how come CMake is the problematic program here?

**Comment by jonesmz** [comment]
Because those are errors that cmake produces, and not errors that ninja produces.

You are just going to have to believe me on this. You should talk to the cmake support people.

**Comment by jhasse** [comment]
You need to run the commands in the x64 Native Tools Commands Prompt for VS 2019.
