### ISSUE TITLE
Add a switch to let users decide whether to disable/enable stdout buffering on Windows

### ISSUE THREAD

**Issue by shithappens2016** [ninja-build/ninja#2136]
msys2/MINGW-packages#11711

#2085

**Comment by jhasse** [comment]
I think we should always flush here: https://github.com/ninja-build/ninja/blob/55f54511d35716c43637dee2bcb5fbc7839f967b/src/line_printer.cc#L104

**Comment by jonesmz** [comment]
This seems related to https://github.com/ninja-build/ninja/issues/2164

**Comment by jhasse** [comment]
fixed by #2143
