### ISSUE TITLE
[Feature] Support permission checks

### ISSUE THREAD

**Issue by marcosmoyano** [ninja-build/ninja#2144]
I find myself repeating some sort of permission check against the authenticated user. It would be nice if Ninja supported permission checks. Would something like this be welcome?

```python
@router.get(
    url_name="resorce-get",
    path="/{user}/resource",
    response=ResourceSchema,
    auth=[auth1(), auth2(), ....].
    permissions=[perm1(), perm2(), ...]  # <- This
)
@paginate
def list_resources(
    request: HttpRequest,
    user: str,
    **kwargs
):
....
```

**Comment by jhasse** [comment]
I don't understand. Are you sure you've opened the issue on the correct repository?

**Comment by marcosmoyano** [comment]
Apparently not 🤦🏼 . I apologize. Closing
