### ISSUE TITLE
Questions about ninja

### ISSUE THREAD

**Issue by diuming** [ninja-build/ninja#2155]
I'm looking for build system for macOS, Linux and Windows.

Does ninja is independent build system? take a look  [how to compile hello world in c with ninja](https://stackoverflow.com/questions/58989884/how-to-compile-hello-world-in-c-with-ninja).

Could you provide some examples for building c++ with ninja?
- build static library
- build dynamic library
- build executable binary linking with static library
- build executable binary linking with dynamic library

Do you provide detail document about ninja?

thx

**Comment by jonesmz** [comment]
I strongly recommend you use a higher level tool, like cmake or meson.

Ninja is almost certainly not what you want for this.

**Comment by eli-schwartz** [comment]
> Does ninja is independent build system? take a look [how to compile hello world in c with ninja](https://stackoverflow.com/questions/58989884/how-to-compile-hello-world-in-c-with-ninja).

Ninja is a command runner, like Make.

The same way people would usually use something like GNU autotools to generate Makefiles, people would typically use something like Meson or cmake to generate ninja files.

It is of course *possible* to write your own rules by hand, but it's not ergonomic and supporting options of any kind, including "which OS to compile for", is needlessly painful.
