### ISSUE TITLE
Idea: remember what translation units were most slow to compile and schedule these jobs earlier.

### ISSUE THREAD

**Issue by alexey-milovidov** [ninja-build/ninja#2157]
To avoid long tails, for better parallelism.

Imagine, we have three jobs to do and the number of threads is 2.

Job A takes 1 second.
Job B takes 1 second.
Job C takes 2 seconds.

If we schedule jobs A and B first, then C, it will run like this:

```
thread 1: <A> <--C-->
thread 2: <B>
```

and finish in 3 seconds.

If we schedule jobs C, A first, then B, it will run like this:

```
thread 1: <--C-->
thread 2: <A> <B>
```

and finish in 2 seconds.

Ninja can remember the info about previous runs in a temporary file.

**Comment by hadrielk** [comment]
I think this idea was actually posted in an issue or PR before, or maybe on the mailing list.

We're actually writing a python wrapper for ninja right now at my day job, to do that. And also to constrain jobs based on memory load, which we just got working this past week.

**Comment by jonesmz** [comment]
https://github.com/ninja-build/ninja/pull/2019

**Comment by jhasse** [comment]
see #376

**Comment by alexey-milovidov** [comment]
Continued in https://github.com/ninja-build/ninja/issues/2682
