### ISSUE TITLE
"error: FindFirstFileExA(...): The directory name is invalid." when directory in .ninja_deps changes to regular file on Windows

### ISSUE THREAD

**Issue by zmodem** [ninja-build/ninja#2159]
To reproduce on Windows:

```
C:\src\temp\ninja_bug>type build.ninja
msvc_deps_prefix = Note: including file:
rule cc
  deps = msvc
  command = cl -showIncludes -c $in -Fo$out

build foo.obj: cc foo.c

C:\src\temp\ninja_bug>type foo.c
#include "bar/bar.h"

C:\src\temp\ninja_bug>type bar\bar.h
void f() {}

C:\src\temp\ninja_bug>ninja foo.obj
[1/1] cl -showIncludes -c foo.c -Fofoo.obj
Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29336 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

C:\src\temp\ninja_bug>ren bar baz

C:\src\temp\ninja_bug>echo > bar

C:\src\temp\ninja_bug>ninja foo.obj
ninja: error: FindFirstFileExA(bar): The directory name is invalid.
```

The problem is that `StatAllFilesInDir()` does not handle `FindFirstFileExA` returning `ERROR_DIRECTORY`. A fix for this was already merged as 6c864097ef11da366fb4070e6ab9f34d6a293766 a few years ago, but later reverted in 49626c3610826a49f5fa7aee139415fe03d650fd. It's not clear why it was reverted (problems with the test?), but I believe the fix was correct.

(We hit this in Chromium after a reverted update of libc++ changed __string from a directory to a regular file, see http://crbug.com/1337238)

**Comment by hsdk123** [comment]
+1

**Comment by pushpa85** [comment]
The build is successful the first time when we run it with Ninja. After modifying a code file and performing an incremental build, we encounter the following error, even when using CMake version 3.29:
Ninja command:
C:\tools-dev\NINJA\ninja.exe -C O:\Application\ZZZ_Intermediates\Project

Error:
ninja: error: FindFirstFileExA("O:/Application/Build_Dependencies/SW_Version): 
The filename, directory name, or volume label syntax is incorrect.

Can someone help with this issue?
