### ISSUE TITLE
Add ARM64/ARM precompiled binaries in releases assets on GitHub.

### ISSUE THREAD

**Issue by ww898** [ninja-build/ninja#2169]
Hi, could you please add some additional precompiled binaries for more platforms such as Windows arm64, Linux aarch64 (Glibc / MUSL)?

**Comment by jonesmz** [comment]
Implementing this would need to use a cross compiler. Or build resources donates from outside of githubs actions system.

Anyone wanting to work on this should consider looking at my pull request that tries to modernize the ci system for ninja to provide some inspiration : https://github.com/ninja-build/ninja/pull/2109

**Comment by jonesmz** [comment]
Related / duplicate https://github.com/ninja-build/ninja/issues/2061

**Comment by martin-g** [comment]
I could help with this !
Let me try it!

**Comment by martin-g** [comment]
Linux ARM64 binaries: https://github.com/ninja-build/ninja/pull/2201
I have no idea how to do the same for Windows/MacOS ARM64.

**Comment by ThadHouse** [comment]
It looks like macOS already builds a universal binary, so thats fine. Windows is easy as well, you just pass `-A arm64` to the first cmake command. I can try to PR that to the repo at some point.
