### ISSUE TITLE
SIGFPE on system with zero in /cgroup/cpu/cpu.cfs_period_us

### ISSUE THREAD

**Issue by lrtfm** [ninja-build/ninja#2173]
In the code, to calculate the cpu limit, if the value of `/cgroup/cpu/cpu.cfs_period_us` is 0, the program will generate the signal SIGFPE. Should we protect this by checking the value of `period.first`?

code: https://github.com/ninja-build/ninja/blob/d4017a2b1ea642f12dabe05ec99b2a16c93e99aa/src/util.cc#L650

The error information:
```
Program received signal SIGFPE, Arithmetic exception.
0x000000000042d2d5 in ParseCPUFromCGroup() () at ./src/util.cc:650
650       return quota.first / period.first;
```

**Comment by AyandaRevon** [comment]
> *123
