### ISSUE TITLE
configure_file does not rerun if output deleted

### ISSUE THREAD

**Issue by p3732** [ninja-build/ninja#2183]
Hi, I realized that after running `ninja clean` building would no longer work, as the output of a `configure_file` does not get recreated. Here is the relevant code snippet:

```
configure_file(input: 'about_dialog.ui.in',
               output: 'about_dialog.ui',
               configuration: {
                 'contributors': contributors,
                 'translators': translators,
                 'version': meson.project_version(),
                 'website': application_url,
               })
```

In CMake terms, I'd expect this to create a custom target that also gets rebuild upon changes to the output. Is that correct or am I missing something?

ninja version 1.11.0 with meson version 0.63.1

**Comment by jonesmz** [comment]
This seems less like a problems with ninja and more a problem with whatever is generating your ninjafile.

Ninja just cleans up what the ninjafile says to. So the thing that generates the ninja file would need to correct its generated output to get the behavior you are asking for.

**Comment by eli-schwartz** [comment]
> Hi, I realized that after running `ninja clean` building would no longer work, as the output of a `configure_file` does not get recreated. Here is the relevant code snippet:

A meson [`configure_file()`](https://mesonbuild.com/Reference-manual_functions.html#configure_file) does not get created as a build edge, so `ninja clean` (which runs `ninja -t clean`) should NOT be deleting the configured file.

> In CMake terms, I'd expect this to create a custom target that also gets rebuild upon changes to the output. Is that correct or am I missing something?

In CMake terms, a cmake [`configure_file()`](https://cmake.org/cmake/help/latest/command/configure_file.html) is also created directly by cmake, and is NOT a build edge.

**Comment by jhasse** [comment]
Try `ninja -t clean` instead of `ninja clean`. Does `about_dialog.ui` get deleted then, too? If not, this is a Meson bug.

**Comment by p3732** [comment]
Thanks for all your answers!

`ninja -t clean` does indeed not delete the file. I found a duplicate issue of this in the meson tracker, which will hopefully get reopened: https://github.com/mesonbuild/meson/issues/5504

**Comment by eli-schwartz** [comment]
... but since `ninja clean` is a custom command that runs `ninja -t clean`, the behavior is the same...

**Comment by p3732** [comment]
I triple checked this now, `ninja clean` and `ninja -t clean` do not end in the same state. When running `ninja -t clean` there is indeed an error, that I forgot to mention before.

```
^^/P/o/build >>> ninja -t clean
Cleaning... ninja: error: remove(data/resources): Directory not empty
15 files.
```

For plain `ninja clean` this is not the case. Could it be that one of them is force-deleting directories while the other asserts emptiness? Is this a meson error regardless?

**Comment by eli-schwartz** [comment]
Meson generates a custom clean rule called clean-ctlist, which iterates over all Meson `custom_target(..., output: [...])` outputs, and deletes them if they are a directory.

Do you have, somewhere, a `custom_target(..., output: 'data/resources/')`?

Is that *also* a source directory containing a meson.build with rules such as `configure_file()`?

**Comment by p3732** [comment]
> Do you have, somewhere, a custom_target(..., output: 'data/resources/')?

There is indeed a custom_target in `data/resource/meson.build` that has the output `'.'`, so I assume that is a yes.

> Is that also a source directory containing a meson.build with rules such as configure_file()?

It adds the directory with the erroneous `configure_file` call via `subdir()`, so that seems to also be the case.

The code is freely available at https://gitlab.gnome.org/p3732/os-installer if that makes things easier.
