### ISSUE TITLE
`sudo ninja install` may overwrite `.ninja_deps`

### ISSUE THREAD

**Issue by jerome-pouiller** [ninja-build/ninja#2184]
I am used to build and install application using:

    $ ninja && sudo ninja install

However, it sometime breaks my further builds:

    $ ninja
    [2/7] Building C object ....
    ninja: build stopped: Error writing to deps log: Permission denied.

and indeed:

    $ ls -l .ninja_deps
    -rw-r--r-- 1 root root 192896 Aug 22 14:34 .ninja_deps

Note I use `cmake` 3.24 to generate my ninja files.

Have you an idea of what is happening? Am I doing something wrong?

**Comment by jhasse** [comment]
No, this is a known bug: #1302
