### ISSUE TITLE
Arbitrary character deleted from command argument on Windows

### ISSUE THREAD

**Issue by npatellaoz** [ninja-build/ninja#2185]
Hi, I'm using Ninja (1.11.0) with CMake (3.23) on Windows.

I'm running into a very strange issue with commands.
I have a custom command that is meant to generate an installer script for building installers.
To generate it, I usually invoke a .cmake script with "cmake.exe -P" in a custom command.
However, for simplicity, let's assume I invoke "cmake.exe -E echo" instead. This is CMake's solution for supporting echo multiplatform.

When this command is translated to Ninja, the command line looks like:
```
COMMAND = 84b\354\600\CMakeFiles\InstallFiles.nsh-459c14a.bat ce1be5b2b456e3b8
```

If I open the batch file, the command and its arguments look correct.
The command is of the following form (newlines added for clarity):
```
cmake.exe -E echo
"-DNAME=<some name>"
"-DOUTPUT_PATH=<some path>"
"-DINSTALL_FILES_SCRIPTS=<; separated list of files>"
"-DINSTALL_FILES_SCRIPT_PROVIDERS=<; separated list of names>"
"-DFILES_TO_INSTALL=<; separated list of file paths>"
"-DREL_OUTPUT_PATHS=<; separated list of paths>"
"-DMODULES_TO_INSTALL=<; separated list of names>"
```

This command line is very long (8192 < x < 20000). **First of all, is this a problem / is this expected to result in undefined behavior? I would expect a "The input line is too long" error if it was, but I do not get one. I understand cmd.exe does not support > 8192, but I couldn't find any solid answer about .bat files, and I am not sure if .bat files are executed the same by every application.**

Now for the issue: **When I look to see what echo prints, there is a random character deleted from what was input to the command.** The arguments to the command are being corrupted somehow.

Regarding the input I am passing: in the -DINSTALL_FILES_SCRIPTS argument, I have a ; separated list of 40 files that contain the string ".../Code/Source/...". In exactly one of these file paths, the string is corrupted to ".../Cde/Source/..." instead. The "o" is deleted. This character has an offset of 8,888. If I move things around and use shorter or longer paths, a different character with a completely different offset is deleted: for example, "..._Existing.php" is corrupted to "..._Eisting.php", the "x" having an offset of 8,604. In every case, exactly one character is deleted. The fact that this offset is a few hundred characters above 8192 feels suspect, but I am not sure.

**Also very important to note, I've run this on my own machine and the command executed fine, no corrupted arguments. But when I run it on a Windows build server we use, it fails, despite the .bat file that Ninja is running being identical. Both machines have > 100 GB of RAM. So whether or not the argument gets corrupted varies by machine. It also does not matter whether I run the full build, or only this command target, the exact same character is corrupted.**

Does anyone with insight on how Ninja runs .bat files know why this could be happening? I assumed >8192 commands should be supported, but is it expected to result in undefined behavior with no warning? Would I have to hack a rsp file into my command? (CMake is not nice enough to do this out of the box and will do all in its power to make it difficult).

**Comment by jonesmz** [comment]
Ninja just invokes the .bat file directly, for the most part any chance you can provide some kind of cut down ninjafile that reproduces the problem?

**Comment by npatellaoz** [comment]
@jonesmz I can work on a cut down file. It's a single character being deleted somewhere in the middle of the arguments. It's not adjacent to anything that would be considered an escape character. See the third from last paragraph for two examples I encountered. The character deleted is consistent between runs but changes if the length of the command changes.

**Comment by jonesmz** [comment]
> See the third from last paragraph for two examples I encountered. The character deleted is consistent between runs but changes if the length of the command changes.

That implies this is going to be really tricky to locate the problem.

Having a cut down ninja file, or even if you can run ninja in an interactive debugger (e.g. visual studio, with a debug build of ninja) would probably be necessary to find the issue.

I won't make any promises, but i *might* be able to try to reproduce the issue on my work's windows machine if you can give me a minimal reproduction i can unzip and run.

**Comment by npatellaoz** [comment]
Ok, I've made a test project that can reproduce the issue. Only need CMake and Ninja to run it.

I found that whether I invoke the .bat file through Ninja or invoke it directly from the command line, I get the same result. So I'm not sure if this should be considered a CMake issue, a Ninja issue, or a Microsoft issue.

Also given that I get a different result on my machine vs the build machine, I'm not sure you'll be able to reproduce it, but it's worth a try.

[MinimumReproducibleTestProject.zip](https://github.com/ninja-build/ninja/files/9435714/MinimumReproducibleTestProject.zip)

**Comment by npatellaoz** [comment]
@jonesmz Given that it's not Ninja's fault CMake sets up commands this way, maybe I should bring this over to their issue tracker, unless you feel this has any consequences for Ninja.

**Comment by jonesmz** [comment]
The difference in behavior between your two computers *does* imply this could be an issue with Microsoft more than anything.

That being said. This might be something to do with a mistake in how ninja accesses one of the windows APIs.

Since cmake is only involved up to the point where it generates the ninja file, my suspicion is that its a problem with ninja itself, or the Microsoft api, of a combination of the two.

I'm out of town at the moment and can't make any hard promises, but I can try to use your minimal repo on my windows machine and see what happens.

**Comment by npatellaoz** [comment]
@jonesmz I'm in doubt its a ninja issue now, as I tried running the batch file directly from cmd.exe and it had the exact same issue with the deleted character.

But what's a constant in all the cases I've tried so far is that I'm calling a CMake command. For example, if instead of cmake -E echo I used normal echo, it would truncate the string really early on.

So it could be an issue with how cmake.exe handles arguments. I'm going to write my own test executable and see what it gets as input. If I can verify I'll let you know and open the issue with CMake and we could close this one.

**Comment by npatellaoz** [comment]
@jonesmz Okay, I can confirm the issue is with the .bat execution and not with CMake. I wrote a custom echo executable and compared it with the CMake echo output and they were the same on both machines, but the build machine had a deleted character in the output for both. This setup may be more useful for testing.
[MinimalReproductionWithCustomEcho.zip](https://github.com/ninja-build/ninja/files/9436092/MinimalReproductionWithCustomEcho.zip)

**Comment by npatellaoz** [comment]
My suspicion is that this is a bug in Windows Server 2016 (10.0.14393.5066). We're going to upgrade our machine, and if that fails we'll raise it with Microsoft. I'll go ahead and close this as it's to do with .bat execution and not Ninja itself

**Comment by jonesmz** [comment]
Ahhh OK. Thanks for collaborating with me on it :)
