### ISSUE TITLE
Allow piping colored output

### ISSUE THREAD

**Issue by DarkArc** [ninja-build/ninja#2196]
From the FAQ:

> Ninja itself will detect if it's writing to a terminal and escape color codes from commands if it isn't.

I'd like to have the ability to do the following:

```
ninja | less -r
```

Perhaps with a flag like:
```
ninja --no-color-escape | less -r
```

The reason being, I like using less to keep the start of the output at the top of the screen, but I also find colored output very useful.

**Comment by vmauery** [comment]
Try this: 
`
export CLICOLOR_FORCE=1
ninja -C build-dir
`

**Comment by reddwarf69** [comment]
I was a click away from reporting the same.
a) I can't find that FAQ. Even searching for "Ninja itself will detect if it's writing to a terminal and escape color codes from commands if it isn't." in Google/DDG only brings me to this issue.
b) I don't think CLICOLOR_FORCE is documented anywhere? If there is a FAQ, surely it should say "Ninja itself will detect if it's writing to a terminal and escape color codes from commands if it isn't. You can override the decision by setting the CLICOLOR_FORCE environment variable (https://bixense.com/clicolors/)."

**Comment by MRedies** [comment]
The env-variable doesn't seem to work for me. Are the any additional requirements to make it work?

**Comment by jhasse** [comment]
No, nothing else.

**Comment by MatthiasRedies** [comment]
> The env-variable doesn't seem to work for me. Are the any additional requirements to make it work?

Turns out this works for newer ninja versions and mine was too old.
