### ISSUE TITLE
Can't install in CentOS Stream 9

### ISSUE THREAD

**Issue by erik-whiting** [ninja-build/ninja#2199]
Hello! I am trying to install `ninja-build` on CentOS Stream 9 and I can't. Check it out:

```
sh-5.1# dnf install ninja-build
Last metadata expiration check: 0:21:27 ago on Fri Sep 30 06:29:54 2022.
No match for argument: ninja-build
Error: Unable to find a match: ninja-build
sh-5.1# dnf install ninja      
Last metadata expiration check: 0:21:30 ago on Fri Sep 30 06:29:54 2022.
No match for argument: ninja
Error: Unable to find a match: ninja
```
Is there something special I'm supposed to do? Is it available on stream 9? I would try to build it from source but I can't clone the repo from the Docker image without logging into Git, so I have to ask a bunch of people for a bunch of permissions so I can put my credentials in secrets and blah blah blah. Was hoping there's an easier way. Thanks!

**Comment by mwichmann** [comment]
It's in the repo named "CRB". You may have to enable that - it looks like it's off by default.  I didn't know what CRB was by name, it's something Red Hat calls the "Builder" repo, short for "CodeReady Linux Builder" - extra tools for building compiled languages.

**Comment by Goutham7358** [comment]
sudo su
dnf config-manager --enable crb
dnf repolist 
then check if crb is coming up in the list
dnf update
PS: Shamelessly copied from Bard but keeping it here so that others dont have to go that far.
