### ISSUE TITLE
yocto编译qtwebengine 报错unexpected EOF

### ISSUE THREAD

**Issue by Itomyl** [ninja-build/ninja#2207]
ninja: error: toolchain.ninja:28935: unexpected EOF
rspfile = __extensions_renderer_renderer__jum     
                                                                                                   ^ near here   
make[3]: *** [Makefile.gn_run:376: run_ninja] Error 1

**Comment by jhasse** [comment]
Please ask qtwebengine or some of the other tools involved. This doesn't look like a Ninja issue.
