### ISSUE TITLE
`ninja --version` returns a nonzero error code in a shell on Linux.

### ISSUE THREAD

**Issue by WarrenWeckesser** [ninja-build/ninja#2212]
I just upgraded to 1.11.1, and I get a nonzero return code when I run `ninja --version`:
```
$ ninja --version
1.11.1.git.kitware.jobserver-1
$ echo $?
245
```
This is on a Linux system.

With 1.10.2.4, the return code is 0, as expected:
```
$ ninja --version
1.10.2.git.kitware.jobserver-1
$ echo $?
0
```

This breaks `meson`, which expects the return code of `ninja --version` to be 0.  And the failure of `meson` breaks the builds any package that depend on `meson`.  I noticed this because the CI builds of SciPy are currently failing.

**Comment by eli-schwartz** [comment]
Note that the ninja project itself doesn't actually release those PyPI binaries, it's done totally unofficially by a third-party project that also adds various patches.

On a fresh clone and build of ninja:

```
$ ./ninja --version
1.12.0.git
$ echo $?
0
```

So the bug was most likely introduced downstream...

**Comment by WarrenWeckesser** [comment]
I'll close this, as it is a duplicate of https://github.com/ninja-build/ninja/issues/2211.

**Comment by henryiii** [comment]
Can you retry? I uploaded a manylinux2010 wheel for 64-bit Intel.
