### ISSUE TITLE
Trojan:Win32/Wacatac.H!ml

### ISSUE THREAD

**Issue by DJStompZone** [ninja-build/ninja#2222]
# A bit too much malware
Heya, cool project but I'm seeing a bit too much malware for my personal tastes.
Maybe y'all could do Ninja Lite, with just the build tools, without any of the Privilege Escalation, Defense Evasion, write calls to NTUSER.DAT, or other sketchy process behaviors exhibited by [ninja.bootstrap.exe](https://www.virustotal.com/gui/file/901b102ebb0e3daffdcafc9497d076ee209f17d99cff6d45be07e2c14a1ebdca/behavior) and [ninja.exe](https://www.virustotal.com/gui/file/c4c8425d7ef95fdd08b13eb41e011a0d9a4ec478acc0db59e9fbefdfda9df94f/behavior)?

<hr>

I think I'd prefer that version.
<img src="https://i.imgur.com/7ZAELlB.png" width="200">

--DJ

**Comment by apsheronets** [comment]
Hey guys. What's going on here?
I just compressed my windows binary with [upx](https://upx.github.io/) version 4 and now this stupid windows defender detects it as a `Trojan:Win32/Wacatac.H!ml`
Did you do the same here?
