### ISSUE TITLE
[Installation Issue]  installation steps for Automatic1111 - Stable Diffusion ?

### ISSUE THREAD

**Issue by X-Ray-Obs** [ninja-build/ninja#2226]
Hi,

I have installed Stable Diffusion with xformers successfully, however, Automatic1111, recommends using ninja in addition to xformers to get better performance. I have followed the installation steps for ninja but I don't see any difference. 

### **The installation steps by Automatic1111 :**
--------------------------------------------------
Install ninja https://github.com/ninja-build/ninja. Steps to install:

1. download ninja-win.zip from https://github.com/ninja-build/ninja/releases and unzip **(I have done it)**
2. place ninja.exe under C:\Windows OR add the full path to the extracted ninja.exe into system PATH **(I have done it [in C:\Windows])**
3. Run ninja -h in cmd and verify if you see a help message printed **(I have done it [successfully])**
4. Run the follow commands to start building. It should automatically use Ninja, no extra config is needed. You should see significantly higher CPU usage (40%+). **(Blocked at this step)**
 
```
python setup.py build 
python setup.py bdist_wheel
```
--------------------------------------------------

Can anyone tell me how to do a clean install of ninja for Stable Diffusion please ?

**Comment by jhasse** [comment]
This is not a support forum for Stable Diffusion.
