### ISSUE TITLE
ninja: error: unknown target 'install'

### ISSUE THREAD

**Issue by mszhanyi** [ninja-build/ninja#2228]
When I tried using ninja to build protobuf as the external dependencies on Windows
the  `cmake build . --target installl --config XXX` always throw the exception of 
`ninja: error: unknown target 'install'`

But it worked when I changed the cmake command to 
`cmake build . --config ReleaseWithDebInfo` and `cmake --install .`

And if the generator is Visual Studio, `cmake build . --target installl` works too.

Does the ninja not work with `cmake build . --target install`?

**Comment by jhasse** [comment]
Ninja can only work with what it's been given by the generator.

-> CMake issue

**Comment by abhinavbandaru** [comment]
Hi. I'm facing a similar issue while trying to build setuptools-rust. 

2023-02-13 20:50:46 gobuilds.Compile : 20:50:46.188 ninja      INFO         ninja: error: unknown target 'install'

Could you provide some links/docs where I can understand what the "install" command does and could it be replaced with something else?
