### ISSUE TITLE
Mixing Swift in ObjC: "fatal error: 'ObjcSwiftNinja-Swift.h' file not found"

### ISSUE THREAD

**Issue by Coeur** [ninja-build/ninja#2261]
While it works fine with Xcode, I seem unable to use Ninja to build a mixed ObjC+Swift project. I get:
```
/Users/User/Developer/ObjcSwiftNinja/MyObjC.m:2:9: fatal error: 'ObjcSwiftNinja-Swift.h' file not found
#import "ObjcSwiftNinja-Swift.h"
        ^~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

Minimal sample project: https://github.com/Coeur/ObjcSwiftNinja

The CMakeList.txt is as minimal as possible to highlight the issue:
https://github.com/Coeur/ObjcSwiftNinja/blob/97d926d454a8210731b42ddcc92c3a7fbc72ff9a/CMakeLists.txt

The README gives what works and what fails.
Succeeds:
```
cmake -B build -G Xcode
xcodebuild -project build/ObjcSwiftNinja.xcodeproj -target ObjcSwiftNinja-app
```
Fails:
```
cmake -B build -G Ninja
ninja -C build ObjcSwiftNinja-app
```

**Comment by jhasse** [comment]
This is a CMake issue, please open an issue in their bug tracker.

**Comment by Coeur** [comment]
Issue in cmake tracker: https://gitlab.kitware.com/cmake/cmake/-/issues/24571
