### ISSUE TITLE
Release Linux aarch64 Precompiled Binaries for v1.11.1

### ISSUE THREAD

**Issue by mdmedley** [ninja-build/ninja#2264]
Hi @jhasse can we use #2201 to release Linux aarch64 binaries for `v1.11.1` and possibly previous releases?
![](https://media2.giphy.com/media/lqTp5c1mI423u/giphy.gif?cid=ecf05e4790us82uji07asutykhnjwide995yagk9ly3vv0yc&rid=giphy.gif&ct=g)

**Comment by jhasse** [comment]
Will be uploaded with 1.12.0.
