### ISSUE TITLE
Please add support for the Windows Package Manager / winget

### ISSUE THREAD

**Issue by BrainSlugs83** [ninja-build/ninja#2269]
Winget is a front-end commandline tool for the windows package manager service; please consider adding support for this, as it's the built-in package manager that ships with windows.

https://learn.microsoft.com/en-us/windows/package-manager/winget/

**Comment by nightlark** [comment]
Just looking at the winget-pkgs repository, it seems like a Ninja package has already been added to winget: https://github.com/microsoft/winget-pkgs/blob/f37af5277d82ac0e259242857dd4db8d72ef9834/manifests/n/Ninja-build/Ninja/1.11.1/Ninja-build.Ninja.installer.yaml

**Comment by BrainSlugs83** [comment]
My sincere apologies.  I could have sworn I had tried this before logging the bug, but it seems to be working today.

```
Winget install "Ninja-build.Ninja"
Found ninja [Ninja-build.Ninja] Version 1.11.1
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip
  ██████████████████████████████   279 KB /  279 KB
Successfully verified installer hash
Extracting archive...
Successfully extracted archive
Starting package install...
Command line alias added: "ninja"
Path environment variable modified; restart your shell to use the new value.
Successfully installed
```

Nice, thank you. 🙂
