### ISSUE TITLE
Build fails on Windows with cmake 3.26.0 and clang-cl (LLVM), possibly related to parsing `showIncludes`

### ISSUE THREAD

**Issue by emmenlau** [ninja-build/ninja#2276]
I have been using ninja with hundreds of projects and thousands of builds for over two years mostly without problems. Today I updated Visual Studio 2022 from 17.4.1 to 17.5.2 and LLVM from 15.0.6 to 16.0.0. Since then I can not build simple project `zlib` anymore (did not try other builds). The build fails with error:

```
[...]
Visual Studio Non-Incremental Link
LINK:
C:\BDA\ci\LLVM-16.0.0\bin\lld-link.exe CMakeFiles\zlib.dir\adler32.obj CMakeFiles\zlib.dir\compress.obj CMakeFiles\zlib.dir\crc32.obj CMakeFiles\zlib.dir\deflate.obj CMakeFiles\zlib.dir\gzclose.obj CMakeFiles\zlib.dir\gzlib.obj CMakeFiles\zlib.dir\gzread.obj CMakeFiles\zlib.dir\gzwrite.obj CMakeFiles\zlib.dir\inflate.obj CMakeFiles\zlib.dir\infback.obj CMakeFiles\zlib.dir\inftrees.obj CMakeFiles\zlib.dir\inffast.obj CMakeFiles\zlib.dir\trees.obj CMakeFiles\zlib.dir\uncompr.obj CMakeFiles\zlib.dir\zutil.obj CMakeFiles\zlib.dir\win32\zlib1.res /out:zlib1.dll /implib:zlib.lib /pdb:zlib.pdb /dll /version:1.2 /machine:x64 /INCREMENTAL:NO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:zlib1.dll.manifest
MT:
C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\mt.exe /nologo /manifest zlib1.dll.manifest /outputresource:zlib1.dll;#2
ninja: error: FindFirstFileExA(Note: including file:       C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.35.32215/include): The filename, directory name, or volume label syntax is incorrect.
```

I'm building on Windows 11 latest (updated today) using a Cygwin-shell to orchestrate the build. The actual ninja execution is not via cmake but directly a call to `ninja` from a DOS command prompt started from Cygwin bash.

I tried this with ninja build from master from 2022.02 and with current master from today (2d9083b). Both fail with the same error.

**Comment by emmenlau** [comment]
When I run the same build without clang-cl (only using Visual Studio) the error is gone, so it seems it is related to LLVM 16.0.0.

**Comment by emmenlau** [comment]
I have tried now various combinations of build tools. Here is what I tried:
 - Build with Visual Studio 2022 17.4.1 with clang-cl 15.0.6: works
 - Build with Visual Studio 2022 17.5.2 without clang-cl: works
 - Build with Visual Studio 2022 17.5.2 with clang-cl 15.0.6: does not work
 - Build with Visual Studio 2022 17.5.2 with clang-cl 15.0.7: does not work
 - Build with Visual Studio 2022 17.5.2 with clang-cl 16.0.0: does not work

Therefore it seems that the problem comes from the combination of Visual Studio 2022 17.5.2 with clang-cl, independent of the clang-cl version.

**Comment by emmenlau** [comment]
After downgrading cmake to 3.25.3 (latest before 3.26.x), the problem is gone. Updating the info what I tried:
 - Build with Visual Studio 2022 17.4.1 with cmake 3.25.x with clang-cl 15.0.6: works
 - Build with Visual Studio 2022 17.5.2 with cmake 3.26.x without clang-cl: works
 - Build with Visual Studio 2022 17.5.2 with cmake 3.26.x with clang-cl 15.0.6: does not work
 - Build with Visual Studio 2022 17.5.2 with cmake 3.26.x with clang-cl 15.0.7: does not work
 - Build with Visual Studio 2022 17.5.2 with cmake 3.26.x with clang-cl 16.0.0: does not work
 - Build with Visual Studio 2022 17.5.2 with cmake 3.25.3 with clang-cl 16.0.0: works

So the problem seems to appear in combination with clang-cl (any version) and cmake 3.26.x. It seems the Visual Studio version is irrelevant.

**Comment by jhasse** [comment]
Looks like a CMake bug then. Thanks for reporting, pinging CMake devs: @bradking @mathstuf

**Comment by emmenlau** [comment]
Nice @bradking ! Then I will close this issue in favor of the upstream MR.
