### ISSUE TITLE
Run/Debug

### ISSUE THREAD

**Issue by asura95** [ninja-build/ninja#2294]
I have problem with my CLion. If I try to run a my code on CLion, I get the message 
ninja: error: build.ninja:32: loading 'CMakeFiles/rules.ninja': No such file or directory
include CMakeFiles/rules.ninja
I am newbie at coding 😅 and I know how to run code in terminal with flags "gcc ...." and so on but I want to run code with just one click and also use Debug because I sometimes need it. 
I use Mac with Intel CPU (if it relevant)

**Comment by jhasse** [comment]
This is not a support forum and your issue doesn't look like a ninja issue. I suggest asking at https://stackoverflow.com/
