### ISSUE TITLE
Suspicious IP tracking link in wiki

### ISSUE THREAD

**Issue by BestProgrammingLanguage** [ninja-build/ninja#2297]
Why is there a hyperlink to an IP tracking website on [this page](https://github.com/ninja-build/ninja/wiki#basic-overview) (See header "bootstrapping" -> "ninja.exe") that redirects you to the initial github page?

**Comment by jhasse** [comment]
Good question. [The user who did the change](https://github.com/ninja-build/ninja/wiki/Home/_compare/b4af71be80bd5b7fd42b226752a81f9a105a8729...5c1530a1439005240199081bbf965b613a09b0b4) doesn't exist anymore so I guess it's spam. Thanks for pointing it out, I've reverted the change.
