### ISSUE TITLE
ninja call GetFullPathNameA error The filename or extension is too long.

### ISSUE THREAD

**Issue by CaiHuan** [ninja-build/ninja#2325]
ninja post error when compiling chromium project:
GetFullPathNameA(gen/third_party/blink/renderer/bindings/modules/v8/v8_union_gpucanvascontext_imagebitmaprenderingcontext_offscreencanvasrenderingcontext2d_webgl2renderingcontext_webglrenderingcontext.h): The filename or extension is too long. chromium project file name is longer and longer，like v8_union_gpucanvascontext_imagebitmaprenderingcontext_offscreencanvasrenderingcontext2d_webgl2renderingcontext_webglrenderingcontext.h
includes_normalize-win32.cc:InternalGetFullPathName

**Comment by jere8184** [comment]
Hi how did you solve this?

**Comment by EndoSakura** [comment]
Hi how did you solve this?
