### ISSUE TITLE
ninja cmake doesn't support cmake build type override

### ISSUE THREAD

**Issue by farzonl** [ninja-build/ninja#2326]
Building ninja doesn't support `CMAKE_BUILD_TYPE`
So if I run:
`cmake -Bbuild -DCMAKE_BUILD_TYPE=Release` 
you get cmake warnings
```bash
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_BUILD_TYPE
```
Since the build type is ignored.  `cmake --build build`  defaults to a debug build.

For ninja if you want a release build you run 
` cmake --build build  --config Release`

This is fine but it makes it so this one project build is non-standard with other cmake build projects.

**Comment by jhasse** [comment]
I think this depends on the generator you're using and is a behavior of CMake, nothing we can do about that.
