### ISSUE TITLE
ninja cmake ignores compiler override

### ISSUE THREAD

**Issue by farzonl** [ninja-build/ninja#2328]
I want to be able to switch out `cl` for clang. However when I do
`cmake -Bbuild --DCMAKE_C_COMPILER=clang-cl.exe -DCMAKE_CXX_COMPILER=clang-cl.exe`
`CMAKE_C_COMPILER` is not recognized and the compiler tool change defaults to msvc.

```bash
-- Building for: Visual Studio 17 2022
-- The CXX compiler identification is MSVC 19.37.32822.0

CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_C_COMPILER
```

**Comment by jhasse** [comment]
Did you clear your CMakeCache.txt? Anyway: This works for me and there seems to be some issue on your side. But it's a general CMake question, nothing Ninja specific.
