### ISSUE TITLE
CMake: Add `-d keeprsp` arguments in CMakeLists.txt

### ISSUE THREAD

**Issue by tim-hilt** [ninja-build/ninja#2349]
I use `cmake` in combination with `ninja`. It seems like `ninja` is deleting the `.rsp`-files right after the cmake-build succeeds, but this is fixable by calling `ninja` like this:

``` sh
ninja -d keeprsp
```

which already is great news.

I would like to configure this behaviour from `CMakeLists.txt` though, as all our configuration is done in the `cmake`-files. Is there a way of tweaking the call to `ninja` from `CMakeLists.txt`?

**Comment by jhasse** [comment]
This is a CMake question, I would suggest asking on stackoverflow or their bug tracker. (I don't know the answer)

**Comment by tim-hilt** [comment]
Thanks for the response! I totally forgot to close this. In the meantime I found out I can just run `cmake --build -- -d keeprsp`
