### ISSUE TITLE
Enable "longpath" support on Window

### ISSUE THREAD

**Issue by CoorFun** [ninja-build/ninja#2359]
Regarding to [historical reason](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry), path that exceeds 260 characters are not directly supported on Windows.

Ninja now uses ANSI instead of Unicode style on some of Windows APIs. This could lead to ["ERROR 206"](https://learn.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-) (The filename or extension is too long.).

Ninja fails when calling `GetFullPathNameA` etc on a file that is deeply nested or has long generated name. For now, the only solution is reducing directories nested for the project to bypass. But it doesn't solve this issue if Ninja comes to a file that really has a 260 characters long name. 

For example, the following error was generated when I tried to compile V8:
```
GetFullPathNameA(gen/third_party/blink/renderer/bindings/modules/v8/v8_union_gpucanvascontext_imagebitmaprenderingcontext_offscreencanvasrenderingcontext2d_webgl2renderingcontext_webglrenderingcontext.h): The file name or extension is too long
```

So should we migrate all ANSI styled call to the Unicode version?

**Comment by jhasse** [comment]
Duplicate of #1900. Please try the latest master build with the Registry change as mentioned there.

**Comment by CoorFun** [comment]
@jhasse FYI, the latest master build `1.12.0.git` doesn't solve the problem.

**Comment by EndoSakura** [comment]
Hi how did you solve this?

**Comment by pkasting** [comment]
> Hi how did you solve this?

Patching in the changes on https://github.com/ninja-build/ninja/pull/2552 worked for me.
