### ISSUE TITLE
How to build manual.html/manual.pdf?

### ISSUE THREAD

**Issue by hwhsu1231** [ninja-build/ninja#2362]
### Problem Description

Hello, Ninja Development Team.

I wonder what commands/tools should I use to build manual.html/manual.pdf?

It looks like we need to install Asciidoctor, right? What else?

After installing prerequisites, what commands should I run to build manual.html/manual.pdf?

**Comment by digit-google** [comment]
This is not properly documented, but looking at `configure.py` and its output, you need `asciidoc` and `xsltproc` installed, then do:

```
./configure.py
ninja manual
```

Which will generate `doc/manual.html`, there is no PDF option as far as I know.

**Comment by hwhsu1231** [comment]
@digit-google First of all, thanks for your replies.

After running the commands you provided, I successfully built the `manual.html`.

<details><summary>Click to expand logs</summary>

```bash
hwhsu1231@vb-kubuntu:/media/hwhsu1231/Data/Test$ git clone https://github.com/ninja-build/ninja.git
Cloning into 'ninja'...
remote: Enumerating objects: 12313, done.
remote: Counting objects: 100% (262/262), done.
remote: Compressing objects: 100% (174/174), done.
remote: Total 12313 (delta 133), reused 170 (delta 86), pack-reused 12051
Receiving objects: 100% (12313/12313), 4.58 MiB | 3.47 MiB/s, done.
Resolving deltas: 100% (8643/8643), done.
hwhsu1231@vb-kubuntu:/media/hwhsu1231/Data/Test$ cd ninja
hwhsu1231@vb-kubuntu:/media/hwhsu1231/Data/Test/ninja$ ./configure.py
wrote build.ninja.
hwhsu1231@vb-kubuntu:/media/hwhsu1231/Data/Test/ninja$ ninja manual
[2/2] XSLTPROC doc/manual.html
hwhsu1231@vb-kubuntu:/media/hwhsu1231/Data/Test/ninja$ 
```

</details>

As for `manual.pdf`, I wonder how does ninja build it if there's no PDF option?

**Comment by digit-google** [comment]
You can generate the PDF by having `dblatex` installed then doing `ninja doc/manual.pdf`. I have uploaded a [PR](https://github.com/ninja-build/ninja/pull/2373) to update the `README.md` file to mention this.
