### ISSUE TITLE
gtkmm4 building in Ubuntu 22.04 : Ninja : Unknown IO error

### ISSUE THREAD

**Issue by raphael10-collab** [ninja-build/ninja#2365]
raphy@raohy:~/gtkmm-4.8.0$ meson setup --prefix /usr --libdir lib your_builddir .
    The Meson build system
    Version: 1.3.0
    Source dir: /home/raphy/gtkmm-4.8.0
    Build dir: /home/raphy/gtkmm-4.8.0/your_builddir

For size limits I've put the entire output of `meson setup --prefix /usr --libdir lib your_builddir .` command in google drive : https://drive.google.com/file/d/1kvP_xitHnRaVyNmXLOy7ZBtjdP1zZyev/view?usp=drive_link

Execuing ninja got this error: 

    raphy@raohy:~/gtkmm-4.8.0/your_builddir$ ninja
    [125/2744] Generating subprojects/libsigcplusplus/docs/docs/manual/manual_html with a custom command
    FAILED: subprojects/libsigcplusplus/docs/docs/manual/html 
    /usr/bin/python3 /home/raphy/gtkmm-4.8.0/subprojects/libsigcplusplus/tools/tutorial-custom-cmd.py html ../subprojects/libsigcplusplus/docs/docs/manual/libsigc_manual.xml subprojects/libsigcplusplus/docs/docs/manual/html
    error : Unknown IO error
    warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/html/chunk.xsl"
    cannot parse http://docbook.sourceforge.net/release/xsl/current/html/chunk.xsl
    [134/2744] Generating subprojects/libsigcplusplus/docs/docs/reference/html_and_tag with a custom command
    ninja: build stopped: subcommand failed.

How to make it work?

**Comment by digit-google** [comment]
That does not look like a Ninja issue at all, just Ninja reporting that the command it launched (in this case running the `tutorial-custom-cmd.py` script) failured. I suggest you ask this question on the `gtkmm` mailing list (or possibly on the one for `libsigcplusplus` since this is failing to build a Meson subproject).
