### ISSUE TITLE
How to create task hierarchies?

### ISSUE THREAD

**Issue by mcandre** [ninja-build/ninja#2372]
Hi,

I regularly write makefiles with nested task hierarchies. For example, my default `all` task often expands to `lint` and `test` tasks. My `lint` task expands to `bashate`, `shellcheck`, and `shfmt` tasks. My `test` task expands to `unit_test` and `integration_test` tasks. Then the leaves of the task tree finally resolve to simple shell commands.

How do I do the same in a build.ninja file?

I tried declaring a build that depends on further builds, but ninja rejects that syntax.

```console
$ cat build.ninja
rule ninja_dry_run
    command = ninja -n

rule shellcheck
    command = shellcheck hello.sh

build lint: ninja_dry_run | shellcheck

build default: lint

$ ninja
ninja: error: build.ninja:9: unknown build rule 'lint'
build default: lint
               ^ near here
```

I tried declaring dependencies on a rule, but ninja also rejects that syntax.

```console
$ cat build.ninja
rule ninja_dry_run
    command = ninja -n

rule shellcheck
    command = shellcheck hello.sh

rule lint: ninja_dry_run | shellcheck

build default: lint

$ ninja
ninja: error: build.ninja:7: expected newline, got ':'
rule lint: ninja_dry_run | shellcheck
         ^ near here
```

Meanwhile, I'll continue to just use make, which supports task hierarchies out of the box, since forever, with no special syntax required.

**Comment by digit-google** [comment]
I am sorry, but the issue tracker is to report bugs and feature requests, not to ask generic questions that can be answered on the mailing list or by reading the manual (hint: the phony rule).
