### ISSUE TITLE
Inconsistent behaviour of "-t compdb"

### ISSUE THREAD

**Issue by ransel117** [ninja-build/ninja#2374]
Hi! I've noticed that "-t compdb" gives different results in some cases when in my mind they should be equal.
```console
folder> cat test1.ninja
rule test1_rule
    command = echo $in
build test1: test1_rule test.c
folder> ninja -f test1.ninja -t compdb               
[
  {
    "directory": "folder",
    "command": "echo test.c",
    "file": "test.c",
    "output": "test1"
  }
]

folder> cat test2.ninja
rule test2_rule
    command echo test.c
build test2: test2_rule
folder> ninja -f test2.ninja -t compdb               
[
]

```
It seems like if it doesn't have "$in" in the command variable it just skips the generating part.

**Comment by digit-google** [comment]
This is working as intended. The [Compilation Database Format Spec](https://clang.llvm.org/docs/JSONCompilationDatabase.html)  requires a `file` entry in each JSON object (only `output` is optional).

Looking at the source code shows that `-t compdb` _intentionally_ skips rules with empty inputs.
Through git history, one can see that this was added 10 years ago in PR #758 with the motive that "the tool crashes with empty inputs" without much more details.

One could argue that the fact that only the first input in a given build statement generates an entry into the database is a bug. Alas, Ninja tools don't have a real spec or integration tests, so changing anything here is likely to wreck some developer workflow somewhere and should be done with care. But that's for a different issue I guess.

**Comment by ransel117** [comment]
Ah ok I didn't know if it was intended or not, cheers! I found a way to circumvent it with an "empty" rule as input to make '-t compdb' output my desired result 🙂
