### ISSUE TITLE
[feature] add a mechanism to pass a subset of input files that needs rebuilding to a single compiler invocation

### ISSUE THREAD

**Issue by Mis012** [ninja-build/ninja#2376]
My problem is as such: using `javac` the same way as one does a C compiler - compiling each `.java` file to a `.class` file with a separate `javac` execution - is EXTREMELY slow compared to just supplying multiple `.java` files to a single `javac` execution.

Therefore, it would be nice if one was able to use ninja's knowledge of which input files have changed to pass exactly these files to `javac`. 

Maybe something like the following:

```ninja
rule javac_batched_foo
 command = javac $in [options specific to classes that will go into foo.jar]
 batched = 1
 
 rule javac_batched_bar
 command = javac $in [options specific to classes that will go into bar.jar]
 batched = 1
```

with simply `build foo.class: javac_batched_foo foo.java` to keep the information about which input files correspond to which output files.

Of course, there might be better approaches, but it seems like some sort of a solution is necessary since not all compilers are able to do one thing at a time without a massive performance hit.

**Comment by jhasse** [comment]
Passing multiple .java files will result in .class file for each of them, too?

To me it sounds like that this would better be solved with a separate program that collects the java files to compile via IPC and blocks each client until it is done.

**Comment by Mis012** [comment]
passing a single .java file can already result in multiple .class files, there is an option to only save the one but afaict the other files are still compiled, just not saved

**Comment by digit-google** [comment]
This is not something that Ninja is designed to handle well (because the actual command outputs will vary on each invocation).

Note that Bazel solves this by using [Persistent Workers](https://bazel.build/remote/persistent), a feature where a long-lived compiler is run in a separate process, and receives requests from the build system and generates outputs.

You may have a similar experience by setting up your own persistent Java builder (jmake maybe)? and have your Ninja commands invoke it through whatever means necessary.

**Comment by Mis012** [comment]
https://github.com/pantsbuild/jmake? seems a little dead, and it doesn't look like that's because it was perfected and there is nothing to add

**Comment by digit-google** [comment]
I haven' t done Java in a long time, it looks like there are tools named `sjavac` or `NailGun` to do something similar these days, but I have no idea about their level of support. Just pointing this here in case this helps.

**Comment by Mis012** [comment]
It seems the remnants of sjavac can be built outside the openjdk tree and used as-is, and it does certainly improve the build time quite considerably. However, it's still orders of magntitude faster to simply pass every single .java file to a single `javac` invocation, to the point where incremental builds don't really seem worth it...
