### ISSUE TITLE
Ninja target path with .. in the filename

### ISSUE THREAD

**Issue by ttessier1** [ninja-build/ninja#2380]
There is an issue where a build.ninja file has targets with 

build libSomeLib/.._somefile1.c.o: # rest of file goes here

build libSomeLib/.._somefile2.c.o: # rest of file goes here

appearst to generate an $out of the directory "libSomeLib" instead of libSomLib/.._somfile1.co which creates a multiple rules error to generate libSomeLib error as a result.

If the .. are removed and just the _ remains - the target builds.

This may be an auto generation of build.ninja file but also happens to effect ninja build files building correctly.
Note: it is possible to create a file with .._fileName as an actual file.

If this is not going to be corrected then an error needs to be generated on running up against .._ in targets.

Multiple rules generate prevents listing rules and targets in favor of displaying the error of multiple targets which makes it difficult to track this down.

Not sure if ninja will take action but this effects several open source projects of which I do not have control.

version 1.12.0.git

**Comment by digit-google** [comment]
Can you provide reproduction steps? The following `build.ninja` file works as expected on my Linux workstation with the current Ninja tip-of-tree binary:

```
rule touch
  command = touch $out

build foo/.._bar: touch
build foo/.._qux: touch
```

I.e. if I do `ninja`, I get:

```
$ ninja | cat
[1/2] touch foo/.._qux
[2/2] touch foo/.._bar
```

**Comment by jhasse** [comment]
Feel free to reopen after the steps have been provided.
