### ISSUE TITLE
error: command 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin\nvcc.exe' failed with exit code 1

### ISSUE THREAD

**Issue by China-pzy** [ninja-build/ninja#2381]
输入命令：python setup.py develop 
env：openpcdet配置环境
报错：
D:\anaconda\envs\eye\lib\site-packages\torch\include\c10/util/Optional.h(411): note: 查看对正在编译的 类 模板 实例化“c10::constexpr_storage_t<T>”的引用
        with
        [
            T=std::vector<at::Tensor,std::allocator<at::Tensor>>
        ]
D:\anaconda\envs\eye\lib\site-packages\torch\include\c10/util/Optional.h(446): warning C4624: “c10::trivially_copyable_optimization_optional_base<T>”: 已将析构函数隐式定义为“已删除”
        with
        [
            T=std::vector<at::Tensor,std::allocator<at::Tensor>>
        ]
D:\anaconda\envs\eye\lib\site-packages\torch\include\pybind11\detail/common.h(152): warning C4005: “HAVE_SNPRINTF”: 宏重 定义
D:\anaconda\envs\eye\include\pyerrors.h(315): note: 参见“HAVE_SNPRINTF”的前一个定义
"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin\nvcc" -c pcdet\ops\iou3d_nms\src/iou3d_nms_kernel.cu -o build\temp.win-amd64-cpython-38\Release\pcdet\ops\iou3d_nms\src/iou3d_nms_kernel.obj -ID:\anaconda\envs\eye\lib\site-packages\torch\include -ID:\anaconda\envs\eye\lib\site-packages\torch\include\torch\csrc\api\include -ID:\anaconda\envs\eye\lib\site-packages\torch\include\TH -ID:\anaconda\envs\eye\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\include" -ID:\anaconda\envs\eye\include -ID:\anaconda\envs\eye\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=iou3d_nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --use-local-env
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.6\\bin\\nvcc.exe' failed with exit code 1     

Package             Version      Editable project location
------------------- ------------ --------------------------------------------------------------------
ccimport            0.4.2
certifi             2024.2.2
charset-normalizer  3.3.2
cmake               3.28.1
colorama            0.4.6
contourpy           1.1.1
cumm-cu113          0.4.11
cumm-cu117          0.4.11
cycler              0.12.1
easydict            1.11
fire                0.5.0
fonttools           4.47.2
idna                3.6
imageio             2.33.1
importlib-metadata  7.0.1
importlib-resources 6.1.1
joblib              1.3.2
kiwisolver          1.4.5
kornia              0.5.2
lark                1.1.9
llvmlite            0.39.1
matplotlib          3.7.4
networkx            3.1
ninja               1.11.1.1
numba               0.56.4
numpy               1.20.0
packaging           23.2
pccm                0.4.11
pillow              10.2.0
pip                 23.3.1
portalocker         2.8.2
protobuf            4.25.2
pybind11            2.11.1
pyparsing           3.1.1
python-dateutil     2.8.2
PyWavelets          1.4.1
pywin32             306
PyYAML              6.0.1
requests            2.31.0
scikit-image        0.15.0
scikit-learn        1.3.2
scipy               1.9.1
setuptools          68.2.2
SharedArray         1.2          c:\users\desktop\sharednumpyarray-master\sharednumpyarray-master
six                 1.16.0
spconv-cu117        2.3.6
tensorboardX        2.6.2.2
termcolor           2.4.0
threadpoolctl       3.2.0
tifffile            2023.7.10
torch               1.13.1+cu116
torchaudio          0.13.1+cu116
torchvision         0.14.1+cu116
tqdm                4.66.1
typing_extensions   4.9.0
urllib3             2.2.0
wheel               0.41.2
zipp                3.17.0

**Comment by China-pzy** [comment]
![Uploading 1706866518049.jpg…]()

**Comment by jhasse** [comment]
not a ninja issue
