### ISSUE TITLE
`compile_commands.json` does not use absolute paths for the compiler

### ISSUE THREAD

**Issue by deribaucourt** [ninja-build/ninja#2383]
This is a cross-post between meson and ninja.  It's not clear which tool should expand the compiler path to an absolute path. See discussion on Meson: https://github.com/mesonbuild/meson/issues/12834

**Describe the bug**
The generated `compile_commands.json` copies the name of the compiler as it can be found in the `$PATH`. According to the [LLVM specification](https://clang.llvm.org/docs/JSONCompilationDatabase.html): *"All paths specified in the command or file fields must be either absolute or relative to this directory"*. Because the command relies on `$PATH`, it is not possible to replay the compilation database if a different environment is used. I encountered this limitation when working with an external cross-compilation SDK. The meson workspace was configured inside the SDK environment and I'd like to replay the compilation in an IDE that doesn't source the SDK environment. I need absolute paths for this.

**To Reproduce**
I used the [gtk-doc test-case](https://github.com/mesonbuild/meson/tree/master/test%20cases/frameworks/10%20gtk-doc) as an example. I ran meson and ninja to produce `compile_commands.json` inside the build directory. The `command` field references the compiler without an absolute path:
```
[{ "directory": "/home/deribaucourt/Workspace/yocto-vscode/meson/test cases/frameworks/10 gtk-doc/builddir",
    "command": "cc -Ilibfoo.so.p -I. -I.. -Iinclude -I../include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -g -fPIC -MD -MQ libfoo.so.p/foo.c.o -MF libfoo.so.p/foo.c.o.d -o libfoo.so.p/foo.c.o -c ../foo.c",
    "file": "../foo.c",
    "output": "libfoo.so.p/foo.c.o" }]
```

**Expected behavior**
`compile_commands.json` should contain the absolute compiler path instead of relying on `$PATH` to improve portability and respect the specification from LLVM:
`"command": "cc` => `"command": "/usr/bin/cc`

I had a look at the Meson and Ninja code myself to try to find a solution, but I need some pointers from the maintainers. My guess is that we need to resolve the compiler path before passing it to ninja. A less obtrusive way would be to only edit the .json file as a post processing phase.

**system parameters**
* The issue is noticeable when cross-compiling mostly, but can be easily reproduced on native builds (by looking at the command field)
* Ubuntu 22.04
* Python 3.10.12
* Meson 0.61.2
* Ninja 1.10.1

**Comment by digit-google** [comment]
This is very interesting, but I believe using paths relative to the directory where Ninja runs, or to the current PATH value is completely in-spec here.

Your use case is very specific, and should be served more easily by writing a custom tool to rewrite the content of the compile_commands.json for your IDE environment instead (by turning paths into absolulte ones, whenever possible).

Note that in general, this is not something that Ninja can handle reliably. For example, my project's build system injects multipe wrapper scripts before each compilation command, which look like this in the generated Ninja manifest:

```
rule compile_cxx
  command = path/to/wrapper1 <wrapper1_args> -- path/to/wrapper2 <wrapper2_args> -- <compilation command>
```

The point of each wrapper is to perform a different thing from the compilation command (e.g. `wrapper2` sends the compilation command to a remote builder, while `wrapper1` checks that output files do not include unexpected absolute paths that would break our shared caches. And here Ninja doesn't have enough information to translate some of the tool paths to absolute ones here.

**Comment by deribaucourt** [comment]
Thanks for your answer,
Indeed, if I reconfigure my tool to invoke meson with an absolute path in meson.cross, then the output of ninja in `compile_commands.json` ends up with an absolute path as well. It's more appropriate than editing the .json after hand in my use case.
Your wrapper example also shows that ninja doesn't necessarily have the information to handle reproducing the initial environment and expects that the compile commands are invoked in the same one. It makes sense. I'll also keep that example in mind, I may have to use wrappers as well ;)

**Comment by digit-google** [comment]
Oh, yes, having the generator provide absolute paths works well too.

For the record, certain generators, such as [GN](https://gn.googlesource.com/gn/) can also emit the `compile_commands.json` directly, and sometimes have extra configuration options to format its content.

**Comment by zwnewton** [comment]
I used clangd, which also doesn't find the desired compiler. So how do you let meson write absolute path to the compile_commands.json?

> Thanks for your answer, Indeed, if I reconfigure my tool to invoke meson with an absolute path in meson.cross, then the output of ninja in `compile_commands.json` ends up with an absolute path as well. It's more appropriate than editing the .json after hand in my use case. Your wrapper example also shows that ninja doesn't necessarily have the information to handle reproducing the initial environment and expects that the compile commands are invoked in the same one. It makes sense. I'll also keep that example in mind, I may have to use wrappers as well ;)

**Comment by deribaucourt** [comment]
> I used clangd, which also doesn't find the desired compiler. So how do you let meson write absolute path to the compile_commands.json?
> 
Hello @zwnewton, in my case I changed the environment variables providing C and CXX to contain the absolute path before invoking meson. You should try to edit whatever is providing relative commands to meson to provide absolute paths.

**Comment by printfdebugging** [comment]
Hi, I also still see various relative paths in the generated `compile_commands.json` file. I compile a lot of projects which use a mix of Autotools, CMake & Meson. CMake + Ninja generate a json file with absolute paths while meson does not. I think this is an issue with meson? 

Meson generates a build.ninja with relative paths CMake's build.ninja has absolute paths. Let me confirm with meson devs on the matrix channel...
