### ISSUE TITLE
error loading build.ninja, no such file or directory

### ISSUE THREAD

**Issue by dogger7** [ninja-build/ninja#2397]
I am currently trying to compile aseprite's source code, but it isn't exactly going as planned, when running ninja with or without the attribute of aseprite, I get this error:

`ninja: error: loading 'build.ninja': No such file or directory`

This is annoying because it stops the entire build process, how can I either make this file or find a workaround?

**Comment by digit-google** [comment]
This error message means you are running Ninja in a directory that doesn't have a `build.ninja` file, which is normally generated by another generator look such as CMake or Meson. Maybe you forgot to run such a tool.

This doesn't seem a Ninja problem. I suggest you contact the aseprite development team instead.
