### ISSUE TITLE
Ninja: Windows10 Filename longer than 260 characters

### ISSUE THREAD

**Issue by cctv130** [ninja-build/ninja#2400]
Currently using absolute paths causes this error on windows platforms, and the problem still exists.

https://gitlab.kitware.com/cmake/cmake/-/issues/22435

**Comment by cristianadam** [comment]
Note that the real problem here might be the command line size limitation on Windows. See https://learn.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/command-line-string-limitation

> The maximum length of the string that you can use at the command prompt is 8191 characters.

For static libraries `lib.exe` is called, and for dynamic libraries `link.exe` is called.

You can check in `build.ninja` file to see how big the command line for each case is.

**Comment by bradking** [comment]
Ninja is just running the commands that the generator gives to it.  This issue belongs purely on the CMake side, and IMO should be closed here.

**Comment by jhasse** [comment]
for the 260 char problem, see #1900

**Comment by DmitryFX** [comment]
Same problem. When I try to run
`pip install xformers==0.0.26.post1`
I get
` ninja: error: Stat(V:/TEMP/pip-install-lou3njk7/xformers_4a5fc5efae7b42e1831104cf6a0f89e6/build/temp.win-amd64-cpython-312/Release/TEMP/pip-install-lou3njk7/xformers_4a5fc5efae7b42e1831104cf6a0f89e6/third_party/flash-attention/csrc/flash_attn/src/flash_fwd_split_hdim128_bf16_sm80.obj): Filename longer than 260 characters`

But I can't change the path to make it shorter. It's fully automatic process.

**Comment by vaibhavdhake123** [comment]
ninja: error: Stat(...): Filename longer than 260 characters

**Comment by SidneyLann** [comment]
why not truncate the fileName less than 260 chars, nobody want to look for a solution!

**Comment by h1nson** [comment]
Download the latest Ninja release from the [official repository](https://github.com/ninja-build/ninja/releases)
Replace the existing ninja.exe in $SDK_PATH$\cmake\$CMAKE_VERSION$\bin with the newly downloaded version

**Comment by h1nson** [comment]
> why not truncate the fileName less than 260 chars, nobody want to look for a solution!

Download the latest Ninja release from the [official repository](https://github.com/ninja-build/ninja/releases)
Replace the existing ninja.exe in $SDK_PATH$\cmake\$CMAKE_VERSION$\bin with the newly downloaded version

**Comment by h1nson** [comment]
> ninja: error: Stat(...): Filename longer than 260 characters

Download the latest Ninja release from the [official repository](https://github.com/ninja-build/ninja/releases)
Replace the existing ninja.exe in $SDK_PATH$\cmake\$CMAKE_VERSION$\bin with the newly downloaded version

**Comment by SidneyLann** [comment]
Ok. Thanks.
