### ISSUE TITLE
[windows clang++] multiple rules generate capstone.lib 

### ISSUE THREAD

**Issue by cctv130** [ninja-build/ninja#2403]
![4aab7e804b5592c9047872002c131a7](https://github.com/ninja-build/ninja/assets/133784576/8504cb71-43ba-4a01-be85-4fd9446a027f)
[build.txt](https://github.com/ninja-build/ninja/files/14729674/build.txt)

**Comment by jhasse** [comment]
Looks like a CMake bug. Please report it here: https://gitlab.kitware.com/cmake/cmake
