### ISSUE TITLE
Issue with re2c

### ISSUE THREAD

**Issue by SSHUSSAIN-86** [ninja-build/ninja#2404]
I am getting this issue with re2c. The build was okay sometime ago. Please help resolve this!

C:\ninja>python configure.py --bootstrap
bootstrapping ninja...
warning: A compatible version of re2c (>= 0.15.3) was not found; changes to src/*.in.cc will not affect your build.
depfile_parser.cc
c:\ninja\src\depfile_parser.h(18): fatal error C1083: Cannot open include file: 'string': No such file or directory
when running:  cl  /nologo /Zi /W4 /WX /wd4530 /wd4100 /wd4706 /wd4244 /wd4512 /wd4800 /wd4702 /wd4819 /wd4127 /wd4355 /wd4091 /GR- /Zc:__cplusplus /wd4267 /DNOMINMAX /D_CRT_SECURE_NO_WARNINGS /D_HAS_EXCEPTIONS=0 /DNINJA_PYTHON="python.exe" /FS /Ox /DNDEBUG /GL -I. -c .\src\depfile_parser.cc /Fobuild\depfile_parser.obj /Fdbuild\ninja.pdb
Traceback (most recent call last):
  File "C:\ninja\configure.py", line 509, in <module>
    re2c_objs += cxx(name, variables=cxxvariables)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ninja\configure.py", line 284, in cxx
    return n.build(built(name + objext), 'cxx', src(name + '.cc'), **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ninja\configure.py", line 166, in build
    self._run_command(self._expand(cmd, local_vars))
  File "C:\ninja\configure.py", line 191, in _run_command
    subprocess.check_call(cmdline, shell=True)
  File "C:\Users\syedsheh\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cl  /nologo /Zi /W4 /WX /wd4530 /wd4100 /wd4706 /wd4244 /wd4512 /wd4800 /wd4702 /wd4819 /wd4127 /wd4355 /wd4091 /GR- /Zc:__cplusplus /wd4267 /DNOMINMAX /D_CRT_SECURE_NO_WARNINGS /D_HAS_EXCEPTIONS=0 /DNINJA_PYTHON="python.exe" /FS /Ox /DNDEBUG /GL -I. -c .\src\depfile_parser.cc /Fobuild\depfile_parser.obj /Fdbuild\ninja.pdb' returned non-zero exit status 2.

**Comment by digit-google** [comment]
The error message `Cannot open include file: 'string': No such file or directory` means that your C++ compiler is not properly configured. This is failing to compile an `#include <string>` statement, which loads a header from the C++ standard library. The compiler cannot find it for some reason.

**Comment by jhasse** [comment]
Most likely you need to run in a Visual Studio command prompt.
