### ISSUE TITLE
Can't install a package due to "ninja: build stopped: subcommand failed."

### ISSUE THREAD

**Issue by pavelkomarov** [ninja-build/ninja#2409]
Here's a longer description of the issue. https://github.com/clawpack/clawpack/issues/249 I'm not sure whether this is a `ninja` problem, a `meson` problem, or a problem with how they're getting used by `clawpack`.

It appears there are some auto-generated files that aren't getting properly generated, resulting in `FileNotFoundError`s and a build failure. If anyone here has any further ideas, I'd appreciate it.

**Comment by jhasse** [comment]
This doesn't look like a Ninja problem.

**Comment by sandeep-chaturvedi** [comment]
Today I had an error like this, in Android Studio, and I found no solution over internet, While looking for solution I saw a inconsistency in the project

Go **android/app/.cxx** folder, 

```
Note - for checking .cxx as it's a hidden folder.
For window users -  In file explorer, make show hidden files and deleted that folder (**.cxx**), 
For mac users - (cmd + shift + .) Now you can see the hidden files/folders and deleted that folder (**.cxx**), 
```

Then clean the project and that was the solution LOL!
