### ISSUE TITLE
Unable to bootstrap itself in Windows container 

### ISSUE THREAD

**Issue by snpefk** [ninja-build/ninja#2411]
Hi! 

I'm trying to bootstrap LLVM-16 in [Windows containers](https://learn.microsoft.com/en-us/virtualization/windowscontainers/quick-start/run-your-first-container). It successfully builds itself with the system's preinstalled Clang version

```log 
-- The C compiler identification is MSVC 19.29.30154.0
-- The CXX compiler identification is MSVC 19.29.30154.0
-- The ASM compiler identification is MSVC
```

However, when I try to build LLVM-16 with the newly built distribution using clang-cl.exe (which is now a symlink after I updated from LLVM-11), Ninja does not recognize it as an MSVC compiler:

```log
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- The ASM compiler identification is unknown
```

I'm using Ninja 1.11.0 and install `Microsoft.VisualStudio.Workload.VCTools` workload in Visual Studio.

**Comment by digit-google** [comment]
This looks like a CMake issue (these messages come from CMake's builtin detection logic, nothing specific to Ninja here).

**Comment by snpefk** [comment]
Here is more errors 

```log
  The C compiler
    "C:/BuildAgent/work/146ec9ca0430856d/llvm-stage-1/bin/clang-cl.exe"
  is not able to compile a simple test program.
  It fails with the following output:
    Change Dir: 'C:/buildagent/work/146ec9ca0430856d/llvm-stage-2-build/CMakeFiles/CMakeScratch/TryCompile-6oryyf'
    Run Build Command(s): C:/ProgramData/chocolatey/bin/ninja.exe -v cmTC_c4e18
    CreateProcess failed. Command attempted:
    "C:\BuildAgent\work\146ec9ca0430856d\llvm-stage-1\bin\clang-cl.exe    -o CMakeFiles\cmTC_c4e18.dir\testCCompiler.c.obj -c C:\buildagent\work\146ec9ca0430856d\llvm-stage-2-build\CMakeFiles\CMakeScratch\TryCompile-6oryyf\testCCompiler.c"
    ninja: fatal: CreateProcess: The system cannot find the path specified.
```
