### ISSUE TITLE
Tests can't be built with configure.py

### ISSUE THREAD

**Issue by thesamesam** [ninja-build/ninja#2447]
`configure.py` doesn't support building/running tests since https://github.com/ninja-build/ninja/pull/1562.

This is tricky for us downstream, as to run tests (which is something we care about, especially for a critical package like ninja), we would need to use the CMake build - but then we get a circular dependency with e.g. ninja->cmake->jsoncpp->ninja.

Could test support please be restored to `configure.py`?

This is similar to https://github.com/ninja-build/ninja/pull/2423.

**Comment by digit-google** [comment]
I have uploaded a PR to build `ninja_test` with GoogleTest, but this requires a source checkout of the library. (Because probing for an installed version + linking against it is error prone and full of system-specific gotchas, and the CMake build already does that).

**Comment by thesamesam** [comment]
Many thanks @digit-google!
