### ISSUE TITLE
C++ modules not working yet

### ISSUE THREAD

**Issue by MennoVink** [ninja-build/ninja#2457]
I was under the assumption that ninja already supported modules, but i cant get the simplest of module based programs to work. I'm new to ninja as well as cmake modules so maybe i'm doing something wrong?

Here's the module code i cant get to compile:
[cpp_modules.zip](https://github.com/ninja-build/ninja/files/15497644/cpp_modules.zip)

I've tried with Ninja 1.12.0 as well as the master branch but neither work. I'm using these commands (replace the path to where master branch is built):
```
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_MAKE_PROGRAM=PATH_TO_MASTER_BUILD/ninja.exe -G Ninja -B build/
cmake --build build/
```

This fails with:
_helloworld.ixx:2:8: error: header file iostream cannot be imported because it is not known to be a header unit_

Using these commands it does work:
```
cmake -DCMAKE_BUILD_TYPE=Debug -G "Visual Studio 17 2022" -B build/
cmake --build build/
```

**Comment by digit-google** [comment]
Ninja doesn't directly support C++ modules, or other language-specific features. It provides lower-level abstraction that generators like CMake can use to support them.

What you describe seems to be an issue with the Ninja build plan generated by CMake, which supports C++ modules, starting from version 3.28, according to https://cmake.org/cmake/help/latest/manual/cmake-cxxmodules.7.html. Note that header units are not supported, but that doesn't seem the case here.

I recommend you raise an issue on the CMake bug tracker instead.

**Comment by MennoVink** [comment]
Will do, thanks for looking at it 👍
