### ISSUE TITLE
Which pytorch version can ninja 1.12.1 support?

### ISSUE THREAD

**Issue by drxxy98** [ninja-build/ninja#2458]
The question started with the problem I met that "ninja: build stopped: subcommand failed." 
So, I guessed that it might be the version conflict with the pytorch and ninja.
BTW, I am using the torch 2.3.0+cu121
Do you think that's why? Is my torch version too high?
And which pytorch version can ninja 1.12.1 support？
![屏幕截图 2024-06-06 103445](https://github.com/ninja-build/ninja/assets/136697671/5857ec3a-491f-49f7-b3e9-cb67835b9310)

**Comment by eli-schwartz** [comment]
It doesn't really make sense to ask this question here. You should ask the torch project instead.

The error message you posted is anyways missing all the information about what actually failed.
