### ISSUE TITLE
ninja use "-std=gnu++1y" in build.ninja while it's only "set(CMAKE_CXX_STANDARD 17)" in CMakeList.txt

### ISSUE THREAD

**Issue by ziyang-arch** [ninja-build/ninja#2459]
I was trying to build TransformerEngine with `pip install .` 
it gives `fatal error: filesystem: No such file or directory`
while I'm using GCC 11.2.1.
After checking, in the CMakeLists.txt of TransformerEngine it uses `set(CMAKE_CXX_STANDARD 17)` and in build/cmake/build.ninja the build command for some files using `-std=gnu++1y` then it cause the error of cannot find filesystem because it's only fully support in c++17 and needs extra flag in c++14.
I want to know why ninja choose `-std=gnu++1y` when it's `set(CMAKE_CXX_STANDARD 17)` in CMakeLists.txt and how can I force it to c++17.

I'm using ninja 1.10.2 installed from conda.

**Comment by jhasse** [comment]
It was actually CMake who did that, best to ask here: https://stackoverflow.com/questions/ask?tags=cmake
