### ISSUE TITLE
Ninja build edge dirty only when timestamp is newer leads to build not being triggered in some cases

### ISSUE THREAD

**Issue by krolli** [ninja-build/ninja#2463]
We were experimenting with some changes in our CI build processes and we ran into situations where build was not correctly triggered even though files were changed since last time they were built. Investigating it, we tracked the issue down to the way ninja determines whether an output needs to be rebuilt by checking whether any input timestamp is newer than the output timestamp.

While I understand that this is not a typical scenario for developers modifying code, we found out that it can happen in some situations that might not be that uncommon. The two cases where we ran into it are:
1. Restoring files from backup by copying.
2. Configuring version control system (in our case subversion) to set time of last modification to time of last commit that changed the file.

Case 1. is default behavior of Windows `copy` and `xcopy` utilities. Based on my testing, unix `cp` requires `--preserve=timestamps` to result in the same behavior, but I have also noticed some Linux file managers that preserve timestamps when copying files by default.

Case 2. is maybe a little more unusual, but I feel like use-case described in https://github.com/ninja-build/ninja/issues/1459 (ie. switching to a branch and then back) actually benefits from this setting in version control system as well. Note that I didn't check whether VCS other than subversion support this behavior.

For this to work correctly, ninja would have to remember timestamp of each input when last output was produced, and check it against current timestamp of each input. It is definitely not enough to check most recent input timestamp against output timestamp and only triggering an edge if input is newer. I am not sure how much of the infrastructure is already in place to do this, so I can't really say how hard this will be to add or how much of a performance impact it would have.

I tried looking through open issues to see if this has already been brought up, but I didn't find it discussed like this anywhere. I apologize if I missed it.

Would this be a welcome change? To me it feels like a bug that a change in metadata and contents of a file does not trigger build of outputs that depend on it, but maybe there are some good reasons for not doing it.

**Comment by jhasse** [comment]
The good reason is: Performance.

I think the only real and correct fix for this would be using hashes instead of timestamps. See #1459.

**Comment by krolli** [comment]
@jhasse

> I think the only real and correct fix for this would be using hashes instead of timestamps.

I disagree. Content hashes are meant to prevent unnecessary rebuilds (at least that was my understanding of that discussion). In this case, `ninja` does not trigger build when it is necessary.

I agree that performance might be affected by this, but I wouldn't expect that to be anywhere near the impact of hashes (if at all measurable). `ninja` may already end up `stat`ing all input files to determine which one is the most recent, which is what I'd expect to be the most expensive part of the process. Looking at the deps log, it seems that last input timestamps are also already stored and loaded. So isn't the change just about switching the condition and checking all inputs instead of just the most recent one? Or am I missing something? (I admit, I didn't step through it, just read code in some functions)

**Comment by jhasse** [comment]
> Looking at the deps log, it seems that last input timestamps are also already stored and loaded.

Not necessarely, see https://github.com/ninja-build/ninja/issues/2465#issuecomment-2168109927

**Comment by krolli** [comment]
Hmm, I will have to look at `restat` in more detail.

**Comment by digit-google** [comment]
Ninja does not store the timestamp of source files (i.e. inputs without a generating command/edge) _at_ _all_. Both the deps and build logs only store timestamps related to outputs / generated files.

IMO, the feature you are asking goes against the core design of Ninja. Besides, this would require a brand new log file, additional logic to use it and more importantly heuristics to resolve conflicts when the log and file-system do not agree.

Note also that Ninja is already pretty flaky when the build plan changes between invocations (because the build/deps log corresponds to dependencies in the old build graph, not the newest one, and there are cases where this creates broken incremental builds). This change is likely to add even more sources of flakiness.

**Comment by krolli** [comment]
I see. Thank you for the explanation. That indeed sounds like a lot more complicated change than I thought at first, and one that doesn't fit into the big picture.

**Comment by alecazam** [comment]
I still think that ninja could store input timestamps and compare them against the last timestamp for a file.   We also have artists and devs that drop say an old png into a folder, and ninja doesn't pick up on building it.  It's error prone to expect someone to touch a file to get a build system to pick up on the change.

Make didn't have any stored state, so had to stat(src) > stat(dst).   Ninja if it stored an input stat, could do stat(srcName) != savedStatSrc.find(srcName).  Further extension would be a content hash, but the modstamp should be enough to avoid that.
