### ISSUE TITLE
Built targets are still dirty after a successful build

### ISSUE THREAD

**Issue by nre-ableton** [ninja-build/ninja#2473]
When we use ninja to build our software, we run it twice: first to build the actual software, and then a second time afterwards to verify that it no-ops. We do this is because we have a very complex build with several no-code targets and such, and we want to make sure that no targets are still considered dirty even after a successful result. This second no-op pass is achieved by running `ninja -n -d explain` and then failing the build if we don't grep `no work to do` in ninja's output.

As of ninja 1.12.0, our builds now fail this step because ninja outputs the following:

> `ninja explain: recorded mtime of <redacted>.app older than most recent input <redacted>.app/Contents/MacOS/<redacted> (1722997299569634707 vs 1722997299973748395)`
> `ninja explain: <redacted>.app is dirty`

We have about a dozen such targets that fail this test (none of which are no-code targets). The difference in these timestamps varies from a few milliseconds to a few seconds. Looking at the release notes and changelog of 1.12.0, this PR jumped out at me:

- https://github.com/ninja-build/ninja/pull/1943

> If an input is changed, the subsequent run will detect the output as dirty since its recorded mtime reflects when the build command began, not when the output was actually written to disk.

For a no-op build, it seems that this could mistakenly mark a target as dirty, since the mtime would be when the command started and not when the output (ie, none) was written to disk. I'm not terribly familiar with ninja internals, so please forgive me if I'm way off here. :sweat_smile: 

We are running ninja 1.12.0 (we'll update to 1.12.1 later, but not until we figure out what's going on with 1.12.0) on macOS Ventura using Xcode 15.2, in case that matters.

**Comment by nre-ableton** [comment]
Ping @jdrouhard, is there any chance that the changes in https://github.com/ninja-build/ninja/pull/1943 could be responsible for this behavior?

**Comment by nre-ableton** [comment]
It turns out the problem was in our build-system's ninja generator. Sorry for the noise!

**Comment by digit-google** [comment]
Thanks for telling us about it :-)
