### ISSUE TITLE
 ninja build output "regenerating ninja files"

### ISSUE THREAD

**Issue by FCRobben** [ninja-build/ninja#2491]
I use the ninja build chromium mojo(git@github.com:Drecc/chromium-mojo.git), but without a SRC/build/util/LASTCHANGE files.And the gn without error, but nijia build will output "regenerating ninja files". Could the python script be added to check whether the file "LASTCHANGE" exists?
![1](https://github.com/user-attachments/assets/91135467-8b68-40ee-98c6-d74221e1d54a)

**Comment by digit-google** [comment]
This is likely a problem with the GN-generated Ninja build plan. I recommend contacting the Chromium developer mailing list for this.

**Comment by FCRobben** [comment]
yes,close

**Comment by FCRobben** [comment]
oh,Caused by glient sync failed,close
