### ISSUE TITLE
Ninja lost the ability to print compiled file names in the same line

### ISSUE THREAD

**Issue by L00pZBreak3r** [ninja-build/ninja#2499]
Commit [1ba5570807e3ded62c4939ca87f20d8c8696fa46](https://github.com/ninja-build/ninja/commit/1ba5570807e3ded62c4939ca87f20d8c8696fa46) kills ninja's ability to avoid flooding with the names of compiled files.
Old behavior:
![good](https://github.com/user-attachments/assets/80763669-f557-47ca-ac0e-372dc436c73e)

New behavior (after the commit):
![bad](https://github.com/user-attachments/assets/dbbe4749-2fb3-4536-899e-1fe780de22e4)

**Comment by digit-google** [comment]
Thanks for reporting this, it is indeed a major regression. I am surprised we didn't catch it earlier. I have uploaded a fix with a regression test to ensure that does not happen in the future. Sorry about that.
