### ISSUE TITLE
No pre-build event support? How to capture `git describe --dirty`?

### ISSUE THREAD

**Issue by bmcdonnell** [ninja-build/ninja#2500]
I have an embedded C project that builds with CMake, Ninja, and gcc-arm-none-eabi.

I want to capture the output (string) of a `git describe --dirty ...` command as (1) a string variable in my program, and (2) in the generated executable filename. I think the sensible way to do this would be with a pre-build event, which ninja does not appear to support.

Without the `--dirty` argument, I have it working using [this `git_describe` CMake function](https://github.com/rpavlik/cmake-modules/blob/1b450496c5d11fdcad8b000843d0c516e1eaa59f/GetGitRevisionDescription.cmake#L178). But that is only run by CMake at configure time (and it hard codes the output strings in `build.ninja`). So for example, if I just add the `--dirty` arg in my current setup, then CMake configure (on a clean git working tree), then modify a source file (making the worktree dirty), then build again, it does not re-run CMake configure, and does not re-run the `git describe` command, and so does not detect the dirty.

Questions:
1. Am I correct that ninja does not support pre-build events?
2. Is it possible to use ninja to reliably do what I'm describing here? On every build, without requiring the user to manually trigger a CMake configure before triggering the build.

Ideally, I think, I'd want to be able to make ninja execute and  check the output of my preferred `git describe` command on every build, and trigger the dependent targets to rebuild if it changes.

**Comment by digit-google** [comment]
This type of questions are better asked and answered on the mailing list. See https://groups.google.com/group/ninja-build

**Comment by asit-dhal** [comment]
CMake allows you to run commands at build time. Check this documentation [add_custom_command](https://cmake.org/cmake/help/latest/command/add_custom_command.html

**Comment by bmcdonnell** [comment]
@asit-dhal

Discussion here:
https://groups.google.com/g/ninja-build/c/W407yFUY-AM/m/jXMLPY9MAgAJ

I've not yet attempted the various solutions proposed to me there.

I don't believe your proposal will do what I want, since `PRE_BUILD` only executes _pre-build_ for the Visual Studio Generator (as documented on the page you linked).

I guess I'll close this issue, at least for now, pending the outcome on the discussion linked above.
