### ISSUE TITLE
globbing in cmake with ninja, incomplete status log

### ISSUE THREAD

**Issue by jkammerland** [ninja-build/ninja#2507]
Hello

Following https://github.com/microsoft/vscode-cmake-tools/issues/4100

When globbing in cmake

```cmake
file(GLOB_RECURSE TEST_SOURCES CONFIGURE_DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/*.cpp)
target_sources(tests PRIVATE ${TEST_SOURCES})
```

and running `cmake .... -G Ninja`

then `ninja` 

I get 

[0/2] Re-checking globbed directories...
[6/7] Linking CXX executable test/tests

It never goes to [7/7].

Removing the globbing it will go to [6/6] successfully. This is just a debug output issue, the build work fine

**Comment by jhasse** [comment]
I think this is #1336.
