### ISSUE TITLE
elisp save-excursion

### ISSUE THREAD

**Issue by spaette** [ninja-build/ninja#2513]
@mavit 

`https://github.com/ninja-build/ninja/commit/11377a46d103f788982e9a190c50a8526b9a6b80`

Correctly recognize a comment if the previous line is a comment ending in $.
Fanael committed on Nov 23, 2014

If you're so inclined to comment on the following.

Is it a correct interpretation that the `sed` output is referring to Emacs running in text terminals using truncation?

On graphical displays, a small straight arrow in the fringe indicates truncation at either end of the line.

```
$ sed -n '70,71p' ninja/misc/ninja-mode.el
                  ;; Except if the previous line is a comment as well, as the
                  ;; continuation dollar is ignored then.
$ 
```

**Comment by mavit** [comment]
I'm not sure why you're asking me in particular, but no, this is nothing to do with Emacs' display.

It's discussing the fact that, in a `.ninja` file, a `$` at the end of the line is used to indicate that the next line is a continuation of the current line, except if the `$` is part of a comment.  https://ninja-build.org/manual.html#ref_lexer

Hope this helps.

**Comment by spaette** [comment]
you're the most recent contributor to the file

thanks for the clarification, supposing reading the manual is generally advised before opening a ticket

my presumption then would be adding a comment line as below would therefore be superfluous


```diff
                    (not (eq ?$ (char-before)))
+                   ;; https://ninja-build.org/manual.html#ref_lexer
                    ;; Except if the previous line is a comment as well, as the
                    ;; continuation dollar is ignored then.
```

**Comment by spaette** [comment]
@jhasse 

I've had the time to think about the previous comment and the manual's linked to section.

misc/ninja-mode.el

If the lisp function is treating code lines and comment lines differently this makes more sense to me.

```diff
                   (or
-                   ;; If we're continuing the previous line, it's not a
-                   ;; comment.
+                  ;; This is a code line.
                    (not (eq ?$ (char-before)))
-                   ;; Except if the previous line is a comment as well, as the
-                   ;; continuation dollar is ignored then.
+                   ;; This is a comment line, the escape character $ is ignored.
                  (nth 4 (syntax-ppss)))))
```

> `https://ninja-build.org/manual.html#ref_lexer`

doc/manual.asciidoc

I think his might be an improvement in the manual. 

```diff
  There is only one escape character, `$`, and it has the following
  behaviors:

  `$` followed by a newline:: escape the newline (continue the current line
  across a line break).
- 
- `$` followed by text:: a variable reference.
- 
- `${varname}`:: alternate syntax for `$varname`.
  
  `$` followed by space:: a space.  (This is only necessary in lists of
  paths, where a space would otherwise separate filenames.  See below.)
  
  `$:` :: a colon.  (This is only necessary in `build` lines, where a colon
  would otherwise terminate the list of outputs.)
  
  `$$`:: a literal `$`.
+ 
+ An unescaped `$` retains it's ordinary use in shell parameter
+ expansion.
  
  A `build` or `default` statement is first parsed as a space-separated
  list of filenames and then each name is expanded.  This means that
  spaces within a variable will result in spaces in the expanded
  filename.
```

**Comment by jhasse** [comment]
Regarding ninja/misc/ninja-mode.el or anythimg Emacs: Couldn't care less.

> An unescaped `$` retains it's ordinary use in shell parameter expansion.

I don't understand. This section is about Ninja's lexing, why does the shell have anything to do with it?

**Comment by spaette** [comment]
> why does the shell have anything to do with it

...it seems I'm fatigued

The the use of the escape character `$` before the newline (as per the docs) in this .ninja file excerpt is obvious. What I was attempting to address is my reading of `$builddir` involves what for example the bash manual refers to as parameter expansion.

https://ninja-build.org/build.ninja.html

```ninja
root = .
builddir = build
cxx = g++
ar = ar
cflags = -g -Wall -Wextra -Wno-deprecated -Wno-missing-field-initializers $
    -Wno-unused-parameter -fno-rtti -fno-exceptions -fvisibility=hidden $
    -pipe '-DNINJA_PYTHON="python"' -O2 -DNDEBUG -DUSE_PPOLL $
    -DNINJA_HAVE_BROWSE -I.
ldflags = -L$builddir
```

**Comment by musvaage** [comment]
misc/ninja-mode.el

remind the reader what we're doing here

shorten to (end-of-line 0)

```diff
                 (save-excursion
+                ;; This moves to the end of the previous line.
-                  (goto-char (line-end-position 0))
+                  (goto-char (end-of-line 0))
                   (or
```
(1+ (buffer-size)) should be replaced with (point-max)


```diff
              ;; Otherwise we get an `args-out-of-range' error.
-             (unless (= line-end (1+ (buffer-size)))
+             (unless (= line-end (point-max))
                (put-text-property line-end (1+ line-end) 'syntax-table '(12)))))))))
```

an author/maintainer might clarify why they don't change the syntax of $ to "escape" and of \n to "end of comment"

tho (and presumably set `comment-end-can-be-escaped`)

**Comment by monnier** [comment]
It shouldn't be `(goto-char (end-of-line 0))` but `(end-of-line 0)`.

@mavit: Why did you say "except if the $ is part of a comment"?  I don't see such an exception in the spec you pointed to.  IOW, AFAICT, if a comment line ends in `$`, then the next line is still part of the comment.

**Comment by musvaage** [comment]
@evmar

Are you OK with updating the ninja mode file?

**Comment by mavit** [comment]
@monnier asked:

> @mavit: Why did you say "except if the $ is part of a comment"? I don't see such an exception in the spec you pointed to. IOW, AFAICT, if a comment line ends in `$`, then the next line is still part of the comment.

My understanding was that this takes priority:

> Comments begin with # and extend to the end of the line.

**Comment by monnier** [comment]
>> @mavit: Why did you say "except if the $ is part of a comment"? I don't
>> see such an exception in the spec you pointed to.  IOW, AFAICT, if
>> a comment line ends in `$`, then the next line is still part of
>> the comment.
>
> My understanding was that this takes priority:
>> Comments begin with # and extend to the end of the line.

Ah, I see.  You read "the line" to mean "the physical line" whereas
I read it to mean "the logical line possibly spread over several
physical lines".  The joys of prose specifications.  🙂
When you think how easy it is to specify lexers formally, it's a shame.

In any case if `$` is given "escape" syntax, then this is simply
controlled by `comment-end-can-be-escaped`.

**Comment by spaette** [comment]
_cf_: https://github.com/ninja-build/ninja/issues/2513#issuecomment-2406162272

doc/manual.asciidoc

Presenting "escape character, `$`," as exhibiting a behavior in regards to parameter expansion still seems off.

As it stands there seems now to have been added to this ticket clarification and references on how to update the file.

**Comment by evmar** [comment]
> @evmar
> 
> Are you OK with updating the ninja mode file?

I last touched this twelve years ago, I remember nothing!

Looks like @Hi-Angel is the most recent person to touch this file, so maybe they could provide a useful comment.

**Comment by Hi-Angel** [comment]
> > @evmar
> > Are you OK with updating the ninja mode file?
> 
> I last touched this twelve years ago, I remember nothing!
> 
> Looks like @Hi-Angel is the most recent person to touch this file, so maybe they could provide a useful comment.

Please open a PR and link to it from here for review. I see multiple things being discussed in the thread, it'd be easier to review the actual code 😊 But I'm in favor of "end-of-line" and "point-max" changes if that's what the question is about.

FWIW, I'm pretty sure there's more to refactor, it's a pretty old code that's been touched by many different people. I personally only added indentation support to the mode, and fixed a minor highlighting bug. But I'd be happy to provide review, no problem.

**Comment by musvaage** [comment]
consensus seems to be that "end-of-line" and "point-max"  changes (https://github.com/ninja-build/ninja/issues/2513#issuecomment-2435757184) are to be implemented

doesn't matter who opens a pull on that

> In any case if `$` is given "escape" syntax, then this is simply
> controlled by `comment-end-can-be-escaped`.

what remains is whether this quote is actionable, and if so how to implement that change in the elisp file

**Comment by musvaage** [comment]
> more to refactor

@girzel

I'd be curious of your comments if you have the time to look over the code.
