### ISSUE TITLE
AOSP 9.0 cannot compile

### ISSUE THREAD

**Issue by enessmr** [ninja-build/ninja#2518]
Hi. I use arch btw and I used latest version of ninja and the version of ninja that comed out at AOSP 9.0 release.
Log: (not a common message, but google did not work)
`[hyprlanduser@archuser aosp-9.0]$ lunch 52

============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=9
TARGET_PRODUCT=p4wifi
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm
TARGET_ARCH_VARIANT=armv7-a
TARGET_CPU_VARIANT=generic
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-6.11.5-arch1-1-x86_64-Arch-Linux
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=PPR1.180610.009
OUT_DIR=out
============================================
[hyprlanduser@archuser aosp-9.0]$ make recoveryimage
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=9
TARGET_PRODUCT=p4wifi
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm
TARGET_ARCH_VARIANT=armv7-a
TARGET_CPU_VARIANT=generic
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-6.11.5-arch1-1-x86_64-Arch-Linux
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=PPR1.180610.009
OUT_DIR=out
============================================
[1/1] out/soong/.minibootstrap/minibp out/soong/.bootstrap/build.ninja
[55/56] glob prebuilts/ndk/stl.bp
[77/77] out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
out/build-p4wifi-cleanspec.ninja is missing, regenerating...
out/build-p4wifi.ninja is missing, regenerating...
[566/937] including system/sepolicy/Android.mk ...
system/sepolicy/Android.mk:79: warning: BOARD_SEPOLICY_VERS not specified, assuming current platform version
[937/937] including vendor/samsung/p4wifi/proprietary/vendor/lib/Android.mk ...
build/make/core/Makefile:28: warning: overriding commands for target `out/target/product/p4wifi/system/etc/permissions/android.software.live_wallpaper.xml'
build/make/core/base_rules.mk:412: warning: ignoring old commands for target `out/target/product/p4wifi/system/etc/permissions/android.software.live_wallpaper.xml'
[  1% 12/707] glob /overlay/**/*
ninja: error: rebuilding 'out/combined-p4wifi.ninja': Error writing to deps log: Success
19:57:33 ninja failed with: exit status 1

#### failed to build some targets (38 seconds) ####

[hyprlanduser@archuser aosp-9.0]$ `

Why?

**Comment by jhasse** [comment]
this is not a support forum.

**Comment by enessmr** [comment]
thanks

i will use that binary proably months later cause i stopped aosp 9.0 ( ͡° ͜ʖ ͡°)╭∩╮ myself

**Comment by enessmr** [comment]
Compiling andriod 1.6 for p4...
Will use Google's meson & ninja.

**Comment by enessmr** [comment]
Well...
Did AOSP 9.0 but...
The error again.
