### ISSUE TITLE
ninja -v  not works!

### ISSUE THREAD

**Issue by yaoyutian** [ninja-build/ninja#2536]
ninja --version works,but ninja -v not!！
torch /cpp_extension /_run_ninja_build/command[ninja ,-v],not compiling.
confusing.

OS:ubuntu 24.04
ninja version :1.21.1

![image](https://github.com/user-attachments/assets/ba1ed750-c7df-4d28-bd09-5699462db23d)

![image](https://github.com/user-attachments/assets/d1f672de-062e-4781-8a54-6b3d07370e9b)

**Comment by digit-google** [comment]
This is working as intended. As explained in the `--help` output that you even provided, but did not care to read, the `-v` flag is a synonym for `--verbose` and impact Ninja's output during the build. It has nothing to do with the version.

In the initial example you gave, the error message corresponds to the normal error that occurs when you launch Ninja in a directory that does not contain a `build.ninja` plan. In the final screenshot, the error comes from a failed build command.
