### ISSUE TITLE
Please do not use uppercase header. use dbghelp.h instead. Cross compiling always needs lowercase header.

### ISSUE THREAD

**Issue by trcrsired** [ninja-build/ninja#2542]
```cpp
/home/cqwrteur/toolchains_build/ninja/src/minidump-win32.cc:18:10: fatal error: 'DbgHelp.h' file not found
   18 | #include <DbgHelp.h>
      |          ^~~~~~~~~~~
1 error generated.
```

https://github.com/trcrsired/windows-msvc-sysroot/tree/main/include

**Comment by jhasse** [comment]
PR welcome :)

Regarding mt.exe: I'm not sure how to fix that.

**Comment by zufuliu** [comment]
`DbgHelp.h` is the Windows SDK header name, lower case `dbghelp.h` is the mingw-w64 name.
![image](https://github.com/user-attachments/assets/d99214c0-eebc-4a1e-bbc3-08feef8d1b30)

`minidump-win32.cc` is only enabled for MSVC target, maybe you can try GNU target (`aarch64-w64-windows-gnu`) instead?
https://github.com/ScintillaOrg/ninja-build/ninja/9d31ebba91515097e64184ca5bd460f6a7d6dfe5/src/minidump-win32.cc#L15-L20

**Comment by trcrsired** [comment]
> `DbgHelp.h` is the Windows SDK header name, lower case `dbghelp.h` is the mingw-w64 name. ![image](https://private-user-images.githubusercontent.com/2289926/395857947-d99214c0-eebc-4a1e-bbc3-08feef8d1b30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMjQ4NzksIm5iZiI6MTczNDMyNDU3OSwicGF0aCI6Ii8yMjg5OTI2LzM5NTg1Nzk0Ny1kOTkyMTRjMC1lZWJjLTRhMWUtYmJjMy0wOGZlZWY4ZDFiMzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTZUMDQ0OTM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjA0MmZlMjFmMDg0NDQ2ZjJlMTE5YTYyYjBkYWViMWIzZGVmZDkxMTNlN2JlMDMyMzAwYTEzYmZhOTg3NmNjMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.83n5k-71S7o_K7JJFsjvlZOLa8r9Nv6fR12SCcb9l-k)
> 
> `minidump-win32.cc` is only enabled for MSVC target, maybe you can try GNU target (`aarch64-w64-windows-gnu`) instead?
> 
> https://github.com/ninja-build/ninja/blob/9d31ebba91515097e64184ca5bd460f6a7d6dfe5/src/minidump-win32.cc#L15-L20

That is the problem. Cross-compiling Windows MSVC target is impossible unless you make the header lowercase. For, Windows case does not matter but it matters for linux.

I am using msvc's target for the same behavior as gcc or it just fails to compile

**Comment by trcrsired** [comment]
https://github.com/trcrsired/windows-msvc-sysroot/blob/main/include/dbghelp.h
@zufuliu 
Everything must be lowercase since even Microsoft is not consistent with their own shit

**Comment by trcrsired** [comment]
Regarding the mt.exe issue, it was caused by llvm-mt requiring libxml2 as a dependency, which I hadn't built. This oversight was entirely my own, as confirmed by the LLVM team.

**Comment by trcrsired** [comment]
@zufuliu Also ninja uses ```windows.h```, based on your logic, you should use ```Windows.h``` instead.

Just use lowercase header and it should all be okay. Plus I think $ARCH-windows-gnu targets can also use this minidump. I will submit a PR

**Comment by trcrsired** [comment]
I have submitted a PR #2545

**Comment by trcrsired** [comment]
See:
https://github.com/trcrsired/windows-msvc-sysroot
https://github.com/trcrsired/llvm-releases/releases

**Comment by zufuliu** [comment]
> based on your logic, it should use `Windows.h` instead.

tested clang with [-Wnonportable-include-path](https://clang.llvm.org/docs/DiagnosticsReference.html#wnonportable-include-path), it does not warn on change file case, so PR #2545 is OK to me.
