### ISSUE TITLE
Use sub-1s resolution in timestamps

### ISSUE THREAD

**Issue by evmar** [ninja-build/ninja#371]
There's a pull request here that implements it:
https://github.com/martine/ninja/pull/337

However, the timing changes are mixed in with other unrelated changes, so finishing this bug will involve extracting that logic.

**Comment by nirbheek** [comment]
We're hitting this in [Meson](/mesonbuild/meson) when timestamps are within 200ms of each other. What's blocking Ninja from moving to millisecond-resolution granularity in timestamp checking? How can we help with this?

**Comment by mathstuf** [comment]
I think the issue is that no one has extracted the relevant bits from #337 into its own PR.

**Comment by nirbheek** [comment]
Okay, thanks, I'll work on that then. :)

**Comment by QuLogic** [comment]
Ping? This is making Meson testing painfully slow as it needs to wait 1 second on every test just to be sure ninja will work. And there's a PR available...
