### ISSUE TITLE
Shortcomings of current quoting scheme for $in/$out

### ISSUE THREAD

**Issue by sorbits** [ninja-build/ninja#390]
1. The `$in` and `$out` variables are quoted at too low a level meaning internally ninja ends up working with quoted strings even when not given to `sh -c "…"`, e.g. if we have:
   
   ```
   rule build
     command = $cc $flags -o $out -MMD -MF $out.d $in
     depfile = $out.d
   ```
   
   And `$out` is `some file.cc` then ninja internally will work with `"some file.cc".d` which effectively has the depfile ignored.
2. Wrapping `$in` and `$out` in double-quotes is not sufficient as double-quoted shell strings can contain both variables, dollar-expressions, and command substitutions.
3. While `$in` and `$out` are magically handled, it’s unclear how to deal with potential problematic characters in other variables such as `$builddir`.
4. Sometimes we actually don’t want to quote `$in` or `$out`. For example with a rule like this:
   
   ```
   rule build
     command = $cc $flags -o $out -MMD -MF $out.d $in
     depfile = $out.d
     description = Building ‘$out’…
   ```
   
   This will produce output text like: _Building ‘"some file.cc"’…_ which is aesthetically unpleasing.

**Comment by jhasse** [comment]
If I understand it correctly this is fixed by 7cb65617bdad38eab397b1049ed9ea95b4db6799 now, correct? If not, please reopen.
