### ISSUE TITLE
-C option creates unwanted chdir message, add -q quiet option (patch attached)

### ISSUE THREAD

**Issue by rgeary1** [ninja-build/ninja#420]
The -C option creates a "Changing to X directory" message which can't be suppressed. For our use case, ninja is part of a larger build process where this message isn't relevant. Since I can't use grep -v or sed  on the ninja output without losing the smart screen formatting, I've added a -q quiet option (patch below).
If someone else has another use for a quiet option later, it could be extended to take a number value as a quietness level.
This could be solved in other ways, this is just one solution.

From 1d11fc53cb4181199c065f138bc8513469ae1d7e Mon Sep 17 00:00:00 2001
From: Richard Geary richardg.work@gmail.com
Date: Fri, 14 Sep 2012 05:41:37 -0400
Subject: [PATCH 1/1] Add quiet -q option to suppress changedir message when using -C option
## Change-Id: I12f1bf232e29786e6699cbe9b0724425e7dcb0ff

 src/ninja.cc |   10 +++++++---
 1 files changed, 7 insertions(+), 3 deletions(-)

diff --git a/src/ninja.cc b/src/ninja.cc
index ad56f1c..9a7ac8b 100644
--- a/src/ninja.cc
+++ b/src/ninja.cc
@@ -106,7 +106,7 @@ void Usage(const BuildConfig& config) {
 "options:\n"
 "  --version  print ninja version (\"%s\")\n"
 "\n"
-"  -C DIR   change to DIR before doing anything else\n"
+"  -C DIR   change to DIR before doing anything else. Use -q to supress directory change notification.\n"
 "  -f FILE  specify input build file [default=build.ninja]\n"
 "\n"
 "  -j N     run N jobs in parallel [default=%d]\n"
@@ -726,6 +726,7 @@ int NinjaMain(int argc, char*\* argv) {
   const char\* input_file = "build.ninja";
   const char\* working_dir = NULL;
   string tool_name;
-  bool printChdir = true;
  
  setvbuf(stdout, NULL, _IOLBF, BUFSIZ);

@@ -740,7 +741,7 @@ int NinjaMain(int argc, char*\* argv) {

   int opt;
   while (tool_name.empty() &&
-         (opt = getopt_long(argc, argv, "d:f:hj:k:l:nt:vC:V", kLongOptions,
-         (opt = getopt_long(argc, argv, "d:f:hj:k:l:nt:vC:Vq", kLongOptions,
                           NULL)) != -1) {
   switch (opt) {
     case 'd':
  @@ -785,6 +786,9 @@ int NinjaMain(int argc, char*\* argv) {
     case 'C':
       working_dir = optarg;
       break;
-      case 'q':
-        printChdir = false;
-        break;
     case OPT_VERSION:
       printf("%s\n", kVersion);
       return 0;
  @@ -815,7 +819,7 @@ int NinjaMain(int argc, char*\* argv) {
   // subsequent commands.
   // Don't print this if a tool is being used, so that tool output
   // can be piped into a file without this string showing up.
-    if (!tool)
-    if (!tool && printChdir)
     printf("ninja: Entering directory `%s'\n", working_dir);
   if (chdir(working_dir) < 0) {
     Fatal("chdir to '%s' - %s", working_dir, strerror(errno));
  -- 
  1.7.4.1

**Comment by jhasse** [comment]
Fixed by #1968.
