### ISSUE TITLE
Duplicate header deps in gcc depfiles

### ISSUE THREAD

**Issue by evmar** [ninja-build/ninja#423]
I noticed multiple instances of the same header in a local depfile.  I haven't yet tracked down why this occurs.  See also #418.

**Comment by Lekensteyn** [comment]
This occurs whenever the deps command generates duplicate dependencies. Can we just require non-duplicate entries from the command for simplicity?

build.ninja
```
rule gen
  command = echo "$out: x.h x.h" > $out.d && touch $out
  deps = gcc
  depfile = $out.d
build x: gen
```

Output of `ninja -t deps`
```
x: #deps 2, deps mtime 1508637043 (VALID)
    x.h
    x.h
```

**Comment by mathstuf** [comment]
Couldn't the input list be deduped when reading as well (with a warning available for it possibly?). Though I think the logic pending #1534 seems to dedupe anyways. I now get this:

```
x: #deps 1, deps mtime 1580311346270505630 (VALID)
    x.h

```

**Comment by mathstuf** [comment]
@jhasse Seems like this can be closed as well.
