### ISSUE TITLE
g_metrics pointer is leaked

### ISSUE THREAD

**Issue by tfarina** [ninja-build/ninja#444]
We dynamic allocate it in src/ninja.cc:600, but I don't see we ever deleting it anywhere.

**Comment by jpsainfeld** [comment]
If this issue has been on the books since 2012, is there a way to mark it resolved or 
not worth fixing?

**Comment by jonesmz** [comment]
I suspect that this is an explicit wontfix. I recall seeing in at least one place in the ninja codebase that it prefers to simply exit than to do any cleanup, since the OS will free the allocated memory much easier than the program will.

@jhasse thoughts?

**Comment by jhasse** [comment]
yes
