### ISSUE TITLE
Use SetConsoleTextAttribute on Windows to simulate color

### ISSUE THREAD

**Issue by evmar** [ninja-build/ninja#486]
Rather than stripping ANSI codes, we could implement them.  Not sure if that serves a user need but it would at least be a cool hack.

Suggested by TheOneRing on IRC.

**Comment by nico** [comment]
Clang can output ansi on windows by passing `-fcolor-diagnostics -fansi-escape-codes`.

Currently, ninja strips them in cygwin (where they would work) because that terminal isn't detected as smart, and ninja prints them in cmd.exe (where they don't work – it'd be cool if ninja could interpret them and make them do the right thing).

**Comment by sgraham** [comment]
I have ansicon installed in cmd, and I noticed after I did that some tools started magically outputting color. Maybe there's some easy way to probe for that.

**Comment by sgraham** [comment]
Hmm, maybe not, https://github.com/ggreer/the_silver_searcher/blob/master/src/options.c just does getenv("ANSICON"). The other one was 'less', didn't look at its code.

**Comment by nico** [comment]
`-fcolor-diagnostics -fansi-escape-codes` + ansicon already works today. However, I'd guess that most people don't use ansicon, and I feel it'd be nice if things just worked without requiring everyone to get ansicon (?)

**Comment by sgraham** [comment]
Yes that would be nice, I don't think ansicon is very popular (and I've found it crashes cmd occasionally too).

Interpreting ANSI and outputting using console functions sgtm if you think that belongs in ninja.

**Comment by jhasse** [comment]
Now that Windows supports ANSI codes natively, I'm closing this in favor of #1462.
