### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [ninja-build/ninja#509]
I have looked at a few source files for your current software. I have noticed that some checks for return codes are missing.

Would you like to add more error handling for return values from functions like the following?
- [setvbuf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/setvbuf.html) ⇒ [BuildLog::OpenForWrite](https://github.com/martine/ninja/blob/7d41c2f521e27a3c2891e6f1c8da42f0f6f3c266/src/build_log.cc#L110)
- [printf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html) ⇒ [State::Dump](https://github.com/martine/ninja/blob/13dd08c1a03e5a8f4299816fbd3af1b6cb6d9642/src/state.cc#L193)

**Comment by jonesmz** [comment]
@elfring Is this still an issue?

If so, could you make a PR?

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by jhasse** [comment]
Definitely good to check as often as it makes sense. Checking the return value of printf is too much though IMHO.

**Comment by elfring** [comment]
Thanks for [your small source code adjustment](https://github.com/ninja-build/ninja/commit/d45ff8ebf88ef4add46a80ccdfc2d97a8b4b091b "Check return value of setvbuf()").

* I suggest to care also for file output failures.
* How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") for this software?

**Comment by jhasse** [comment]
I've added static analysis in #1768, but had to revert due to GitHub Actions shipping a messed up version of Ubuntu. I will revisit the PR using Docker.
