### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [ninja-build/ninja#511]
I find the use of the variable "[SubprocessSet::interrupted_](https://github.com/martine/ninja/blob/d8d3b2f0bdee4cd3d801bcd19bf65f91fb6760e0/src/subprocess-posix.cc#L150)" questionable because of the data type "bool". I recommend to change its data type to "[sig_atomic_t](https://www.securecoding.cert.org/confluence/display/seccode/SIG31-C.+Do+not+access+shared+objects+in+signal+handlers)".

I suggest also to reconsider the implementation detail about the use of "SetInterruptedFlag" and "NotifyInterrupted" as [static member functions](https://github.com/martine/ninja/blob/a46abb1011cbf99bf9752bc440246dd5c1cb5a9a/src/subprocess.h#L86) for the intended purpose. Does the class "SubprocessSet" need a different design for [portable signal handling](http://lazarenko.me/2013/01/15/how-not-to-write-a-signal-handler/)?

**Comment by jonesmz** [comment]
@elfring Could you make a PR?

@jhasse Help Wanted tag?

**Comment by jhasse** [comment]
Too many unanswered questions.

**Comment by elfring** [comment]
Would you like to consider other software design options?
- [sigwaitinfo()](http://pubs.opengroup.org/onlinepubs/9699919799/functions/sigwaitinfo.html)
- [Self-pipe trick](http://cr.yp.to/docs/selfpipe.html)

**Comment by jhasse** [comment]
I'm not sure what the issue is exactly?

**Comment by elfring** [comment]
Do you understand the initial clarification request?

**Comment by jhasse** [comment]
Yeah somewhat. Are we talking about a theoretical problem though or a bug that manifests in the wild because of this?

**Comment by elfring** [comment]
:thought_balloon: Would more developers become interested to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/bugprone/signal-handler.html "Checking the application of signal handler functions")?

**Comment by jhasse** [comment]
We're using clang-tidy already :)

**Comment by elfring** [comment]
Do such source code analysis tools point any remaining issues out for further development considerations? :thinking:

**Comment by jhasse** [comment]
We only have a few checks enabled: https://github.com/ninja-build/ninja/blob/master/.clang-tidy
See for example this PR which fixes a check and adds it to the configuration so that we don't regress: #1790

**Comment by elfring** [comment]
>We only have [a few checks enabled](https://github.com/ninja-build/ninja/blob/29b8f161b42530a15d82f242dcfff941b1c03039/.clang-tidy#L2 "Update candidate")

:crystal_ball: Will the support grow for any more adjustment opportunities (besides readability items)?
