### ISSUE TITLE
Sometimes bogus "multiple rules generate" warning

### ISSUE THREAD

**Issue by rchl** [ninja-build/ninja#543]
Ninja can output this warning:

ninja: warning: multiple rules generate [foo]. build will not be correct; continuing anyway

The problem is that it doesn't warn based on the target that was selected to be build but based on target 'all'. When having two targets, foo and bar, both generating same files but not being dependent on each other then nothing wrong should really happen when building. Ninja will still raise a warning when building any of them.

It could probably analyze dependencies of the target that was requested to be build and only raise warning if conflicting target is actually gonna be compiled too.

**Comment by advancedwebdeveloper** [comment]
Still a bug for me, while compiling libunwind (LLVM 10.0.1)
