### ISSUE TITLE
Show subcommand output as it happens when only running one command

### ISSUE THREAD

**Issue by dabrahams** [ninja-build/ninja#545]
Output buffering is awesome…  …but only when there's actual parallelism.  For example, a cmake build often contains a bottleneck process that runs all the tests (sometimes in many threads, but ctest manages its own output).  If output wasn't buffered, we'd be able to watch a nice progress graph.  As things stand, we only get the graph when the build is finished.

**Comment by Qix-** [comment]
Sorry to gravedig 7 years later, but this is the top Google result.

Starting in CMake 3.2, you can use `USES_TERMINAL` (or `JOB_POOL console` starting in 3.15, but preferably the first one) option of `add_custom_command()` to specify Ninja uses the `console` pool.

**Comment by bruce-optibrium** [comment]
Your gravedig was very welcome - turned my [stackoverflow question](https://stackoverflow.com/questions/76005036/flush-the-output-of-ninja-on-windows/76005037#76005037) into an answer.
