### ISSUE TITLE
depfiles parser can't handle windows paths (with colons for drive letters)

### ISSUE THREAD

**Issue by ScottSheehan** [ninja-build/ninja#56]
In my usage, depfiles didn't handle things like c:\foo well. I think ninja is expecting the format to be ident: ident+ newline. ":" is not an identifier char. I worked around this by treating quoted entities as identifiers for makefile_flavor only. 

I'm not sure if depfiles was intended _solely_ for gcc, which I'm not using. If it is I'd recommend making the depfiles rule key mention gcc specifically (i.e. gccdepfiles), and have a generic ninja-controlled format for depfiles [if depfiles are smiled upon].

**Comment by zlolik** [comment]
Hi, I am trying to use ninja with compiler for Texas Instruments DSP TMS320C6726. 
Ninja can't handle paths with semicolons and **spaces**!
For example:
`.\FCM_datasets.o: FCM_datasets.c \`
`"ds_Group.h" \`
`"dataset_types.h" \`
`"c:\Program Files (x86)\C6000 Code Generation Tools 6.0.13\include\stddef.h" \`
`"../hw/hw_define.h"`
Output of **ninja -d explain**
`ninja explain: output Program of phony edge with no inputs doesn't exist
ninja explain: Program is dirty
ninja explain: output Files of phony edge with no inputs doesn't exist
ninja explain: Files is dirty
ninja explain: output (x86)/C6000 of phony edge with no inputs doesn't exist
ninja explain: (x86)/C6000 is dirty
ninja explain: output Code of phony edge with no inputs doesn't exist
ninja explain: Code is dirty
ninja explain: output Generation of phony edge with no inputs doesn't exist
ninja explain: Generation is dirty
ninja explain: output Tools of phony edge with no inputs doesn't exist
ninja explain: Tools is dirty
ninja explain: output 6.0.13/include/stddef.h of phony edge with no inputs doesn't exist
ninja explain: 6.0.13/include/stddef.h is dirty`
By the way I wrote AWK program to convert dependency file, cause it generated like this: 
`.\FCM_datasets.o: FCM_datasets.c`
`.\FCM_datasets.o: ds_Group.h`
`.\FCM_datasets.o: dataset_types.h`
`.\FCM_datasets.o: c:\Program Files (x86)\C6000 Code Generation Tools 6.0.13\include\stddef.h`
`.\FCM_datasets.o: ../hw/hw_define.h`
AWK program source:
`BEGIN {
  level = 0
}
/.*:/{
  if (level == 0) {
    print $0 " \\" > out
    level = 1
  } else {
    if (line != "") {
      print "\"" line "\"" " \\" > out
    }
    line = $2
    for (i = 3; i <= NF; i++) {
      line = line " " $i
    }
  }
}
END{
  if (level != 0) {
    level = 0
    print line > out
  }
}`

**Comment by zlolik** [comment]
Usually system headers in compiler folder are not changed, so I decided cut lines with letter "c:".
New AWK program:
`BEGIN {
  level = 0
}
/.*:/{
  if (level == 0) {
    print $0 " \\" > out
    level = 1
  } else {
    if (line != "") {
      print line " \\" > out
    }
    split($2,a,":")
    if ((a[1] == "c") || (a[1] == "d") ) {
      line = ""
    } else {
      line = $2
      for (i = 3; i <= NF; i++) {
        line = line " " $i
      }
    }
  }
}
END{
  if (level != 0) {
    level = 0
    print line > out
  }
}`

**Comment by martine** [comment]
(Sorry for not closing this old bug, which I think is obsolete.)

Ninja's parser for depfiles attempts to match the parser used by Make, which doesn't allow you to quote paths in the way you invented here.  Most resources I see with an online skim say that Make doesn't support paths with spaces.  Here's a nice overview:

http://www.cmcrossroads.com/article/gnu-make-meets-file-names-spaces-them

However, taking a look at the parser code, it looks like you might be able to write spaces in your paths by escaping them with a backslash.
https://github.com/ninja-build/ninja/blob/master/src/depfile_parser.in.cc#L17

**Comment by zlolik** [comment]
Thanks, martine! Your mention about spaces was really helpful. I have rewrote awk script to handle spaces and now **ninja v1.6.0 works ok with colons for drives**. Dep files look like this:
```
./Release/flashlib_c.obj: ../hw/flashlib_c.cpp \
..\hw\hw_common.h \
..\hw\hw_define.h \
C:/Program\ Files\ (x86)/C6000\ Code\ Generation\ Tools\ 6.0.13/include/assert.h \
C:/Program\ Files\ (x86)/C6000\ Code\ Generation\ Tools\ 6.0.13/include/limits.h \
..\hw\hw_types.h
```
and messages from `ninja -d explain`:
```
ninja explain: output Release/flashlib_c.obj older than most recent input C:/Program Files (x86)/C6000 Code Generation Tools 6.0.13/include/limits.h (480271925 vs 480271983)
ninja explain: Release/flashlib_c.obj is dirty
```
Finally, awk script:
```
BEGIN {
  level = 0
}
/.*:/{
  if (level == 0) {
    print $0 " \\" > out
    level = 1
  } else {
    if (line != "") {
      print line " \\" > out
    }
    line = $2
    for (i = 3; i <= NF; i++) {
      line = line "\\ " $i
    }
  }
}
END{
  if (level != 0) {
    level = 0
    print line > out
  }
}
```
