### ISSUE TITLE
add overrides of file-level variables via ninja command line

### ISSUE THREAD

**Issue by ghost** [ninja-build/ninja#602]
It is often useful to use a single script which can be dynamically configured using command-line arguments. For instance:

ninja compile CFLAGS=-gProf
or
ninja all releaseVersion=1.0.2,assertionsDisabled=false

**Comment by jcelerier** [comment]
>  If you change a command line flag you'll have to recompile everything anyways

that's not true : right now I'm having the case of a gigantic codebase for which I  want to add `-fdiagnostics-color=always` to the compilation flags: this doesn't alter the binaries in any way, only the compiler's stdout. So it should definitely not incur a full rebuild.
