### ISSUE TITLE
crosscompile linux->win32 fails with "CreateProcess failed: The system cannot find the file specified."

### ISSUE THREAD

**Issue by abma** [ninja-build/ninja#618]
cross-compiling doesn't work (on linux):

export CC=i686-mingw32-gcc CXX=i686-mingw32-g++ AR=i686-mingw32-ar
python2.7  ./bootstrap.py --platform=mingw
Building ninja manually...
Building ninja using itself...
wrote build.ninja.
Application tried to create a window, but no driver could be loaded.
Make sure that your X server is running and that $DISPLAY is set correctly.
err:systray:initialize_systray Could not create tray window

FAILED: re2c -b -i --no-generation-date -o src/depfile_parser.cc src/depfile_parser.in.cc
CreateProcess failed: The system cannot find the file specified.

FAILED: re2c -b -i --no-generation-date -o src/lexer.cc src/lexer.in.cc
CreateProcess failed: The system cannot find the file specified.

FAILED: i686-mingw32-g++ -MMD -MT build/build.o -MF build/build.o.d -g -Wall -Wextra -Wno-deprecated -Wno-unused-parameter -fno-rtti -fno-exceptions -pipe -Wno-missing-field-initializers -DNINJA_PYTHON="python2.7" -O2 -DNDEBUG -D_WIN32_WINNT=0x0501 -c src/build.cc -o build/build.o
CreateProcess failed: The system cannot find the file specified.

FAILED: i686-mingw32-g++ -MMD -MT build/build_log.o -MF build/build_log.o.d -g -Wall -Wextra -Wno-deprecated -Wno-unused-parameter -fno-rtti -fno-exceptions -pipe -Wno-missing-field-initializers -DNINJA_PYTHON="python2.7" -O2 -DNDEBUG -D_WIN32_WINNT=0x0501 -c src/build_log.cc -o build/build_log.o
CreateProcess failed: The system cannot find the file specified.

FAILED: i686-mingw32-g++ -MMD -MT build/clean.o -MF build/clean.o.d -g -Wall -Wextra -Wno-deprecated -Wno-unused-parameter -fno-rtti -fno-exceptions -pipe -Wno-missing-field-initializers -DNINJA_PYTHON="python2.7" -O2 -DNDEBUG -D_WIN32_WINNT=0x0501 -c src/clean.cc -o build/clean.o
CreateProcess failed: The system cannot find the file specified.

FAILED: i686-mingw32-g++ -MMD -MT build/deps_log.o -MF build/deps_log.o.d -g -Wall -Wextra -Wno-deprecated -Wno-unused-parameter -fno-rtti -fno-exceptions -pipe -Wno-missing-field-initializers -DNINJA_PYTHON="python2.7" -O2 -DNDEBUG -D_WIN32_WINNT=0x0501 -c src/deps_log.cc -o build/deps_log.o
CreateProcess failed: The system cannot find the file specified.

FAILED: i686-mingw32-g++ -MMD -MT build/disk_interface.o -MF build/disk_interface.o.d -g -Wall -Wextra -Wno-deprecated -Wno-unused-parameter -fno-rtti -fno-exceptions -pipe -Wno-missing-field-initializers -DNINJA_PYTHON="python2.7" -O2 -DNDEBUG -D_WIN32_WINNT=0x0501 -c src/disk_interface.cc -o build/disk_interface.o
CreateProcess failed: The system cannot find the file specified.

FAILED: i686-mingw32-g++ -MMD -MT build/edit_distance.o -MF build/edit_distance.o.d -g -Wall -Wextra -Wno-deprecated -Wno-unused-parameter -fno-rtti -fno-exceptions -pipe -Wno-missing-field-initializers -DNINJA_PYTHON="python2.7" -O2 -DNDEBUG -D_WIN32_WINNT=0x0501 -c src/edit_distance.cc -o build/edit_distance.o
CreateProcess failed: The system cannot find the file specified.

FAILED: i686-mingw32-g++ -MMD -MT build/eval_env.o -MF build/eval_env.o.d -g -Wall -Wextra -Wno-deprecated -Wno-unused-parameter -fno-rtti -fno-exceptions -pipe -Wno-missing-field-initializers -DNINJA_PYTHON="python2.7" -O2 -DNDEBUG -D_WIN32_WINNT=0x0501 -c src/eval_env.cc -o build/eval_env.o
CreateProcess failed: The system cannot find the file specified.

FAILED: i686-mingw32-g++ -MMD -MT build/explain.o -MF build/explain.o.d -g -Wall -Wextra -Wno-deprecated -Wno-unused-parameter -fno-rtti -fno-exceptions -pipe -Wno-missing-field-initializers -DNINJA_PYTHON="python2.7" -O2 -DNDEBUG -D_WIN32_WINNT=0x0501 -c src/explain.cc -o build/explain.o
CreateProcess failed: The system cannot find the file specified.

FAILED: i686-mingw32-g++ -MMD -MT build/graph.o -MF build/graph.o.d -g -Wall -Wextra -Wno-deprecated -Wno-unused-parameter -fno-rtti -fno-exceptions -pipe -Wno-missing-field-initializers -DNINJA_PYTHON="python2.7" -O2 -DNDEBUG -D_WIN32_WINNT=0x0501 -c src/graph.cc -o build/graph.o
CreateProcess failed: The system cannot find the file specified.

FAILED: i686-mingw32-g++ -MMD -MT build/graphviz.o -MF build/graphviz.o.d -g -Wall -Wextra -Wno-deprecated -Wno-unused-parameter -fno-rtti -fno-exceptions -pipe -Wno-missing-field-initializers -DNINJA_PYTHON="python2.7" -O2 -DNDEBUG -D_WIN32_WINNT=0x0501 -c src/graphviz.cc -o build/graphviz.o
CreateProcess failed: The system cannot find the file specified.

FAILED: i686-mingw32-g++ -MMD -MT build/line_printer.o -MF build/line_printer.o.d -g -Wall -Wextra -Wno-deprecated -Wno-unused-parameter -fno-rtti -fno-exceptions -pipe -Wno-missing-field-initializers -DNINJA_PYTHON="python2.7" -O2 -DNDEBUG -D_WIN32_WINNT=0x0501 -c src/line_printer.cc -o build/line_printer.o
CreateProcess failed: The system cannot find the file specified.

FAILED: i686-mingw32-g++ -MMD -MT build/manifest_parser.o -MF build/manifest_parser.o.d -g -Wall -Wextra -Wno-deprecated -Wno-unused-parameter -fno-rtti -fno-exceptions -pipe -Wno-missing-field-initializers -DNINJA_PYTHON="python2.7" -O2 -DNDEBUG -D_WIN32_WINNT=0x0501 -c src/manifest_parser.cc -o build/manifest_parser.o
CreateProcess failed: The system cannot find the file specified.

FAILED: i686-mingw32-g++ -MMD -MT build/metrics.o -MF build/metrics.o.d -g -Wall -Wextra -Wno-deprecated -Wno-unused-parameter -fno-rtti -fno-exceptions -pipe -Wno-missing-field-initializers -DNINJA_PYTHON="python2.7" -O2 -DNDEBUG -D_WIN32_WINNT=0x0501 -c src/metrics.cc -o build/metrics.o
CreateProcess failed: The system cannot find the file specified.

FAILED: i686-mingw32-g++ -MMD -MT build/state.o -MF build/state.o.d -g -Wall -Wextra -Wno-deprecated -Wno-unused-parameter -fno-rtti -fno-exceptions -pipe -Wno-missing-field-initializers -DNINJA_PYTHON="python2.7" -O2 -DNDEBUG -D_WIN32_WINNT=0x0501 -c src/state.cc -o build/state.o
CreateProcess failed: The system cannot find the file specified.

FAILED: i686-mingw32-g++ -MMD -MT build/util.o -MF build/util.o.d -g -Wall -Wextra -Wno-deprecated -Wno-unused-parameter -fno-rtti -fno-exceptions -pipe -Wno-missing-field-initializers -DNINJA_PYTHON="python2.7" -O2 -DNDEBUG -D_WIN32_WINNT=0x0501 -c src/util.cc -o build/util.o
CreateProcess failed: The system cannot find the file specified.

FAILED: i686-mingw32-g++ -MMD -MT build/version.o -MF build/version.o.d -g -Wall -Wextra -Wno-deprecated -Wno-unused-parameter -fno-rtti -fno-exceptions -pipe -Wno-missing-field-initializers -DNINJA_PYTHON="python2.7" -O2 -DNDEBUG -D_WIN32_WINNT=0x0501 -c src/version.cc -o build/version.o
CreateProcess failed: The system cannot find the file specified.

FAILED: i686-mingw32-g++ -MMD -MT build/subprocess-win32.o -MF build/subprocess-win32.o.d -g -Wall -Wextra -Wno-deprecated -Wno-unused-parameter -fno-rtti -fno-exceptions -pipe -Wno-missing-field-initializers -DNINJA_PYTHON="python2.7" -O2 -DNDEBUG -D_WIN32_WINNT=0x0501 -c src/subprocess-win32.cc -o build/subprocess-win32.o
CreateProcess failed: The system cannot find the file specified.

FAILED: i686-mingw32-g++ -MMD -MT build/includes_normalize-win32.o -MF build/includes_normalize-win32.o.d -g -Wall -Wextra -Wno-deprecated -Wno-unused-parameter -fno-rtti -fno-exceptions -pipe -Wno-missing-field-initializers -DNINJA_PYTHON="python2.7" -O2 -DNDEBUG -D_WIN32_WINNT=0x0501 -c src/includes_normalize-win32.cc -o build/includes_normalize-win32.o
CreateProcess failed: The system cannot find the file specified.

FAILED: i686-mingw32-g++ -MMD -MT build/msvc_helper-win32.o -MF build/msvc_helper-win32.o.d -g -Wall -Wextra -Wno-deprecated -Wno-unused-parameter -fno-rtti -fno-exceptions -pipe -Wno-missing-field-initializers -DNINJA_PYTHON="python2.7" -O2 -DNDEBUG -D_WIN32_WINNT=0x0501 -c src/msvc_helper-win32.cc -o build/msvc_helper-win32.o
CreateProcess failed: The system cannot find the file specified.

FAILED: i686-mingw32-g++ -MMD -MT build/msvc_helper_main-win32.o -MF build/msvc_helper_main-win32.o.d -g -Wall -Wextra -Wno-deprecated -Wno-unused-parameter -fno-rtti -fno-exceptions -pipe -Wno-missing-field-initializers -DNINJA_PYTHON="python2.7" -O2 -DNDEBUG -D_WIN32_WINNT=0x0501 -c src/msvc_helper_main-win32.cc -o build/msvc_helper_main-win32.o
CreateProcess failed: The system cannot find the file specified.

FAILED: i686-mingw32-g++ -MMD -MT build/getopt.o -MF build/getopt.o.d -g -Wall -Wextra -Wno-deprecated -Wno-unused-parameter -fno-rtti -fno-exceptions -pipe -Wno-missing-field-initializers -DNINJA_PYTHON="python2.7" -O2 -DNDEBUG -D_WIN32_WINNT=0x0501 -c src/getopt.c -o build/getopt.o
CreateProcess failed: The system cannot find the file specified.

FAILED: i686-mingw32-g++ -MMD -MT build/ninja.o -MF build/ninja.o.d -g -Wall -Wextra -Wno-deprecated -Wno-unused-parameter -fno-rtti -fno-exceptions -pipe -Wno-missing-field-initializers -DNINJA_PYTHON="python2.7" -O2 -DNDEBUG -D_WIN32_WINNT=0x0501 -c src/ninja.cc -o build/ninja.o
CreateProcess failed: The system cannot find the file specified.
ninja: build stopped: subcommand failed.

**Comment by jonesmz** [comment]
@jhasse Given CMake can now be used to build Ninja, is this bug still worth addressing?

**Comment by jhasse** [comment]
Yes, cross-compiling worked with CMake the last time I've tried.
