### ISSUE TITLE
Race condition with mspdbsrv sometimes causes Windows builds to fail.

### ISSUE THREAD

**Issue by cpizano** [ninja-build/ninja#620]
the pdb symbols are not written by the linker, are written by the pdb server and ninja being very parallel can cause the following error as seen in chromium's waterfall

FAILED: ninja -t msvc -e environment.x64 -- "C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\bin\amd64\cl.exe" /nologo /showIncludes /FC @obj\build\libphonenumber_without_metadata.precompile.obj.rsp /c ....\build\precompile.cc /Foobj\build\libphonenumber_without_metadata.precompile.obj /Fdobj\third_party\libphonenumber\libphonenumber_without_metadata.pdb 
c1xx : fatal error C1033: cannot open program database 'c:\b\build\slave\cr-win-rel-x64\build\src\out\release_x64\obj\third_party\libphonenumber\libphonenumber_without_metadata.pdb'
ninja: build stopped: subcommand failed.

The solution is to run ninja again. By that time the mspdb would have finished and the file can now be accessed.

Some background links:

http://connect.microsoft.com/VisualStudio/feedback/details/132753/mspdbsrv-holds-on-to-file-handles-resulting-in-fatal-error-c1033-cannot-open-program-database

http://social.msdn.microsoft.com/Forums/vstudio/en-US/b1d1bceb-06b6-47ef-a0ea-23ea752e0c4f/mspdbsrv-reference-page

http://blogs.msdn.com/b/ravi_kumar/archive/2009/06/17/my-2-cents-on-mspdbsrv-exe.aspx

**Comment by Knitschi** [comment]
Are there any news if this got fixed in recent visual studio versions?

**Comment by nico** [comment]
We worked around this with this https://codereview.chromium.org/88303004 and haven't seen the issue since. Maybe you can do something similar?

**Comment by dmerejkowsky** [comment]
@nico: do you know if CMake implemented a similar workaround ?

**Comment by Knitschi** [comment]
I don't have any .c files in my codebase. So either I had a different problem or it is not only caused by having .c and .cc files at the same time.

**Comment by nico** [comment]
@dmerejkowsky I do not know.
@Knitschi Then this bug here isn't your bug :-) You could try using /Z7 and /debug:fastlink if you're using a recent MSVC. Then you don't use mspdbsrv at all and link times might still be bearable.

**Comment by Knitschi** [comment]
@nico Ok thank you. I think for now I will just use MsBuild when using MSVC to sidestep possible problems.
