### ISSUE TITLE
Makefile -> build.ninja; is that even possible?

### ISSUE THREAD

**Issue by IngwiePhoenix** [ninja-build/ninja#680]
Hello there!

I have to say, I really love ninja for how it works, and how easily one can just create their own build files. I am currently working on a project which can create a configure script that outputs build.ninja instead.

But in that process, I have come across a question: Is it even possible to convert existing makefiles to ninja files? I just tried to `ninja -f Makefile` within a PHP source tree. Appearently, ninja doesnt handle `$(command)`'s.

So, is there a way how one could convert from Makefile to build.ninja? One option is just to parse the output of `make --dry-run` and pack all the commands line by line into  a ninja build file - but as you can honestly recognize, that is absolutely no way to go XD.

So yeah, is there a way to convert a Makefile to build.ninja?

Kind regards, Ingwie!

**Comment by nico** [comment]
Zombie comment: https://github.com/google/kati is (was?) used by Android and compiles (some) makefiles to ninja.
