### ISSUE TITLE
Support color in NINJA_STATUS

### ISSUE THREAD

**Issue by mathstuf** [ninja-build/ninja#713]
It would be nice if ninja understood color natively. Currently, I have a wrapper script which tests stdout for being a terminal and changes NINJA_STATUS accordingly. The problem is that ninja doesn't know that the color escape sequences are really zero-width when printed on the terminal and causes elision to happen at improper places.

**Comment by mqudsi** [comment]
Why not just hard-code an ignore for ansi escape codes (or at least ansi escape color codes) when counting the characters?

This seems to be going about it the hard way, adding complexity both to the code and to the language. Current situation: no ansi codes are supported in `JOB_STATUS`. If we go with a hard-coded patch for ansi color codes, the situation becomes no ansi codes aside from ansi color codes are supported in `JOB_STATUS` but with zero additional cost or complexity (aside from a change to the status length counter function).

**Comment by jhasse** [comment]
> Why not just hard-code an ignore for ansi escape codes (or at least ansi escape color codes) when counting the characters as #912 is trying to do?

Yes, that sounds like the best idea. Ideally that counting should only be done once (when parsing `NINJA_STATUS`) and not in `ElideMiddle`.

> Current situation: no ansi codes are supported in JOB_STATUS.

It's supported:

```sh
env $'NINJA_STATUS=\x1b[32m[%f/%t] \x1b[0m' ninja
```

The problem is `EllideMiddle`.

**Comment by mathstuf** [comment]
To do the count once, a map of console width to string length would be necessary. But it is possible to elide it as long as the `description` never contains ANSI escape sequences. If it does support that, you need to figure out `ConsoleWidth` every call.

**Comment by mathstuf** [comment]
See #1584.

**Comment by mathstuf** [comment]
Sorry, I meant #1494.
