### ISSUE TITLE
Root bug for outstanding display/output issues/requests

### ISSUE THREAD

**Issue by fischman** [ninja-build/ninja#746]
As of now these are the open ninja issues that have to do with status display or ninja output.  Listing them in hopes of a cohesive plan forming.

curses-based rule progress indicator #717 
Support color in NINJA_STATUS #713
print "still waiting" for long running commands if we serialize on them #678 
Address FIXME: Add --no-strip-ansi-escapes option #672
Throttle rate of output messages #663
Use ANSI escapes to output to Cygwin-based terminals #659
Proposed/still running #629
Add NINJA_SMART_TERMINAL environment variable, with on, off, and hide_newline options #581
Use SetConsoleTextAttribute on Windows to simulate color #486
Add a `-q` "quiet" option. #480
Automatically use pager for failed output #413
"smart" output (e.g. overprinting) doesn't work under cygwin #374
Slow down on big tool output #326
Feature request -- print elapsed time #267
Show progress when waiting #111

**Comment by nico** [comment]
#916 asks for what #672 is implementing.

**Comment by nicolasdespres** [comment]
Ninja output into dumb terminal is not machine parsable #1010

**Comment by nicolasdespres** [comment]
Print successful command along with their output. #658

**Comment by nicolasdespres** [comment]
Support table status a la Buck build system: #1020

**Comment by colincross** [comment]
Print output file on failure #1033

**Comment by martine** [comment]
Make width of failure printouts configurable. #606

**Comment by nicolasdespres** [comment]
Print commands when they start: #1158

**Comment by jhasse** [comment]
I think a nice way to fix all these is by adding support for external frontends. Check out the PR by colincross: https://github.com/ninja-build/ninja/pull/1210

The PR implements the point @nicolasdespres said:

> To complete this list I think Ninja should provide enough control on its
output so that an external program, such as GUI for instance, could easily
turn Ninja's textual output into a more structured graphical display.

I've extended Colin's Python command line frontend which you can use with the PR which already fixes some of the other points (e.g. color) raised here. https://bixense.com/ja/

**Comment by nicolasdespres** [comment]
I would like to renew the proposition I have made above in this thread on June, 5th 2014 to use only a limited set of environment variables to configure Ninja's output. I think this is enough and have a small impact on Ninja's codebase while giving all the power to external scripts to do what they need to build nice frontend. That would preserve Ninja's philosophy to do one thing well and remain fast by delegating the work.

**Comment by fischman** [comment]
I've been out of the ninja game for years so unsubscribing from this.  Feel free to close if no longer useful, or @ me if you want me to see a followup.

**Comment by jhasse** [comment]
I've created a label and added all the bugs and PRs from here that are still opened: https://github.com/ninja-build/ninja/issues?q=label%3Afrontend
