### ISSUE TITLE
Ninja adds extra CR to subprocess output on Windows yielding CR CR LF

### ISSUE THREAD

**Issue by cdbennett** [ninja-build/ninja#773]
Ninja 1.4.0 on Windows is adding an extra CR character to any CRLF line endings in output produced by a subprocess, so that lines are terminated with CR CR LF.

This is causing Eclipse (CodeWarrior 10.5, to be precise) to have trouble parsing the compiler warning and error messages.

This test case has two .c programs designed to be compiled with MinGW gcc which print "Hello, World" with a newline. But one program changes the mode of stdout to binary so that the MinGW stdio library does not convert the \n to a \r\n.

[Test case: ninja_extra_cr_test](https://github.com/cdbennett/ninja_extra_cr_test)
A self-contained test case for Ninja which uses MinGW gcc to build two programs, one which produces LF and one CRLF line endings output, and shows how Ninja is adding an extra CR to the CRLF output:

**Comment by Optiligence** [comment]
This is also an issue here: https://bugreports.qt.io/browse/QTCREATORBUG-14177.

**Comment by cdbennett** [comment]
@nico I pushed two branches with pull requests that both solve the problem.  One by stripping extra CR characters, and the other based on your above patch that writes to `stdout` in binary mode on Windows.

I can see some possible advantages to each option.

**Comment by nico** [comment]
Thanks! I kind of like the "set output to binary" version best, I think. What do you think?

**Comment by martine** [comment]
I also like "set output to binary".  Ninja shouldn't even need to care about the newline format of the text output by its subprocesses -- it just wants to buffer and pass the bytes through.  So the fewer conversions/text processing the better.

**Comment by nico** [comment]
#1156 should've fixed this.
