### ISSUE TITLE
DiskInterface::Stat() needs to deal with inconvenient mtimes

### ISSUE THREAD

**Issue by fischman** [ninja-build/ninja#795]
DiskInterface::Stat() today returns the mtime of existing files, 0 for missing files, and -1 on error.
Unfortunately stat(2)'s mtime is a time_t which can legitimately be 0 or negative (on ubuntu, for example, it's a signed long) so DiskInterface::Stat() needs to either be respecified (to return missing/error info in a different param) or else needs to fudge its returned value to avoid having to rewrite callers.

**Comment by nico** [comment]
Due to the work of letting failing stat() calls abort the build, it's now feasible to abort on mtimes <= 0. Maybe we should just do that.

**Comment by fischman** [comment]
@nico assuming your comment of 6min ago is a "yes" to my Aug 25, 2014 comment above, then SGTM.

**Comment by nico** [comment]
I've been working on this nonstop for the last half year, these things take time! :-P

**Comment by nico** [comment]
Enough people ended up needing support for inputs with mtime 0 that we added support for that in #1120
