### ISSUE TITLE
Ninja/cmake/clang does not track dependencies correctly.

### ISSUE THREAD

**Issue by SirVer** [ninja-build/ninja#796]
Okay, brace yourself. This cost me 5h to track down. 

I have a repro case in https://github.com/SirVer/cmake_dependency_bug. If I clone this and run:

```
> mkdir build          
> cd build             
> cmake -G Ninja ..
-- The C compiler identification is AppleClang 5.0.0.5000279
-- The CXX compiler identification is AppleClang 5.0.0.5000279
-- Check for working C compiler using: Ninja
-- Check for working C compiler using: Ninja -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler using: Ninja
-- Check for working CXX compiler using: Ninja -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/sirver/Desktop/cmake_deps_problems/build

> ninja blub      
[2/2] Linking CXX static library src/library/libblub.a

> mvim ../src/library/a.h
# do modifications.
> ninja blub 
ninja: no work to do.
```

Since `a.cc` includes `a.h` this is obviously wrong. It should be rebuild.

Following observations:

1) gcc 4.9 with ninja tracks the dependency correctly
2) clang/gcc4.9 with makefile generation tracks the dependency correctly
3) Cmakelists.txt uses a wrappermacro for setting the include file path for a target. If you do not use the macro, but use `target_include_directories` directly, it tracks the dependency correctly too.

I am at a loss and need help.

**Comment by laurentcau** [comment]
Hi,
We are also using CMake+Clang+Ninja on linux and it seems we have related issue. 
It seems one of our system header has been updated but not detected and it makes the build fail:
```
fatal error: file '/usr/include/asm-generic/errno-base.h' has been modified since the precompiled header '.../Imagery.dir/cmake_pch.hxx.pch' was built: mtime changed (was 1688996036, now 1692019868)
note: please rebuild precompiled header '.../Imagery.dir/cmake_pch.hxx.pch'
```
Do you know a workaround for that ?

**Comment by alecazam** [comment]
Still happening even with -MD, so I think this is some clang timestamp bug on linux with pch.  We're not using -Isystem either, so I did check that.  This header hasn't changed, and the timestamp is older than the .pch generated.  So this shouldn't be getting flagged.  It's like whatever timestamp the pch file originally wrote is wrong, so then it thinks that one file is stale on next compile with the cached pch.  errno-base.h is in the deps (.d) file.

```
fatal error: fatal error: file '/usr/include/asm-generic/errno-base.h' has been modified since the precompiled header '../../../Foo/SystemPrecompiled-Bar.h.pch' was built: mtime changed (was 1744435980, now 1747513711)

file '/usr/include/asm-generic/errno-base.h' has been modified since the precompiled header '../../../Foo/SystemPrecompiled-Bar.h.pch' was built: mtime changed (was 1744435980, now 1747513711)
```
