### ISSUE TITLE
Non-ASCII characters should be allowed in filenames for dependency files.

### ISSUE THREAD

**Issue by DemiMarie** [ninja-build/ninja#811]
Currently, Ninja does not allow non-ASCII characters (> 127) in dependency files (It treats them as whitespace). This breaks dependencies for those using D or Python and are using non-ASCII filenames, such as UTF-8.

I consider this to be a bug, as it is a rather arbitrary limitation. My previous pull request (pull request #763) fixes the problem and adds a test case.

**Comment by Lekensteyn** [comment]
This has been fixed for a while by #763, it can be closed.
