### ISSUE TITLE
Better debug output for `multiple rules generate (...)`

### ISSUE THREAD

**Issue by RedX2501** [ninja-build/ninja#821]
I'm currently trying to build llvm/clang.

When executing ninja the error:
`ninja: warning: multiple rules generate lib/libclang.dll.a. builds involving this target will not be correct; continuing anyway`
but there is nothing i can really do with this message. It would be nice if all the rules that output this target would also be shown or have a tool that can do that. Something like query but in the different direction. Give it a target and it will tell you what rule(s) generates it.

**Comment by Kaze1027** [comment]
The same problem, but everything works well with ninja v1.11.1

**Comment by digit-google** [comment]
@Kaze1027 , can you be more specific, since #718 has been closed already? Do you have a simple reproduction case?
