### ISSUE TITLE
MSVC dependency parsing fails when run from inside MSVC IDE

### ISSUE THREAD

**Issue by rmitton** [ninja-build/ninja#824]
Hi,

When using `deps=msvc`, ninja completely fails to parse any /showIncludes output if ninja was invoked from inside the MSVC IDE.

This is because the MSVC IDE sets the **VS_UNICODE_OUTPUT** environment variable, which causes CL.EXE to report it's output as Unicode instead of ASCII. Ninja then silently fails to parse anything.

An easy fix for this is to make Ninja automatically clear VS_UNICODE_OUTPUT to empty when spawning any `deps=msvc` child processes.

**Comment by jonesmz** [comment]
@rmitton is this reproducible with Ninja 1.10.0?

If so, does this PR resolve the problem? https://github.com/ninja-build/ninja/pull/1671

**Comment by rmitton** [comment]
I can't reproduce the bug any more because Visual Studio no longer seems to set the VS_UNICODE_OUTPUT variable at all. It's possible perhaps it only appeared in VS2005/2008 and may have been removed in later versions.

In which case it seems fair to close this bug report and move on.
