### ISSUE TITLE
ninja not build on armv71

### ISSUE THREAD

**Issue by vahpetr** [ninja-build/ninja#886]
Linux bananapi 3.4.104+ #3 SMP PREEMPT Wed Nov 19 08:28:34 CET 2014 armv7l
Hello.

Unknown architecture (armv7l) -- unable to run ninja.
No prebuilt ninja binary was found for this system.
Try building your own binary by doing:
cd ~
git clone https://github.com/martine/ninja.git -b v1.5.3
cd ninja && ./configure.py --bootstrap
Then add ~/ninja/ to your PATH

./configure.py --bootstrap 
bootstrapping ninja...
wrote build.ninja.
bootstrap complete. rebuilding...
[23/23] LINK ninja
./configure.py --bootstrap 237.16s user 15.97s system 132% cpu 3:10.76 total

I did it, but i take same message.
I think `ninja` doesn't parse `armv7l` correctly.

**Comment by sgraham** [comment]
I think that's from Chromium's depot_tools ninja wrapper. Probably just
needs an extra forwarding case.

**Comment by vahpetr** [comment]
`depot_tools` contains `ninja`
and fix `$PATH` order `ninja:depot_tools:etc`
it works

**Comment by dakrawczyk** [comment]
I'm seeing this same issue. What was the ultimate fix here? In my path I have
`[root@artik10-2257ee6 electron]# echo $PATH                                                                                                                                                                  
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/ninja/                                                                                                                                    
`
