### ISSUE TITLE
Confusing error message on undefined $in variable

### ISSUE THREAD

**Issue by perj** [ninja-build/ninja#907]
Hello,

This ninja.build produces a very confusing error message:

```
rule compile
    command = cc -c $out $in

build foo: compile $bar
build ok: compile ok.c
```

The error message produced is:

```
ninja: error: build.ninja:5: empty path
```

There is no problem on line 5. The problem is on line 4 and is that $bar is undefined.

A more desirable error message would be:

```
ninja: error: build.ninja:4: $bar is empty or undefined.
```

This bit us in a semi-large project and took a long time to figure out the problem was on the previous line and that it was a missing variable.

**Comment by jonesmz** [comment]
@perj Is this still reproducible on Ninja 1.10.0 ?

If so, would you consider creating a test case to include in the Ninja unit tests, and maybe try your hand at a fix?
