### ISSUE TITLE
Add environment variable and/or command line option to prevent ninja from stripping color escape codes

### ISSUE THREAD

**Issue by ngladitz** [ninja-build/ninja#916]
Ninja strips out color escape codes from e.g. gcc/clang when it detects that it isn't connected to a terminal.

In a CMake/Ninja based project the QtCreator IDE invokes ninja and is apparently capable of interpreting color codes.

It would be nice if ninja would provide the means to disable stripping of color codes in this case as to allow them to be visualized by QtCreator.

**Comment by martine** [comment]
Ninja doesn't strip the escapes.  gcc/clang turn off the color when they're run under ninja.

There's more discussion here, that I think summarizes all the pros and cons of all the workarounds.
https://github.com/martine/ninja/issues/174

**Comment by martine** [comment]
I totally misremembered the conclusion of that issue!  Reopening.

**Comment by ngladitz** [comment]
Yes, I did read up on that discussion as well.
To clarify I am forcing color output of gcc with -fdiagnostics-color=always.

**Comment by nico** [comment]
See also #672, #746.

**Comment by pseyfert** [comment]
See also #1268 and https://github.com/ninja-build/ninja/blame/master/src/build.cc#L146

**Comment by jhasse** [comment]
Fixed by bf7107bb864d0383028202e3f4a4228c02302961.
