### ISSUE TITLE
Inconsistent handling of cycle in phony rules

### ISSUE THREAD

**Issue by ddunbar** [ninja-build/ninja#935]
## Ninja does not consistently diagnose a cycle in a phony build command:

```
$ rm -f output
$ cat build.ninja
build output: phony output
$ ninja output
ninja: no work to do.

$ cat build.ninja
build ignored: phony
build output: phony output ignored
$ ninja output
ninja: error: dependency cycle: output -> output
```
## 

It seems as if CMake has grown to depend on this behavior, as it has a strong tendency to generate build commands using phony rules with cycles, and will even do this as part of its most basic check for running a C compiler during configuration.

**Comment by ddunbar** [comment]
Filed against CMake here: http://www.cmake.org/Bug/view.php?id=15454

**Comment by jhasse** [comment]
This has been fixed in CMake, right? If not, please reopen.
