### ISSUE TITLE
Build fails with uclibc: src/util.cc:426:28: error: 'getloadavg' was not declared in this scope

### ISSUE THREAD

**Issue by tstellar** [ninja-build/ninja#985]
Hi,

The ninja builds fails on Linux systems that use uclibc as the C standard library rather than glibc: 

i686-gentoo-linux-uclibc-g++ -O2 -march=i686 -pipe -Wno-deprecated -DNINJA_PYTHON="/usr/bin/python2.7" -DNI/graphviz.cc src/manifest_parser.cc src/eval_env.cc src/line_printer.cc src/subprocess-posix.cc src/debug_fc src/lexer.cc -o ninja.bootstrap
src/util.cc: In function 'double GetLoadAverage()':
src/util.cc:426:28: error: 'getloadavg' was not declared in this scope
   if (getloadavg(loadavg, 3) < 0) {
                            ^

**Comment by nico** [comment]
http://linux.die.net/man/3/getloadavg says that this is in stdlib.h which util.cc does include, and http://linux.die.net/man/7/feature_test_macros says "If no feature test macros are explicitly defined, then the following feature test macros are defined by default: _BSD_SOURCE, _SVID_SOURCE, _POSIX_SOURCE, and _POSIX_C_SOURCE=200809L". So I'm not sure what uclibc needs.

**Comment by tstellar** [comment]
I think those man pages are for glibc an not linux in general.

My understanding is that the reason uclibc doesn't implement getloadavg,  is because it is not part of the POSIX specification.  I think uses of getloadavg on linux will need to be guarded by something like #if defined(__GLIBC__) if ninja wants to support alternative standard library implementations, like uclibc.

**Comment by nico** [comment]
ninja doesn't have an opinion on this. If someone wants to use ninja with uclibc and doing so isn't too ugly, we'd merge the patch.

**Comment by jbergstroem** [comment]
musl provides a generic getloadavg.c to mitigate this (pretty common use). I reckon we copy that, put it into ninja and provide it for systems that lack it (so far, my only knowns are ulibc and ulibc-ng)

**Comment by martine** [comment]
musl's implementation is essentially this with error handling, where "b" is the output array:

```
	FILE *f = fopen("/proc/loadavg", "rbe");
	i = fscanf(f, "%lf %lf %lf", b, b+1, b+2);
```

https://github.com/cloudius-systems/musl/search?utf8=%E2%9C%93&q=getloadavg

**Comment by jbergstroem** [comment]
@martine thats the old version. The newer uses `sysinfo.h`: http://git.musl-libc.org/cgit/musl/commit/?id=20cbd607759038dca57f84ef7e7b5d44a3088574

**Comment by jbergstroem** [comment]
Want me to file a PR with the suggested change?
