### ISSUE TITLE
[DOC] replace yum with dnf in Fedora install section

### ISSUE THREAD

**Issue by ignatenkobrain** [ninja-build/ninja#993]
Fedora uses DNF as default package manager since F22, so no one should use yum ;)

Reference: https://fedoraproject.org/wiki/Changes/ReplaceYumWithDNF

**Comment by martine** [comment]
I guess it's worth leaving around yum instructions as long as there are old RH-based distros in use?  I'm thinking of stuff that's likely to be kept at old versions, like centos.

(Forgive me if I got this wrong, I don't have a lot of RH experience.)

**Comment by ignatenkobrain** [comment]
We don't support EL (centos, scientific linux) packages in Fedora, so only in Fedora ninja is. F21 will be orphaned in October-November, so it is only one distro which uses `yum`.

**Comment by QuLogic** [comment]
If you're referring to [this wiki page](https://github.com/ninja-build/ninja/wiki/Pre-built-Ninja-packages), then I guess this is fixed?
